### ISSUE TITLE
Android themes page shows extensions and categories throw Invalid "category" parameter on desktop

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10033]
A while ago, themes have been removed from android searches https://github.com/mozilla/addons-frontend/issues/9903 
Right now, on Android, themes cannot be found, all pages are hidden.

On desktop themes homepage show right now extensions
A category will throw an error    ->  Invalid "category" parameter. This has been discussed https://github.com/mozilla/addons-server/issues/5981#issuecomment-768172671

![android themes on desktop](https://user-images.githubusercontent.com/33448286/105856124-86e76200-5ff1-11eb-8aa1-3e0914801eb3.gif)

**Comment by bobsilverberg** [comment]
I'm trying to understand this issue. I can see from what @eviljeff discussed at https://github.com/mozilla/addons-server/issues/5981#issuecomment-768172671, that we are sending an invalid API request, and for some reason sending `type=extension` instead of `type=statictheme`, so that's something we should investigate and fix, but this isn't something a user could encounter on the site, correct? The only way to get into this state is by editing the URL. Please confirm whether there is currently a bug that manifests on the site via regular navigation, or whether this is something that only reproduces by manually changing the URL.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Hello, Yes, you understood it right. I mentioned above that I used desktop to navigate to these pages (so, yes, I manually changed the URLs). Also I mentioned that on Android, the pages are hidden, which means that an android user cannot find these pages via regular navigation.
