### ISSUE TITLE
Investigate duplicate / client-side calls to ratings API on detail pages

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10039]
Going to a detail page directly (so the page has gone through server side rendering), I can see the following requests:

- /api/v5/ratings/rating/?addon=XXXX&show_grouped_ratings=true&lang=en-US
- /api/v5/addons/search/?app=firefox&appversion=86.0&author=YYYY&exclude_addons=adblock-plus&page=1&page_size=6&sort=hotness&type=extension&lang=en-US
- /api/v5/addons/recommendations/?guid=ZZZZZ&recommended=true&lang=en-US
- /api/v5/ratings/rating/?user=WWWW&addon=XXXX&lang=en-US
- /api/v5/ratings/rating/?addon=XXXX&show_grouped_ratings=true&lang=en-US (duplicate)

That raises a few questions:
- Why do we call the ratings API on the client for non-user specific ratings info ? Could we only do this on the server side ?
- Why is it duplicated ? Could we get rid of that extra call ? 
- In both cases, we load the first page of ratings, but the only thing we should need for the detail page is the grouped ratings info, right ? Investigate either having a separate endpoint just for grouped ratings info, or consolidating it into the detail API when `show_grouped_ratings=true` (https://github.com/mozilla/addons-frontend/issues/10038)
    -  Note that the ratings API is kinda slow and even if it was fast, that's extra data going over the wire we probably don't need

**Comment by bobsilverberg** [comment]
I can start by trying to determine why this API is being called twice, and then we can also look at some of the other suggestions about addressing this.

**Comment by bobsilverberg** [comment]
The problem comes from the fact that we're not checking whether the grouped ratings are currently being fetched before issuing the API request to fetch them. This is something we have implemented for a number of fetches on the frontend, as it's often difficult to predict when we might attempt a duplicate fetch. In this case, it only happens with SSR, and I think it's just an inconvenient timing issue. When we load the details page with SSR, it tries to fetch the grouped ratings twice, I believe because the first fetch is attempted on the server, but doesn't complete in time, and hence is tried again on the client.

It may be possible to address this SSR fetch issue, but really, we should have code in place to prevent a duplicate fetch if one is already in progress, as we do for many of our API calls.

I have already written a patch that fixes this (currently sans tests), but before going ahead and implementing that we might want to consider whether we should simply add the grouped ratings data to the add-on detail API response as Mat suggested above. If we include a param (e.g., `show_grouped_ratings=true`) then we can ensure that this data is only returned when necessary.

What do folks think?

**Comment by willdurand** [comment]
> What do folks think?

Let's fix the issue you found first (we can get this bug fixed before this week's push I suppose?)

**Comment by diox** [comment]
Yeah if we can get the duplicate call fixed first this week, let's do that. Before adding `grouped_ratings` to the detail API, I want to make sure there is nothing else we'd like to add there.

**Comment by ioanarusiczki** [comment]
@bobsilverberg On -dev and -stage the issue is no longer present. When going directly to an add-on detail page - https://addons-dev.allizom.org/api/v5/ratings/rating/?addon=616840&show_grouped_ratings=true&lang=en-US is present only once in the network.

![olny once](https://user-images.githubusercontent.com/33448286/106754467-b15e9e00-6635-11eb-8713-6db9b9990a91.png)
