### ISSUE TITLE
Update code to deal with translated fields from the hero API

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10075]
This is a companion issue to https://github.com/mozilla/addons-server/issues/16515. Once that is fixed we will need to adjust the frontend code to expect localized strings (objects) as opposed to simple strings.

**Comment by ioanarusiczki** [comment]
@eviljeff Following https://github.com/mozilla/addons-server/issues/8712#issuecomment-769912249, the test results on -dev are below and I bolded the results that raise question marks: 

1. Results for Primary hero "description" field:
I used for testing sample addon "id":7560,  with "fr" set as default language. 

1.1 The primary "description" field with a custom description set in the admin:
- v4,v5, lang specified and translation is available - returns the value of the custom description added in the description admin field for that locale.
- v4,v5, lang specified but translation is not available - returns the value of the custom description added in the description admin field for en-US.
- v4,v5 lang not specified or invalid, unsupported - returns the description admin field for en-US. I don't know if that's correct because `fr` is set as default in dev hub. **Perhaps it should be "fr" ?** 
-v4 lang is not specified - accept language header is "it"  - returns "it" because the addon has translated strings for these languages
- v5 lang is not specified - accept language header is "it"  - returns the description in "en-US" and "it".  **I don't know if that's alright as it is, or should it be only "it" ?** 

1.2 The primary "description" field without a custom description set in the admin when there are translated strings provided by the summary of the add-on (the same addon 7560, with "fr" set as default language):
- v4,v5, lang specified and translation is available - returns the value of the language specified. 
- v4,v5, lang specified but translation is not available - returns the default locale set by the developer - which is "fr" in this case.
- v4 lang not specified - returns the summary in en-US.
- v5 lang not specified - returns all translated summaries (description in all languages). 
- v4/v5 lang not supported - returns the summary in the default language which is "fr".
- v4/v5 lang is not supported - and I use an `accept-language` header other than the default (fr), a lang in which the summary translations are available (de,it, en-US) - returns the default "fr" **Perhaps the accept-language should be returned here, "de", "it" or "en-US"?** 

2. Results for Secondary Hero "description" field: 
"description", "headline" and "cta.text" fields from the secondary hero->
- v4,v5 with a specified lang in which translation exists (de) - returns one language (de)
- v4,v5 with a specified lang that does not have a translation - returns en-US
- v4,v5 with not specified, not supported or invalid lang - returns en-US
- for lang not specified using an accept header lang other than en-US (de) and "de" translations are available: 
   v4 returns strings in "de"
   v5 returns strings for  "de" and "en-US"  **Should v5 return only the accepted header "de" without "en-US" ?** 
- for unsupported lang using an `accept-header` lang other than en-US(de) and "de" translations are available -
   v4,v5 return translations in en-US **Should it be "de" instead of en-US?**

**Comment by ioanarusiczki** [comment]
@eviljeff I don't see anything broken on the frontend after testing with similar scenarios mentioned on the server side https://github.com/mozilla/addons-server/issues/16515#issuecomment-781242982

Verified on AMO dev with FF85(Win10).
