### ISSUE TITLE
Cache frontend pages for a short period for unauthenticated users

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10116]
Similar to https://github.com/mozilla/addons-server/issues/16311 we want to look into caching unauthenticated responses for a few minutes (and serve those cached responses to unauthenticated requests).

We want to use the same general strategy: have `nginx` handle the caching depending on `Cache-Control` header set by the nodejs app.

Main difference is that at the nginx level, we can't use the mere presence of an `Authorization` header in the request to figure out if it's an authenticated request - ideally we'd be able to look at the presence of a specific cookie, `frontend_auth_token`.

**Comment by diox** [comment]
> Main difference is that at the nginx level, we can't use the mere presence of an Authorization header in the request to figure out if it's an authenticated request - ideally we'd be able to look at the presence of a specific cookie, frontend_auth_token.

This should be doable via `$cookie_frontend_auth_token` in `proxy_cache_bypass` in the nginx config.

**Comment by willdurand** [comment]
IIRC caching causes issues with the client side navigation, which is why cache-control exposes "no-store".

In addition, we serialize the redux store in the html so we should double check that it won't be a problem.

**Comment by diox** [comment]
Yeah, both are on my list of things to investigate. Regarding the header, we don't have to have nginx obey `Cache-Control` - we can set a default timeout in the nginx config and/or use a different header and/or ask nginx to ignore `Cache-Control`, so we have some options if we need to keep exposing `no-store`.

I was initially worried about redux store in the HTML but if we only do this for non-authenticated requests, I think we should be ok. Note that we already `Vary` on relevant things like `User-Agent`.

**Comment by diox** [comment]
Original issue about `Cache-Control: no-store`: https://github.com/mozilla/addons-frontend/issues/6217

It's probably safer to leave that alone and use `X-Accel-Expires` (and not doing that if the user is authenticated). That being said, there are other ways yo fix the original issue that led us to use `Cache-Control: no-store`. In fact, it's quite similar to https://github.com/mozilla/addons-frontend/issues/10058 which we closed recently as technically not a frontend issue.

**Comment by diox** [comment]
Regarding Redux Store, the only 2 differences between unauthenticated requests are:
- `api.requestId`; Do we even still need this? Note that we discussed [removing Sentry integration for addons-frontend](https://github.com/mozilla/addons-frontend/issues/10028). If we were to keep it, then we could generate a new one on the client-side when the page is loaded, if non-authenticated.
- `errors: { "<Page>-xxx": ... }` ; Should always be `null` anyway for cached pages, hopefully ? And I don't think it matters anyway.

**Comment by bobsilverberg** [comment]
> Regarding Redux Store, the only 2 differences between unauthenticated requests are:
> 
> * `api.requestId`; Do we even still need this? Note that we discussed [removing Sentry integration for addons-frontend](https://github.com/mozilla/addons-frontend/issues/10028). If we were to keep it, then we could generate a new one on the client-side when the page is loaded, if non-authenticated.
> 
> * `errors: { "<Page>-xxx": ... }` ; Should always be `null` anyway for cached pages, hopefully ? And I don't think it matters anyway.

I agree that neither of these should be an issue. For `api.requestId`, this is populated from the `amo-request-id` header. Is it possible that that can be a different, unique value for each request, even if they are being served from cache, or is that not possible? As you indicate, we might not even need it anymore, but I'm still curious.

**Comment by willdurand** [comment]
> `api.requestId`; Do we even still need this? Note that we discussed [removing Sentry integration for addons-frontend](https://github.com/mozilla/addons-frontend/issues/10028). If we were to keep it, then we could generate a new one on the client-side when the page is loaded, if non-authenticated.

mmm why would this be related to Sentry?

**Comment by diox** [comment]
> Is it possible that that can be a different, unique value for each request, even if they are being served from cache, or is that not possible?

If the response is coming from cache, the redux store has already been generated in that response we're serving, so even if nginx somehow altered the cached response every time it's serving it the request id in the HTML would be wrong. We're back to having to re-generate one client-side.

> mmm why would this be related to Sentry?

In my mind the request id was mostly useful to correlate error tracebacks. But I guess it's for logging in general... Regardless, the question remains: is that actually useful ?

**Comment by diox** [comment]
> In my mind the request id was mostly useful to correlate error tracebacks. But I guess it's for logging in general... Regardless, the question remains: is that actually useful ?

Looking at it more deeply... AFAIK it's only useful for server-side logging and sentry. So if we remove the Sentry integration then we should be OK ?

**Comment by diox** [comment]
Ops bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1696432

**Comment by willdurand** [comment]
We discussed this issue on Matrix:

`requestId` is used for both Sentry and logs, we're getting rid of Sentry but we'll keep `requestId` to correlate logs. The `requestId` is only used for the node server logs and we don't pass it to the API requests issued from either the server or client side. In other words, it's fine to keep the `requestId` serialized in the HTML that is going to be cached because it's not used on the client. Things would be slightly different if we wanted to use the `requestId` in API calls, though.

> errors: { "<Page>-xxx": ... } ; Should always be null anyway for cached pages, hopefully ? And I don't think it matters anyway.

Not necessarily, it can be non-null, e.g., https://addons-dev.allizom.org/en-US/firefox/addon/doesnotexist/

In most cases we generate a predictable ID (to reuse the ID generated on the server on the client) but not for all pages. It shouldn't be a problem but asking QA to verify expected error pages with caching enabled would be good.

We also store the `userAgent` (+ `userAgentInfo`) and `regionCode` but I suppose that won't be a problem?

And there is a `survey` state that depends on a cookie (not depending on authentication) but we don't have an active survey right now. (same would be true for A/B experiments)

**Comment by diox** [comment]
> Not necessarily, it can be non-null, e.g., https://addons-dev.allizom.org/en-US/firefox/addon/doesnotexist/

That wouldn't be cached since it's a 404 (we'd only cache 20x, 30x responses)

> We also store the userAgent (+ userAgentInfo) and regionCode but I suppose that won't be a problem?

Both shouldn't be an issue: We already `Vary` on `User-Agent` and `regionCode` should be part of the cache key on nginx side.

> And there is a survey state that depends on a cookie (not depending on authentication) but we don't have an active survey right now. (same would be true for A/B experiments)

What are the cookies used for that ? We could have the cache key depend on that.

**Comment by willdurand** [comment]
> What are the cookies used for that ? We could have the cache key depend on that.

The cookie depends on the survey (IIRC) and it was used to remember when a user dismissed the message.

**Comment by diox** [comment]
Ok, so we should just be careful in the future, ensuring any new code that depends on cookies (or state in general if it's coming from the server side) works correctly with caching.

**Comment by AlexandraMoga** [comment]
@diox I'm trying to verify this issue on -dev but there are some things I need to clarify:
- I'm looking at requests in the dev tools console and I've noticed that the `X-Cache-Status` response header is present now in loaded documents  (i.e. homepage (https://addons-dev.allizom.org/en-US/firefox/), landing pages (https://addons-dev.allizom.org/en-US/firefox/extensions/), etc.);
- the `X-Cache-Status` response header for these types of requests will have a `BYPASS` value for authenticated users; unauthenticated requests, on the other hand, will always return `MISS`. I was expecting to see a `HIT` after the document is loaded once, similar to what we have for the API caching;
- the `Cache-Control` response header value is `no-store` for  requests with a 200 status code
- for 301 responses, `Cache-Control` will return `max-age=31536000`

If you have some suggestions on how I can make sure that the frontend caching is indeed working as it should, please let me know.

**Comment by diox** [comment]
> the `X-Cache-Status` response header for (...) unauthenticated requests, on the other hand, will always return MISS. I was expecting to see a HIT after the document is loaded once, similar to what we have for the API caching

Yes, there is definitely a problem there, I am seeing this too and don't know what's going on yet. This shouldn't negatively impact stage or prod (the caching isn't enabled there anyway).

**Comment by diox** [comment]
@AlexandraMoga can you retest on dev ? In addition to what you tested, a couple things to look for:
- Make sure geoblocking still works as expected together with caching, both on direct load of a detail page and navigation to the detail page from another page. So doing things like ensuring the detail page is in the cache for a given country, then loading from another where it's supposed to be blocked, then reloading from both countries ensuring they behave like they should. That kind of thing
- Make sure logging in and out from a cached page still works as expected, and then navigating as normal still works too.

**Comment by AlexandraMoga** [comment]
@diox I've retested the frontend caching on -dev and these are the results I have:

 - the `X-Cache-Status` response header seems to indicate that caching is working now and will take the following values:
    - `BYPASS` for authenticated requests 
    - `MISS` when a document is being loaded for the first time (unauthenticated requests) 
    - `HIT` on subsequent document reloads, until the cache expires after ~3 minutes (unauthenticated requests) 
    - `EXPIRED` after the cache expires and until a cache `HIT` occurs again (unauthenticated requests) 
 - log in, log out and account registration is working as expected; the log in states are being preserved during site navigation or when navigating from frontend to devhub, revtools and backwards.
  
 Region restrictions:
  1. Requests coming from the same country: 
  - detail page accessed from a country where the add-on is NOT restricted => detail page is loaded, cache HIT
  - add-on becomes restricted in the country where the request originated; detail page is reloaded in the same browser window, from the same country => the detail page is loaded from cache until the cache expires (~3 mins), afterwards the response status changes to 451; the same result applies if the detail page is reached by client side navigation instead of reloading;
  - detail page URL is loaded in a different browser window, from the same restricted country => a 451 page is displayed immediately 
  2. Requests come from different countries:
  - detail page accessed from a country where the add-on is NOT restricted => 200 response, cache HIT
  - detail page is reloaded in the same tab, from a country where the add-on IS restricted => 451 error page is displayed; the same result applies if the detail page is reached by client side navigation instead of reloading;
	
	
**Question**: should the `Disable-cache` option from the Developer tools console have an effect on our cache hits? As far as I can tell, it doesn't seem to have any effect when enabled, i.e. frontend caching works the same.
	
**Additional observations**: in https://github.com/mozilla/addons-server/issues/16311#issuecomment-785050691, I've explained how sometimes responses can fluctuate; I've noticed now that this can also happen with georestrictions but _only when_ the requests are coming from the same country; so, if I have a loaded detail page in a country where the add-on has become restricted in the meantime, when I reload the page I will sometimes receive a 451 (as expected), while on the next reload the detail page will be displayed normally (with a cache HIT); this will happen only until the cache is settled again -  so for ~3 mins.

**Comment by willdurand** [comment]
> **Question**: should the `Disable-cache` option from the Developer tools console have an effect on our cache hits? As far as I can tell, it doesn't seem to have any effect when enabled, i.e. frontend caching works the same.

This is for client-side caching so I think that's expected?

**Comment by diox** [comment]
Yep, that all seems OK.

**Comment by AlexandraMoga** [comment]
I've tested the frontend caching on stage and the it seems to work there as well. The same observations and results mentioned for -dev are valid for stage too.

**Comment by AlexandraMoga** [comment]
Looks like frontend caching is also functional on prod.
