### ISSUE TITLE
Wrapping issue with "Flagged" notice in AddonReviewCard

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10138]
I noticed this when testing https://github.com/mozilla/addons-frontend/pull/10137. After flagging a review, the "Flagged" notice is wrapping. Here's an example from dev:

<img width="863" alt="Screen Shot 2021-03-01 at 8 58 41 AM" src="https://user-images.githubusercontent.com/142755/109507111-61c09600-7a6c-11eb-9677-d09c380a9bb2.png">

**Comment by AlexandraMoga** [comment]
@bobsilverberg there was another issue opened for this - https://github.com/mozilla/addons-frontend/issues/9446
Maybe we should close that one and keep the current issue only.

**Comment by bobsilverberg** [comment]
> @bobsilverberg there was another issue opened for this - #9446
> Maybe we should close that one and keep the current issue only.

Thanks @AlexandraMoga. I must really be getting old, as I am the one who opened that other issue! Yeah, I'll close that one.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on stage, Win10 and Android 10:

[desktop]
![image](https://user-images.githubusercontent.com/31961530/110637947-a1972400-81b6-11eb-8584-0cfb69b94b55.png)



[mobile]
![image](https://user-images.githubusercontent.com/31961530/110637798-790f2a00-81b6-11eb-97a0-04e3ac416164.png)

@bobsilverberg I've noticed another wrapping issue with the 'Flag' label on mobile view, but it's not a regression from your changes, so I've filed a separate issue - #10184
