### ISSUE TITLE
Update experiment code to deal with anonymous page caching

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10188]
Because experiments rely on cookies, we need to make sure that our anonymous page caching scheme doesn't interfere with the running of experiments, and vice versa.

Some things to consider:
1. We need the correct cookie to be sent for each user in the experiment.
2. Ideally we should be able to cache a page for an experiment user (as opposed to disabling caching for anyone enrolled in an experiment).
3. We cannot `Vary` on a particular cookie value.

Some suggestions from our chat in Slack:
1. We could have a single cookie that lists all experiments a user in enrolled in, along with the corresponding variant. Then nginx can use that value as part of the cache key.
2. We should always clean up cookies after an experiment is over. Currently we just set them to expire in 30 days, but we should add code to delete them (or rather, update the single cookie mentioned above) when the experiment is no longer active.
3. If we change an experiment (i.e., change some of the UX associated with a variant) we need to ensure that we assign a new, unique id for the experiment. This is something we would generally do anyway, but it becomes critical now, because of caching.
4. We could use a scheme similar to what addons-server does for activity logs by adding all experiment ids to a file, keeping old ones around, having a list with them all and adding a test to make sure the list only contains unique items.

@diox Can you think of anything we discussed that I haven't captured?

**Comment by willdurand** [comment]
>     3\. we need to ensure that we assign a new, unique id for the experiment

semi related: https://github.com/mozilla/addons-frontend/issues/9137

**Comment by diox** [comment]
Looks like you've summarized everything we discussed. For reference the issue about frontend caching is https://github.com/mozilla/addons-frontend/issues/10116

**Comment by bobsilverberg** [comment]
Note that we also need to open a bugzilla ticket for ops to add the cookie to the cache key. From Slack:

"that can be a bugzilla ticket for ops giving the exact change to make to the cache key (adding $cookie_<cookie_name> to proxy_cache_key in the frontendamo config)"

**Comment by ioanarusiczki** [comment]
@bobsilverberg Please add some STR for qa. 
Thanks!

**Comment by bobsilverberg** [comment]
@ioanarusiczki Because there are no experiments enabled right now, I don't think it's possible to test anything for this patch. The changes made here will be testable when the next experiment lands on dev, which should happen in the next few weeks. I'm going to mark this as QA not needed for now.

**Comment by bobsilverberg** [comment]
@diox I submitted https://bugzilla.mozilla.org/show_bug.cgi?id=1702993 for the `proxy_cache_key`. Can you take a look when you have a moment and make sure it is accurate?

**Comment by bobsilverberg** [comment]
For QA: You should be able to verify this by making sure you are not logged in, and then loading a page with the cookie value of `current-cta`, check that it looks like the current site, and then changing the cookie value to `new-cta`, reloading the page, and you should see the new, experimental UX for the download button.

@diox Does that cover it, or is there something else required to check the cache key?

**Comment by diox** [comment]
Now that we have an experiment on dev (#10333) we can see a problem in this logic:

- [By default, if a response has `Set-Cookie` header set, nginx won't cache it](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_valid). That default behavior makes sense: typically if the response is setting a cookie, it's because it's doing something specific to the client it's serving, so nginx is being super safe here to avoid caching something private.
- We're including the cookie value in the cache key, so if a client comes with the cookie already, it's fine: the response won't contain a `Set-Cookie`, so it can be cached and served to future requests coming in with the same cookie value
- If a client makes a request without a cookie set however, we set one on the response we return. But that means those responses will never be cached, and in turn similar future requests will always be a cache miss!

The only 2 potential solutions I can think about right now:
- Add `Set-Cookie` to `proxy_ignore_headers` in nginx config. If we go that route, we need to be extremely careful because it turns off the entire handling of `Set-Cookie` resulting in responses not being cached in nginx, it's not granular depending on the cookie name/value. It would also start caching responses setting other cookies, and we need to check if that's ok. This may requires further tweaks in addons-frontend
- Alternatively, in addons-frontend, set the initial `frontend_active_experiments` cookie in JavaScript only, never server-side

**Comment by bobsilverberg** [comment]
> 
> The only 2 potential solutions I can think about right now:
> 
> * Add `Set-Cookie` to `proxy_ignore_headers` in nginx config. If we go that route, we need to be extremely careful because it turns off the entire handling of `Set-Cookie` resulting in responses not being cached in nginx, it's not granular depending on the cookie name/value. It would also start caching responses setting other cookies, and we need to check if that's ok. This may requires further tweaks in addons-frontend
> 
> * Alternatively, in addons-frontend, set the initial `frontend_active_experiments` cookie in JavaScript only, never server-side

We might be able to do that. We could read the cookie on the server, and if it doesn't exist, rather than set it, we could dispatch an action, similar to what we're already doing for the enrollment event. We could then read data from the redux store that was recorded by that action, on the client, and set the cookie. I'm not sure if this will work or not, but I can give it a try.

**Comment by diox** [comment]
Let's try that, it seems the safest approach.

**Comment by willdurand** [comment]
Do we have a feature flag or can we NOT enable the experiment on -prod this week?

**Comment by bobsilverberg** [comment]
> Do we have a feature flag or can we NOT enable the experiment on -prod this week?

We do not plan to enable the experiment on prod this week, so this isn't an issue that needs to be addressed for this week's tag, but should be dealt with before next week.

**Comment by bqbn** [comment]
Is it easier to use a custom header to address the issue in stead of a cookie?

**Comment by bobsilverberg** [comment]
We have decided that the way to deal with this is to ensure that any cookie-writing code for experiments is always done on the client. None of this code will be executed on the server. This means that the UI may be updated client-side, after a user receives a cached response from the server, which could cause a minor flash of content, but that is a tradeoff in order to ensure that caching works with experiments.

**Comment by bobsilverberg** [comment]
For QA: The experiment has been re-enabled on dev and is able to be tested again.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Without log in, after deleting several times the cookie for the new-cta, the current-cta loaded the page correctly, with the current UX. 
This should be working as expected on AMO dev - with Chrome/Edge

2. UX issues observed:
https://github.com/mozilla/addons-frontend/issues/10399
https://github.com/mozilla/addons-frontend/issues/10400
