### ISSUE TITLE
Add Vary on User-Agent instead of having nginx do it

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10381]
We have to `Vary` on `User-Agent` to be able to do some browser detection (which is usually a bad idea, but for a site that serves add-ons specific to a particular browser/version, we have to). 

It's currently done in nginx, but for all other headers we have to `Vary` on we do it in addons-frontend, so for consistency sake we should do it inside addons-frontend for `User-Agent` as well.

**Comment by ioanarusiczki** [comment]
@diox Please add some STR for qa in case it can be verified.
Thanks!

**Comment by AlexandraMoga** [comment]
@diox I've noticed the change in the Response headers concerning `Vary`.

Previously, this is what the response headers looked like:
```
Vary: Accept-Encoding
Vary: DNT
Vary: User-Agent
```

Now, we have this structure - the first being the Vary set by nginx and the second being set by the frontend:
```
Vary: DNT, User-Agent, Accept-Encoding
Vary: User-Agent
```

I've looked in several browsers on desktop and mobile to see if the user agent is detected accordingly. For example, in Firefox browsers I've checked that the browser version was correctly identified and that we served content available for those browsers - such as add-on compatibility in desktop Firefox and Fenix on mobile.

In non-Firefox browsers, I've checked that the User-Agent is correctly detected and that we prompt users to Download Firefox instead of displaying the Install buttons.

If you have some additional scenarios that need to be covered, please let me know and I'll investigate further.
