### ISSUE TITLE
Font could be a bit darker to avoid being a bit blurry 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10400]
It's obvious on the see more versions page that the font is a bit blurry in the yellow banners above the download buttons 

Chrome 

![See all version page - experiement](https://user-images.githubusercontent.com/33448286/115038785-b7b69500-9e84-11eb-9814-ef5756ce1a78.png)

Edge

![Edge](https://user-images.githubusercontent.com/33448286/115039705-8ab6b200-9e85-11eb-9114-19526375909c.png)

Maybe it could look like the fonts from 
"Be careful with old versions! These versions are displayed for testing and reference purposes.You should always use the latest version of an add-on." which looks clear to me. 

Also the banner on the other pages could use this.

**Comment by championshuttler** [comment]
I can work on it once its triaged ;)

**Comment by championshuttler** [comment]
May be we can increase font-weight a little bit for these banners

**Comment by willdurand** [comment]
I don't quite understand the problem here. Is that the text appears too "thin" as @championshuttler suggested?

**Comment by bobsilverberg** [comment]
I mentioned this issue in the UX meeting. The colour used for this text is not exactly black, so I think the colour itself could be darker and that might fix the issue, rather than increasing the font-weight. I notice that on this page we have at least three different colours that are close to, but not exactly, black, and I'm not sure if that is intentional, or just a result of different elements being added at different times. I will post some examples in a bit.

**Comment by bobsilverberg** [comment]
Looking at the colours on this page, I see that:
- the text in the yellow download callout is `#1d1d1d`, which is the default body colour.
- the text in the yellow warning about being careful with old versions is `#0c0c0d`, which is specific to this warning text.
- the text of the "Latest version" heading is `#000`, which is the default for an `h1`.
- the text of the card heading that says "Video DownloadHelper version history - 2 versions" is `#1d1d1d`, which is the default body colour. Note that it has a `font-weight` of `600` which makes it appear darker.
- the text of the word "by" in the byline for the add-on is `#343a40`, which is specifically set for `.AddonTitle`.

So we have a lot of variations on "black", and I'm not sure if that is intentional, or just a result of things being changed in pieces over time. This might be something we want to look into, but for now I'm going to suggest we simply change the text inside the yellow callout and the banner to be `#0c0c0d`, which is what is used for both the "older versions" warning, as well as the site warning (the one that says "a small notice" on dev. Or perhaps we want to change them to `#000000`?

@Verdi @jvillalobos What are your thoughts on this?

**Comment by jvillalobos** [comment]
> This might be something we want to look into, but for now I'm going to suggest we simply change the text inside the yellow callout and the banner to be #0c0c0d

This sounds good to me for internal consistency with other yellow callouts. 

It's crazy how many variants of black we have, and it's not clear to me that they make much difference compared with `#000000`. That's a separate discussion to have, though.

**Comment by championshuttler** [comment]
We also have a different color for release data `#737373`, its not black though, but was it also intentional @jvillalobos ? I could fix it up for yellow text

**Comment by bobsilverberg** [comment]
@championshuttler Please go ahead and change the colour for the download callout and the heading banner to `#0c0c0d`.

**Comment by championshuttler** [comment]
@bobsilverberg I did but IMO stil it looks blurry to me WDYT?

![Uploading image.png…]()

**Comment by bobsilverberg** [comment]
I think it looks fine to me. I think it's a decent, interim fix.

**Comment by willdurand** [comment]
Why not using `$black` everywhere?

**Comment by championshuttler** [comment]
> Why not using `$black` everywhere?

I had the same thought

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

For the banner and yellow warnings from the detail pages the color is  #0c0c0d;

Banner

![banner](https://user-images.githubusercontent.com/33448286/115555937-f1ace000-a264-11eb-8e88-8c0c330c9bc6.png)

Detail page

![0c0c0d](https://user-images.githubusercontent.com/33448286/115555975-fd000b80-a264-11eb-8d2b-70d5dc03838f.png)
