### ISSUE TITLE
Some layout issues on iOS - with unbroken strings

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10414]
I'll add what I said here: https://github.com/mozilla/addons-frontend/issues/10289#issuecomment-821165825

On homepage long unbroken strings break the layout of the page on iOS and that's because the page is https://addons-dev.allizom.org/en-US/firefox/ . Also on Android with Chrome the issue is reproducible. On the other hand the android page can be accessed with https://addons-dev.allizom.org/en-US/android/. If I check the android URL on all platforms and browsers it looks optimized for small screens and these issues are not reproducible. 

Hero Shelves - on Android with Chrome when accessing https://addons-dev.allizom.org/en-US/firefox/ - issue reproducible on iOS with Safari and FF

Primary and secondary shelves are edited by the admin 

![Android ff page](https://user-images.githubusercontent.com/33448286/115023653-c2dee480-9ec7-11eb-9e5f-2f67b0c9ceb2.png)

The name of an addon is edited by users/developers

![ioS issue](https://user-images.githubusercontent.com/33448286/115028439-87471900-9ecd-11eb-86b1-f51d31f35b66.jpg)

**Comment by willdurand** [comment]
Yeah, this is a known-issue. We fixed something for Safari in #10289 but it does not help with long strings (only with long sentences). I am not quite sure what our options are because `anywhere` seeems like the best option available to us, sadly not available on Safari...

Reading about all those properties and values, I think `overflow-wrap: anywhere` does what `word-break: break-word` is supposed to do in addition to other things. I think we might want to add `word-break: break-word` in addition to the other `overflow-wrap` properties we have and see how it looks. I think it shouldn't affect FF. 

@championshuttler I know you said that before but I am slow to understand certain things :)

**Comment by championshuttler** [comment]
> I think we might want to add `word-break: break-word` in addition to the other `overflow-wrap` properties we have and see how it looks. I think it shouldn't affect FF.

I dont think too it will affect, IIRC I tested too back then, @muffinresearch may be can confirm?

Context is overflow-wrap: anywhere is not supported in Safari, only `word-break: break-word;`
