### ISSUE TITLE
Username is not vertically aligned with the other external links in the header

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10416]
### Describe the problem and steps to reproduce it:

1. Go to AMO
2. Log in
3. Observe the menu with your username

### What happened?

It's not aligned with the other links:

![Screen Shot 2021-04-19 at 09 31 50](https://user-images.githubusercontent.com/217628/115199448-81328180-a0f3-11eb-9fbc-159ed7c5d0a3.png)

### What did you expect to happen?

Not that.

**Comment by AlexandraMoga** [comment]
Looking in other browsers, looks like the 'Download Firefox' and the 'Register and Log in' buttons are also misaligned. Not sure if that could be fixed as part of the same issue or if we should address that separately. 

![image](https://user-images.githubusercontent.com/31961530/115388200-43615600-a1e4-11eb-9018-cf1ffc10e62a.png)

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on AMO -dev:

![image](https://user-images.githubusercontent.com/31961530/115866710-b9fb8f00-a442-11eb-93a0-ff55bfdf6c49.png)
![image](https://user-images.githubusercontent.com/31961530/115866728-bec04300-a442-11eb-86ae-24253f6797d8.png)
![image](https://user-images.githubusercontent.com/31961530/115866752-c67fe780-a442-11eb-80db-6988b4b789f4.png)
