### ISSUE TITLE
Langpicker in Footer should be aligned with the column above it

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10415]
### Describe the problem and steps to reproduce it:

1. Browse any page on AMO, scroll down to see the footer

### What happened?

![Screen Shot 2021-04-19 at 09 40 43](https://user-images.githubusercontent.com/217628/115199266-51837980-a0f3-11eb-9c69-5c224f689117.png)

### What did you expect to happen?

The language picker should be aligned on the right side (for non-RTL locales). It should be aligned with the column above it, giving a bit more room for the paragraph on its left.

### Anything else we should know?

That might have regressed a while ago and it looks like a CSS grid problem. I was able to find this issue from a long time ago: https://github.com/mozilla/addons-frontend/issues/3407, and the mocks show that the langpicker should be aligned with the last column above it.

**Comment by Patil2099** [comment]
Hi, @willdurand  I would like to take this issue.

**Comment by AlexandraMoga** [comment]
This issue was verified on AMO stage, with FF88, Win10:

[LTR orientation]
![image](https://user-images.githubusercontent.com/31961530/117128597-4b092900-ada6-11eb-8343-a1805386810e.png)

[RTL orientation]
![image](https://user-images.githubusercontent.com/31961530/117128097-a25ac980-ada5-11eb-92b6-958d4f0e5475.png)

[mobile]
![image](https://user-images.githubusercontent.com/31961530/117128111-a7b81400-ada5-11eb-82cd-8667e5379d1c.png)
