### ISSUE TITLE
Error messages should make it clear what field(s) have error(s)

### ISSUE THREAD

**Issue by tublitzed** [mozilla/addons-frontend#10516]
### Describe the problem and steps to reproduce it:

On this page: https://addons.mozilla.org/en-US/firefox/users/edit

I went to rename my username and got a "this field cannot be null" error at the top. No fields were highlighted. A bunch were empty though.

So...I filled them all in with a single character. Now, I see a "Ensure this field has at least 2 characters."

What field? As a user, I would have an easier time editing my account if I understood which fields had errors.

Guessing maybe we used to have field highlighting here and now it's missing?

### What happened?

Errors with unexplained linkage to form fields.

### What did you expect to happen?

Able to edit my profile without guessing which field has an error.

### Anything else we should know?

![Screen Shot 2021-04-29 at 5 33 01 PM](https://user-images.githubusercontent.com/1756056/116621355-0a765f00-a911-11eb-861d-6eaffc681e6c.png)

**Comment by willdurand** [comment]
I think you have privileges on AMO, seeing the "reviewer name" field. This is the field that throws the error because all other fields are optional (except display name). There should be an asterisk on the reviewer name but we probably missed that given that it does not appear for most users.

As for the error messages, I think we have issues for what you suggested. It likely requires some API work before we can update the UI, though.

**Comment by willdurand** [comment]
Maybe related: https://github.com/mozilla/addons-frontend/issues/9217
