### ISSUE TITLE
Rename blog to Firefox Add-on Reviews

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#10645]
We link to the new blog on the footer and the More menu. Currently it's just labelled as Blog, but let's call it Firefox Add-on Reviews instead.

**Comment by wagnerand** [comment]
@jvillalobos This clashes with our current definition of Add-on Reviews, which is something entirely different. Could we use a different name?

**Comment by jvillalobos** [comment]
If it ends up causing user confusion we will reconsider. I don't think it should be much of a problem, given that the forum name isn't too prominent.

**Comment by ioanarusiczki** [comment]
@willdurand 

- "Firefox Add-on Reviews" is displayed : in the More menu and footer.

- I filed  an issue on the blog repo - https://github.com/mozilla/addons-blog/issues/224 because there's "Blog" too present in the Menu.

- is the URL ok with /blog? https://addons-dev.allizom.org/blog/ 

![on dev blogname](https://user-images.githubusercontent.com/33448286/121018555-6d9ab300-c753-11eb-971f-1ef881cdeb83.gif)

**Comment by willdurand** [comment]
>     * I filed  an issue on the blog repo - [mozilla/addons-blog#224](https://github.com/mozilla/addons-blog/issues/224) because there's "Blog" too present in the Menu.

Indeed, we need to update the shared library now.

>     * is the URL ok with /blog? [addons-dev.allizom.org/blog](https://addons-dev.allizom.org/blog/)

Yes.
