### ISSUE TITLE
Stop showing AddonInstallError and AddonCompatibilityError for any versions other than the current one

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10649]
We removed the install buttons from all versions on the All Versions page, except for the current version, awhile back, but we still display a compatibility error, and an install error, on each version on the page, when applicable.

We really should never be showing that install error on any of these, as any errors that occur during the installation of the current add-on will end up appearing with all the versions. Also, while it's true that different versions may have different compatibilities with the current browser, it seems unnecessary, and ugly, to display the compatibility error for every old version.

This issue is about removing both of those types of messaging from all older versions, and only maintaining them for the latest version. See the attached screenshot for an example of the AddonCompatibilityError.

![Screen Shot 2021-06-03 at 1 10 33 PM](https://user-images.githubusercontent.com/142755/120686074-99c1e580-c46e-11eb-9e01-63fd57500537.png)

@jvillalobos Can you comment on whether this makes sense to you?

**Comment by jvillalobos** [comment]
I think it'd be great if we do the same as we plan to do for listing pages, which is to show the new UX with the button and the message bubble (only for the latest version), and not show compat error messages at all.

**Comment by bobsilverberg** [comment]
> I think it'd be great if we do the same as we plan to do for listing pages, which is to show the new UX with the button and the message bubble (only for the latest version), and not show compat error messages at all.

The change proposed in https://github.com/mozilla/addons-frontend/issues/10637 will also apply to this page, so we will "automatically" get the new CTA here as well, but thanks for calling that out.

**Comment by AlexandraMoga** [comment]
I've created add-on versions with different compatibility statuses and checked the compatibility messages displayed on the detail and on the All versions page. The All versions page now shows compatibility messages only for the Latest version:

[higher compatibility]
![image](https://user-images.githubusercontent.com/31961530/121170458-e9812200-c85d-11eb-9c10-fa89526ac632.png)

[lower compatibility]
![image](https://user-images.githubusercontent.com/31961530/121170529-00277900-c85e-11eb-8534-fc87ff5e2255.png)

[platform compatibility]
![image](https://user-images.githubusercontent.com/31961530/121170543-061d5a00-c85e-11eb-87f4-11791fcb43fe.png)

@bobsilverberg I understand that #10637 will change the style of the higher incompatibility message to be more in line with the non-Firefox CTA. Should we also think about including the other compatibility messages that are still displayed as a red banner in order to have a more unified style?

**Comment by bobsilverberg** [comment]
> 
> @bobsilverberg I understand that #10637 will change the style of the higher incompatibility message to be more in line with the non-Firefox CTA. Should we also think about including the other compatibility messages that are still displayed as a red banner in order to have a more unified style?

This is a good question, @AlexandraMoga. I did not address the other types of messages as none of them currently prompt the user to download the latest version of Firefox, but this is worth considering. Can you open a new issue suggesting this and we can discuss it there?
