### ISSUE TITLE
Always show the correct URL when the download button is clicked

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10681]
Followup for https://github.com/mozilla/addons-frontend/issues/10600

I tested and reproduced with VM - Sandbox (but also on Win10x64 with installed Edge and Chrome browsers) this: when I have the new-link experiment set and click on a download button from AMO for the first time, I land on https://www.mozilla.org/en-US/firefox/download/new/.  I go back and click again a download button from AMO and now I am redirected correctly to https://www.mozilla.org/en-US/firefox/download/thanks/

![the new page not available1](https://user-images.githubusercontent.com/33448286/121902945-a64f0500-ccdc-11eb-9830-b5f887daa20a.gif)

Expected:
It should always redirect to https://www.mozilla.org/en-US/firefox/download/thanks/

Notes:
Reproducible on AMO dev - FF89(Win10).

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. I have a few questions:

1. When you say "when I have the new-link experiment set", do you mean when the cookie exists and contains that value?
2. Is this always reproducible, or only on occasion?
3. Can you check whether this happens only with server-side or only with client-side rendering? For server-side rendering, refresh the browser and then start the test. For client-side rendering, refresh the browser, navigate to a new page, and then start the test.
4. Can you also test, both with server-side and client-side rendering, what happens when you *do not* already have a cookie set?

**Comment by ioanarusiczki** [comment]
@bobsilverberg I'm sorry I did not see your comment earlier. 
I remember this issue was reproducible 5/5 as I described above when the cookie's value contained `new-link`. 
I cannot reproduce this issue anymore.
