### ISSUE TITLE
Use the `page_count` returned from the API response to determine the maximum number of pages for pagination links

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10689]
This was discovered during the investigation of https://github.com/mozilla/addons-server/issues/17362.

According to @diox:

"We have configured Elasticsearch in a way that doesn't allow pagination to go past 25000 items (1000 pages of 25). The search API returns a 404 on purpose here."

Therefore, we should not base the maximum number of pages that we use for pagination links on a calculation, but rather we should use `page_count` which is returned to us in the API response.

**Comment by AlexandraMoga** [comment]
We had an issue opened for this since the beginning of the new frontend, but we never got to fixing it :) - https://github.com/mozilla/addons-frontend/issues/3887

**Comment by bobsilverberg** [comment]
Wow, yeah, that's an old issue! Thanks @AlexandraMoga!

**Comment by diox** [comment]
Given that there is an API field returning the page count, I think the frontend should use that. We should probably close this and re-open the old one...

**Comment by bobsilverberg** [comment]
Reading through the old issues, I'm not sure it makes sense to re-open any of them, as they are somewhat confusing. Let's just rename this one to have it be about using `page_count`.

**Comment by oopsalljake** [comment]
I can take this on. I looked into it a little bit already; it's not a complicated change but it does touch a lot of files.

My plan is to make `pageCount` a required prop on `Paginate` (and remove its computed `pageCount()` and props that were only used for the computation), and to update the relevant reducers/sagas to store the page count returned from the API so they can be used in the paginator.

**Comment by mihaidogaru2537** [comment]
Hello! I was thinking of giving this a shot and I tried to reproduce by following the steps from [#3887](https://github.com/mozilla/addons-frontend/issues/3887) but unlike shown in that example, I get 0 search results.

Was this fixed? I was hoping to make this my very first open source pull request. Thank you!

**Comment by diox** [comment]
Hi! It's still valid, we have not fixed this. The URL in that issue linked before is no longer valid because we switched away from `persona` and the limit is now at 30000 instead of 25000 (https://github.com/mozilla/addons-server/issues/19794)

Updated steps to reproduce:
- Search for themes on -dev
- Go to page 1200 (you can use the direct URL https://addons-dev.allizom.org/en-US/firefox/search/?type=statictheme&page=1200)

Expected results:
- You shouldn't see pagination links to page 1201 and beyond (because we should obey the `page_count` the API returns instead of computing it ourselves - note that the API also doesn't return a `next` for page 1200)

Actual results:
- You see a link to page 1201 (which raises an error when you go to it - *that* is expected, the API returns that error)

**Comment by mihaidogaru2537** [comment]
Thanks for the update.
It helped me produce the PR from above, I hope we'll be able to close this issue together!

**Comment by vcarciu** [comment]
Verified as fixed in AMO Stage:
![1200](https://user-images.githubusercontent.com/1583842/214547389-711a28bf-a026-49bb-b73e-4d1c7fac6019.png)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-12
