### ISSUE TITLE
Shelf module pointing to blog post can trigger 404

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#10721]
We tried publishing a new shelf pointing to one of the new editorial posts on AMO, but ran into some issues. [Here's the shelf](https://addons-internal.prod.mozaws.net/en-US/admin/models/discovery/shelfmodule/7/change/).

The contents of the shelf come from a collection, so the only issue is the "footer" link, which in this case points to `blog/translate-the-web-easily-with-a-browser-extension/`. On the front end, we saw the URL being transformed to `/en-US/firefox/blog/translate-the-web-easily-with-a-browser-extension/`. Now, [that URL](https://addons.mozilla.org/en-US/firefox/blog/translate-the-web-easily-with-a-browser-extension/) works correctly and redirects to the right page if you load it in a new tab, but it seems to glitch between the right page and a 404 if you click on it in the homepage.

I suppose the easier fix here is to not add the `/en-US/firefox/` to blog links, but the other glitch might also be worth investigating.

/cc @devaneymoz @willdurand

**Comment by willdurand** [comment]
> We tried publishing a new shelf pointing to one of the new editorial posts on AMO, but ran into some issues. [Here's the shelf](https://addons-internal.prod.mozaws.net/en-US/admin/models/discovery/shelfmodule/7/change/).

I cannot see it but I don't think the footer link can accept any URL.

**Comment by bobsilverberg** [comment]
> > We tried publishing a new shelf pointing to one of the new editorial posts on AMO, but ran into some issues. [Here's the shelf](https://addons-internal.prod.mozaws.net/en-US/admin/models/discovery/shelfmodule/7/change/).
> 
> I cannot see it ~but I don't think the footer link can accept any URL.~ Edit: we can accept _any_ URL so we need to change our code to detect "internal" URLs differently.
> 
> @bobsilverberg if we want to truly accept any URL, I don't think we should keep this `checkInternalURL()` call because checking the host isn't enough. The problem would be similar with other URLs served by addons-server, likely because the client-side navigation isn't able to navigate to such URLs as they aren't served by addons-frontend (the react router doesn't know them). Removing the function call mentioned above would trigger a page reload but that isn't so much a problem these days (with caching). WDYT?

I recall we had this discussion when implementing the new shelf logic, and it was determined that we do still want to treat internal links as internal links and external links as external links. If I'm understanding it correctly, your suggestion is that we treat all footer links as external links. I'm wondering if a better solution would be to change the logic of `checkInternalURL` to add an exclusion for the blog. It is highly unlikely that we would ever use a URL that points to a page served by addons-server for a shelf footer. WDYT?

**Comment by willdurand** [comment]
> If I'm understanding it correctly, your suggestion is that we treat all footer links as external links

Yes. I don't like this term, though. All URLs containing the AMO domain are _internal_, it's just that some of them are served by addons-frontend, for which client side navigation can be used.

> I'm wondering if a better solution would be to change the logic of checkInternalURL to add an exclusion for the blog.

That doesn't sound better because if the exclusion list isn't comprehensive, we're back to where we are right now. I'd like to understand why we think we absolutely need to keep client side navigation (which seems to be the culprit) on these links?

> It is highly unlikely that we would ever use a URL that points to a page served by addons-server for a shelf footer.

As much as blog URLs indeed.

**Comment by bobsilverberg** [comment]
> > If I'm understanding it correctly, your suggestion is that we treat all footer links as external links
> 
> Yes. I don't like this term, though. All URLs containing the AMO domain are _internal_, it's just that some of them are served by addons-frontend, for which client side navigation can be used.
> 
> > I'm wondering if a better solution would be to change the logic of checkInternalURL to add an exclusion for the blog.
> 
> That doesn't sound better because if the exclusion list isn't comprehensive, we're back to where we are right now. 

Sometimes we need to write code to ensure a good user experience. It's our doing that the blog cannot be navigated to via client-side navigation, so perhaps we should deal with that, rather than make the experience worse for all navigations from shelf footers?

> I'd like to understand why we think we absolutely need to keep client side navigation (which seems to be the culprit) on these links?
> 

I think we just try to use client-side navigation whenever possible as it makes for a better user experience. I suppose we could do a full page reload for all shelf footers, but that seems like a worse user experience to me.

> > It is highly unlikely that we would ever use a URL that points to a page served by addons-server for a shelf footer.
> 
> As much as blog URLs indeed.

Actually, it was expected that we'd use blog URLs in shelf footers, so this isn't an accurate statement. We are not adding new, user-facing pages to addons-server, so I don't think it's equivalent to the blog at all.

**Comment by willdurand** [comment]
Very well then, let's update the `checkInternalURL()` function.

**Comment by bobsilverberg** [comment]
> Very well then, let's update the `checkInternalURL()` function.

By "let's" do you mean you, or do you mean me? 😉 I'm happy to do it if you'd prefer that.

**Comment by bobsilverberg** [comment]
> > Very well then, let's update the `checkInternalURL()` function.
> 
> By "let's" do you mean you, or do you mean me? 😉 I'm happy to do it if you'd prefer that.

@willdurand I'll take your lack of a reply as an indication that you'd like me to take this.

**Comment by ioanarusiczki** [comment]
@bobsilverberg On AMO dev I've noticed the following behavior:
- I added for 2 homepage shelves Footer pathname:`blog`, `/blog` or `/blog/`. 
Shelves are: the [first one](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/62/change/) on the homepage and the [last one](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/68/change/) 

Result: every time I clicked on the links from the homepage it resulted into a 404, At page refresh the right URL is loaded and the blog is displayed. 

![the blog page](https://user-images.githubusercontent.com/33448286/125076034-11b3a900-e0c8-11eb-8081-6711a1de0bf1.gif)

- I changed the pathname to `blog/watch-videos-with-friends-anywhere-how-to-social-stream-with-browser-extensions/`

The footer pathname changes are not immediately visible on the frontend. There's a delay(every time I reloaded the page and clicked the URLs I had https://addons.allizom.org/blog/ displayed and this time without 404) ,then after a while the blog article above is displayed into a new tab without errors. It happened that on a profile the previous content (`blog`) was displayed but this time without 404s. So there's a delay in loading the new content after it's been modified.  
- I edited again the pathname for the last shelf (search extension endpoint) to `blog`. At first, the page was displayed without 404 errors. Then again, after some minutes I had the initial 404 behavior for this page.
- 
On AMO dev the blog articles seem to be working as expected but the blog's homepage has issues and there's a delay in updating the content on the frontend after editing the pathname field from django (I refreshed the page, cleared data, tried hard refresh too).

I've noticed that on AMO stage adding blog pages results into 404 at all times, (no matter it's a blog article or https://addons-dev.allizom.org/blog/)

**Comment by bobsilverberg** [comment]
@ioanarusiczki I'm not sure I follow everything you are saying above, but I think the first thing to consider is that the blog links will only work as expected if they are specified as fully qualified URLs (e.g., `https://addons-dev.allizom.org/blog/watch-videos-with-friends-anywhere-how-to-social-stream-with-browser-extensions/`). Anything that is a relative URL to a blog page won't work because our code will try to add the language and clientApp to it.

Are there cases above where there are still problems with a fully qualified blog URL?

**Comment by ioanarusiczki** [comment]
@bobsilverberg It doesn't have to be a full URL. 

When I add into the admin field `blog/whats-the-best-ad-blocker-for-you/` it is working. So, for the articles I don't need the full URL.

If I add only `blog` (this should be the homepage of the blog) - this is not working, I still have a 404 because the frontend adds en-US/firefox/. I also tried now the full URL https://addons-dev.allizom.org/blog/ and it can see the blog page just fine.
