### ISSUE TITLE
Remove InfoDialog and associated code

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10759]
The [`InfoDialog`](https://github.com/mozilla/addons-frontend/tree/master/src/amo/components/InfoDialog) component is no longer needed. We should remove it and any code that references it. This has been discussed in detail on Slack.

**Comment by willdurand** [comment]
> This has been discussed in detail on Slack.

1. We are going to remove the pref in FF as well given that it does not seem very useful these days.
2. We decided to remove the `InfoDialog` on AMO because it only shows a message _after_ the add-on is installed (post-install), which isn't necessarily super useful to end users. The pref is also disabled by default in clients, meaning users should never see this `InfoDialog`.
3. This `InfoDialog` was added for Discopane a long time ago and it isn't clear why or when it was added to AMO.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

With extensions.webextPermissionPrompts set to False - the info dialog displayed on the right side of the screen is no longer displayed. 

![without info box on the right](https://user-images.githubusercontent.com/33448286/125629180-f373b0c3-8536-4298-9ae9-ddfeca587c12.gif)

- I could enable extensions/themes.

I tested this with extensions, also with a static theme, a dictionary and lang pack. - FF 90.0 unbranded
