### ISSUE TITLE
Invalid category and tag pages produce unexpected errors when some symbols are used in the url

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10879]
### Describe the problem and steps to reproduce it:
1. Try to open the following invalid category page - https://addons-dev.allizom.org/en-US/firefox/extensions/category/?appearance/
2. With the browser console opened, verify the page that is being opened

### What happened?
The page is redirected to https://amo.dev.mozaws.net/en-US/firefox/extensions/category/category/ and the page is opened with css not loaded:
![image](https://user-images.githubusercontent.com/31961530/132326012-99a87d86-8611-49fa-b617-b3e77b15a11c.png)
This seems to happen because I've introduced a symbol - `?` - at the beginning of the searched category page

### What did you expect to happen?
I think the redirect should not occur and a 404 for the invalid category should be triggered in the frontend

### Anything else we should know?
- other unhandled symbols: `%`, `.`, `#`, with a note that `.` only triggers an unexpected response when used without additional characters
- the behavior on stage and prod is a bit different from -dev - i.e. stage and prod will load the css, but the redirect still occurs
- I've also checked the `/tag/` urls since they are constructed in a similar way to `/category/` urls. In this case, the only symbol that seems to cause problems is `%`, but the response is different. 

For example, invalid tags like https://addons-dev.allizom.org/en-US/firefox/tag/%abc/ will result in a 500 error (also seen on stage and prod):
![image](https://user-images.githubusercontent.com/31961530/132323930-8ef578ba-2a95-40d7-ab10-d94f41855b5f.png)

And valid tags like https://addons-dev.allizom.org/en-US/firefox/tag/%chat/ triggers a 400 Error from cloudfront (dev and stage) or nginx (prod):
![image](https://user-images.githubusercontent.com/31961530/132323961-b5479840-f73c-430b-9b55-b5db8342f16e.png)

**Comment by diox** [comment]
Following fixes to https://github.com/mozilla/addons-frontend/issues/10887, https://addons-dev.allizom.org/en-US/firefox/extensions/category/?appearance/ now redirects to https://addons-dev.allizom.org/en-US/firefox/extensions/category/category/ instead, which is an error page, but loads fine.

https://addons-dev.allizom.org/en-US/firefox/tag/%abc/ still is a 500
https://addons-dev.allizom.org/en-US/firefox/tag/%chat/ still is a 400

We don't really care about the 400, it'd be nice to fix the 500 but it's not a high priority. It's caused by node trying to interpret the `%` as percent encoding:
```
URIError: Pathname "/en-US/firefox/tag/%abc/" could not be decoded. This is likely caused by an invalid percent-encoding.
    at createLocation (/srv/node/node_modules/history/cjs/history.js:110:13)
    at /srv/node/node_modules/history/cjs/history.js:835:40
    at Array.map (<anonymous>)
    at createMemoryHistory (/srv/node/node_modules/history/cjs/history.js:834:32)
    at _createHistory (/srv/code/src/amo/server/base.js:50:14)
    at /srv/code/src/amo/server/base.js:270:23
    at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
    at /srv/node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
```

**Comment by diox** [comment]
(Note that even if we don't care much about these weird errors in particular, I do appreciate you filed this: it gave me more insight into what the root cause of https://github.com/mozilla/addons-frontend/issues/10887 would be, which was definitely important to fix. So it was still a nice find, even if ultimately this is a low priority issue)

**Comment by willdurand** [comment]
The URIError was found earlier this year: https://github.com/mozilla/addons-frontend/issues/10061
