### ISSUE TITLE
Display a link to the AddonQRCode on the add-on detail page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10905]
An `AddonQRCode` component will land via https://github.com/mozilla/addons-frontend/issues/10800.

This issue is about creating a link on the add-on detail page that can be clicked on to reveal the add-on QR code panel. For now we will put this link behind a flag, as we don't want it to appear until we are ready to run the experiment.

For QA:
Now all of the functionality of the QR code feature can be tested. Here is the expected behaviour:
- A link to view the QR code should be displayed on the add-on detail page, only on /firefox/ URLs, and only for add-ons that are currently installable on Fenix. The list of installable add-ons is the same as the list of recommended add-ons for Android. 
- Note that for this implementation, a list of `addonIds` is being used to enforce this, not the response from an API, so the list of ids is currently the same on all environments. This means that an add-on that is recommended on Android on dev might not be part of this list. Here is the current list of ids: `229918, 328839, 506646, 520576, 521554, 607454, 627490, 722, 735894, 811592, 824288, 855413, 866226, 869140, 953945, 9609`. On dev, the add-on `youtube-high-definition` happens to have an id in this list, so it will work for testing.
- When clicking the link, a panel should appear that displays the QR code, as well as a link to the detail page for the add-on on the /android/ site. 
- When scanned, the QR code should take the user to the detail page for the add-on on the /android/ site.
- For both the link and the QR code, utm params should be present for:
	- utm_source=addons.mozilla.org
	- utm_medium=referral
	- utm_campaign=addon-qr-code
	- utm_content={addonId}
- When clicking on the link to open the panel, a GA event should be sent with:
	- action: "addon-qr-code-impression"
	- category: "Addon QR Code"
	- label: "{addonId}"
- When clicking on the link *in* the panel, under the QR code, a GA event should be sent with:
	- action: "addon-qr-code-click"
	- category: "Addon QR Code"
	- label: "{addonId}"
- Clicking either outside of the panel, or on the dismiss button in the top-right corner of the panel, should hide the panel.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
1. I tested this with https://addons-dev.allizom.org/en-US/firefox/addon/youtube-high-definition/ using FF92 and Edge on Desktop.

- the requirements described above all look good to me. 

_Note:_ when "this link" is clicked the addon's URL changes into the address bar to https://addons-dev.allizom.org/en-US/android/addon/youtube-high-definition/?utm_source=addons.mozilla.org&utm_medium=referral&utm_campaign=addon-qr-code&utm_content=328839 into the same tab .Then, for example, the link can be copied and send via e-mail to an android device.

![copy link](https://user-images.githubusercontent.com/33448286/134904955-0a4fa94d-7f37-4ad8-9603-ea3c6cad50a9.gif)


Please let me know if that's the intended behavior for copy link. 

2. I was thinking to test this with at least one more addon from the list of id's mentioned above but right now I cannot access the fenix collection with admin because of https://github.com/mozilla/addons-server/issues/17970 I'll try again later this week.

**Comment by bobsilverberg** [comment]
That all sounds fine, @ioanarusiczki. The link is behaving in the way I would expect. I suppose the main purpose of the link it to allow users to copy it, and not necessarily click on it, but if you do click on it the behaviour your described is expected.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
1. I've noticed that the link contains utm_campaign=addon-qr-code and when scanning the code utm_campaign=amo-fenix-qr-code. 
I hope that's fine. 

2. This is how the URL is generated after scanning the code:
![scanapp](https://user-images.githubusercontent.com/33448286/135071939-32d40b2d-8c87-461b-b5e9-b1d7a2215545.png)

I could open it with FF and Chrome - the URL redirects to the addon from AMO prod which I believe it's expected.

**Comment by willdurand** [comment]
>     1. I've noticed that the link contains utm_campaign=addon-qr-code and when scanning the code utm_campaign=amo-fenix-qr-code.
>        I hope that's fine.

I think the links should be the exact same.

**Comment by ioanarusiczki** [comment]
@willdurand I filed a followup and I'll mark this verified on -dev with FF92(Win10) and Android.
