### ISSUE TITLE
Pass `app` to the Recommendations endpoint

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10912]
### Describe the problem and steps to reproduce it:

1. Go to https://addons.mozilla.org/en-US/android/addon/ublock-origin/ with either Fenix or FF Desktop

### What happened?

The URL pointing to the XPI contains "firefox" instead of "android".

### What did you expect to happen?

The URL should always contain "android" because we fixed this bug in https://github.com/mozilla/addons-server/issues/16597 (see also https://github.com/mozilla/addons-frontend/issues/10100).

### Anything else we should know?

This happens because we load recommendations (the card below the description card), which are not for "Android" but for "Firefox" (maybe because we don't pass `app` or something else). When loading the recommendations, we seem to update the `addons` state with the new data, thus updating the download URL.

This is reproducible with uBlock Origin because it is very likely to be recommended. It does not happen with all add-ons compatible with Fenix.

This issue is reproducible on all envs, and it breaks the nice install flow we have in Fenix (instead of opening the Add-ons Manager, it downloads the XPI).

**Comment by willdurand** [comment]
Looks like we can pass the `app` parameter to the Recommendations API endpoint (even if it isn't documented). Let's do this.

**Comment by ioanarusiczki** [comment]
@willdurand I reproduced the issue on prod with Search by Image and uBlock. I'll check this today, I'm on it

**Comment by ioanarusiczki** [comment]
@willdurand 
On production the way I could reproduce this was:
- with Search by Image and uBLock Origin
- opening a new tab and going on the android detail page, checking the URL, I get https://addons.mozilla.org/firefox/downloads/file/3815277/search_by_image-3.7.1-an+fx.xpi which will trigger a download instead of an install. If I navigate away from the detail page and return to it, the second time I will get the correct URL so it seems to be reproducible only the first time I landed onn the detail pages when opening AMO with a new tab.
- reason why this affects only 2 addons on production is explained https://github.com/mozilla/addons-frontend/issues/10912#issue-1002422289. Indeed, I could not reproduce it with the rest of the addons, which are not displayed into the recommendation card.

on AMO stage:
- I added the addons from the recommendation card into the fenix collection and also made all of them compatible for All Platforms. I did not have them into the fenix list (reason why this bug was not observed on stage). I tested the installs with: 
https://addons.allizom.org/android/downloads/file/1097987/searchbyimage-4.0-an+fx.xpi
https://addons.allizom.org/android/downloads/file/1097988/enhancerforyoutubetm_enhancerforyoutubetm-1.0-an+fx.xpi
https://addons.allizom.org/android/downloads/file/1097989/ublock_origin-1.0-an+fx.xpi

The issue looks fixed to me.

**Comment by ioanarusiczki** [comment]
@willdurand I made some check on production today, and found some issues again. I filed https://github.com/mozilla/addons-frontend/issues/10920
