### ISSUE TITLE
utm_campaign should have `addon-qr-code` as value when scanning the code

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10927]
Followup for https://github.com/mozilla/addons-frontend/issues/10905

STR:
1. Using a  QRcode app - I scanned the code for https://addons-dev.allizom.org/en-US/firefox/addon/youtube-high-definition/

The URL displays for utm_campaign `amo-fenix-qr-code` instead of utm_campaign=addon-qr-code

**Comment by bobsilverberg** [comment]
This issue is about the fact that the QR code contains a link with `utm_campaign` of `amo-fenix-qr-code`, while the html link in the panel contains a `utm_campaign` of `addon-qr-code`.

Although this was not intentional, I think it could be valuable to use a different, but similar, campaign string for each. This would allow us to understand how users are interacting with this panel. I.e., how many users are making use of the QR code vs. how many users are copying and using the link.

For this reason, I think we should use the following values for `utm_campaign`:
- Use `addon-qr-code` for the link embedded in the QR code.
- Use `addon-qr-code-link` for the link displayed in the panel.

This will make it easy to aggregate the results in GA, if we want to know data about all clicks on both versions, and it will also allow us to report separately on the two different types of links.

**Comment by willdurand** [comment]
sorry wrong button...

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- the link is : utm_campaign=addon-qr-code-link
- when scanning it: utm_campaign=amo-fenix-qr-code. Should it be addon-qr-code?
- I checked stage but the link "Also available on Firefox for Android" is only present on -dev.

**Comment by willdurand** [comment]
> when scanning it: utm_campaign=amo-fenix-qr-code. Should it be addon-qr-code?

mmm we should cache-bust the images probably...
