### ISSUE TITLE
Make CSS consistent in the tree

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1100]
Talked with @muffinresearch on IRC, I think we landed on moving `lib` into `inc` just to make things a bit easier to follow. I get the distinction, but some apps weren't even using it and I think it's more confusing than useful 😄

**Comment by muffinresearch** [comment]
Perhaps just move the buttons file [1] up into the `css` dir since it's just the CSS for buttons for the admin?

As the buttons file isn't a mixin or a var or something **inc**luded in other sass files it probably doesn't belong in `inc`.

[1] https://github.com/mozilla/addons-frontend/blob/master/src/admin/css/lib/buttons.scss

**Comment by tofumatt** [comment]
Ah, good point. Mainly I wanted to ditch the confusing two folders that
seem similar, so that works for me.

**Comment by kumar303** [comment]
related to consolidating component layout: https://github.com/mozilla/addons-frontend/issues/1260

**Comment by willdurand** [comment]
Done along with #1260.
