### ISSUE TITLE
drop authTokenValidFor and timer that auto-logs the user out after X time

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#11020]
in https://github.com/mozilla/addons-server/pull/18185 SESSION_COOKIE_AGE will be changed to 5 days, from 30 days; frontend needs to stay in sync so it knows when to show the user as logged out

**Comment by diox** [comment]
Some notes as I investigated `authTokenValidFor` a bit more.

Currently, the only reason `authTokenValidFor` exists is for the frontend to automatically log out the user if they have an expired token (that's different from https://github.com/mozilla/addons-frontend/issues/9482, which handles a token being no longer valid because the user explicitly logged out from elsewhere).

The code that uses that config variable is: https://github.com/mozilla/addons-frontend/blob/193656da70a5922740024db944bd432b03487917/src/amo/components/App/index.js#L149-L204

Essentially setting up a `setTimeOut` to log the user out when the token expires, to avoid making requests with an expired token.

As far as I understand it, this is mostly meant for client-side rendering - for server-side rendering, we'd likely no longer have the cookie anyway (it would have expired and wouldn't be sent by the browser). 

Side note: It only does this when the delay would be less than `maximumSetTimeoutDelay`, which is `2147483647`. With the current 30 days expiration, it's also only relevant when the user has already been logged in for a few days, because `30*24*60*60*1000 > 2147483647`.

**Comment by diox** [comment]
So, with our planned strategy of having a shorter expiry (5 days), issuing a new token when the underlying FxA token has expired, the following can happen:
- Someone logs in, navigates etc.
- Sometime before the FxA token expires, they leave a tab opened
- They open a new tab, navigate etc. Since the FxA token has expired, we issue a new frontend token
- They come back to their original opened tab. From there:
  - Either the 5 days from the original log in date are up, and the client-side logout is triggered. They end up mildly confused because of this, as they are still logged in if they refresh, but it should be ok.
  - Or the 5 days are not up yet, the frontend token is not seen as expired, only the corresponding FxA token has, so when they make a request, we end up refreshing the FxA token, generating yet _another_ frontend token, but it should all work transparently. In their other tab, they have a different frontend token, but that should still work as well. When they refresh either page, they'll get the latest cookie that has been set.

That should be fine but we need to verify I'm right.

**Comment by eviljeff** [comment]
If we handle auth tokens being invalid (API returning a 401 - #9482) properly then we could remove the timer and just leave the user (apparently) logged in.  The next time they did something that caused an API request they'd either be silently reauth'd without them knowing (if another tab had refreshed the token within 5 days) or they'd be prompted/redirected to reauth with FxA

**Comment by eviljeff** [comment]
repurposing this issue as per https://github.com/mozilla/addons-frontend/issues/11020#issuecomment-970159001

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some str for qa. 
Thanks!

**Comment by ioanarusiczki** [comment]
@eviljeff

Login Expired page was displayed when going on the detail pages after 5 min as in https://github.com/mozilla/addons-frontend/issues/11014
Also, depending on what page I was on I've seen a red warning as I described in https://github.com/mozilla/addons-server/issues/14730#issuecomment-1021032062 , I reproduced today while creating a collection. 
For the red warnings and repeated 401 errors I know that an issue has been filed https://github.com/mozilla/addons-frontend/issues/11109 

Verified on -dev
