### ISSUE TITLE
Recover from syntax error while running karma in a loop

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1103]
### Describe the problem and steps to reproduce it:
- run the karma dev server in a loop, for example `npm run unittest:dev`
- create a syntax error in one of the source files
### What happened?

The karma runner dies with something like this:

```
Module build failed: SyntaxError: Unexpected token (19:4)

  17 |     i18n = getFakeI18nInst(),
  18 |     createRating = () => {}
> 19 |     ...customProps
     |     ^
  20 |   } = {}
  21 | ) {
  22 |   const props = {

21 09 2016 22:36:12.588:ERROR [karma]: [Error: Syntax error encountered, bailing]
```
### What did you expect to happen?

The karma loop should continue running, waiting for you to fix the syntax error. Otherwise, you have to fix it and wait for karma to restart which takes a couple seconds and slows you down.
### Anything else we should know?

I don't know if this is possible but it's worth looking into!

**Comment by muffinresearch** [comment]
That happens because we require test syntax errors to cause the tests to fail. 

However, we should be able to modify this conditional to not throw if we can detect we're running tests in the watch mode.

https://github.com/mozilla/addons-frontend/commit/4db9f36b3d5a3c147e6737d16cf78c2ad61abed9#diff-a2a3b7b0c9c3b4b93b4aebf4e3ec3cfbR51

**Comment by muffinresearch** [comment]
I'll take a look at fixing this...
