### ISSUE TITLE
Deal with themes page on android

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#11331]
https://addons.mozilla.org/en-US/android/themes/ is weird. Since Firefox for Android doesn't support themes anymore, it really shouldn't exist. But it does, and although the main block finds no themes, the "Recommended Themes" and "Top rated themes" and "Trending themes" block show up, and are filled with... extensions.

You can currently find it from the blog (https://github.com/mozilla/addons-blog/issues/331) but also just if you stumble upon it from past links. I think ideally we should keep this page with just a warning about how themes are not supported for Android. We might also want to fix the relevant components for the 3 blocks mentioned above to ensure we can never end up in this weird situation where we pretend those blocks are going to show themes when actually they are displaying extensions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-26)

**Comment by diox** [comment]
Still not ideal. If we could get some idea of what it should look like we could mark this as a `contrib: welcome` ...

**Comment by ioanarusiczki** [comment]
@willdurand 

I checked with Fenix 119.0 on AMO dev:

- add-ons blog no longer displays the header menu
- theme category pages throw a 404 on Android
- the only way to access themes pages is using `firefox` in the url , for example going to a  themes search result such as
https://addons-dev.allizom.org/en-US/firefox/search/?promoted=recommended&sort=random&type=statictheme
with `android` I'd see extensions instead of themes. 

Add-on blog:

![no themes](https://github.com/mozilla/addons-frontend/assets/33448286/ba50689e-f327-490b-bd58-5c7ab7664558)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-26
