### ISSUE TITLE
Stop trying to enable themes after install

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#11600]
Some code was added a while ago, in https://github.com/mozilla/addons-frontend/issues/5681, to enable themes (and only themes) after install. This was meant for the disco pane, and to work around around https://bugzilla.mozilla.org/show_bug.cgi?id=1477328.

Disco pane is no longer an AMO thing (it's in client) and that bug has long been fixed, so we shouldn't need to do that anymore: installing a theme should just immediately switch to it without us having to do anything about it.

That would mean we could remove some logic around `isAddonEnabled`, too, which seems to only exist to support that use-case.

**Comment by diox** [comment]
QA: installing themes (whether the user had them installed already or not) should work as usual and immediately enable the theme, changing the button on the detail page once installed.

**Comment by AlexandraMoga** [comment]
I haven't found issues with theme installations on -dev - the button states change as expected when managing installations from the frontend or from about:addons.

I still have to verify the "whether the user had them installed already or not" on stage tomorrow, because I didn't have any themes from AMO already installed on my -dev profiles to check this part.

**Comment by AlexandraMoga** [comment]
If a user had themes already installed from AMO, they will remain  enabled. Also, if other themes were installed but are in a Disabled state in about:addons, once they are Enabled, the button states change as expected both in about:addons and on AMO.

This issue is verified fixed on stage.
