### ISSUE TITLE
500 server error on https://addons.allizom.org/en-US/firefox/Extensions/

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#11788]
Followup for https://github.com/mozilla/addons-frontend/issues/11644#issuecomment-1192503594

When upper case is used for https://addons.allizom.org/en-US/firefox/Extensions/ or https://addons.allizom.org/en-US/firefox/Themes/ it results into a 500 sever error 

![server error](https://user-images.githubusercontent.com/33448286/181724717-71881c24-e5f2-4770-8ffd-35f48e3c2efe.png)

which is reproducible on all AMO servers

**Comment by bobsilverberg** [comment]
This is a problem that has always existed. Using a value in the URL for either `extensions` or `themes` that has mixed case (e.g., `Extensions`, or even `eXtensions`) ends up throwing an error when [our code that tries to translate that part of the URL](https://github.com/mozilla/addons-frontend/blob/master/src/amo/utils/index.js#L265-L270) is executed.

There are a couple of ways we can address this:
1. We could update the code referenced above to use `.toLowerCase()` which would make the string compatible with the code as is, and would allow a URL with `Extensions` (for example) to work.
2. We can update the code in the `Route` for this and other pages that use this URL part, to add `sensitive`, which would make them case sensitive and would yield a 404.

Option 2 is probably the most correct, because really, these are not valid URLs, and we would never have generated any links to them, but option 1 is, I suppose, more user friendly, as it would allow the URLs to work even with an incorrect case. I am therefore going to opt for option 1.

**Comment by ioanarusiczki** [comment]
@bobsilverberg This is no longer reproducible on AMO dev, FF103(Win10, Edge)

![uppercase](https://user-images.githubusercontent.com/33448286/184861438-6450d003-0d60-4e23-a3e1-2ed7072da173.gif)
