### ISSUE TITLE
Display name overlaps the search bar at 900 px  

### ISSUE THREAD

**Issue by Carmentataru** [mozilla/addons-frontend#11824]
Display name overlaps the search bar at 900 px  

Steps to reproduce:  

1. Launch AMO homepage   

2. Access Edit my profile   

3. Set a long display name (at least 19 characters)   

4. Change the language to any available one  

5. Observe display name 

Expected results:   

The display name should be correctly shown at any resolution   

  
Actual results:  

The display name overlaps with the search bar upon changing the resolution to 900 px on any language  

Notes: This issue is reproducible on all AMO servers  
<img width="1105" alt="Display name overlaps the search bar2022-09-08 at 13 13 27" src="https://user-images.githubusercontent.com/112865359/189110304-c66c2a1d-35b6-4627-95c5-1b58486a346c.png">

**Comment by BhavyaT-135** [comment]
Hi @ioanarusiczki , could I give this issue a try? 😊

**Comment by Marble879** [comment]
Hi @diox, is it possible to work on this/has it already been solved? I took a look into this, and think I may have found a fix:
![image](https://user-images.githubusercontent.com/68125677/216839961-7ff7205b-673e-4d34-afe6-85dcbe95bea7.png)

**Comment by diox** [comment]
It it's still an issue, and nobody is working on it, feel free to submit a pull request. Note that a solution needs to work in right-to-left languages as well, and not break at other window sizes (you can see in our CSS we have multiple breakpoints already).

**Comment by Marble879** [comment]
Great, thank you!

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I still get the overlap at one point for other languages , el or bg.

Another thing I've noticed is that when the display name is between the  and I hover over it, the user menu won't open.  That would be a different bug.


![no menu](https://user-images.githubusercontent.com/33448286/220048514-05eff43a-134a-42c5-a144-81a4aa5020dc.png)

That does not happen when the name overlaps the search bar, the user menu will be displayed.

![at hover](https://user-images.githubusercontent.com/33448286/220048951-7dd8400e-7833-4651-b006-367c8074b9ae.png)

**Comment by bobsilverberg** [comment]
@ioanarusiczki I see that there is still a bit of overlap for a small number of screen widths in some languages (e.g., in `el` the overlap happens between 900 and 967 pixels in width), but I am guessing that is because the rest of the text in the header is ending up too large. So I think a different fix is probably needed, but I also think this current fix is still better than what we had before, so perhaps we keep this in place but reopen the issue with a detailed STR.

As for the menu not working once the username drops down to a new row, that seems to be an old bug, as it also exists on stage. I think a separate issue should be filed for that, and I don't think that means we need to back this "fix" out. Do you agree?

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I was thinking the same because it did fix part of it yet not entirely. 

So in this case, I'll try to add more precise str for the overlapping problem into a new issue.
And file a separate issue for the Menu.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-97
