### ISSUE TITLE
‘’Request was throttled’’ message fails to be dismissed 

### ISSUE THREAD

**Issue by Carmentataru** [mozilla/addons-frontend#11885]
Steps to reproduce:

1. Launch AMO homepage https://addons.allizom.org/en-GB/firefox/ 
2. Navigate to Extensions https://addons.allizom.org/en-GB/firefox/extensions/ 
3. Select an extension  
4. Submit reviews until the throttle message appears  
5. Navigate to another addon page  

Expected:  
The message ‘’Request was throttled. Expected available in x seconds’’ should be dismissed after the page it’s changed or the time mentioned passed  

 Actual: 
The message fails to be dismissed after the page it’s changed or the time mentioned passed  

Notes: This issue is reproducible on all AMO servers
[Screen Recording 2022-10-12 at 16.10.48.mov.zip](https://github.com/mozilla/addons-frontend/files/9765143/Screen.Recording.2022-10-12.at.16.10.48.mov.zip)

**Comment by eviljeff** [comment]
Throttling is enabled on all environments (setting: `API_THROTTLING`) but would be bypassed if you have the permission `API:BypassThrottling` - the superpowers permission of `*:*` would give you this too, if you have that on stage.

**Comment by vyshnavrajs2019** [comment]
`{"detail": "Request was throttled. Expected available in 58 seconds."}`
This is the response to the API call. IMO, the delay (58 seconds in this case) should be a separate field in the response object. @bobsilverberg

**Comment by bobsilverberg** [comment]
The problem here is that errors from API calls are stored in the `errors` state, but that state is not reset when a new location is navigated to. When we navigate to a new add-on, the component is re-mounted, but that also seems to be the case when we click a star to record a rating, so we cannot simply clear the error in `componentDidMount`, otherwise we never see the error. We need to figure out what logic to use to clear the error when it needs to be cleared, but to keep it in place when we need it to be shown.

**Comment by diox** [comment]
> IMO, the delay (58 seconds in this case) should be a separate field in the response object. 

Note that throttling errors have their own HTTP status code (429) if we want to make a specific case for that.

**Comment by bobsilverberg** [comment]
It could be that we could simply clear all errors whenever a `LOCATION_CHANGE` occurs, as I cannot think of a case where we need to keep errors around between page navigations. I tried doing that and it seems to work for this case, but I'm not sure if there are some edge cases where it would cause a problem. It also causes a bunch of tests to fail, but that might have more to do with how the tests are written (i.e., dispatching errors before rendering a page) than with it being an actual problem. 

@diox @eviljeff @willdurand Does anyone have any thoughts about taking that approach?

**Comment by bobsilverberg** [comment]
> It also causes a bunch of tests to fail, but that might have more to do with how the tests are written (i.e., dispatching errors before rendering a page) than with it being an actual problem.
>

Of course, this might be a tricky thing to address, as we have tests where we are testing logic that a component doesn't dispatch actions on render when an error exists, and that might be hard to test if we cannot dispatch an error before rendering. And when we render it generates a `LOCATION_CHANGE` action, which is what makes the whole thing difficult. It's probably not insurmountable, but it might be annoying and a bunch of work. 

It might be better to just address this individual use case, rather than clear all errors when we navigate.

**Comment by bobsilverberg** [comment]
I found a simpler solution to this issue, which is based on the fact that the problem stems from the fact that we do not attempt to load a new rating if there has been an error. By changing that logic to go ahead and fetch a new rating when the error was a `429`, the problem goes away.

We still will see the throttled message when navigating to a new add-on detail page, but that is actually ok, because this throttling is not per add-on, but it per user, so the user is actually still throttled when navigating to the new page. The message will update with a new timeout if the user clicks a rating button, and once the time has elapsed clicking a rating button will record the new rating.

Another problem that existed prior to this fix was that the rating stars were disabled, so there was no way to submit a new rating even after the timeout elapsed. Now the rating stars are not disabled, allowing a user to try to submit a rating again. If they are still throttled, as described above, the message will update with a new number of seconds which must elapse.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

On -dev with an account without privileges after I get the throttling message and then I navigate on a new detail page -> the message is no longer displayed here. If I immediately make a new rating attempt without waiting the seconds displayed by the message (click on stars)  I'm getting a new throttle message. 

![the message is gone](https://user-images.githubusercontent.com/33448286/223092941-abf7726b-75cd-428e-8787-1cf686b7663b.gif)

I've noticed on -stage the issue described initially -> the message disappears only if I refresh the detail pages, even if the throttle period expired.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-104
