### ISSUE TITLE
Scrollbar disappears on addon detail page  

### ISSUE THREAD

**Issue by Carmentataru** [mozilla/addons-frontend#11909]
STR: 
1. Launch AMO homepage  https://addons-dev.allizom.org/en-US/firefox/ 
2. Select an addon with a minimum of 3 screenshots ex: https://addons-dev.allizom.org/en-US/firefox/addon/cockat-chillark-raill/ 
3. Click out of the screenshots section  

Expected: 
Scrollbar should be displayed at all times  

 Actual:  
The scrollbar disappears after click out of the screenshots section and fails to be displayed again  

https://user-images.githubusercontent.com/112865359/200596675-4aac5967-d216-4e7b-82b9-5cba703624e9.mov

 Note: The scrollbar appears again after the page is refreshed 
On all AMO environments, on macOS V 12.4, this issue could not be reproduced on Windows

**Comment by bobsilverberg** [comment]
This seems to be a feature of Firefox. The scrollbar isn't displayed by default, but if you start scrolling with the mouse it appears. This happens even in your scenario of where it seems to disappear: Scrolling with the mouse makes it reappear. Even refreshing only makes the scrollbar appear for a moment, but if you don't interact with it almost immediately it disappears, and only reappears when you try to scroll with the mouse.

It looks like there's a setting in `about:config` called `layout.testing.overlay-scrollbars.always-visible` which can be turned on to make scrollbars always be visible, but without that setting enabled I think what is described here is the expected behaviour.

**Comment by abhijain2003** [comment]
i don't think so it is an issue, as scrollbar appears all-time in chrome and scrolling works smoothly as well, i think we need to do something for specifically firefox

**Comment by eviljeff** [comment]
I see the same behaviour here in github so it's a Firefox feature/issue and so not something we need to override on AMO.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-106
