### ISSUE TITLE
Remove author and slash from some collection slugs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11988]
This is a follow-up to #11959. Some authorIds and an extra slash were included by accident via copy/paste when the list of categories was added at https://github.com/mozilla/addons-frontend/blob/fba0fbd287be5462eefc131b388aa7a82d558f64/src/amo/components/AddonSuggestions/index.js#L65.  They should be removed.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I addded all remaining collections on AMO dev. Those I see in the .js like ` collection: '4757633/22469a386e654ca487b14d789e7250'` are below:

[games-entertainment ](https://addons-internal.dev.mozaws.net/en-US/admin/models/bandwagon/collection/5497865/change/) 
[photos-music-videos](https://addons-internal.dev.mozaws.net/en-US/admin/models/bandwagon/collection/5497868/change/)
[feeds-news-blogging](https://addons-internal.dev.mozaws.net/en-US/admin/models/bandwagon/collection/5497869/change/)

I have a question, are shopping and other not part of this, because the code looks different but also I added shopping using `shopping` for slug and the [detail page](https://addons-dev.allizom.org/en-US/firefox/addon/shoptagr/) won't display the shelf.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Nevermind, I found information about shopping and other, into a function where  I see the slug I must use 'b4d5649fb087446aa05add5f0258c3' and also description is available  `Explore our 'Starter Pack' to get started with extensions` 

An example: https://addons-dev.allizom.org/en-US/firefox/addon/shoptagr/

So these 2 categories are together into one collection.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-194
