### ISSUE TITLE
Create a new URL for the new disco pane.

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#121]
Currently the disco pane URL is set in Firefox Prefs at:

https://services.addons.mozilla.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%

Since we've got such a shiny new disco pane that works for Firefox only, we'll need to make a new URL (for the new end point). We'd then need to update Firefox to get to the new URL and ideally we'd like to do this by 48, or we are uplifting into Firefox.

Just for confusion, we can map the new URL and then when disco pane is standing up on prod, just flip our config to point to the new page (if that makes sense).

**Comment by muffinresearch** [comment]
Based on last week's meeting we are planning to use discovery.a.m.o. For simplicity we may as well keep the path exactly the same so for config changes it's purely a host change.

Depending on our level of paranoia I was also thinking that we might want to consider using a separate CDN host for the discovery pane too so that there's complete separation in terms of statics between the discovery pane and the rest of a.m.o. Our CSP config would therefore be limited to just discovery pane related hosts and little else.

/cc @jasonthomas

**Comment by jasonthomas** [comment]
Using a separate CDN endpoint works for me. We can use some variation of addons-discovery.cdn.mozilla.net for prod

**Comment by muffinresearch** [comment]
The URL for the disco pane itself is done. Closing.
