### ISSUE TITLE
Change "application" URL param to "app"

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1213]
The [Search API on addons-server uses `app`](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search), not `application` to set application (eg: "firefox", "thunderbird", etc.). We should do the same for consistency, as right now we right `application` everywhere then change it to `app` at the API call, but it'd be nicer to be consistent everywhere.

(Note this really only applies to the [in-progress categories branch](https://github.com/mozilla/addons-frontend/tree/implement-categories-1183), but will apply to master once that gets merged.)

**Comment by muffinresearch** [comment]
The name app or application to represent the user's application  e.g. `firefox` and `android` is a bit weird already imho. I deliberately chose to not shorten `application` to `app` since we have the concept of `app` in addons-frontend already, although this too is something of a misnomer - it comes from how we're needing to ~~ab~~use a feature of node config to achieve config separation with `APP_INSTANCE`.

Maybe we'd be better to go further and use `userApplication` over `application` and if we have to pass that as `app` to the API at least we're improving how easy it is to instantly understand what the `app` param represents?

**Comment by tofumatt** [comment]
Actually yeah, that's a good point. And we already translate query to q for
the api, so userApplication is way nicer and clearer. Let's do that 👍🏻

- tofumatt

**Comment by tofumatt** [comment]
We changed this to `clientApp` ages ago, so this can be closed.
