### ISSUE TITLE
link feedback form from addon detail page

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#12485]
When `enableFeatureFeedbackForm` is enabled we want to have the button on the add-on detail page navigate to the feedback form page rather than show a small feedback input inline, or launch Firefox's abuse reporting form.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-245)

**Comment by ioanarusiczki** [comment]
@eviljeff 

The form is linked on -dev to extensions, themes, lang packs and dictionaries. 
I'm going to check around.

**Comment by willdurand** [comment]
mm so technically we don't need the feedback form to apply to langpacks, maybe we should remove the report button for langpacks? WDYT @wagnerand?

**Comment by wagnerand** [comment]
> mm so technically we don't need the feedback form to apply to langpacks, maybe we should remove the report button for langpacks? WDYT @wagnerand?

Yes, we should remove that button for langpacks

**Comment by willdurand** [comment]
@ioanarusiczki could you please file a new issue for hiding the report button for langpacks? I think we can do that now, it doesn't have to be tied to this feature flag.

**Comment by ioanarusiczki** [comment]
@willdurand done https://github.com/mozilla/addons-frontend/issues/12561

**Comment by ioanarusiczki** [comment]
@willdurand 

The feedback form is present on AMO dev for:
- extensions , which have 2 reasons for "Send some feedback about the add-on" and 4 below "Report the add-on because it's illegal or incompliant" section

- themes and dictionaries have the same reasons but different from extensions:  "It's SPAM" at feedback and 3 reasons under. "Report the add-on because it's illegal or incompliant" section 

- user reports did not change 

Other notes:
- location and providing more details (the message) are optional
- with a login the user can choose to file the report anonymously 
- not being authenticated , the user can add a name and e-mail address 
- only one reason can be chosen when sending the report 

Only one question, shouldn't dictionaries have the same reasons as the extensions?

**Comment by ioanarusiczki** [comment]
@willdurand I forgot to add, I think I could send these reports one after the other under 1 min. 

I did not check the 20/ip/day, but I remember running into the 24 h throttle the other days. I'll re-check.

**Comment by willdurand** [comment]
I haven't specifically checked rate limiting but IIRC this isn't something we do in the frontend anyway. cc @diox

**Comment by willdurand** [comment]
> Only one question, shouldn't dictionaries have the same reasons as the extensions?

nope, themes and dicts seem are a bit different than extensions

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-245
