### ISSUE TITLE
implement theme reporting for DSA

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#12513]
Users need to be able to report themes for potentially infringing content.  This will be largely the same as extension reporting but the categories are slightly different

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-252)

**Comment by ioanarusiczki** [comment]
@willdurand 

1. The form for public themes looks like https://github.com/mozilla/addons-frontend/pull/12552#issue-1983802857 
Also public dictionaries have the same form. 

2. For a purely unlisted theme the form would look like the extension's feedback form (with a guid instead of name) for regular  or unauthenticated users.

![unlisted theme](https://github.com/mozilla/addons-frontend/assets/33448286/b1af8671-35f1-47cc-9341-47094f252d17)

The admin can view it like it's a public theme 

![unlisted theme for an admin](https://github.com/mozilla/addons-frontend/assets/33448286/a4be04fc-6910-4723-8075-5482b9ffa519)

**Comment by willdurand** [comment]
> 2\. For a purely unlisted theme the form would look like the extension's feedback form (with a guid instead of name) for regular  or unauthenticated users.

Yeah, the assumption is that unlisted "things' are treated as extensions.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-252
