### ISSUE TITLE
In feedback form, replace add-on guid by name if installed

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#12537]
Once https://github.com/mozilla/addons-frontend/issues/12478 is implemented, for non-public add-ons the feedback form will display the add-on guid. If the add-on is installed on the user's Firefox browser, we can replace that by the `name` by pulling the information from `mozAddonManager` client-side.

It might be a bit jarring on load since when the page is generated server-side it will only have the guid, but it might still be worth doing to make the UX less confusing to users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-260)

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-frontend/issues/12477

**Comment by willdurand** [comment]
FTR UX suggests that we hide the header instead.

**Comment by diox** [comment]
Could/should we still use `mozAddonManager` to show an error instead of feedback form if the parameter doesn't match a public `guid`/`slug`/`pk` and is not detected as installed ?

**Comment by diox** [comment]
In addition, if the parameter doesn't match a public add-on via `guid`/`slug`/`pk` *and* doesn't look like a valid `guid` pattern, maybe we should error out as well.

**Comment by ioanarusiczki** [comment]
@willdurand 
- Removing an unlisted addon
1. I'm on the form of an unlisted add-on https://addons-dev.allizom.org/en-US/firefox/feedback/addon/MV2testlaMV2@test/ not installed yet , there's the guid in the header.
2. Installed the unlisted version
3. After refreshing the feedback I see the name of the extension 
4. Removed the extension from add-on manager 
5. In the other tab I see the feedback form displays the guid 
6. At page refresh I am going to see the name again (with or without being authenticated on amo)

![step1](https://github.com/mozilla/addons-frontend/assets/33448286/11a732a9-e6c1-4fee-9cde-c0ef9d75f7cf)

I can avoid that if at step
 4. after I removed the extension from addon manager I click the Theme or Recommendations tab
5. Then I go to the feedback form and after page refresh I won't see the name - it's just the guid

![step2](https://github.com/mozilla/addons-frontend/assets/33448286/d460925a-a5ca-4227-9401-c126ad07ade8)


- Disabling or enabling the add-on would again change the feedback form in the other tab - the guid is displayed but after a page refresh it would display the name again. In these cases I think it's the expected result in this case since the addon is not removed (it's still installed). 

-  With listed addons installed which later go invisible I will get the slug instead of the name (in this case a report cannot be sent, I must replace manually the guid). Scenarios from https://github.com/mozilla/addons-frontend/issues/12539#issuecomment-1812614256 
So I believe this issue is only applicable for purely unlisted versions installed. Is this alright?

**Comment by willdurand** [comment]
> At page refresh I am going to see the name again (with or without being authenticated on amo)

I think that's because we don't fully uninstall the add-on in Firefox until the user navigates away: there is a "undo" action.

**Comment by willdurand** [comment]
> * With listed addons installed which later go invisible I will get the slug instead of the name (in this case a report cannot be sent, I must replace manually the guid). Scenarios from

That's kinda expected yeah.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-260
