### ISSUE TITLE
Standardize on component layout

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1260]
Our components typically have associated Sass and image files and we have a couple different styles of organizational layout. We should pick one and convert everything to that style.

Here are the current approaches:

Component is self contained:

```
src/amo/components/SystematicDysfunctioner/index.js
src/amo/components/SystematicDysfunctioner/SystematicDysfunctioner.scss
src/amo/components/SystematicDysfunctioner/img/thing.svg
```

Component is mingled with everything else:

```
src/amo/components/SystematicDysfunctioner.js
src/amo/components/SystematicDysfunctioner.scss
src/amo/components/SomeOtherThing.js
```

Component parts are scattered:

```
src/amo/components/SystematicDysfunctioner.js
src/amo/css/SystematicDysfunctioner.scss
src/amo/img/thing.svg
```

I like the self-contained approach. However, I think it would be fair to allow `src/amo/components/SystematicDysfunctioner.js` _only_ if there are no other files associated with the component. Thoughts?

**Comment by tofumatt** [comment]
I really dislike the contained style SOLELY because it means I have a bunch
of index.js files open in my editor and I find that really hard to scan. I
also find it much easier to find files in the flat folder structure.

I think putting scss and js together with the same name and different
extensions is nice, and then perhaps a folder of the same name for assets.

**Comment by kumar303** [comment]
I guess another self-contained approach could be this:
````
src/amo/components/SystematicDysfunctioner.js
src/amo/components/SystematicDysfunctioner/SystematicDysfunctioner.scss
src/amo/components/SystematicDysfunctioner/img/thing.svg
````
although I dislike the clutter of more than one component item in the directory of components.

The thing I like about the self-contained approach (`SystematicDysfunctioner/index.js`) is that it's easy to move stuff around, such as when you extract something into core.

In any case, it doesn't matter too much to me what we pick. We just need to pick something otherwise it will be super annoying to try and find files any time you're looking for one.

**Comment by mstriemer** [comment]
I prefer the self-contained approach, even if there's only a .js file.

> src/amo/components/SystematicDysfunctioner/index.js
> src/amo/components/SystematicDysfunctioner/SystematicDysfunctioner.scss
> src/amo/components/SystematicDysfunctioner/img/thing.svg

or

> src/amo/components/SystematicDysfunctioner/index.js

That being said `src/amo/components/SystematicDysfunctioner.js` without styles/images isn't the worst thing but I'd rather it be consistent.

**Comment by tofumatt** [comment]
While I find it easier to just see a list of files as components and not have to open another folder and have more nesting in my tree view, my biggest woe with `index.js` is–as mentioned–this:

<img width="1024" alt="screenshot 2016-10-20 13 45 28" src="https://cloud.githubusercontent.com/assets/90871/19560231/7b35753a-96cb-11e6-872c-454c7c2e6121.png">

-----

There's also the issue of how we name the tests–do we also do `tests/amo/components/SystematicDysfunctioner/TestIndex.js`?

It seems odd to me.

**Comment by mstriemer** [comment]
Tests would stay as `tests/amo/components/TestSystematicDysfunctioner.js` I think since there's only ever one test file they don't need to be contained.

The all files showing up as `index.js` thing does look annoying. I'm not sure I'd have any constructive suggestions for avoiding that. I've never had any problems since I don't have mouse support in my editor so I just use my fuzzy finder or step through each tab one-by-one.

**Comment by kumar303** [comment]
@tofumatt hmm, that's unfortunate. Is there a plugin or anything that will show the parent directory, maybe? For me, in Vim, it doesn't really feel like a problem: 
![screenshot 2016-10-20 11 59 31](https://cloud.githubusercontent.com/assets/55398/19569839/d0502182-96bc-11e6-82a2-6dbdd7c4003f.png)

**Comment by mstriemer** [comment]
Another thing about test files: currently we mostly do `translate.js` is tested as `test_translate.js` but I think there was a file added recently like `testTranslate.js`.

It probably makes more sense to do camel case `testTranslate.js` rather than our mixed snake-camel-case of `test_browserWindow.js`.

I'm not sure of the original rationale but it may have been to keep the case of the file the same so `browserWindow.js` is `test_browserWindow.js` rather than `testBrowserWindow.js`. Regardless we should standardise this as well.

**Comment by tofumatt** [comment]
I use Atom (which is a popular editor). Maybe there’s a plugin though I
think it’s a bad enough option by default (it’d be the same for sublime and
other popular editors) that I don’t like it. Asking contributors to install
an editor plugin to make sense of all our files being the same name is bad.
(It also makes Fuzzy search a bit awkward as I have to scan folder names
instead of file names too)

**Comment by mstriemer** [comment]
@tofumatt maybe it's the theme you have installed messing it up? On my atom (I think it's running the default theme, not seeing one installed) it looks like this:

![screenshot 2016-10-27 08 58 57](https://cloud.githubusercontent.com/assets/211578/19770176/f2809e6e-9c23-11e6-9078-a89b795691c1.png)

**Comment by tofumatt** [comment]
@mstriemer That works if you only have a few files open, but open enough and it starts cutting things off:

<img width="1030" alt="screenshot 2016-10-27 15 49 41" src="https://cloud.githubusercontent.com/assets/90871/19772094/fce6429e-9c5c-11e6-945a-d047ba461e4b.png">

**Comment by mstriemer** [comment]
We should move ahead with standardising soon.

I still like the `index.js` form since it keeps everything together and I'd actually like moving the related test file into the folder too if we did this. I don't think we need to nest images into another `img` folder.

```
src/amo/components/SystematicDysfunctioner/index.js
src/amo/components/SystematicDysfunctioner/thing.svg
src/amo/components/SystematicDysfunctioner/SystematicDysfunctioner.scss
src/amo/components/SystematicDysfunctioner/TestSystematicDysfunctioner.js
```

If the `index.js` bit is too annoying then I'd say we just pull the one file out but I still like how clean it is to have it all nested. I definitely don't like putting it all in the `components/` folder and doubling, tripling or worse the number of files in that folder.

```
src/amo/components/SystematicDysfunctioner.js
src/amo/components/SystematicDysfunctioner/thing.svg
src/amo/components/SystematicDysfunctioner/SystematicDysfunctioner.scss
src/amo/components/SystematicDysfunctioner/TestSystematicDysfunctioner.js
```

Regarding the name of the test file we could use `SystematicDysfunctioner.test.js` and use the eslint rule to avoid imports so that nothing with `.test` in the name gets imported directly (or at least from a non `.test.js` file or something).

**Comment by muffinresearch** [comment]
Images might be shared so moving them per component doesn't really make sense imho. If you need a mix of shared and centralized image files to me that dilutes the gains of having images in the component dir in the first place.

Personally (and I know it's not up to me :)) I feel like everything is more findable in separate dirs - the only big win I see with component dirs is that it helps with moving files around, but how often is that necessary? 

I tried to move towards putting scss files next to a component but it doesn't feel like a huge win on balance. I often find making CSS changes involves hopping around multiple CSS files at one time so all in one dir makes that easier.

To me the mixed `component.js` + `component dir` thing is not that nice so I think `component dir` + `index.js` is the way to go if you really want to have component dirs.

I'm not against a re-org. However, a suggestion might be to consolidate by moving out the couple of SCSS files centrally to make things consistent now (with minimal changes) and then re-visit this for a bigger re-organization later. There's higher priorities currently and a move to component dirs might be easier in december when there's less chance of conflicts?

**Comment by tofumatt** [comment]
The one thing I really do like is the CSS being next to a component actually, I think it also helps with me (and maybe other developers) keeping their CSS to be as specific to that component as possible. I also like being able to very easily find the CSS that affects a component and the content it renders.

If there's a way to make the filename the name of the component rather than `index.js` I'd be so over it but I really dislike the idea of a tonne of `index.js` files. Otherwise I'm for the filename + component folder approach.

I totally like adding the test to the component folder. That is nifty!

**Comment by mstriemer** [comment]
It's a bit gross but maybe makes sense, we could do:

```
src/amo/components/SystematicDysfunctioner/index.js
src/amo/components/SystematicDysfunctioner/thing.svg
src/amo/components/SystematicDysfunctioner/SystematicDysfunctioner.js
src/amo/components/SystematicDysfunctioner/SystematicDysfunctioner.scss
src/amo/components/SystematicDysfunctioner/SystematicDysfunctioner.test.js
```

Where `index.js` is just:

```js
import Component from './SystematicDysfunctioner';

export default Component;
export * from './SystematicDysfunctioner';
```

Here's an [example patch](https://github.com/mozilla/addons-frontend/compare/master...mstriemer:module-restructure) updating the `InstallButton` component (without the test change because that needs updates to our test runner).

> Images might be shared so moving them per component doesn't really make sense imho.

I'm hoping we don't need to share images. If we want to include them in CSS then we can have a directory that has the shared images and we can import the CSS from there instead. Ideally we'd have the images in each component and reuse the component instead of the image/CSS though.

**Comment by tofumatt** [comment]
https://github.com/mozilla/addons-frontend/pull/2122 was a WIP; can use it for a base to tackle this again later.

**Comment by willdurand** [comment]
So here are the rules for our code nowadays:

- React components live into a `components/` folder
- Each React component is a directory with a `index.js` and a `styles.scss`, imported with a relative path from the `index.js` file
- Assets related to a component should live in a sub-folder of the component (e.g., `Icon/images/`)

**Comment by willdurand** [comment]
I'd like to find a common naming rule for the test files, currently we have:

- `TestComponent` for a React `Component`
- `test_someThing` for a `someThing` JS file

But it is not really consistent and not always used that way (for instance, we have `testSomeThing` files sometimes). Can we agree on a single convention _or_ only the two above?

**Comment by bobsilverberg** [comment]
I would be happy to keep those two conventions, and make sure we stick to them.

**Comment by willdurand** [comment]
So I think I am done with this issue. I'll open another issue for the test files.
