### ISSUE TITLE
parsePage allows out-of-range page numbers

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1385]
### Describe the problem and steps to reproduce it:
Our `parsePage` function allows `-1`, `foo`, etc. to be parsed as `1`. This should return a 404 instead.

See: https://github.com/mozilla/addons-frontend/blob/a3291ba10c376c18a85ac90dbe631aec6607199b/src/core/containers/SearchPage.js#L32 and https://github.com/mozilla/addons-frontend/pull/1376#discussion_r88390196

**Comment by Ryuno-Ki** [comment]
If you only care for Google, they have some articles about [Duplicated content](https://support.google.com/webmasters/answer/66359?hl=en) and [URL categorisation](https://support.google.com/webmasters/answer/6080550?hl=en) on their support page.

As I mentioned I can tell from personal experience, that search engine will consider webpages with the same content but different search param (the `?page=1` in the URL) as different, hence flagging it as duplicated content.

You could redirect the user (Status code 301, according to Google docs) or set a canonical meta tag. Best 

In HTTP/1.1 the [status code 303 was added](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection). Otherwise default to 404 to tell the search engine to remove that link from their index.

**Comment by muffinresearch** [comment]
Let's 404 for these.

**Comment by muffinresearch** [comment]
This is already fixed. See https://addons-dev.allizom.org/en-US/firefox/search/?page=lol&platform=mac&q=test

**Comment by AlexandraMoga** [comment]
This issue can still be reproduced in add-on reviews page, for which there already is another case opened. Adding it here for tracking purposes: [#4081](https://github.com/mozilla/addons-frontend/issues/4081)
