### ISSUE TITLE
Ratings stars activated on hover strangely

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1399]
This is a niche bug as most mobile browsers don't have mice. But it will presumably affect desktop if the interface for stars is the same.

There is a hover bug where the review star hover is activated with all five stars enabled regardless of mouse position. Presumably this is a padding/hover bug.

Screencast:

![nov-21-2016 13-03-28](https://cloud.githubusercontent.com/assets/90871/20483652/0cb994a4-afeb-11e6-8b8d-57a8e7dc4c77.gif)

**Comment by kumar303** [comment]
Yes, it's because we have a rule that selects all stars (before deselecting the others) when you hover over the backing element (a span). We could maybe fix it by adjusting the height of the buttons to make sure there is no overlap. The selecting/deselecting could perhaps be implemented in a different way too.

**Comment by eviljeff** [comment]
For this to be a goodfirstbug can @kumar303 or @tofumatt explain exactly what needs to be changed?   (It's possible at this point you'll just end up fixing it 😃 )

**Comment by tofumatt** [comment]
The star hover effect should only be enabled when hovering over a start; note that all five stars appear lit when the mouse is inside one area before activating the right number of stars.

Hope that makes sense, any further and yeah it'd be easier to do myself I think. The screenshot says it all; when the five stars are lit it should really be four (or the hover effect shouldn't be active yet).

**Comment by eviljeff** [comment]
what file/ css rule would need to be changed?

**Comment by kumar303** [comment]
It might require someone to use browser developer tools to understand what elements correspond to which styles. It would probably be a good first bug for anyone who is familiar with CSS and HTML.

There is a conflict between these two hover rules: https://github.com/mozilla/addons-frontend/blob/master/src/amo/css/OverallRating.scss#L22 I think it's because the height of `.OverallRating-star-group` is too big but I'm not sure.

**Comment by kewisch** [comment]
The mentor for this issue is @kumar303  and is ready to be fixed by an awesome contributor!

**Comment by Tikam02** [comment]
can i contribute to this issue i know how star-ratings works and i am a frontend-webdeveloper.please send me the link of source code-file.

**Comment by tofumatt** [comment]
@Tikam02 You can work on it, the file to edit is likely https://github.com/mozilla/addons-frontend/blob/master/src/amo/css/OverallRating.scss, though like @kumar303 said you'll want to inspect with the browser developer tools to make sure you're editing the right CSS.

**Comment by Tikam02** [comment]
#1399
i had fixed this issue on my own way just finding a way to implement.

**Comment by Tikam02** [comment]
sir please send me the html index file so that i can check and implement my solution to this issue.

**Comment by kumar303** [comment]
Hi @Tikam02 thanks for your interest in helping out! Sorry for the confusion but this was fixed a couple days ago, I just hadn't merged in the fix (see https://github.com/mozilla/addons-frontend/pull/1494).

**Comment by tofumatt** [comment]
Oh shoot, sorry I forgot about that. That’s on me! :-/
