### ISSUE TITLE
Create a diagram to show how FxA + JWT might integrate for the universal case

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#141]
We'd like to be able to come out of a successful FxA auth and render the page to the auth'd user without needing the client to make a request with a JWT.

We should make some diagrams to plan how this will work for the initial request and then client requests.

This will not only help us to see how it will fit together but also provide something to start conversations with the security team too.

**Comment by mstriemer** [comment]
I don't have a diagram but here's what I think the plan looks like:

1. When hitting the /authenticate/ endpoint addons-server will set the django session cookie and a separate `access-token` cookie.
2. When the universal server gets a request it proxies the `access-token` into the redux state.
3. When the user accesses an authenticated view (wrapped in `<LoginRequired />` by react-router or something) it will check for a valid access token in the state, otherwise redirect to FxA.
  * We might need an endpoint on addons-server to kick this off and set `fxa-state` in the session.
4. The API module somehow accesses the state and seamlessly passes the token in the `Authorization` header.
  * The more I think about this and locales adding a middleware and using redux-thunk seems like a good idea. Maybe there's something easy though.
5. The state is already being serialized to the client so the token is dropped on the page with the state.

See `https://github.com/erikras/react-redux-universal-hot-example/issues/608` for more discussion on this.
