### ISSUE TITLE
Why do we pass `withRef: true` to (nearly?) all translate calls?

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1427]
As mentioned here: https://github.com/mozilla/addons-frontend/pull/1425#discussion_r89662114

Maybe it should just be the default? I just do it now as convention without knowing why, which seems like a case for a default arg.

**Comment by mstriemer** [comment]
I think we do it so that you can use `.getWrappedComponent()` (or something like that) but we normally end up using `findRenderedComponentWithType(..., MyComponent)` and we don't seem to need to unwrap it ever.

I'd say leave the default and remove the usage of `withRef: true` all over if the tests still pass.
