### ISSUE TITLE
Handle onInstallCancelled

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1435]
With required permissions landing for WebExtensions a user will now be able to cancel an install by not accepting the permissions dialog. We should catch this and display a message to the user that the install was cancelled.

Firefox work in [bug 1308309](https://bugzilla.mozilla.org/show_bug.cgi?id=1308309).

![webextensions-permissions-prompt](https://cloud.githubusercontent.com/assets/211578/20681138/d7a29f04-b567-11e6-9887-ef39f5b4c985.png)

**Comment by aswan** [comment]
I don't have an opinion about whether another message is needed, but the immediate problem is that if the user decides to cancel, the install button is left in limbo since it is still waiting for an `Ended` or `Failed` event which will never arrive.

**Comment by muffinresearch** [comment]
@tofumatt hi could you take a look at this one? It should be as simple as setting state to UNINSTALLED when receiving the `onInstallCancelled` event.

If you run nightly you should see these prompts in the disco pane / mobile site without modification.

**Comment by muffinresearch** [comment]
Another condition here is that we should make sure that from a tracking perspective a cancelled install is not sending successful install beacons.

**Comment by vasilicamihasca** [comment]
This issue is verified as fixed while following the happy flow on Firefox 55.0a1 (2017-05-03) under Windows 10 64-bit. A new related issue was encountered during this testing after the tab was moved to a new window: #2341 
Postfix screencast:
![animation3](https://cloud.githubusercontent.com/assets/18114210/25663870/7cad7fd0-3021-11e7-9804-4d16417b6136.gif)
