### ISSUE TITLE
Minify JS bundle

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1575]
Our JS bundle isn't being minified in production. Gzip is likely making this not terrible but we can likely squeeze out some more bytes by minifying.

Current disco pane js: https://addons-discovery.cdn.mozilla.net/disco-6fc7e9484a5f0795d9fa.js

**Comment by muffinresearch** [comment]
A bit of investigation shows that camelcase was upgraded back in Nov and the changes made it es2015 since it's targetted at node rather than node + browsers. This update causes uglify to barf so it doesn't minify the file.

To fix this we need to downgrade back to 3.x as a quick fix and then either transpile that lib when we go back to the most recent version or find a replacement.

We also need to fix the build so that if webpack encounters an error it bails rather than carrying on.

**Comment by ValentinaPC** [comment]
@muffinresearch : not very sure on how to check this; can you please give me a hand? Thanks!

**Comment by muffinresearch** [comment]
@ValentinaPC just look at the main disco JS file, it should be minified as opposed to containing whitespace e.g:

Viewing source on https://addons-discovery-cdn.allizom.org/disco-fa9f177b8bdf1ebe08c9.js

Bad:

<img alt="nightly" src="https://cloud.githubusercontent.com/assets/1514/21803507/49db8b18-d722-11e6-8dc4-6a102f4bb565.png">

Good (It should look like this): 
![nightly](https://cloud.githubusercontent.com/assets/1514/21803538/6af0188c-d722-11e6-83e3-35233116d4d6.png)

**Comment by ValentinaPC** [comment]
Oh, that is clear - it is for sure, _minified._ :)
Verified as fixed from about:addons set to `-dev` and `-stage` using FF53.0a1 and FF50.1 under Win 7:
- `https://addons-discovery-dev-cdn.allizom.org/disco-331f293256bf0af3ccc3.js`:
![n-dev](https://cloud.githubusercontent.com/assets/15685960/21804351/33774000-d737-11e6-908a-7ee2c3420628.png)
- `https://addons-discovery-cdn.allizom.org/disco-fa9f177b8bdf1ebe08c9.js`:
![n-stage](https://cloud.githubusercontent.com/assets/15685960/21804404/7e12c67a-d737-11e6-9458-3f2a1fc755ef.png)
