### ISSUE TITLE
The TravisCI build sometimes fails silently

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1615]
### Describe the problem and steps to reproduce it:

This [pull request](https://github.com/mozilla/addons-frontend/pull/1600) showed all tests passing but the unit tests [completely failed](https://travis-ci.org/mozilla/addons-frontend/jobs/191112353).

### What happened?

You tell me.

### What did you expect to happen?

The build should have failed!

### Anything else we should know?

This is pretty serious so I'm nominating it for v1 otherwise we'll have a hard time merging greenkeeper PRs.

**Comment by muffinresearch** [comment]
I've been debugging this and it's a karma issue - there's a bug in 1.3.0 where `SIGINT` is called on server startup and that just returns a 0 exitCode due to how that's handled. 

Looking further in karma's master and it appears it was fixed here: https://github.com/karma-runner/karma/commit/86e2ef22c79276ea56031955fd81352413f8b1ba so as soon as that's in a release we should see the same scenario exit with 1 instead of 0.

**Comment by muffinresearch** [comment]
FWIW upgrading `karma-webpack` should now work since they fixed the problem that caused the plugin to not be found.

**Comment by kumar303** [comment]
hooray for upstream bug fixes!

**Comment by muffinresearch** [comment]
Closing this since we got the patch since upgrading to 1.4+ https://github.com/karma-runner/karma/blob/v1.5.0/CHANGELOG.md#140-2017-01-14
