### ISSUE TITLE
Upgrading react-redux to 5.0.2 caused action data to be undefined.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1631]
See https://github.com/mozilla/addons-server/issues/4312 for the regression. I'm looking to downgrade by reverting in #1630.

This issue is filed so that we can upgrade and at the same time investigate and hopefully fix the incompatibility. 

When upgraded the disco pane shows logs like:

```
[disco] Add-on "undefined" not found so setting status to UNINSTALLED
```

And looking at the data for a payload object in the related `INSTALL_STATE` action, the `guid` and the `url` are both `undefined`.

If at all possible a regression test to cover us against a similar future scenario would be handy.

**Comment by kumar303** [comment]
I haven't looked at this in detail but I think the concept in https://github.com/mozilla/addons-frontend/issues/1371 might have revealed this regression. The problem with the disco tests (and a lot of others) is that they inject component data [with raw props](https://github.com/mozilla/addons-frontend/blob/master/tests/client/disco/components/TestAddon.js#L64-L70) instead of dispatching an action to trigger a [state mapper](https://github.com/mozilla/addons-frontend/blob/master/src/disco/components/Addon.js#L220) to set the props. 

I think dispatching an action gives us more realistic app coverage and shouldn't slow down the tests or anything. It's really hard [1] to keep hand written prop objects in sync with what the action + reducer would create in real life.

[1] unless we switch to Flow!

**Comment by muffinresearch** [comment]
Closing in favour of https://github.com/mozilla/addons-frontend/issues/1371
