### ISSUE TITLE
Add-on rating is not displayed on detail page

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1638]
We show the add-on's rating on the search results but not on the detail page. It would be nice to see the rating there.

@pwalm any thoughts on where this should go?

Here's a quick mock, I'm not sure how we want to fit the rating and the count or maybe just the rating.

![screen shot 2017-01-18 at 23 34 11](https://cloud.githubusercontent.com/assets/211578/22094940/c6d1f3f4-ddd6-11e6-9b9a-9ffdbd720433.png)

**Comment by pwalm** [comment]
The only thing I would change is remove the number of reviews and balance it with the number of users so the icons are the same size and the text sits on the same line. Looks a bit weird with the two lines of text stacked like that.

**Comment by kumar303** [comment]
@pwalm thanks for taking a look. I filed an issue to make that change https://github.com/mozilla/addons-frontend/issues/1698

**Comment by pwalm** [comment]
Thanks @kumar303!

**Comment by madalincm** [comment]
Verified as fixed in FF51(Android 7.1.1) addons-dev.allizom.org
The rating is now displayed in add-on detail page.

![screenshot_20170206-173627](https://cloud.githubusercontent.com/assets/15685441/22653671/d0469bcc-ec92-11e6-803b-b732e8301b72.png)

The problem about the text and the balancing is being tracked in #1698. Marking this bug as verified fixed.
