### ISSUE TITLE
2 confirmation pop-ups for add-ons installed via DiscoPane 

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-frontend#1679]
**Note:**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1308310

**Steps to reproduce:**
1.Launch Firefox with clean profile.
2.Create extensions.webextPermissionPrompts and set it to true.
3.Restart the browser.
4.Navigate to Add- ons Manager -> Get Add- ons
5.Enable Block ads add-on.

**Expected Results:**
DiscoPane confirmation doorhanger (Your add-on is ready) is no longer displayed.

**Actual Results:**
- There are 2 confirmation pop-ups displayed.
- This issue reproduces on Firefox 54.0a1 (2017-01-30) under Windows 10 64-bit.
- See attached screenshot:

![2017-01-30_1717](https://cloud.githubusercontent.com/assets/18114210/22428545/1f352236-e710-11e6-96aa-8fe07c714bef.png)

**Comment by muffinresearch** [comment]
Now that the native addon installation notification has landed the one on the disco pane can be omitted if the version is major version is 54+

**Comment by muffinresearch** [comment]
I note in writing the patch for this that when an addon is enabled the browser doesn't show in the install notification but we do from content for the same event. I think that's actually the correct behaviour so I've wrapped enable in the same check for extensions.webextPermissionPrompts so that when we move to native notifications we will no longer see the install notifications for a disabled addon being re-enabled.

**Comment by muffinresearch** [comment]
# QA Notes:

Here's a list of the key scenarios for checking stable and nightly.

## Stable:

### When installing an addon via the disco pane:

* Should see the notification on the right side of the page (with LTR locale) 

### When enabling a previosly disabled addon by clicking install in the disco pane:

* Should see the notification on the right side of the page (with LTR locale) 


## Nightly `extensions.webextPermissionPrompts: false` or missing:

### When installing an addon via the disco pane 

* Should see the notification on the right side of the page (with LTR locale) 

### When enabling a previosly disabled addon by clicking install in the disco pane:

* Should see the notification on the right side of the page (with LTR locale) 


## Nightly `extensions.webextPermissionPrompts: true`

### When installing an addon via the disco pane 

* Should see the browser install notification on the left side of the page (with LTR locale) 

### When enabling a previously disabled addon by clicking install in the disco pane:

* No notification since the browser doesn't provide anything natively for this scenario.

**Comment by ValentinaPC** [comment]
Verified this on:

**1. Firefox 51 (`en-US` and `ar` builds) using Windows 7**  
- installing an add-on via the disco pane - notification is listed on the right
- enabling a previously disabled add-on by clicking install in the disco pane - notification is listed on the right   
Video `en-US`: 
![en-ff](https://cloud.githubusercontent.com/assets/15685960/22694803/4323c822-ed51-11e6-88c0-17ab315d940a.gif)
Screenshot `ar`: 
![release-ar](https://cloud.githubusercontent.com/assets/15685960/22694811/4f4cf948-ed51-11e6-9565-35d7c05661d6.png)
Work as expected.

**2. Firefox Nightly (`en-US` and `ar` builds) using Windows 7** 
_a. extensions.webextPermissionPrompts: false or not available_
- installing an add-on via the disco pane - notification is listed on the right
- enabling a previously disabled add-on by clicking install in the disco pane - notification is listed on the right   
Screenshot` en-US`:
![notif](https://cloud.githubusercontent.com/assets/15685960/22694102/88333784-ed4e-11e6-8fc7-c84b45352899.png)
 Screenshot `ar`:
 ![n-ar](https://cloud.githubusercontent.com/assets/15685960/22694221/fd60f302-ed4e-11e6-8e23-4cc5cc665bfa.png)  
Work as expected. 
  
_b. extensions.webextPermissionPrompts: true_
- installing an add-on via the disco pane - **browser install notification on the left side AND AMO notification listed on the right** - **not as expected**
Screenshots `en-US`/`ar`:
![en-ar](https://cloud.githubusercontent.com/assets/15685960/22694292/4885dd98-ed4f-11e6-951e-dfd267f1d239.png)

- enabling a previously disabled add-on by clicking install in the disco pane - notification is listed on the right - work as expected.

**Comment by muffinresearch** [comment]
@ValentinaPC for 2b what version do you have? The modification to enable this permission hint only landed a few days ago.

**Comment by ValentinaPC** [comment]
@muffinresearch: I am using FF 54.0a1 (2017-02-06) (32-bit) under Win 7.

**Comment by muffinresearch** [comment]
I've just re-checked and it's working for -dev for my nightly 54.0a1 (2017-02-06) (64-bit)

**Comment by ValentinaPC** [comment]
Yeah...that was the problem, I've missed that.
Verified for RTL locales also:
![ar_001](https://cloud.githubusercontent.com/assets/15685960/22696231/edadff20-ed55-11e6-8255-2f6addc32fa7.png)

One last question about this:
> When enabling a previously disabled addon by clicking install in the disco pane:
> - No notification since the browser doesn't provide anything natively for this scenario.

No notification from the browser (ok), but also no notification from AMO?

**Comment by muffinresearch** [comment]
> No notification from the browser (ok), but also no notification from AMO?

Yep that's correct. We originally showed the same thing as the install notification on the page but since it's actually only enabling a previously installed addon we're not going to show anything if the browser doesn't show any notification.

**Comment by ValentinaPC** [comment]
Great!
Marking this verified-fixed.
