### ISSUE TITLE
Balance star and user icons in add-on detail metadata

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1698]
If you go to the detail for an add-ons page you see some metadata at the top about how many users it has and what its average rating is (screenshot below). Let's tweak this design based on @pwalm's comment (https://github.com/mozilla/addons-frontend/issues/1638#issuecomment-276976722) -- let's make the star only have one line of text underneath it so it looks balanced with the user icon.

<img width="363" alt="2e9f2b04-e4a4-11e6-878d-a5f85774b067" src="https://cloud.githubusercontent.com/assets/55398/22556548/2976d978-e92d-11e6-8063-c7ac23d034da.png">

**Comment by mstriemer** [comment]
I think this will look better with one line of text but I really like being able to see the number of reviews because that is often just as useful. I suppose you could extrapolate somewhat from the number of users but still.

Here's a really terrible mock up of what it could look like to have the rating in the star partially filled to show the rating.

<img width="361" alt="screen shot 2017-02-03 at 6 11 55 pm" src="https://cloud.githubusercontent.com/assets/211578/22613309/e928378e-ea3c-11e6-8ba4-3e08adbfd6b8.png" width=300>

And another with a number inside the star.

<img width="361" alt="screen shot 2017-02-03 at 6 15 07 pm" src="https://cloud.githubusercontent.com/assets/211578/22613320/f4baaf50-ea3c-11e6-8fbb-3a07fa2a21fd.png" width=300>

It's not the end of the world if we drop the review count but thought I'd suggest some options.

For completeness here's a version with just the rating.

<img width="360" alt="screen shot 2017-02-03 at 6 17 47 pm" src="https://cloud.githubusercontent.com/assets/211578/22613351/3e4e8c4a-ea3d-11e6-9078-b4acf69d1a20.png" width=300>

Thought? @pwalm

**Comment by tofumatt** [comment]
I agree, having the review count is very useful to me. An add-on with a single negative review conveys something very different than one with an average rating of 1.2 stars with 30 reviews. It provides a lot of context and I don't think is worth ditching.

**Comment by mstriemer** [comment]
madalinc posted a screenshot in #1638 with the old version and it looks like the alignment is a bit odd on wider screen sizes. I think the icons should be left aligned or the 3 should be flexed with `space-between` to give then even padding across the bar.

<img alt="weird alignment" src="https://cloud.githubusercontent.com/assets/15685441/22653671/d0469bcc-ec92-11e6-803b-b732e8301b72.png" width=400>

**Comment by pwalm** [comment]
Let go with this option:
<img width="428" alt="screen shot 2017-02-07 at 11 02 28 am" src="https://cloud.githubusercontent.com/assets/6797635/22706665/f17cd60c-ed24-11e6-8c43-bb160e49966d.png">

You're right, we need both the number of reviews and star rating for proper context.

**Comment by tofumatt** [comment]
Sorry I'm just getting to this, but the `2.6` in the centre also lacks context to me; I don't know the scale and while a number with a decimal suggests maybe an /5 scale not /10, it's not always the case and I think makes it hard to grok as well.

What about 2.6/5 | 6 reviews or 2.6/5 (6 reviews).

That shouldn't be too bad for i18n but I really feel we need context or it's just a lot of numbers.

**Comment by tofumatt** [comment]
Just testing this too and "No reviews" in German seems to be "Keine Kommentare" which already can't fit on a line. Even just writing "1,000 ratings" in German is two lines. I think this needs to account for multiple lines but they should extend down. I'll try it and post a mock-up.

**Comment by kumar303** [comment]
@pwalm we went with this change (for now); screenshots: https://github.com/mozilla/addons-frontend/pull/1862 Feel free to suggest additional tweaks though.

**Comment by pwalm** [comment]
Ok, sharpen your pitchforks everyone: What if we laid out this info horizontally instead of stacked vertically? Already playing with it in AMO desktop:
<img width="345" alt="screen shot 2017-02-23 at 9 39 11 am" src="https://cloud.githubusercontent.com/assets/6797635/23271432/3631a8a2-f9ac-11e6-9e0e-5345a01a800b.png">

**Comment by kumar303** [comment]
@pwalm Seems fine by me. That should let us deal with long words (like in German) better. Can you file a new issue for it?

**Comment by tofumatt** [comment]
Horizontal is super easier to read as well, 👍

**Comment by pwalm** [comment]
Proposed:
<img width="575" alt="screen shot 2017-02-23 at 11 24 20 am" src="https://cloud.githubusercontent.com/assets/6797635/23275261/b32a62dc-f9ba-11e6-8cf3-77e20a0aaf8f.png">
We kill the icons and just use text for users/reviews. We'll run into less errors with long l10n translations.

**Comment by tofumatt** [comment]
I like it. I've made a new issue so it doesn't get lost in this closed one.

**Comment by kumar303** [comment]
Thanks @pwalm , the new issue is https://github.com/mozilla/addons-frontend/issues/1888

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Chosen format in #1862 
Postfix screenshot:
![2017-02-24_1611](https://cloud.githubusercontent.com/assets/15685960/23306356/ea9496e2-faab-11e6-8a5e-1e99c5d8dcf0.png)
