### ISSUE TITLE
All fetch requests with responses larger than 16kb fail on the server

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1726]
### Describe the problem and steps to reproduce it:
Turns out #1401 was reopened but the issue encountered is unrelated to the original bug and is, I believe, related to https://github.com/bitinn/node-fetch/blob/master/LIMITS.md.

593b5742a76449879a344a6114ef3ad272253672 introduced usage of `response.clone()` in our fetch code, which works fine on the client, but **fails on node with any response larger than `16kb`** (eg: most search responses) because of the size of the response. Note that a response with no results will work fine: https://addons-dev.allizom.org/en-US/firefox/search/?q=rjkngkwhnkwjnhkwrjnhkjrwnhkjwnrhkwjnhkwh but any large response fails. This is true for search (https://addons-dev.allizom.org/en-US/android/search/?q=Fire) and non-search ( https://addons-dev.allizom.org/en-US/firefox/extensions/) pages

Note that navigating to these pages on the client works without issue.

-----

Looks like we can't use `response.clone` on the server in this way.

**Comment by muffinresearch** [comment]
Nice work on debugging this. 

Looks like not using `clone()` would be best. I reckon looking at reponse headers would work in this case since https://github.com/mozilla/addons-server/issues/4576 suggests those are correct for the response (as you'd expect).

Here's an example from https://jakearchibald.com/2015/thats-so-fetch/

```js
fetch(url).then(function(response) {
  if (response.headers.get('Content-Type') === 'application/json') {
    return response.json();
  }
  return response.text();
});
```

**Comment by kumar303** [comment]
> If you are using res.clone() and writing an isomorphic app, note that stream on Node.js have a smaller internal buffer size (16Kb, aka highWaterMark) from client-side browsers (>1Mb, not consistent across browsers).

WOW. That is ridiculously dumb.

Yeah, maybe the headers will be enough to know when to use `json()` or `text()`. Hopefully!

**Comment by kumar303** [comment]
I'm not even sure how to interpret this. Are we going to hit a 1MB limit when using `json()` too? Do we need to process the response more [like a stream](https://github.com/substack/stream-handbook)?

**Comment by kumar303** [comment]
To elaborate, I wonder if we need to process the response in chunks (which I think is what `read()` does?), maybe like this example from the Streams section of https://jakearchibald.com/2015/thats-so-fetch/ : 
````js
fetch('/big-data.csv').then(function(response) {
  var csvStream = response.body
    .pipeThrough(new TextDecoder)
    .pipeThrough(new CSVDecoder);

  csvStream.read().then(function(result) {
    // array of cell values for the first row
    console.log(result.value); 
  });
});
````
Ours would pipe through a JSON decoder instead.

**Comment by tofumatt** [comment]
That makes sense to me as the way to protect against these types of errors in the future. I'd be surprised if we had API responses in the 1MB range, but, [y'know](http://quoteinvestigator.com/2011/09/08/640k-enough/).

**Comment by muffinresearch** [comment]
Do we have the possibility of using a JSON parser that consumes a stream?

**Comment by tofumatt** [comment]
That would be handy… don’t we have one in the linter already? :-)

**Comment by muffinresearch** [comment]
> That would be handy… don’t we have one in the linter already? :-)

We don't have that in the linter already afaik.  Looking into it real stream capabile JSON parsers tend to emit events or callbacks as data is parsed and if so that wouldn't fit with our typical use-case. and we'd need to change things to be able to progressively deal with the data in that way.

Here's some examples of an existing JS lib for handling JSON streams: http://oboejs.com/examples

My point was more if the parser we're using either requires a string or just inhales the stream into memory prior to parsing then if we just `read()` the stream into memory it mostly amounts to the same thing doesn't it?

**Comment by mstriemer** [comment]
I thought I'd try this out. The docs say it's >1MB in a browser so I have no idea what the max size is but figured I'd go bigger than that. I made a JSON file that's 6.7MB and fetched it in firefox, printing out each key into a `<ul>`.

It works fine using `fetch('json').then((response) => response.json())`.

**Comment by mstriemer** [comment]
I would guess that `json()` handles this for us and the buffer limitation is in `clone()`.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "no qa needed". Thanks!
