### ISSUE TITLE
Welcome mat is missing

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#1740]
The area below the search bar on the Explore page of AMO Mobile is missing:
<img width="712" alt="screen shot 2017-02-07 at 2 52 04 pm" src="https://cloud.githubusercontent.com/assets/6797635/22715277/04d56118-ed45-11e6-8975-31ec06f649e7.png">

If we're waiting on copy, I think Scott might already have something along these lines.

**Comment by mstriemer** [comment]
@devaneymoz do you have copy for this already?

**Comment by devaneymoz** [comment]
Sure thing. Couple thoughts...

"Search extensions and themes" in the search field might prove problematic for localization; could run a bit long for mobile, especially in Slavic languages. How about we just go with "Search" in the field.

For copy below search, let's try:

"Extensions are special features you can add to Firefox. Themes let you change your browser's appearance."

**Comment by vcarciu** [comment]
Verified as fixed : 
![welcomemat](https://cloud.githubusercontent.com/assets/1583842/22794997/b8411eb8-eefd-11e6-8917-36684ad32efd.png)

**Comment by devaneymoz** [comment]
Looks good, except what about the point on the copy in the search field? Can we just have "Search" in the search field instead of " Search extensions and themes"?

**Comment by pwalm** [comment]
Looks great!

@devaneymoz: I suggested "Search Extensions and Themes" to make the action a bit more concrete, and to reinforce the split between extensions and themes. Is "Search" enough?

**Comment by devaneymoz** [comment]
@pwalm: You might be right about the need for a reinforcement, because now that I look at it again, the copy I provided below the search field doesn't make as much sense without first establishing the concept of "extensions" and "themes" which the search field does (in this way it kind of serves as a sub-header for the page). 

I'm fine leaving it as is, but still feel localization will pose an issue in some cases.
