### ISSUE TITLE
After dismissing keyboard, it is not triggered again at subsequent search

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1749]
Steps to reproduce:
1.On Android, go to addons-dev.allizom.org
2.Tap on search field
3.Dismiss the keyboard by pressing back button
4.Tap a Category from add-ons
5. Tap search field again

Expected results:
Keyboard is successfully opened

Actual results:
The keyboard is not triggered, focus is not present, tapping multiple times does nothing

Please see video for this issue : 
![keyboardnottriggered](https://cloud.githubusercontent.com/assets/1583842/22738839/c399d5d0-ee11-11e6-9117-671cc6e95773.gif)

**Comment by mstriemer** [comment]
This worked for me the first few times but I was eventually able to reproduce.

I have a feeling this is because of the animation and it is somehow breaking. The input won't focus until the magnifying glass animates over to the left. It looks like sometimes the animation skips and then focusing breaks.

Maybe this should just `setTimeout(() => this.input.focus(), animationLength)` instead of waiting on the `transitionend` event.

This is somewhat related to #1443 but that issue is just annoying, it doesn't necessarily break the functionality. Hopefully both of these can be fixed at once though.

Possible solution: making the input `color: transparent` appears to hide the cursor. Maybe it can be transparent until the time we expect the animation to end, then back to white.

We should fix the animation too, not sure what's up with that.

**Comment by vcarciu** [comment]
Verified as fixed using different search scenarios , but I will add video only for original bug description : 
![keyboardfix](https://cloud.githubusercontent.com/assets/1583842/22926108/f311725e-f2b3-11e6-9ce5-48ae393bf0d3.gif)
