### ISSUE TITLE
White dot present in the warning for adding review for your own addon

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1771]
Steps to reproduce:
1.Submit an Android add-on on -dev and approve it
2.Try to rate your own add-on
3.Observe the warning

Expected results:
Warning is correctly displayed , no UI issues

Actual results:
White dot displayed in the left side of the warning without reason. 

NOTES:
We should round the corners of the red frame in order to meet the general amo styling. We can write _can not_ in a single  _cannot_

Please see screenshot for this issues : 

![ownreview](https://cloud.githubusercontent.com/assets/1583842/22789624/32ea92f0-eeec-11e6-9cd8-1b4498cc2d63.png)

**Comment by muffinresearch** [comment]
It might be better to also say "their own add-on" instead of "its own add-on"?

**Comment by kumar303** [comment]
Huh, that's weird about the white dot. Thanks. I'll make the style more consistent too.

RE: the error message, that will need to be fixed in https://github.com/mozilla/addons-server so someone could start by filing a bug there to change it. It's an error returned by this API endpoint: http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#post

**Comment by vcarciu** [comment]
Verified as fixed : 
![ownaddon](https://cloud.githubusercontent.com/assets/1583842/22969596/b7c95d0a-f377-11e6-8b8b-0341dde81284.png)
