### ISSUE TITLE
Change error message for add-on author leaving a review on their own add-on

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1775]
Originally filed as https://github.com/mozilla/addons-server/issues/4652, but that's wrong because we shouldn't be using the API message (it doesn't get localised).

Basically, see mozilla/addons-frontend#1771. The error message displayed their would make more sense as "their own add-on" instead of "its own add-on". Actually we should really just say "You can't review your own add-on."

We need to add this message into the frontend, based on the API response.

<img width="773" alt="screenshot 2017-02-09 19 10 52" src="https://cloud.githubusercontent.com/assets/90871/22798861/84c65dc0-eefb-11e6-914b-ed574bb8cafa.png">

**Comment by kumar303** [comment]
Oh, huh. There are a couple issues here. First, I was always under the impression that API responses are localized because we make requests using a language code.

I think it's an easy fix! https://github.com/mozilla/addons-server/issues/4655

I think relying on the API for localized responses is the way to go. Otherwise, we'd have make the API return error codes and the frontend would have to map each code to a localized string which can get cumbersome.

**Comment by tofumatt** [comment]
I guess that’s a good point. I see the value in specialised text per each client, but I suppose localising them on the API doesn’t hurt and is a good place to start. Plus we already localise a lot of content that comes from the API. 👍🏻

**Comment by kumar303** [comment]
Looks like this got closed in https://github.com/mozilla/addons-server/issues/4655 . See https://github.com/mozilla/addons-server/pull/4663/files#diff-6fa948bb9fd6741d9514c8d7a99c02adR150

**Comment by vcarciu** [comment]
Verified as fixed : 
![screenshot_20170222-181211 1](https://cloud.githubusercontent.com/assets/1583842/23220380/86a6c9a2-f92a-11e6-9c75-fae9b052cdac.png)
