### ISSUE TITLE
When selecting a text in review form and scroll , the "quotes" of selection will scroll with the background

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1787]
Steps to reproduce:
1.On Android, go to any add-on details page (https://addons-dev.allizom.org/en-US/android/addon/send-to-mail/)
2.Press the rating stars in order to write a review
3.In Review form, select some text (by double click on a word by example)
4.Scroll up and down

Expected results:
The selection "quotes" will not scroll 

Actual results:
The selection "quotes" will scroll together with the background and this looks weird

Please see video for this bug : 
![weirdo](https://cloud.githubusercontent.com/assets/1583842/22834817/3331dc9a-efbf-11e6-870f-d23bdc1c25b3.gif)

**Comment by kumar303** [comment]
This looks like a Firefox bug. I don't think we need to worry about it though because no one is expected to select text on this page for any feature. In other words, the user does not need to select text in order to enter a review. They just need to type in the text box and press submit. The scrolling bug will not prevent them from submitting the review.
