### ISSUE TITLE
Links from summary are not working on mobile 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1861]
Steps to reproduce:
1.On Android , go to https://addons-dev.allizom.org/en-US/android/addon/clean-links
2.Observe the summary section under add-on title and author

Expected results:
If there are links in summary , users should be able to open them by tap

Actual results:
Links are not clickable (they are working on Desktop)

NOTES:
Desktop link to same add-on : https://addons-dev.allizom.org/en-US/firefox/addon/clean-links/?src=search

Please see screenshot for this issue : 
![summarylinks](https://cloud.githubusercontent.com/assets/1583842/23165895/00b89ed0-f847-11e6-9619-d77ef91783ef.png)

**Comment by muffinresearch** [comment]
Looks like this is due to running the content through DOMpurify https://github.com/mozilla/addons-frontend/blob/78fb3dc700389db221275a56608a27a7207e20de/src/amo/components/AddonDetail.js#L184 which would need to be configured to allow links. Would be good to know what content should be allowed in that field and update accordingly.

**Comment by tofumatt** [comment]
Fixed in #1860.

### Before
![screen shot 2017-02-23 at 02 25 02](https://cloud.githubusercontent.com/assets/90871/23243576/b4d47ca0-f977-11e6-85ed-eb78c0e8a53c.png)

### After
![screen shot 2017-02-23 at 02 24 22](https://cloud.githubusercontent.com/assets/90871/23243575/b4d3bc52-f977-11e6-8c91-83463be63a8c.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![linksandoutgoing](https://cloud.githubusercontent.com/assets/1583842/23263201/29950d16-f9e6-11e6-9901-f8c1510293b6.gif)
