### ISSUE TITLE
A dismissed review is still counted

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2020]
Steps to reproduce:
1.On Android, go to AMO-dev and open any add-on which is not already reviewed by you
2.Log in , then tap on rating stars in order to review the add-on
3.Dismiss the review by taping outside the review form

Expected results:
Review is dismissed 

Actual results:
Review is dismissed but it is counted to the total number of reviews

Please see video for this issue (observe that we had 18 review before and 19 after a dismissed review):
![countnothing](https://cloud.githubusercontent.com/assets/1583842/23712528/efaf8a22-042b-11e7-9d41-20d84ef95ed3.gif)

**Comment by muffinresearch** [comment]
This is by design afaik, the review text is optional. 

FWIW: I proposed an alternative ui to do away with this ambiguity here: https://github.com/mozilla/addons-frontend/issues/1837#issuecomment-282095519

I think this needs UX input to decide on whether we stick with this or make it better. I personally don't like the ambiguity which makes it unclear to the user if they did or didn't do something, I feel that clarifying it should probably outweigh worries about users bailing on the review process.

See also https://github.com/mozilla/addons-frontend/issues/1988 which is the same bug for editing.

**Comment by pwalm** [comment]
What if we just changed the header from "Write a review" to "Rating saved!" and leave the secondary copy as is? Pretty obvious right off the bat.

**Comment by muffinresearch** [comment]
I think this will be solved in #1837
