### ISSUE TITLE
Create a universal link component to make linking easier

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2053]
There is an [AMO-specific link component](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Link.js) that prefixes URLs with locale and application. This is good but when AMO needs to interact with a generic link aware component, the calling code has to pass in a custom link component.

Example:
````js
import AmoLink from 'amo/components/link';
...
render() {
  return <Paginate LinkComponent={AmoLink} ... />;
}
````

This is hard to manage and it's easy to forget to pass in the right component which results in confusing link behavior.

Let's make a single link component for every app and every component to use. It will still introspect Redux state but for apps like `disco` or `admin`, it won't add prefixes.

**Comment by willdurand** [comment]
Actually, only the `Paginate` component takes a `LinkComponent` as prop. This `Paginate` is only used on amo, so I'd like to move `Paginate` to `src/amo/components` rather than implementing a too-smart `Link` component.

On a semi-related note, the `Link` component (amo) is used in the `Button` component (`src/ui/`), which is used in disco (the code path with the `Link` is not used though). That does not look nice.
