### ISSUE TITLE
Compatilibity seems to be checked multiple times according to logs

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2083]
Looking at the disco pane on -dev with testing flags enabled I notice that for the short list of add-ons being served there's a lot of compatibility logging happening. 

This suggest compatibility code paths are being invoked more times that necessary this might be caused by other things but it's worth investigating in case there's some optimizations that can be made.

![add-ons_manager](https://cloud.githubusercontent.com/assets/1514/24006599/301d6b18-0a64-11e7-8fed-dc569bdfcb0a.png)

Looking at the amo details page I see it twice per details page too.

**Comment by willdurand** [comment]
I think it is because `getClientCompatibility()` calls `isCompatibleWithUserAgent()`, which calls `findInstallURL()` under the hood, but this `findInstallURL()` function is also called in the `InstallButton`, a few lines after a call to `getClientCompatibility()`.

That being said, both calls to the same functions are not identical: params are different.

**Comment by kumar303** [comment]
Yeah, the compatibility check method is called in multiple places for things like button states and banners. We could maybe move it to a Redux reducer and have all things read it from state. I'm not sure that it's causing any performance issues but I haven't looked.
