### ISSUE TITLE
Restart browser message for restartless add-ons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2116]
Steps to reproduce:
1. Go to about:addons
2. Install an add-on i.e. OmniSidebar
3. Go to "Extension" tab and remove it
4. Switch back to "Get Add-ons" tab

Expected results:
There are no display or layout issues.

Actual results:
Restart browser message is displayed a few seconds for that the uninstall changes to be applied, even if the add-on is restartless.

Notes/Issues:
Verified for about:addons set to -stage, -dev and -prod using FF55(Win 7).
Video and screenshot for this issue: 
![reqrestart](https://cloud.githubusercontent.com/assets/15685960/24146881/66e9cf1c-0e40-11e7-9d2a-03b927a8016b.gif)

From https://github.com/mozilla/addons-server/issues/4396

**Comment by muffinresearch** [comment]
Needs investigating to see what mozAddonManager is doing re: restart: true hints to cause that UI flash for restarts.

**Comment by muffinresearch** [comment]
Looking into this we appear to get the following events from mozAddonManager:

```
 [disco] Event received Object { type: "onUninstalling", id: "jid0-GXjLLfbCoAx0LcltEdFrEkQdQPI@jetpack", needsRestart: true }
[disco] Event received Object { type: "onUninstalled", id: "jid0-GXjLLfbCoAx0LcltEdFrEkQdQPI@jetpack", needsRestart: false }
```

Seems to only happen via the about:addons removal. This appears to be a browser bug because it seems odd that mozAddonManager is sending a needsRestart hint when firing `onUninstalling` but cancelling it when the `onUninstalled` event is fired. 

This is why there's a momentary flash of the needs restart UI during the uninstall. 

We could file a bug to fix the browser event, which is probably worth doing but it might also be possible to ignore the `needsRestart` hint for `onUninstalling` as a workaround since we should get the `needsRestart` in `onUninstalled`.

**Comment by muffinresearch** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1349543 for the browser part of this bug.

**Comment by muffinresearch** [comment]
The decision made here was that we're not using content that needs restarts on the discovery pane so there's less of a need to fix the bugs that are in Firefox. 

To that end this is a wontfix in favour of #2135 removing the restart hints in disco pane completely.
