### ISSUE TITLE
Check what happens when the token expires

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2130]
We need to look into what happens when the auth token expires and make sure that we're handling that in a sane way.

* What is the user-experience at the point that the token expires?
* What doe we need to do to improve the scenario of token expiration?

We need to know the answers to this before the tokens for current users expire.

**Comment by muffinresearch** [comment]
This will need to be dealt with no later than 30days after #2129 is landed and released since that will implicitly reset the expiration.

**Comment by kumar303** [comment]
I think https://github.com/mozilla/addons-server/pull/5030 will make this a seamless experience. It's still worth trying it out though.

**Comment by diox** [comment]
Bump because we ideally need to solve this for next week's push.

At the moment if a client is making a request with an expired token, the API will return a 403. So the following scenario can happen:
- User logs in, get a token + cookie valid for 30 days
- 29 days later, they open AMO, leaves but keep the tab open
- 24h later, they continue from that opened tab ; the cookie has expired, but since the tab wasn't refreshed, they are still using the old, now expired token
- When making any kind of request the API will return a 403 because the token has expired

Only solutions I see for this are:
1. The frontend needs to decode the token to check for its expiration date
2. The server needs to silently drop expired tokens
3. The frontend needs to handle 403 API errors, recognize that it's a token expired 403, drop the token and try again

I think 2. makes the most sense here. I don't like silently dropping stuff, but that's how django does it for expired sessions.

**Comment by kumar303** [comment]
I logged in and left my detail page open while the token expired and tried to patch my star rating. It returned a 401 response with this as the detail:

<img width="357" alt="screenshot 2017-04-04 17 27 50" src="https://cloud.githubusercontent.com/assets/55398/24682331/af5aa9c8-195e-11e7-9806-b65c61bb3796.png">

I'm not sure what to do yet. Still thinking.

**Comment by muffinresearch** [comment]
Bumping the priority of this based on https://github.com/mozilla/addons-frontend/issues/2130#issuecomment-291506231

**Comment by kumar303** [comment]
I'm thinking that the most helpful thing the frontend can do is automatically change the app to a logged out state when the token expires. After decoding the `api_auth_token` cookie, we'll get a timestamp that I think I can work with. I haven't figure out exactly how yet.

In the meantime, a quick helpful fix is probably to adjust the message in the screenshot up above with a link that says "Refresh the page to continue" (or something). Once they refresh the page they will be logged out which will make more sense.

**Comment by kumar303** [comment]
OK, I checked what happens when the token expires so I'm closing this :) I made a bunch of actionable bugs (above) and I think this one should be the P1 that we push for next release to help people recover from expired tokens: https://github.com/mozilla/addons-server/issues/5122

**Comment by kumar303** [comment]
I would be using the code for https://github.com/mozilla/addons-frontend/issues/2238 but I can use the message string until it's ready.
