### ISSUE TITLE
Remove restart hints in disco pane

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2135]
We shouldn't be featuring add-ons that require a restart so assuming we're not featuring add-ons that don't require a restart  (excluding out of date add-ons on -dev and stage) we should ditch the functionality to handle needs restart and that will resolve a few bugs.

See also:

https://github.com/mozilla/addons-frontend/issues/2116
https://github.com/mozilla/addons-frontend/issues/580
https://github.com/mozilla/addons-frontend/issues/579

**Comment by muffinresearch** [comment]
Before we do this we should confirm with @devaneymoz that disco pane data won't feature any addons that require restart now or in the future.

**Comment by AlexandraMoga** [comment]
I have tried to reproduce https://github.com/mozilla/addons-frontend/issues/2116 on -dev disco in order to check if this patch fixed the issue. There is no requires restart message displayed anymore.

Moreover, the discopane content for -dev an stage can be controlled directly form Admin Tools, which means that the displayed data can always be edited based on needs.

![disco restart](https://user-images.githubusercontent.com/31961530/44331093-5048ad00-a471-11e8-9892-17134dc67f1c.gif)

Marking the issue as verified fixed on -dev with FF61, Win10x64
