### ISSUE TITLE
Anticipate expiring auth tokens and switch to a logged out state

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2237]
### Describe the problem and steps to reproduce it:

Open a page on AMO, let your auth token expire (see https://github.com/mozilla/addons-frontend/issues/2130), and try to do something requiring auth like submit a star rating. 

### What happened?

You see an error like this:
<img width="357" alt="screenshot 2017-04-04 17 27 50" src="https://cloud.githubusercontent.com/assets/55398/24778130/8a1aa12c-1aee-11e7-889a-b11eded68884.png">

### What did you expect to happen?

The frontend code should anticipate the time at which the token will expire and change the UI to a logged out state. It might be nice to show a message saying "you have been logged out" but at the very least everything will make more sense in a logged out state.

**Comment by kumar303** [comment]
I think it should be pretty easy to preserve review text in local storage: https://github.com/mozilla/addons-frontend/issues/2322

**Comment by muffinresearch** [comment]
@kumar303 I needed to use olympia.dev to get this working but it did look to work fine running locally.

The only thing that could improve this even more would be to actually have some kind of notification to the user perhaps providing directly a button to log in again so that it's clearer what actually happened. Unless you notice the login button change from `Logout` to `Log in / Sign up` you might wonder what happened.
