### ISSUE TITLE
Pin dev dependencies to major versions for less Greenkeeper noise

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2293]
Let's change all dev dependency specs in `package.json` from pinning exact versions to pinning major versions. For example, the following:

    "package-name": "1.0.0"

would become:

    "package.name": "^1.0.0"

This will tell `yarn` to upgrade to the latest package for `1.x.x` but not to any major version such as `2.0.0`.

This will also make Greenkeeper behave like:
* When a new minor/patch version is released and the tests pass, it won't send a PR
* If a new minor/patch version breaks the build, it will send a PR
* If a new major version is released, it will send a PR regardless

See https://github.com/greenkeeperio/greenkeeper/issues/27#issuecomment-146212266

**Comment by tofumatt** [comment]
This will make managing Greenkeeper PRs a lot better and will motivate us to actually pay better attention to them, I think 😄 

I know I suggested this so it's bias of me to say, but I think this is a really good thing to tackle so there's less Greenkeeper noise without losing out on its benefits.

I know @kumar303 mentioned the possibility of someone having features someone else doesn't but I'd think using `yarn` would manage that... and worse case we'd have a situation where we realised we'd need to pin `^1.1.0` instead of `^1.0.0`. I think those edge cases would be less frequent than fine-to-merge-but-annoying-to-manage point upgrades from Greenkeeper.

**Comment by kumar303** [comment]
> I'd think using yarn would manage that...

Hmm, I'm not sure what yarn will do since we don't use the lockfile locally to lock down deps. I guess we'll see what happens! It seems worth a try and we can always pin to minor versions, as you say.
