### ISSUE TITLE
Install button doesn't enter installing state

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#2314]
### Describe the problem and steps to reproduce it:
1. Click the switch to install a webextension with permissions.
2. Wait for the download to complete.
3. While the permissions prompt is open examine the button.

### What happened?
Button is green as if still downloading.

### What did you expect to happen?
Button should be striped animating green to show that there is some work being done.

### Anything else we should know?
It looks like this worked in #366 when the install button was running off some fake data. I'm guessing this stopped working when the mozAddonManager support was added but that patch likely shows what state the button should be in or what installation event we aren't checking for anymore.

Old video showing the states:

![InstallButton states](https://cloud.githubusercontent.com/assets/211578/15199011/dad00c62-17a0-11e6-84b0-37ff14f8e991.gif)

**Comment by muffinresearch** [comment]
I noticed this recently with the demos andy was doing to show the various permissions diaologues. Would be good to run this on -dev and see the events. I have a feeling that mozAddonManager events might not be being sent correctly in which case we should file issues there to get them fixed.

I'll investigate and add info to this bug.

**Comment by muffinresearch** [comment]
So looking at the logs this is the process installing a web-ext with the permission prompts on:

* Clicking install starts the download
* The progress indicator shows the download progress
* Gets to a full bar (all-green)
* Then FF shows the permissions dialogue
* If OK'd the install completes as normal

We didn't previous respond to `onDownloadEnded` since it was always followed by the start of the actual installation.

To fix this bug we need fire off a separate state in response to the install objects `onDownloadEnded` event (probably here [1]) (maybe `DOWNLOAD_ENDED`) on completion of the download this should then be hooked up to run the same UI the `INSTALLING` state shows which would then provide the correct stripey animation.

[1] https://github.com/mozilla/addons-frontend/blob/7f3f48cdf6c8380c65a53c9e45c6ce6ded9ede4e/src/core/installAddon.js#L60

**Comment by muffinresearch** [comment]
Bumping the priority of this because it's going to start hitting more users.

**Comment by muffinresearch** [comment]
@kumar303 could you see about fitting this in along side other things? I think the fix should be fairly straight-forward?

**Comment by kumar303** [comment]
ok, I can still reproduce this. When I thought it was fixed I was looking at an add-on without permissions.
