### ISSUE TITLE
Loading bar has dissappeared

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2395]
The loading bar has dissappeared from the mobile site.

There's no loading bar shown when navigating or doing an action that fetches data on -dev, stage or prod.

**Comment by muffinresearch** [comment]
Potentially related to the last update [1] but need investigation.

https://github.com/mozilla/addons-frontend/pull/2349

**Comment by tofumatt** [comment]
QA: To verify you should see the blue loading bar on the top of the page when nagivating from the home page to the "Extensions" or "Themes" link on the homepage (really, anything from the homepage but just trying to make it easy to repro–there are a few links like navigating back to the homepage that won't show the loading bar because they don't make any async requests and are instant).

**Comment by kumar303** [comment]
It's a mystery as to what caused this. Here is all that changed in the package https://github.com/mironov/react-redux-loading-bar/compare/762fa369691aab52df550b1a2b2ee742b2b70b2a...cfb35014376fbd7c01e2a04f5b1a04573a46113a

**Comment by ValentinaPC** [comment]
While being focused on the fact that the `puzzle placeholder` was missing, did not observed that the `loading indicator` was missing too (https://github.com/mozilla/addons-frontend/issues/1219#issuecomment-301026769)

Verified this on AMO-dev FF53(Win 7) and observed a loading indicator in 2 colors:
- `blue` while going, for example, from homepage to "Extensions"
- `orange` while, for example, changing the language
Videos:
![videotogif_2017 05 19_08 59 18](https://cloud.githubusercontent.com/assets/15685960/26235688/4dbfb2b4-3c75-11e7-86e5-4701d02fee84.gif)
![videotogif_2017 05 19_09 02 48](https://cloud.githubusercontent.com/assets/15685960/26235687/4dbf5274-3c75-11e7-9057-64db1aaf1922.gif)

Please let me know if intended.
