### ISSUE TITLE
Edited reviews are displayed with the first creation date

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2440]
Steps to reproduce:
1.On Android, find an add-on where an user added a review some time ago
2.Using same user, edit the review
3.Read the reviews

Expected results:
The date of review should be the date of latest edit 

Actual results:
The date of the review is the date of initial review 

NOTES:
The date was not updated after waiting few hours and multiple refreshes 

Please see video for this bug : 
![recording](https://cloud.githubusercontent.com/assets/1583842/26457620/8882cda6-4179-11e7-86d7-0120814de817.gif)

**Comment by vcarciu** [comment]
Possible related to #1664

**Comment by jvillalobos** [comment]
One problem of updating the date is that the review will show up at the top again, and it could be abused to give a particular review more attention than it should get. Editing is meant to make small changes shortly after posting, so it shouldn't matter too much if the date isn't updated.

I think this should continue to be the expected behavior, at least until we have better ways to rank reviews.

**Comment by kumar303** [comment]
> Possible related to #1664

This one was different. It is some kind of client timing issue that creates a timestamp in the future.

**Comment by vcarciu** [comment]
@jvillalobos : on the other hand, I can submit a very different review for same add-on over time and this should be displayed on the top

**Comment by jvillalobos** [comment]
Yes, it's a trade-off. Will take it into account when we make bigger changes to the rating/reviewing feature.
