### ISSUE TITLE
When running the core app all CSS is amalgamated

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#247]
I was finding it odd that I couldn't set the background color on body for the disco pane. Turns out when running under the core app app CSS is being output for all apps at once. 

We either need to fix this up and stop that happening, or alternatively remove the running of everything at once. 

Having everything running is quite nice for the sanity check that changing something in one project isn't busting the other one so we should try fixing the core app first.

**Comment by mstriemer** [comment]
We might be able to fix this with the routes, but I'm not sure what implications that will have on the server. The core routes currently load the child routes but perhaps that's a bad idea.

Maybe we should go through the apps and load routes until we find one that matches and load only those ones.

So essentially the core app would have one route that just displays the list of apps. Clicking on one of those links would trigger a full page refresh since the core app does not know about the routes in the other apps. On the server we'd notice that the route matches, let's say, the disco app and loads its routes/store/etc.

**Comment by muffinresearch** [comment]
Yeah I'm looking at this now, since it's getting in the way of adding styles to the disco pane. I think it might work better to have multiple entry points in the webpack conf and *not* per app like we have currently. I'm going to see if I can move to building multple entry points and refactor some of the server stuff to provide better separation.

**Comment by muffinresearch** [comment]
This looks to be working, I'm conditionally building multiple entry points so if you run core you get files output for each app. This should mean that if I push the JS inclusion down into the server for each app then the style output will be relevant to that JS and not all of it. This also means that building per app still works as it does now.
