### ISSUE TITLE
yarn test no longer runs lint test

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2489]
It would be nice if `yarn test-once` and `yarn test-coverage-once` also ran the linting tasks (run using `yarn lint`) so that code is linting during a full local test run.

**Comment by tofumatt** [comment]
Note for contributors: this should involve editing the `package.json` to add a new command to `"scripts"` that runs the `yarn test-once` command and the `yarn lint` command.

**Comment by kumar303** [comment]
`yarn test` was a replacement for `unittest:dev` and that never ran lint checks. I always wanted it to! We have this on file to put all fast checks (linting, flow, etc) in one command: https://github.com/mozilla/addons-frontend/issues/2281

> I think yarn test-once should run linting checks

Yeah, that sounds like a good idea.

> Maybe we want test-all for this?

Please, not another one :-D The watcher in `yarn test` makes things tricky but since `test-once` doesn't have a watcher it can test all the things (but probably without coverage).

**Comment by tofumatt** [comment]
> `test-once` doesn't have a watcher it can test all the things (but probably without coverage)

That was also my preferred option, sweet 👍

**Comment by tofumatt** [comment]
To clarify:

It would be nice if `yarn test-once` and `yarn test-coverage-once` also ran the linting tasks (run using `yarn lint` so that code is linting during a full local test run.

**Comment by wagnerand** [comment]
Mentor: @tofumatt 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.
