### ISSUE TITLE
Are we intentionally removing Tabzilla from the site?

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2512]
The new mocks don't have Tabzilla/the Mozilla link in the header. Is this intentional?

I'm actually for this as I find it easier to click on and take me to a totally different page I didn't intend to visit (it feels like a better footer link than header link) and it cleans up the design. I think tabzilla only works when it's the JS drop-down thing.

But I just wanted to make sure it's intended.

**Comment by muffinresearch** [comment]
FWIW I started a patch on Tabzilla to update it to the new brand, but the general consensus with that was that it's going away in favour of just using a link with the up to date logo. I think part of that was informed by it being easier for each property to decide the way they wanted to display it rather than needing a library.

**Comment by pwalm** [comment]
Tabzilla is dead! It is replaced by the new Mozilla logo in the footer.

**Comment by tofumatt** [comment]
Cool. Thanks for the clarification, consider this resolved!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2)
Postfix screenshot:
![tabzilla](https://user-images.githubusercontent.com/15685960/27031872-beab2766-4f7a-11e7-9040-1352ce6beb9b.png)
