### ISSUE TITLE
We should not change icon_url to iconUrl

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2595]
### Describe the problem and steps to reproduce it:
This code https://github.com/mozilla/addons-frontend/blob/master/src/core/reducers/addons.js#L12 doesn't really do much but is really annoying and weird to debug. We should remove it.

### What happened?
I wanted to refactor a test.

### What did you expect to happen?
It was annoying to refactor because we rename this one property.

### Anything else we should know?
@kumar303 is going to run out of GIFs, be sure to bring him extra at the All-Hands.

**Comment by willdurand** [comment]
Code is here AFAIK: https://github.com/mozilla/addons-frontend/blob/afc5cc00788734e3dc74190559097a022825e559/src/core/reducers/addons.js#L194-L197

**Comment by SIMRAN1** [comment]
@willdurand I want to work on this issue. May I proceed?

**Comment by willdurand** [comment]
@SIMRAN1 yep

**Comment by willdurand** [comment]
We actually agreed on not doing this (see: https://github.com/mozilla/addons-frontend/pull/6241#discussion_r217512958).

**Comment by kumar303** [comment]
The add-ons reducer was aliasing `iconUrl` to `icon_url` to accommodate this bonkers code in Discopane that everyone was afraid to touch:

https://github.com/mozilla/addons-frontend/blob/d6c8b4a34204f8848bfceae6f5afbe599432fc86/src/disco/containers/DiscoPane.js#L129

This issue was simply about cleaning up the reducer by removing the unused alias:

https://github.com/mozilla/addons-frontend/blob/3949e3e2bc4d79c0a5510213b9b2f48f942dccd8/src/core/reducers/addons.js#L198-L201

As far as I can tell, Discopane is no longer camel casing keys so I think it's safe to remove?

@willdurand can we re-open this issue? I think you were talking about something completely different in https://github.com/mozilla/addons-frontend/pull/6241#discussion_r217512958

**Comment by willdurand** [comment]
mmh I thought it was a more generic issue stating that aliasing `iconUrl` to `icon_url` was counter-productive, not just this prop. I don't understand why we would like to keep a 1:1 binding for this property and not for other props to be honest.

> As far as I can tell, Discopane is no longer camel casing keys so I think it's safe to remove?

I think so yes.

**Comment by ioanarusiczki** [comment]
@willdurand Is this for "qa not needed" label or is there something we could test ?

**Comment by willdurand** [comment]
@ioanarusiczki in -dev and - stage, there should be no regression in disco pane. Add-on icons should be correctly displayed everywhere.

**Comment by ioanarusiczki** [comment]
@willdurand Verified Disco pane - dev and -stage with FF62 and FF64 (Win10). 
They look good to me!
