### ISSUE TITLE
First time when opening an add-on details page, the install radio button is greyed out

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2636]
Prerequisites:
extensions.webapi.testing set to true

Steps to reproduce:
1.On your Android device, open any add-on for first time on AMO-dev(https://addons-dev.allizom.org/en-US/android/addon/phony)
2.Try to tap the install radio button

Expected results:
Radio button can be used and add-on is installed

Actual results:
Install radio button is greyed out and unusable 

NOTES:
After a refresh, the button becomes active and the add-on can be installed
Not reproducible on desktop with mobile view enabled

Please see video for this issues : 
![unusablebutton](https://user-images.githubusercontent.com/1583842/27589675-e712b21a-5b54-11e7-8500-48f841427ae7.gif)

**Comment by tofumatt** [comment]
Does this happen on the disco pane as well? Can you send any logs along? Thanks.

**Comment by tofumatt** [comment]
Can you reproduce this? I just tried on desktop (where it was failing) and also mobile and it was fine.

**Comment by tofumatt** [comment]
Shoot, never mind, I can get it to happen using android URLs and desktop firefox, but it only happens when navigating to the page from other results, yes.

**Comment by tofumatt** [comment]
FYI this happens on any page if `disableSSR` in config is set to `true` and happens only from the featured landing pages `/extensions` and `/themes`, NOT from search results.

It seems to be caused by the redux-saga patch, which reverting causes a conflict from. But the real issue is that the `withInstallButton` HOC requires having the data before the component is loaded, so using sagas breaks it entirely. This means that component needs to be refactored for us to use sagas on the frontend and disco pane anyplace we have an install button.

**Comment by vcarciu** [comment]
Verified as fixed : 
![firstpress](https://user-images.githubusercontent.com/1583842/27869714-753e5aee-61a9-11e7-9287-db24e632e329.gif)
