### ISSUE TITLE
Stop dispatching action payloads with functions

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2659]
The install helpers [dispatch an action payload](https://github.com/mozilla/addons-frontend/blob/0fa89bffce8b254f3c8e51acbd7796d4cc70c2d8/src/core/installAddon.js#L155) containing a function. This defeats the purpose of Redux because you can't capture and replay the payload for debugging. It should not be dispatching a function.

**Comment by tsl143** [comment]
Is it good for me to get started with this?

**Comment by tofumatt** [comment]
I think this might be a bit of a complex patch requiring redux knowledge, but if you feel comfortable tackling it okay. You'd want to be comfortable with redux though.

Matthew Riley MacPherson (sent from mobile)

**Comment by tsl143** [comment]
I have been working on react-redux for atleast 6 months(company project) and have decent knowledge about how action/reducers/stores/middlewares work.
Will that be good enough to get started with this?

**Comment by tofumatt** [comment]
Yeah I think so then. As long as you understand what the bug is saying you're good. Because it touches installation code you will likely also need to follow the docs in the docs folder about building a custom Firefox to test the install button though. Come to think of it there's a lot of moving parts here... if you understood everything I mentioned you would be okay but if not feel free to find another bug to work on, this one probably seems bigger than it is because it touches the install flow.

Matthew Riley MacPherson (sent from mobile)

**Comment by willdurand** [comment]
Oh, there was actually an issue about this problem.. I filed #5867 and created a PR for it.
