### ISSUE TITLE
Fonts for add-ons in horizontal card view should be modified

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2661]
@sarahmonster pointed out that a larger font size with a lighter font weight would look good for the desktop horizontal card add-ons. She suggested:

```css
font-size: 18px;
font-weight: 500;
line-height: 1.2;
```

and it looked good, so I'll do that. I think that's closer to the mocks anyway and I sized them down like a doofus.

**Comment by aayushsanghavi** [comment]
@tofumatt if you don't mind, could I work this? Also, could you tell me which component are we talking about here (a screenshot of the page, perhaps)?

**Comment by tofumatt** [comment]
It's the AddonsCard component in the amo app when `type="horizontal"` is set. It appears on the desktop pages at /extensions and /themes

**Comment by aayushsanghavi** [comment]
@tofumatt I tried it but when I inserted those rules after [this line](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonsCard/styles.scss#L5) the children elements rejected them; they were overridden by other css rules that the children elements inherited from other elements. I'm definitely not doing the right thing. Suggestion on how could I fix it, please :)

**Comment by tofumatt** [comment]
Turns out we were actually overriding these styles on desktop which is silly, so just gonna remove them.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
@tofumatt Did you kept the suggested dimensions?
Because I've checked in extensions and themes homepages and seems like the `font-size` is `14px` and not `18px`, `font-weight` is `400` and not `500`; `line-heigh`t is ok - `1.2`;
Screenshots:
![ext_homepage](https://user-images.githubusercontent.com/15685960/28626710-7b81e9fe-7228-11e7-9147-33f4936ffab9.png)
![th_homepage](https://user-images.githubusercontent.com/15685960/28626716-7fa15ace-7228-11e7-93c7-8cdb574d5281.png)

**Comment by tofumatt** [comment]
Yes, sorry, that’s correct, we did further tweaks so the new values you reported are correct. Sorry I didn’t update the original issue!

**Comment by ValentinaPC** [comment]
Based on above comments we can mark this verified fixed.
