### ISSUE TITLE
On larger screens, categories should run in a column down the left

### ISSUE THREAD

**Issue by sarahmonster** [mozilla/addons-frontend#2662]
The long string of categories/tags can be a bit tricky to read, particularly with lots of options:
<img width="1339" alt="screenshot 2017-07-01 20 12 55" src="https://user-images.githubusercontent.com/376315/27764772-b87529d6-5e99-11e7-95ce-351650b7ac2f.png">

It would be a boatload more readable like this:
<img width="1338" alt="screenshot 2017-07-01 20 11 30" src="https://user-images.githubusercontent.com/376315/27764774-c4a7a5a8-5e99-11e7-99d3-6021e7a6c2a8.png">

It's also worth considering removing the card background, the further indicate it isn't a card containing content, but rather a series of filters. 

In the future (particularly if the list gets quite long) grouping them by sub-category would help with scannability as well—our brains struggle with long lists of things, unless I guess you happen to be blessed with @tofumatt's genius.

**Comment by tofumatt** [comment]
This is closer to what we did on the old site and I think it's actually a better use of space. Thoughts, @pwalm?

**Comment by tsl143** [comment]
Also shall we stack categories alphabetically in left panel?

**Comment by tofumatt** [comment]
I think so, they should be sorted that way by the reducer but it seems to be a bit flakey. 😒

**Comment by pwalm** [comment]
Hadn't intended for a L-hand column on top level pages, but we do have it in other layouts. I'll do an experiment and see how it looks.

**Comment by pwalm** [comment]
Mock with L-hand column. I could go either way on this. I don't see it adding or subtracting from the current one column mock, so I think we'll stick with one column.
![screen shot 2017-09-12 at 2 45 12 pm](https://user-images.githubusercontent.com/6797635/30349778-03fc8832-97c9-11e7-960d-7a807fc2f3fe.png)

**Comment by muffinresearch** [comment]
Based on @pwalm's mock I think this would only really work if there was less colour in the category labels, I notice my eye is drawn to them too much compared to the actual content.

Since we've fixed the width of the central column it's not quite as bad as it was when first reported.

I think based on the experiment this issue can be closed out as we're going to stick with the current layout but we should definitely consider this if the category layout gets updated in the future.
