### ISSUE TITLE
Empty type query param in search from homepage

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2665]
### Describe the problem and steps to reproduce it:
When searching from the home page, an empty `type` query param is added to the URL. See: https://github.com/mozilla/addons-frontend/issues/2513#issuecomment-312585463

### What happened?
An empty `type` param is in the URL.

### What did you expect to happen?
No type param is set when it's empty.

**Comment by tofumatt** [comment]
Sorry, typo closed this rather than the one it should have. This is still unresolved 😅

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
- While searching for a term the following URL is displayed:
`https://addons-dev.allizom.org/en-US/firefox/search/?q=test`
- While making an empty search the following URL is listed:
`https://addons-dev.allizom.org/en-US/firefox/search/`

Also, making an empty search in homepage after I previously did one in Extensions or Themes pages, will display the message for extensions search but no results
- refresh will fix the issue
Please see video:
![strange](https://user-images.githubusercontent.com/15685960/29359917-3b5410a2-8289-11e7-86c5-d7e9cd84006c.gif)

@tofumatt : please let me know if separate tracking for this issue is required. Thanks!
