### ISSUE TITLE
Discopane UI tests are returning 1 and causing CI to report failures

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2704]
Travis is seeing `TypeError: Cannot set property 'getDocsInfo' of undefined` and can't run `yarn`.

I'm having a look, others seem to be reporting a similar error.

**Comment by tofumatt** [comment]
As [others reported](https://github.com/yarnpkg/yarn/issues/3851#issuecomment-313703599), running it again meant `yarn` worked.

The discopane tests are still failing, returning `1` when they pass.

**Comment by kumar303** [comment]
I'm on PTO today but yesterday I contacted TravisCI support because it doesn't make sense that our `docker logs` command is failing (at least I think that's what's failing). Also, I noticed that the `travis-build` revision got bumped when our job started failing.

If anyone wants to try this before I'm back, they suggested the following:

"A possible close approximation of the issue might be to run it locally with our Docker images, as described here: https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

It is also possible to turn on the debug feature for this repository, so that you can have access to a running VM https://docs.travis-ci.com/user/running-build-in-debug-mode/ "

BTW, it seems unlikely that their build deployment caused the error although it's still possible. They sent me this diff of the release which they said mostly contained housekeeping changes: https://github.com/travis-ci/travis-build/compare/75a27e5e4...6094b6ae8

If no one gets to it before me I'll try in debug mode and try to see if `docker logs` is really the culprit or not.

**Comment by tofumatt** [comment]
I tried doing this but I'll admit I'm a bit unfamiliar with exactly how to run the UI tests from a checkout. I tried building the docker image inside the travis docker image, but running the test-ci command had the travis VM complain that it couldn't find a running docker :-/

I'll try again later when my brain is less hazy.

**Comment by tofumatt** [comment]
Oh I think I'm dumb and probably needed to enable the right config... having another look now. Sorry, I've never run travis VMs/dockers locally before!

**Comment by tofumatt** [comment]
I couldn't quite figure out how to get things set up locally. The Travis docker images aren't, as I understand it, what we're running on because we ourselves use docker. Docker isn't running on those images and I don't get how to start it... but even so it feels like it's not the same process as what's happening on Travis so I didn't keep exploring. 😢

**Comment by kumar303** [comment]
I'll take a look on Monday

**Comment by tofumatt** [comment]
#2722 seems to have Travis running the tests without failing, so removing the P1 label. Would be nice to know why the logs command needs to be run (if it does) and why it's failing, but it's no longer breaking the builds at least 😅

**Comment by kumar303** [comment]
Well, huh. I don't see any new changes in the Travis system so that's weird! Oh well.

For archival purposes, here is the last build that failed:
https://travis-ci.org/mozilla/addons-frontend/jobs/251613465
...and here is the first build that started passing again:
https://travis-ci.org/mozilla/addons-frontend/jobs/251941910

**Comment by kumar303** [comment]
> Would be nice to know why the logs command needs to be run

It will show all output from Docker. This is essential for when the UI tests fail with useless failures (like X is missing from the page). The Docker logs tend to expose server side errors.

**Comment by tofumatt** [comment]
Ah. To be clear my fix was that I removed the `docker logs` command. I figured that's why we had the command in there, so while I think removing them and not having access to the error in the logs is better than them falsely failing all the time... it seems like this isn't entirely fixed.

**Comment by kumar303** [comment]
The log viewing command was removed in https://github.com/mozilla/addons-frontend/pull/2722
