### ISSUE TITLE
0 results for "Any" filter in Django Admin\Addons

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-frontend#2725]
Steps to reproduce:

1. From Django admin pages (/admin/models/) select Addons and pick an add-on in the list, e.g. https://addons-dev.allizom.org/en-US/admin/models/addons/addon/ .
2. From the "By type" tap on the "Any" filter and from "By status" tap on the "All" filter.

Expected results:
Add-ons with the selected filtering are displayed.

Actual results:
0 add-ons are displayed.

Notes/Issues:
Verified on FF54(Win 10). Issue is reproducing on AMO Dev servers.
Video Gif for this issue:
![any](https://user-images.githubusercontent.com/28138132/28010954-533b7c38-6569-11e7-9aa6-245bf290cf93.gif)

**Comment by muffinresearch** [comment]
@SVSanta ideally this should be filed on mozilla/addons-server since that's the django site. 

`addons-frontend` is only currently covering the new look frontend (mobile and desktop (opt-in if the `mamo` cookie is set or your running a mobile users-agent)) and the current discovery pane visible via `about:addons`

**Comment by tofumatt** [comment]
Re-filled on addons-server. Closing here 😀

**Comment by muffinresearch** [comment]
@tofumatt thanks for re-filing 👍
