### ISSUE TITLE
Add search hints/autocomplete

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2747]
Add a search hint/autocomplete as per mocks. Relies on https://github.com/mozilla/addons-server/issues/3545.

**Comment by willdurand** [comment]
The API endpoint has been implemented in https://github.com/mozilla/addons-server/pull/5930, and the API doc is here: https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#autocomplete.

**Comment by willdurand** [comment]
I have started the UI based on the Sketch files. Things have slightly changed but I tried to stick to the original:

![capture d ecran - 2017-08-16 a 12 55 13](https://user-images.githubusercontent.com/217628/29360230-37f644ae-8282-11e7-957f-a3c2a9cb009a.png)

**Comment by willdurand** [comment]
@pwalm Hi, I am a bit confused by the new mockups. I have exported the latest version I have below:

![search](https://user-images.githubusercontent.com/217628/29462291-20551060-842f-11e7-88ee-0a455addc841.png)

What is the first set of entries/suggestions? In the previous mockups, it was about suggestions to help users type right, but now it seems to be different. At first glance, I thought this first set represented a history (previous/past searchs).

Yet, because there are also a second set with icons and arrows, I am not sure about what the first set actually is. If there is an arrow and the icon of a well identified add-on, then I would expect to redirect to the add-on page directly on click/tap, and not to fill the input and trigger the search process.

Could you please give more details about the autocomplete/auto-suggest feature? Thank you!

**Comment by kumar303** [comment]
I think the first set of menu items are suggestions for search *terms* and the second set are suggestions for search *results*.

However, the API only returns suggested search *results* so let's start by implementing that.

**Comment by willdurand** [comment]
Updating milestone.

**Comment by pwalm** [comment]
@kumar303 Is correct! First three: search terms. Second three: search results. I can actually make this clearer by adding subheads if we need to, we've done it for some other drop-downs in the header already: 
<img width="639" alt="screen shot 2017-08-24 at 4 00 01 pm" src="https://user-images.githubusercontent.com/6797635/29692510-50fe9be0-88e5-11e7-9324-7ee96bf498fc.png">

**Comment by tofumatt** [comment]
@pwalm Yeah, I think the subheaders make it a lot clearer, and since we use them elsewhere in similar elements I say 👍

**Comment by ValentinaPC** [comment]
Verified the fix from #2971 using FF55(Win 7, Android 7.2.1)
Search suggestions are displayed.
Postfix videos: 
![videotogif_2017 08 29_11 15 24](https://user-images.githubusercontent.com/15685960/29811416-0b072bdc-8cac-11e7-9b49-b5e6e1c138ed.gif)
![search-desktop](https://user-images.githubusercontent.com/15685960/29811426-0fd039f6-8cac-11e7-9572-e430c9915d7d.gif)
