### ISSUE TITLE
Disable Sentry when DNT is enabled

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2802]
We should disable logging application errors/exceptions to sentry when DNT is enabled. It's not tracking but I'd imagine users who were uncomfortable submitting usage data from the app to GA also don't want to log their errors in Sentry.

**Comment by kumar303** [comment]
It would be pretty terrible to lose Sentry error reporting for DNT users (of which there are probably a lot). We need to check with Legal first if this is really necessary. My read of https://www.mozilla.org/en-US/privacy/websites/ is that it's probably not necessary since Sentry isn't used for what is described as "Metrics."

**Comment by muffinresearch** [comment]
I don't think we need to do this since Sentry is related to the running of the service rather than anything related to tracking.
