### ISSUE TITLE
"+" replaced with empty space in link after sorting

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-frontend#2816]
Steps to reproduce:

1. Load Extensions homepage in AMO-dev https://addons-dev.allizom.org/en-US/ .
2. Click on "View Mobile Site".
3. Perform a search containing spaces.(ex. "add b c")
4. Change the sorting.(ex. to "Most Users")

Expected results:
The link displayed is "https://addons-dev.allizom.org/en-US/firefox/search/?q=add+b+c&type"

Actual results:
The link displayed is: "https://addons-dev.allizom.org/en-US/firefox/search/?q=add b c&sort=users"

Notes/Issues:
Verified on FF54(Win 10 64Bit). Issue is on all servers.
Gif for this issue:
![spaces](https://user-images.githubusercontent.com/28138132/28272309-ca67fd4a-6b13-11e7-8707-33707143b9b8.gif)

**Comment by kumar303** [comment]
Between requests, some code is changing the URL encoding from plus encoding to percent encoding. Both are valid in this context. If you copy the URL with spaces in it and then paste it into a text document you will see that the spaces are actually encoded with `%20`. Since both URLs are technically valid I'm closing the issue. 

The inconsistency is a little weird but since it's not causing a bug, it's not worth spending time to investigate right now.
