### ISSUE TITLE
Tapping on any category loads a 404 page for a few seconds

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2846]
Steps to reproduce:
1. Load AMO homepage on you device https://addons-dev.allizom.org/en-US/android/
2. Tap on a category i.e. "Blocks ads"

Expected results:
Category is loaded without any display or layout issues.

Actual results:
A 404 page is loaded for a few seconds.

Notes/Issues:
- happening first time the page is loaded - reproduce is you must load the page again in a new tab;
- reproducing on new desktop pages also;
- may be a regression from #2084 

Verified on FF54(Win 7). Issue is reproducing around all AMO servers.
Video for this issue:
![videotogif_2017 07 24_11 04 39](https://user-images.githubusercontent.com/15685960/28513760-08c84d14-7060-11e7-8323-7dd2cf64049d.gif)

**Comment by tofumatt** [comment]
Shoot, I thought the code handled the loading state appropriately but seemingly not. I'll get this, should be able to fix it before the tag tomorrow as it's kind of janky UX.

**Comment by tofumatt** [comment]
Hah, this is because the categories and the search load separately, and we have an issue with the categories not being loaded (and `category` being false [during the check, here](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Category/index.js#L37)) while the search is (and thus saying `loading` is `false`.

Looks like `loading` needs to be set based on multiple loading states or this needs to be a bit more robust. Should be an easy fix, just weird to track down.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7, Android 7.2.1).
A 404 page is not longer displayed while accessing any categories from homepage.
Postfix video:
![cat](https://user-images.githubusercontent.com/15685960/28875488-677c910e-779e-11e7-9868-1531db2ef156.gif)
