### ISSUE TITLE
Lighten the colour of the loading indicator bars

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2899]
The grey used in the loading indicator is quite dark which make the effect a bit jarring. It would be less so if the grey used was knocked back a notch.

We might want to get UX input on an appropriate shade for this.

**Comment by tofumatt** [comment]
I think we did but either I forgot to implement it or it's still not dark enough. The first saga patch's PR it was brought up, if I recall correctly.

Matthew Riley MacPherson (sent from mobile)

**Comment by caitmuenster** [comment]
Not sure if this is a good first bug -- we're not sure what the color should be or if this is in progress.

**Comment by muffinresearch** [comment]
@pwalm - could you provide some input on the colour for this?

**Comment by pwalm** [comment]
Which loading indicator do we speak of here?

**Comment by tofumatt** [comment]
The loading bar/text thing that appears in most places on the site when content is loading. The best place to see it is on dev in the search bar while autocomplete is loading or when clicking on an add-on from the autocomplete results.

- tofumatt

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix video:
![loading](https://user-images.githubusercontent.com/15685960/30592853-2aeaaaa4-9d51-11e7-9e2a-be824f52b90a.gif)

@muffinresearch: is there an issue logged for the thing you mentioned in the pull request - the half of add-on puzzle? Because that is still happening. Thanks!
