### ISSUE TITLE
DRY up stub error handlers in the test suite

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2936]
We use this pattern in the tests a lot:

```js
const errorHandler = new ErrorHandler({
  id: 'some-id',
  dispatch: sinon.stub(),
})
```

The `id` doesn't matter (it could be a random string or the same string each time) and the dispatch function is always set to `sinon.stub()`.

Thus, we should just replace it with a helper:

```js
import { createStubErrorHandler } from 'tests/unit/helpers';

const errorHandler = createStubErrorHandler();
```

**Comment by muffinresearch** [comment]
@willdurand our tag is at 9AM PT today (Tuesday), so if this lands before then this **issue** (we only track issues by milestone rather than PRs) should be added to the 2017.08.17 milestone and then it will appear in the milestones app for the week: See https://amo-milestones.herokuapp.com/milestone/2017.08.17/issues/

**Comment by willdurand** [comment]
@muffinresearch roger that!
