### ISSUE TITLE
mozAddonManager install buttons are not version aware

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3055]
I had a beta version of ublock origin installed. As far as mozAddonManager is aware, based on the guid I have that add-on installed. However _**I didn't have the latest version installed**_. I was able to get the latest version by clicking the install button to remove it and re-install.

It made me think it would be nice if the UI reflected that I have the add-on installed but could also offer me the latest version.  Maybe the UI could should a 🔄 icon (or similar) instead of a tick which when clicked could do the update.

This probably needs consideration to decide if this is actually something we want to do. Also I'm not sure to what degree mozAddonManager exposes detailed information about the installed add-on when it is introspected. If we need more info that would need Firefox bugs filing and those would need to ride the trains.

/cc @jvillalobos for input.

**Comment by jvillalobos** [comment]
This would be tricky to do because a single add-on can have multiple update channels (listed, beta, unlisted) and an add-on listing page only shows the latest version of the listed channel. It's useful to offer the install even if you have the add-on installed, particularly in the case a user wants to _switch_ to the listed channel. However, for updates I think it's best that users stick to automatic updates, which run daily anyway.

**Comment by muffinresearch** [comment]
@jvillalobos so I think on this basis we'll just leave the button as is - and accept for now that it's not going to be aware of versioning or channels.
