### ISSUE TITLE
Unusable Filter menu in "No results..." page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3068]
Steps to reproduce:
1. Search for something that would have no results in -dev

Expected results:
No results message displayed. 

Actual results:
Filter menu is displayed with no results to filter.

Notes/Issues:
Verified on AMO-dev FF55(Win 7, Android 7.2.1).
Issue was not reproducible while the sort menu was available.
Screenshot for this issue:
![remove_filter_menu_for_no_results](https://user-images.githubusercontent.com/15685960/30049636-19a7043c-9224-11e7-910d-ba2b889c8934.png)

**Comment by tsl143** [comment]
@muffinresearch  isnt this desired, as we have a testcase `renders SearchFilters even when there are no result` at https://github.com/mozilla/addons-frontend/blob/master/tests/unit/amo/components/TestSearch.js#L83

**Comment by tofumatt** [comment]
The issue is that the sort menu only sorted existing results, but the new filters change the result set. Imagine you searched for something with the filter "Mac OS" only on, and there were no results. You might want to change it to "Platform: Windows" or even "Platform: All". So this is working as intended. 😄

**Comment by ValentinaPC** [comment]
I have a vivid imagination....as I imagined that 0 results page will look nice without a filer menu :D .

**Comment by tofumatt** [comment]
It would look better, but we should allow users to refine/change the search as it could then show results 😄
