### ISSUE TITLE
Layout issues on iOS Firefox & Safari

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#3079]
### Describe the problem and steps to reproduce it:

Filing in one single issue since they seem closely related.
STR:
1. https://addons.mozilla.org/en-US/firefox/addon/ubo-scope/

### What happened?

The blue fox logo, 'Explore' and 'Themes' are not where they should be.
On Firefox, they even move a bit as soon as you scroll down.
On Safari, they don't.

Also, the description is cut, at least on Safari.

### What did you expect to happen?

Correct placement and no moving...

### Safari:
![img_4346](https://user-images.githubusercontent.com/873258/30184278-dd92ff72-941d-11e7-9ee8-13067499f50b.PNG)

### Firefox, top of the page:
![img_4347](https://user-images.githubusercontent.com/873258/30184280-dd94da4a-941d-11e7-9125-6e6c999ef480.PNG)

### Firefox, scrolled down a bit:
![img_4348](https://user-images.githubusercontent.com/873258/30184279-dd9485ea-941d-11e7-9e27-3f36e4f2a851.PNG)

**Comment by ExE-Boss** [comment]
On Firefox for iOS version 9.0 on iOS 11, the layout looks like this:

## Vertical: (Top bar redacted for privacy)
![Firefox for iOS 9.0 on iOS 11 – AMO (Vertical)](https://user-images.githubusercontent.com/3889017/30675015-49f841da-9e7e-11e7-88aa-427683f5a77b.png)

### Zoomed out:
![Firefox for iOS 9.0 on iOS 11 – AMO (Vertical, zoomed out)](https://user-images.githubusercontent.com/3889017/30675011-44146014-9e7e-11e7-8f88-f72dfd2550f1.png)

## Horizontal:
![Firefox for iOS 9.0 on iOS 11 – AMO (Horizontal)](https://user-images.githubusercontent.com/3889017/30675033-63026750-9e7e-11e7-900a-abd0bfdbd4ca.png)

### Zoomed out:
![Firefox for iOS 9.0 on iOS 11 – AMO (Horizontal, zoomed out)](https://user-images.githubusercontent.com/3889017/30675034-6305aa64-9e7e-11e7-8518-e189ff8c2894.png)

**Comment by wagnerand** [comment]
I would recommend opening a new issue.

**Comment by muffinresearch** [comment]
This looks a lot better today. I don't think there's anything else to do.

**Comment by ioanarusiczki** [comment]
I verified this issue with iOS 11.2.5, Firefox for iOS 10.6 and with Safari too.
After making a Search and click on an ad-on from the search results the add-on detail page will display layout issues, the screen looks like it was zoomed in. The user must zoom out in order to obtain the overall view (Register and Log in button and text on the add-on detail page)

Firefox 
![image-1 1](https://user-images.githubusercontent.com/33448286/35908592-d7b46998-0bf9-11e8-888f-0753544ca770.jpg)

Safari
![image-1](https://user-images.githubusercontent.com/33448286/35908930-be54dc0c-0bfa-11e8-9a97-34027fc06329.jpg)
