### ISSUE TITLE
Error handling should allow multiple errors per handler

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3101]
The current error handling (`src/core/errorHandler.js`) does not allow multiple errors for the same handler. If we `dispatch` multiple actions for fetching data within the same component and at the same time, then the current design allows an action to "clear" an error that would have been raised by a previous action.

Using the error handler HOC multiple times would "fix" this but it would be tricky to render the errors correctly, so we should only have one handler and be able to deal with more than one error.

**Comment by kumar303** [comment]
Since this may be tricky to solve (and not high priority), we just need to make sure that no new actions are dispatched when an error exists. The pattern looks like this:

```js
const { errorHandler, dispatch } = this.props;
if (!errorHandler.hasError()) {
  // Now it is safe to dispatch actions.
  dispatch(fetchSomeData({ errorHandlerId: errorHandler.id }));
  dispatch(fetchOtherData({ errorHandlerId: errorHandler.id }));
} else {
  // Let the component render because that will display the error.
}
```

**Comment by kumar303** [comment]
We ran into another complication where using multiple error handlers would have helped: https://github.com/mozilla/addons-frontend/commit/9ecbef893a861ff122d7a9692b63357b0a725d62

**Comment by kumar303** [comment]
We ran into a problem when fixing https://github.com/mozilla/addons-frontend/issues/6447 where the error handler [passed to `fetchReview`](https://github.com/mozilla/addons-frontend/blob/73ea849c7e8b6dce0bbfa2f1789817dc0d972f0e/src/amo/components/FeaturedAddonReview/index.js#L67) does not get cleared when the same review [gets deleted](https://github.com/mozilla/addons-frontend/blob/73ea849c7e8b6dce0bbfa2f1789817dc0d972f0e/src/amo/components/AddonReviewCard/index.js#L112) later on.

IMO, this would be easier to solve by moving the errors into the review state directly so that it can be shared by multiple components. In other words, it would be harder to make a generic error handler that could account for this case.
