### ISSUE TITLE
List my collections and edit / delete / add

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3142]
Refs: https://github.com/mozilla/addons-frontend/issues/2782

No mocks for this one yet. 

This will be a page to view/edit/add your collections, sorted by last updated.

For comparison

<img width="1070" alt="collections_by_muffinresearch____add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30435705-55c96fc8-9962-11e7-8cc7-b3d47e7ea40c.png">

**Comment by muffinresearch** [comment]
We could use the UX + flow for the create/edit/delete too as well as the display of the initial set of collections.

**Comment by muffinresearch** [comment]
@pwalm this is likely to be something to get onto post-release do we have any UX for this yet.

**Comment by pwalm** [comment]
No mocks for this, but I'd treat it the same as the "About this extension" block.

**Comment by pwalm** [comment]
So... we're keeping collections now?

**Comment by jvillalobos** [comment]
Keeping but simplifying. [This doc](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit) has an overview.

**Comment by bobsilverberg** [comment]
@pwalm This is next on my list to tackle. I see this screen in Sketch:

![collections - 1366px copy](https://user-images.githubusercontent.com/142755/41159381-5a497a38-6afa-11e8-9f9b-fa7a2038b622.png)

but I'm not sure how accurate that is now. Did we want, for example, an "Edit" button or link for each collection, and/or possibly a "Delete" button or link? Should the description of the collection be displayed along with the title?

Please let me know if you'll have time to create a new/updated mockup for this sometime soon, or if you'd like to meet to discuss it in SF.

**Comment by pwalm** [comment]
Edit and delete occur in the collection, right? So we don't need to do it from this page.

**Comment by bobsilverberg** [comment]
> Edit and delete occur in the collection, right? So we don't need to do it from this page.

We don't *need to*, but I thought it might be a nice shortcut, edit anyway. That would save a click instead of requiring a user to click first on the collection, to display it, and then on the edit link from the collection details page.

**Comment by pwalm** [comment]
Nope, no extra work. Keep it as is. Thanks!

**Comment by bobsilverberg** [comment]
@pwalm What do we want to do about a user with a large number of collections? I know that we expect, in general, for a user to have a small number, so maybe we always want to display all user collections, or do we want to introduce paging for cases where there is a large number of collections?

**Comment by bobsilverberg** [comment]
@jvillalobos Users can no longer list collections for anyone other than themselves. Do we need to keep the ability for admins to list collections for any arbitrary user? I was planning on doing away with links like /firefox/collections/<username>/, and just have /firefox/collections/ be the link for "My collections".

**Comment by smayer97** [comment]
No Pagination for this please OR at least ability to choose with or without.

**Comment by jvillalobos** [comment]
I don't think we need to keep the feature for admins.

**Comment by pwalm** [comment]
@bobsilverberg No pagination.

**Comment by AlexandraMoga** [comment]
Verified on AMO dev with FF60, Win10x64 and Android 7.0

- when selecting View My Collection from the user menu, the new frontend version of My Collection page is displayed
- the collection list is consistent with the specs, displaying the collection name and the number of add-ons included in the collection
- follow-up issues logged: #5426, #5425, #5424, #5421 

[My collection list]
![image](https://user-images.githubusercontent.com/31961530/41976870-b9367fb0-7a26-11e8-8908-665f77cb7b2a.png)

[My Collections - no collection]
![image](https://user-images.githubusercontent.com/31961530/41976882-c16b5cc8-7a26-11e8-81cb-f3bdebc6d89c.png)

{My Collections - small screen]
![image](https://user-images.githubusercontent.com/31961530/41976892-c8b80ba2-7a26-11e8-8397-0ccee025656e.png)

[My Collection - logged out]
![image](https://user-images.githubusercontent.com/31961530/41976924-d6c3cf2e-7a26-11e8-91b5-20c9976cd5f0.png)


@bobsilverberg, I have some suggestions:
-  when the user logs out from My Collections, wouldn't be better to redirect to AMO homepage instead of the Logged out (mostly blank) page?
- since the new Collections page is very simplified and no additional information will be displayed for a listed collection, wouldn't be possible to reduce the space between the two rows? This could reduce the amount of 'white space' visible on this page.
