### ISSUE TITLE
Implement Account Settings page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3144]
Refs: https://github.com/mozilla/addons-frontend/issues/2781

See also https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit#heading=h.5cheild9uc3u

This page allows the user to customize their site settings:

 - [x] Edit Username
 - [x] E-mail address (read-only), message about Firefox Accounts, link to manage Firefox Accounts, support link
 - [x] Edit metadata: display name, homepage, location, occupation
 - [ ] Upload photo, delete photo
 - [x] Edit more details: including HTML help for more details
 - [ ] Notification settings, this includes some options which are developer only.
 - [ ] ~~Reason for change, Notes, Anonymize, Delete Account (Admin-only)~~
 - [x] Update Account button

I think any admin specific functionality needs moving to the admin. This will need bugs filing on addons-server.

 Current site this looks like this:

<img width="1008" alt="account_settings____add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30439358-6c529a9a-996b-11e7-9ab5-6dbd961fba73.png">

**Comment by muffinresearch** [comment]
@jvillalobos Nominating this for post-release since the account settings are a fairly large item. With the proviso that we'll put this at the top of the post release features. Is that ok with you?

**Comment by jvillalobos** [comment]
As long as we keep the old pages, it's okay, since they are needed for the account creation process.

**Comment by muffinresearch** [comment]
Ok great, removed.

**Comment by eviljeff** [comment]
Couldn't see an implementation issue yet, so adding this to here:

The message about Firefox Accounts and changing email addresses should say instead that they can change their email address via Firefox Accounts.  https://support.mozilla.org/en-US/kb/change-primary-email-address-firefox-accounts seems like the relevant article about it.

mozilla/addons-server#4925 was logged about this on addons-server - and I'll keep that open until mozilla/addons-server#6451 is fully complete - but the messaging needs to update in the UI also.

**Comment by willdurand** [comment]
@wagnerand do we want admins (or any other user with a specific right like `Users:Edit`) to be able to edit someone else's profile in the frontend? Or can we move this to the admin tool? It seems the API would allow to implement that in the frontend but I don't know whether it is a good idea or even if it is still wanted. (also cc @jvillalobos)

**Comment by eviljeff** [comment]
The API was written with thought that any user with the appropriate permission could edit account profiles via the API. 

There aren't really any admin tools, beyond django admin (which is last case scenario, because it's liable to break something.  And doesn't support things like photo uploading at all)

**Comment by tofumatt** [comment]
It’s probably easier/better going forward if as many admin actions as possible are done via the frontend, as it can be well-tested and share code paths with existing code. I don’t think we’ve given much thought to admin functionality on the frontend, but in general it’s easier to add admin code paths like this instead of building a whole new “admin user edit” tool and testing it as well.

If the admin tools are part of the regular site it's probably easier to maintain them, even if just incidentally :-)

**Comment by willdurand** [comment]
I think we could split admin features in two categories: those used everyday and the others. I understand that being able to edit/disable an addon is very often used, but do admins often edit user profiles on behalf of the users?

>  I don’t think we’ve given much thought to admin functionality on the frontend

That's why I raise this point here, maybe we would like to do things differently :-) I ask because I could not find any information.

**Comment by eviljeff** [comment]
Additional admin-only tools, or extra admin functionality on existing tools, might be worth considering too. 
But in this case it's just allowing admins (admin-like-users) to use the user form.  We shouldn't side-track the issue.

**Comment by tofumatt** [comment]
I’ve heard arguments from devs that moving admin functionality into its own piece just means maintaining two components/pages/etc., one of which (the admin one) being internal and easy to neglect. If you look at the existing admin tools on addons-server this is sort of the case. We don’t test them as often as we should and they have a lot of rough edges.

And in the case of the frontend it’s probably another component that would need to be created that would share a lot of the same paths and require its own tests.

Editing a user’s profile content itself might not happen much but this could be the page that allowed admins to edit flags on a user profile. But @jvillalobos probably knows best here :-)

**Comment by tofumatt** [comment]
Yeah all that said a first pass that makes this current-user-only probably works...

**Comment by jvillalobos** [comment]
It's very rare that an admin needs to edit user profile info. It doesn't make much sense to do that for spammers or malicious developers, since they can edit the account back to its previous state. The one admin-only action we want implemented is the ability to ban accounts, but that's something that would be part of a [separate admin tool](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.b7y5z7x7pzhe).

It's true that keeping admin tools separate means duplicated work and neglected admin tools. On the other hand, mixing admin tools into the site like we do on the legacy one means that user-facing and developer-facing pages have the potential for privilege escalation bugs, which is probably a bigger problem.

All that said, it sounds like the API supports admins doing the same editing the users can, so I think it's good to support that in the front-end as well.

**Comment by ioanarusiczki** [comment]
@willdurand @muffinresearch 

I think this can be marked verified fixed but please let me know if I must file new issues for these: 
- we have an inconsistency in naming the new form , on AMO in the drop down menu it's Edit my profile, issue https://github.com/mozilla/addons-frontend/issues/2749 mentions Accounts settings at one point such as the name of this issue. The form has an Edit my profile title as displayed below
![account settings](https://user-images.githubusercontent.com/33448286/40119632-dc078bdc-5925-11e8-9957-5b3663ae4762.png)
- as an admin I cannot edit someone else's user profile info using the front end (no link to indicate that when I'm viewing someone else's profile).
- the biography section had a title for it's section on the View profile page - In a little more detail... 
Maybe this is no longer wanted on the new page but I can't decide that by myself.
- because Edit profile and the View profile pages are connected I checked and filed 
https://github.com/mozilla/addons-frontend/issues/5019
https://github.com/mozilla/addons-frontend/issues/5020
https://github.com/mozilla/addons-frontend/issues/5021

**Comment by willdurand** [comment]
> as an admin I cannot edit someone else's user profile info using the front end (no link to indicate that when I'm viewing someone else's profile).

This will be addressed in #4997.

> the biography section had a title for it's section on the View profile page - In a little more detail...
> Maybe this is no longer wanted on the new page but I can't decide that by myself.

I don't think we want this anymore.

> we have an inconsistency in naming the new form , on AMO in the drop down menu it's Edit my profile, issue #2749 mentions Accounts settings at one point such as the name of this issue. The form has an Edit my profile title as displayed below

I think it makes sense to have the same name in the drop down menu and on this left panel. We can still change that later, but that should be consistent.

**Comment by muffinresearch** [comment]
There's a strong reason we have separated out the admin under different domains. Allowing admin like functionality via the API increases the chances of exposing sensitive operations or sensitive data such as this. I'd like to ensure we protect those things appropriately and review it on a case by case basis. 

If we're exposing admin functionality this way we should weigh the risk of the approach being taken and involve the security team in those discussions as needed. 

> It's very rare that an admin needs to edit user profile info. It doesn't make much sense to do that for spammers or malicious developers, since they can edit the account back to its previous state. The one admin-only action we want implemented is the ability to ban accounts, but that's something that would be part of a separate admin tool.

@jvillalobos Should we just remove profile editing from the API then? It seems weird to even expose this if we don't need to use it that often. As soon as some sensitive operations are in the admin that supports the use case for a working admin. 

/cc @eviljeff @willdurand

**Comment by jvillalobos** [comment]
Isn't it needed for users to edit their own accounts? I thought it'd be okay to give admin that access because users needed it anyway. If there's a distinction I'm missing, I'm okay with not giving admins any extra access here.
