### ISSUE TITLE
Search header doesn't mention type

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3154]
Currently our search header says: `9 results for "foo"` but the mocks and scope doc suggest it should be `9 extension results for "foo"`.

Current site:

<img width="679" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30452431-909f6ffa-998d-11e7-9ddc-f8f0f7f2d458.png">

Mocks:

<img width="393" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30452442-975ebfee-998d-11e7-9783-99d1ce7bfaa2.png">

**Comment by PunitGr** [comment]
Hi @muffinresearch, I have fixed this `bug`. And it is passing all the `test cases` as well.

![screen shot 2017-09-15 at 8 38 56 pm](https://user-images.githubusercontent.com/9111111/30489860-0a8f2184-9a56-11e7-82dc-3d0471d6c44b.png)

I have one query, why does it say `persona` in the search header when the `addonType` is `theme`.

![screen shot 2017-09-15 at 8 41 21 pm](https://user-images.githubusercontent.com/9111111/30490202-ead0976e-9a56-11e7-8a1c-8aca50e816db.png)


And should I change it to `Themes` for when `addonType` is `persona`? Since I could the mocks.
Thanks.

**Comment by tofumatt** [comment]
Yes, it should say "theme" not "persona".

Realistically `500 extension results for "foo"` is a bit awkward phrasing anyway. While you're changing it I'd suggest: `500 extensions found for "foo"`, `500 themes found for "foo"`, etc.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7, Android 7.2.1).
Postfix screenshots:
![ext](https://user-images.githubusercontent.com/15685960/30637291-973f3008-9e00-11e7-9a1c-6b389e8e73fa.png)
![themes](https://user-images.githubusercontent.com/15685960/30637298-9a66bcc4-9e00-11e7-8062-3e92dcacc9e5.png)

**Comment by ValentinaPC** [comment]
@kumar303 : should we display type in header for empty searches also? Thanks!
