### ISSUE TITLE
"Log in to rate ..." banner should be displayed in regular case

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3322]
Steps to reproduce:

1. Go to an extension/theme details page on AMO-dev (i.e.https://addons-dev.allizom.org/en-GB/firefox/addon/anonymox/)
2. Notice the text format for the "Log in to rate ..." blue banner

Expected result:
The "Log in to rate ..." banner is displayed in regular case

Actual result:
The "Log in to rate ..." banner is displayed in upper-case

![image](https://user-images.githubusercontent.com/31961530/31121135-afcbea8c-a83f-11e7-93b6-cd9d1578cb3d.png)

Note: observed on AMO-dev FF56 (Win10 and Android 7.0)
#3190

**Comment by kumar303** [comment]
Why did this bug get filed and fixed? The UI mock shows it in upper case:

<img width="398" alt="screenshot 2017-10-03 14 44 30" src="https://user-images.githubusercontent.com/55398/31145500-80217a0e-a849-11e7-9b1a-32283708ef80.png">

**Comment by tofumatt** [comment]
Because all-uppercase text is extremely inaccessible (for instance: http://uxmovement.com/content/all-caps-hard-for-users-to-read/ <http://uxmovement.com/content/all-caps-hard-for-users-to-read/>). I’ve talked to UX in the past about nixing uppercase text because it creates problems and they agreed to it, but these slipped through the mockups.

I’ve mentioned it in previous issues and in discussions with UX, sorry for leaving sourcing out of that issue.

All-caps are especially difficult for dyslexic users as it makes it extra-hard to differentiate between letters or use custom fonts well. On an add-ons site that users could be going to for accessibility tools I think this matters a lot :-)

**Comment by kumar303** [comment]
ok, thanks for the rationale

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO dev and stage - FF56 (Win10 and Android 7.0)

Postfix screenshot:
![image](https://user-images.githubusercontent.com/31961530/31165051-2dfef892-a8f2-11e7-8e02-1c94381e6c46.png)
