### ISSUE TITLE
"Last updated" section inside a collection changes to another language at page refresh

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3443]
Steps to reproduce:
1. Load a collection details page i.e. https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/change-up-your-tabs/
2. Refresh the page while looking at the "Last updated" section

Expected results:
There are no display or layout issues.

Actual results:
Date changes to other language for a second.

Notes/Issues:
- in stage is happening also, but different.
Verified on AMO-dev FF56(Win 7).
Video for this issue:
![coll](https://user-images.githubusercontent.com/15685960/31450186-76b4d48e-aeb1-11e7-8109-3d4e65f1cd61.gif)

**Comment by willdurand** [comment]
Cannot reproduce it locally, but it affects -dev and -stage.

**Comment by willdurand** [comment]
I think the problem comes from this part: https://github.com/mozilla/addons-frontend/blob/ea70de86fc2543a37001f5c568495598186deb3a/src/core/i18n/utils.js#L277-L280

Not all locales have this `_momentDefineLocale` function in their options, and we only set the current locale on `moment` when this option is there. I would go for moving the following line out of the block:

```
moment.locale(makeMomentLocale(i18n.lang));
```

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix screencast:
![date](https://user-images.githubusercontent.com/15685960/31721128-319a12e0-b421-11e7-933c-b2a19ff23b5f.gif)
