### ISSUE TITLE
Remove the outdated category content from the homepage

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3456]
Now have more shelves in play we can remove the outdated category content from the homepage:

<img width="1484" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31491473-591d17e0-af3f-11e7-9d6d-c7fa27d08f09.png">

**Comment by willdurand** [comment]
Thanks for opening the issue, I wanted to do it after having added all the shelves :)

**Comment by AlexandraMoga** [comment]
Verified as fixed in AMO-dev with FF56 (Win10 and Android 7.0)

The old category content is no longer visible on AMO homepage:
![image](https://user-images.githubusercontent.com/31961530/31544625-5c9ce374-b024-11e7-82ed-fae6659da906.png)

![image](https://user-images.githubusercontent.com/31961530/31544695-c34d7c96-b024-11e7-9f3d-c7a638b24b28.png)
