### ISSUE TITLE
Change install switch to install button on AMO

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3557]
According to our user research the install switch performs very poorly so we should disable it and use the fallback `InstallButton` everywhere on AMO for now. In the future we'll want to improve the button, but switching to it for MVP.

**Comment by tofumatt** [comment]
To be clear to QA/others:

* this will prevent the ability to uninstall an add-on from the page
* this will not show if an add-on is installed
* this will allow clicking on the "Add to Firefox" button on an add-on already installed

These issues will be addressed in the future.

**Comment by pwalm** [comment]
Examples:
![screen shot 2017-10-18 at 12 52 51 pm](https://user-images.githubusercontent.com/6797635/31739608-53b0b29e-b403-11e7-9283-8bee2bf4a12e.png)

![screen shot 2017-10-18 at 12 53 01 pm](https://user-images.githubusercontent.com/6797635/31739612-57dd255a-b403-11e7-8cad-0baa89a79229.png)

![screen shot 2017-10-18 at 12 53 11 pm](https://user-images.githubusercontent.com/6797635/31739626-5c0d2c06-b403-11e7-948b-b1d1974761e6.png)

**Comment by vcarciu** [comment]
After talk with tofumatt on IRC, I will mark this as verified since the install switch is not present anymore. The rest of things described in the attached screenshots will be implemented later in another issues : 
![installbut](https://user-images.githubusercontent.com/1583842/31763818-1bbe5cb8-b4c8-11e7-89c2-524ad0b33afa.gif)

**Comment by pwalm** [comment]
Mocks for the buttons:
<img width="1188" alt="screen shot 2017-10-20 at 3 54 25 pm" src="https://user-images.githubusercontent.com/6797635/31844663-fc66b832-b5ae-11e7-9793-aa71b2499685.png">

Can we get these implemented asap? I will provide proper specs.

**Comment by grahamperrin** [comment]
> … the green button might change to blue.

If it will remain green, then black text might be better. (The white on green of e.g. a 'Comment' button in GitHub is OK, partly because the text is heavier and the green is darker. The green in the mock-up is relatively pale.)

FWIW I do prefer a green, to a blue, for addition. 

In the fourth column of the mock-up: the white on pale grey is probably not good for accessibility.

**Comment by kumar303** [comment]
@pwalm could you file a separate issue for https://github.com/mozilla/addons-frontend/issues/3557#issuecomment-338340569 ?

**Comment by pwalm** [comment]
@kumar303 Yep, absolutely (with greater detail)
