### ISSUE TITLE
Text in search field is not aligned properly

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3592]
Copy in search field needs to be aligned to the centre of the text field (bumped down a few pixels).

<img width="348" alt="screen shot 2017-10-20 at 2 45 31 pm" src="https://user-images.githubusercontent.com/6797635/31842991-a1df8c30-b5a5-11e7-86b5-66e9e94cb301.png">

**Comment by muffinresearch** [comment]
@pwalm I think this is probably close to being centered already but there's a bit of an optical illusion due to the upper-case `F` and the `d` in add-ons. With a search term that features a `q` or a `p` it looks centered without making any changes:

<img width="338" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31894400-402feddc-b806-11e7-901b-1fee95f9236a.png">

Correcting the placeholder would mean that search looks slightly low if it features a `p` or `q` etc.

E.g - adding 2px:

<img width="345" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31894494-88ad4e60-b806-11e7-8a2a-1fcf846db913.png">

<img width="355" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31894474-78a9d6f0-b806-11e7-93ed-d676bb8dbfc1.png">

**Comment by pwalm** [comment]
Ok! Thanks for clarifying that 👍
