### ISSUE TITLE
Category buttons do not use proper palette

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3594]
The category buttons on the top level Extensions and Themes pages do not use the full palette provided.

Current:
<img width="1039" alt="screen shot 2017-10-20 at 3 09 08 pm" src="https://user-images.githubusercontent.com/6797635/31843604-d692264c-b5a8-11e7-9aea-7aa6ff25ea7b.png">
<img width="1039" alt="screen shot 2017-10-20 at 3 10 31 pm" src="https://user-images.githubusercontent.com/6797635/31843610-ea1d0646-b5a8-11e7-9540-5dc9d5abd5b8.png">

Mocks:
<img width="961" alt="screen shot 2017-10-20 at 3 09 18 pm" src="https://user-images.githubusercontent.com/6797635/31843619-f1ebbbd8-b5a8-11e7-8b40-0d067889cd6a.png">
<img width="956" alt="screen shot 2017-10-20 at 3 11 36 pm" src="https://user-images.githubusercontent.com/6797635/31843628-fe1963d8-b5a8-11e7-8743-4bb5cde34fc3.png">

Palette:
<img width="1343" alt="screen shot 2017-10-20 at 3 12 23 pm" src="https://user-images.githubusercontent.com/6797635/31843653-215a8b1a-b5a9-11e7-9f2a-95e9abdc45be.png">
<img width="1340" alt="screen shot 2017-10-20 at 3 12 33 pm" src="https://user-images.githubusercontent.com/6797635/31843655-2440d726-b5a9-11e7-9107-ba9f926c792e.png">

**Comment by muffinresearch** [comment]
@pwalm currently marking this for fix-up post-release.

**Comment by jvillalobos** [comment]
@willdurand can you look into what is needed to address this issue? Is there a direct mapping from categories to colors, or are they assigned in some other way?

**Comment by willdurand** [comment]
> @willdurand can you look into what is needed to address this issue? Is there a direct mapping from categories to colors, or are they assigned in some other way?

@jvillalobos We have a list of 12 colors that we can update with Photon colors and that would solve the issue. This seems uncomplicated, so probably a good first bug.

**Comment by jvillalobos** [comment]
How are they assigned? Stuart pointed out how themes only get green colors, which is odd.

**Comment by rahulsyal2512** [comment]
is this issue still open ? i can work with this one

**Comment by willdurand** [comment]
> How are they assigned? Stuart pointed out how themes only get green colors, which is odd.

We use a simple function for that: https://github.com/mozilla/addons-frontend/blob/e4668770d1329012480c853749fda32e424ab0ab/src/core/utils/index.js#L247

This likely does not work for some categories because it uses the category ID to determine the color.

**Comment by jvillalobos** [comment]
I suggest we do two things:

1) Expand `$category-colors` to include all colors in the palette provided above.
2) Use a modulo operation in the category ID to decide which color should be assigned. Categories tend to have sequential numbering, so that should provide some variability in the colors. I bet the theme category IDs are entering the `if (category.id > maxColors) {` condition and then the division puts them all pretty much in the same place.

Still a good first bug, in my opinion. Thoughts?

**Comment by willdurand** [comment]
> Still a good first bug, in my opinion. Thoughts?

I agree.

**Comment by jvillalobos** [comment]
Mentor: @kumar303 

@rahulsyal2512 yes, you can take it.

**Comment by sashaktpathak** [comment]
If anybody has not taken up this issue, can i work with this one?
Also,  Where is this function used further.

https://github.com/mozilla/addons-frontend/blob/e4668770d1329012480c853749fda32e424ab0ab/src/core/utils/index.js#L247

**Comment by rahulsyal2512** [comment]
i have added all the colors given in the pallete above.
please tell if there is anything to do with modulo operation?

**Comment by kumar303** [comment]
@rahulsyal2512 great, thanks. Did you create a pull request? I can take a look once you create a pull request.

**Comment by rahulsyal2512** [comment]
@kumar303 yes i did

**Comment by kumar303** [comment]
@rahulsyal2512 great, can you send me a link to the pull request? I'll take a look.

**Comment by rahulsyal2512** [comment]
@kumar303 here it is - https://github.com/mozilla/addons-frontend/pull/8139

**Comment by kumar303** [comment]
@rahulsyal2512 your pull request description is missing some important info that was there when you created it ([see the template here](https://github.com/mozilla/addons-frontend/blob/master/PULL_REQUEST_TEMPLATE.md)). Can you add that back? Most importantly, it needs `Fixes #3594` at the top.

**Comment by rahulsyal2512** [comment]
@kumar303 please check if this is fine now? https://github.com/mozilla/addons-frontend/pull/8146

**Comment by kumar303** [comment]
@rahulsyal2512 you still need to edit the description of the PR so that it says `Fixes #3594` (it's the second checkbox item). This is important because it will automatically close the issue when the PR gets merged.

**Comment by kumar303** [comment]
@rahulsyal2512 sorry, I realize that the PR template is a bit confusing here. See the last sentence of the template:

"Once you have met the above requirements please replace this section with a Fixes #ISSUENUM linking to the issue fixed by this PR along with an explanation of the changes. Thanks for your contribution!"

**Comment by rahulsyal2512** [comment]
@kumar303 done

**Comment by rahulsyal2512** [comment]
i hope that will work now

**Comment by rahulsyal2512** [comment]
@kumar303 please merge my PR if there is no issue: - https://github.com/mozilla/addons-frontend/pull/8146

**Comment by kumar303** [comment]
@rahulsyal2512 thanks for all your work on this issue but, unfortunately, the issue was pretty far out of date. The mocks and guidance in the description are no longer valid. I made a new issue for what we need to do but that one is not a good first bug as it's no longer such a straight forward fix. 

Moved to https://github.com/mozilla/addons-frontend/issues/8180
