### ISSUE TITLE
Static theme details page return a 500 error page if logged out

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3601]
Steps to reproduce:
1. Submit a static theme i.e. https://addons-dev.allizom.org/en-US/firefox/addon/static-theme-ex2/
2. Being logged out load its details page using the new frontend pages 

Expected results:
Theme details page is loaded.

Actual results:
A 500 error page is loaded.

Notes/Issues:
- being logged in does not reproduce the issue, even if you are not the author of the theme
- using old desktop pages doesn't reproduce the issue, also

Verified on AMO-dev Ff56(Win 7).
Video for this issue:
![static theme](https://user-images.githubusercontent.com/15685960/31897515-48dda85c-b81f-11e7-8e5c-f101679cb4aa.gif)

**Comment by muffinresearch** [comment]
This is presumably related to the fact that static themes haven't been implemented yet as a type in the new frontend.

**Comment by ValentinaPC** [comment]
...not implemented only for log out state?

**Comment by muffinresearch** [comment]
Here's the sentry log: https://sentry.prod.mozaws.net/operations/addons-frontend-amo-dev/issues/677809/

Error: Unknown extension type: statictheme

**Comment by muffinresearch** [comment]
This would explain why the error only happens when logged-out.

**Comment by muffinresearch** [comment]
This should be resolved when static themes are implemented in the front-end (https://github.com/mozilla/addons-frontend/issues/3388) but we should also consider if throwing is the right approach for an unknown type - especially as this shows it might inconistent.

**Comment by muffinresearch** [comment]
@eviljeff presumably adding static themes is currently limited to -dev?

**Comment by eviljeff** [comment]
Yeah, the submission waffle should be only enabled for -dev.  Tbh I'm surprised it works at all on addons-frontend given #3388 isn't implemented - I wasn't expecting it to.  

Btw, the minimally working detail page on legacy frontend is largely there only to verify the submission, etc, worked.  Because static themes won't be launched until well after addons-frontend is the default, viewing and installing via the legacy detail page isn't a supported use case.  It'd be nice if you could at least install, but that will be about it.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10)
![logout for approved static themes](https://user-images.githubusercontent.com/33448286/41238474-af732f3a-6d9e-11e8-96b0-5a6bbe5226b4.gif)
