### ISSUE TITLE
Link to review guidelines from the review dialog

### ISSUE THREAD

**Issue by dessant** [mozilla/addons-frontend#3627]
The legacy frontend has some useful tips for users which probably prevent at least a couple of invalid reviews. These tips are missing from the new frontend, there should be a prominent [link](https://addons.mozilla.org/en-US/review_guide) with a short paragraph if the new design does not allow a large block of text.

Legacy site:
![screenshot from 2017-10-25 06-41-04](https://user-images.githubusercontent.com/7513068/31979940-07bcce28-b952-11e7-8324-d8dbadd4babf.png)

New site:
![screenshot from 2017-10-25 06-42-12](https://user-images.githubusercontent.com/7513068/31979945-0fe963e0-b952-11e7-8b5a-cdd11f0b36d8.png)

**Comment by kumar303** [comment]
That's a good idea, thanks. We also had a UX mock-up with tips in it but I forgot that we had copy already. We probably just need to make the existing tips a little more concise so they are easy to scan at a glance.

**Comment by kumar303** [comment]
Thanks again for filing this. Showing the review guidelines somehow slipped through the cracks.

A fix has landed (on our dev server only) that makes the review entry form look like this:

<img width="320" alt="screenshot 2017-10-25 17 37 18" src="https://user-images.githubusercontent.com/55398/32064650-0cc2201e-ba40-11e7-82a9-2527230c554a.png">
<img width="321" alt="screenshot 2017-10-25 17 37 30" src="https://user-images.githubusercontent.com/55398/32064658-13376882-ba40-11e7-89ac-9a51910dcbb4.png">

I did not add any explicit tips to that form since that will need a bit more UX thought. The guidelines page does have them though. You can see it here if you click on 'view mobile site' : https://addons.mozilla.org/en-US/review_guide

**Comment by dessant** [comment]
I like the outcome, thanks for the quick turnaround! ❤️

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
Postfix video:
![rev g](https://user-images.githubusercontent.com/15685960/32092529-a9f574d2-bb01-11e7-969b-a00e9cd6df6e.gif)
