### ISSUE TITLE
Add browser logging

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#369]
It would be nice to have some browser API for logging. Ideally the same module could be used universally.

If we want to go the bunyan route to get that to work we'll need to add some webpack conf to deal with fs e.g:

```
 node: {
  fs: 'empty'
}
```
See https://webpack.github.io/docs/configuration.html#node

**Comment by muffinresearch** [comment]
I spent quite a bit of time looking at this and there's a number of problems here:

* Currently there's no great way to wrap console.log in firefox without losing the references to the lines involved. I'd previously solved this problem on ffos by using bind but that appears to no longer work.
* Using bunyan will inevitably add code that we don't need on the client.

I'm thinking that just relying on uglify to strip console.log statements in production + stage is a better way to go - but if we do that we'll not see any *view* logging from in the universal code in the server logs - would that be a problem?

If we want a universal solution then we should ignore the platform issue re: line numbers and just do universal logging in which case I've got most of a branch sorted.

**Comment by muffinresearch** [comment]
One interesting thing is that console.error does provide the line (presumably because it implicitly gets a stack trace).

**Comment by mstriemer** [comment]
We discussed this on vidyo. I think we decided to go with plain bunyan since line numbers won't be too useful in minified code. Likely turn off logging through the config and then provide some mechanism for a user to turn it back on. Using a settings page or setting something in `localStorage`. Maybe provide some way to easily export the log but don't spam things by default.
