### ISSUE TITLE
Add-on description is "too" wrapped

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3708]
Steps to reproduce:
1. Load details page for an add-on that has a long description i.e. https://addons-dev.allizom.org/en-US/firefox/addon/tabletools2/
2. Observe text from description section

Expected results:
Text is wrapped to fit the section.

Actual results:
Text is wrapped, but  a white space remains in the right side of the section.

Notes/Issues:
- looks more weird for an add-on without any screenshots
Verified on AMO-dev FF56(Win 7).
Screenshot for this issue:
![wrap](https://user-images.githubusercontent.com/15685960/32212992-13c2e908-be22-11e7-91fd-7bfcb202800a.png)

**Comment by tofumatt** [comment]
This is intentional because stretching the text out any wider makes it much harder to read; text should be a certain length before being wrapped  or it’s harder for users to maintain their place and get to the next line.

Unfortunately it does look a bit odd, but I think it’s better to be accessible in this instance.

- Matt (Sent from mobile)
