### ISSUE TITLE
SeaMonkey view of abbreviated addons.mozilla.org/addon/rescroll/ redirects to the extension for Android

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3726]
From IRC this morning: 

> A minor observation: https://addons.mozilla.org/addon/rescroll/ viewed with SeaMonkey redirects to the Android page for the extension with the green badge 'Compatible with Firefox 57+'. 
> 
> Would it be better for such cases to redirect to https://addons.mozilla.org/en-GB/firefox/addon/rescroll/ with the 'Only with Firefox — Get Firefox Now!' green badge?

https://useragent.openadmintools.com/ reports: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:52.0) Gecko/20100101 Firefox/52.0 SeaMonkey/2.49.1 Lightning/5.3`

`general.useragent.compatMode.firefox` is `true` (the default).

**Comment by kumar303** [comment]
> https://addons.mozilla.org/addon/rescroll/ viewed with SeaMonkey redirects to the Android page

I'm not sure what's going on right there. I guess it's redirecting to `android` because that's the only app supported by the add-on? Requesting a `seamonkey` add-on should work, like `https://addons.mozilla.org/addon/flip-or-rotate-image/`

As an aside, we need to redirect to `/seamonkey/` URLs. I will do this in https://github.com/mozilla/addons-frontend/issues/3728

**Comment by muffinresearch** [comment]
This should be fixed by https://github.com/mozilla/addons-frontend/issues/3719 which is already live on -dev (https://addons-dev.allizom.org) if you'd like to try it there.
