### ISSUE TITLE
Revisit loading script with async/defer attribute

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3733]
Whilst having the script at the bottom of the page means we're not blocking the DOM, there's some suggestions that using the async attribute will help the browser with preloading. 

There's a good overview here: https://www.igvita.com/2014/05/20/script-injected-async-scripts-considered-harmful/

http://caniuse.com/#feat=script-async shows that support is good. 

One big consideration here is that with `async` script execution order isn't guaranteed. So before we get into this we might want to consider what we could be doing with bundle splitting. E.g. if we break vendor code out into a separate bundle we'll need that to load before the rest of the code, if that's the case then async may not be appropriate.

We should measure the difference this change makes.

## Update

See below for Kumar's link to an article that suggest that using the defer attribute is preferred over using async.

Support is similarly good http://caniuse.com/#feat=script-defer

**Comment by tofumatt** [comment]
> if we break vendor code out into a separate bundle

I gather the main win in doing this is if our code updates but our dependencies stay the same, we only load our new code. That sounds good but unless we split out *each* dependency (loading a bunch of script tags at once with HTTP2 or whatever), there isn't a big win as our vendor file will almost certainly change every week with a single Greenkeeper dependency update (our production code tends to only change once a week with the tag, so that's what most users see).

If we were doing continuous deployment this could work well... but otherwise I don't think splitting out our vendor files from our own code will yield any benefits.

**Comment by muffinresearch** [comment]
@tofumatt yep I alluded to exactly the same concern in the bundle splitting issue which is probably the best place to discuss the vendor bundle aspect of this.

**Comment by kumar303** [comment]
Apparently `async` is still blocking whereas `defer` is not https://calendar.perfplanet.com/2016/prefer-defer-over-async/

**Comment by muffinresearch** [comment]
@kumar303 nice find, this different is interesting too:

> ASYNC scripts may load out-of-order, whereas DEFER scripts are executed in the order in which they appear in markup. (Although there’s a bug that makes DEFER’s execution order questionable in IE<=9.)
