### ISSUE TITLE
If an addon is not compatible with both platform and FF version, show the platform incompatibility first

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3739]
Steps to reproduce:
1.Using Windows and  FF Nightly , open https://addons-dev.allizom.org/en-US/firefox/addon/youtube-high-definition/
2.Observe the incompatibility banner ("This add-on is not compatible with your version of Firefox.")

Expected results:
Since the add-on is not compatible with Windows, we should show the platform incompatibility message first (or at least both platform and FF incompatibility messages) because the user will think that a Firefox version change will suffice in order to install that add-on, which is not true

Actual results:
The FF incompatibility banner is displayed 

NOTES:
In old AMO , both banners are displayed

Please see video for this bug: 
![banners](https://user-images.githubusercontent.com/1583842/32287984-2b785974-bf3b-11e7-9858-70e4407e5580.gif)

**Comment by tofumatt** [comment]
A note as well: we know which OSes the add-on *is* compatible with, so instead of showing a "This add-on is not available for your platform" we should be explicit about the ones it does support. I think a message like "This add-on is only available for MacOS" would be much more useful–it would also help us catch bugs if the supported platform is getting the error.

**Comment by kumar303** [comment]
> a message like "This add-on is only available for MacOS" would be much more useful

I agree but this might be hard to implement--the *platform* values in `addon.installURLs` are not reliable. There are just too many quirks with how the DevHub decides to make it "all platforms" or one of each. Also, the concept of "Android" is complicated because it's both a client app and a platform (sometimes). I would suggest filing it as a separate issue so we don't lose track of it.

**Comment by willdurand** [comment]
I don't think we can do anything here so I am going to close this issue.
