### ISSUE TITLE
Deleted lightweight thems show in the main gallery listings.

### ISSUE THREAD

**Issue by twisfowt** [mozilla/addons-frontend#3778]
### Describe the problem and steps to reproduce it:

When listing only themes created by me in the gallery,
themes which have been deleted show up but when
clicked on say (correctly) "Page Not Found".

### What happened?
See above.

### What did you expect to happen?
Deleted themes should not show up in the gallery.

### Anything else we should know?

https://addons.mozilla.org/en-US/firefox/search/?page=7&q=twisfowt

This in only the last item in the list, but all are the same.

**Comment by jvillalobos** [comment]
Calling this a P2, since it could potentially expose inappropriate admin-deleted themes.

**Comment by tofumatt** [comment]
I'm not quite clear on what's happening here but it seems to be that:

1. there are four items in the search results
2. the last item ("**TheForestPrimeval(V2)**") was deleted but appears in the search results
3. clicking on the last item shows an error page because the add-on is not available

So basically deleted themes are showing up in the search results. This seems like an API error/issue (maybe deleted themes aren't being removed from ElasticSearch or something?).

cc @diox because my guess is this isn't a frontend issue.

**Comment by willdurand** [comment]
That's because of https://github.com/mozilla/addons-server/issues/5999, again (@diox said that on IRC).

**Comment by caitmuenster** [comment]
Pam & Candelora (our featured themes curators) are also reporting this issue.

**Comment by muffinresearch** [comment]
Duplicate of https://github.com/mozilla/addons-server/issues/5999
