### ISSUE TITLE
Please don't cut the add-on logo in the review view

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/addons-frontend#3786]
Logos are part of the branding of a product and should be displayed properly. That's not the case in the reviews view. Please remove the following CSS rule:

border-radius: 9px;

<img width="418" alt="bildschirmfoto 2017-11-05 um 07 28 29" src="https://user-images.githubusercontent.com/1100614/32412537-f205e1f8-c1fa-11e7-9770-8e9543e4baf5.png">

**Comment by tofumatt** [comment]
This is intended as part of the new design but if it’s worth keeping (I like it) we should probably communicate the developers their icon should look good with rounded corners. What do you think, @pwalm?

**Comment by cadeyrn** [comment]
I am not happy with this but in case you keep the rounded corners the rounded corners should also be added to all other places. Because at the moment the logo looks different on different places and that's the worst case.

**Comment by muffinresearch** [comment]
@tofumatt I think we shouldn't be doing this because id we are breaking peoples logos. I don't think there's a good workaround either. We can't guess the background colours used so it's not like we can pad the icon. 

Until we can communicate around something different and show the different display of the icons at upload it would make sense to revert the border radius.

**Comment by muffinresearch** [comment]
I've raised a new issue to discuss the radiusing with UX and have a PR to revert this for now. 

The new issue is here: https://github.com/mozilla/addons-frontend/issues/3793

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev  FF56 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/32442610-b263908a-c304-11e7-8008-7a066e5fe09d.png)
