### ISSUE TITLE
Redirect atype parameters to the new type parameter

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3791]
via https://www.reddit.com/r/firefox/comments/7aza66/no_search_engines_section_on_mozillas_restyled/

From Firefox in about:preferences#search there's a search tools link https://addons.mozilla.org/en-US/firefox/search/?atype=4

<img width="903" alt="preferences" src="https://user-images.githubusercontent.com/1514/32435463-e1b53e00-c2d8-11e7-92fa-da1e998ab03b.png">

This shows no results via the new frontend. That link should now be https://addons.mozilla.org/en-US/firefox/search/?type=search

We need to redirect from the former to the latter.

**Comment by muffinresearch** [comment]
Looking at this further I think we need to map redirects for all the atype parameters otherwise we're going to be breaking a lot of historical links.

**Comment by muffinresearch** [comment]
`atype=1` ->  `type=extension`
`atype=3` -> `type=dictionary`
`atype=4` ->  `type=search`
`atype=5` -> Unknown - this should be language packs.

**Comment by willdurand** [comment]
@muffinresearch no `atype` for themes?

**Comment by muffinresearch** [comment]
@willdurand there isn't there's complete themes but we don't want to migrate them. Personas use a weird category hack which seems to work going from the old site to the new.

**Comment by diox** [comment]
FWIW, there were actually 2 weird category hacks on the old frontend:

- While in the `Themes` page, doing a search for `test` would result in calling `/en-US/firefox/search/?q=test&cat=themes`. While in a category page insides `Themes`, the same thing would happen (the category would be "lost"). That's what @muffinresearch is describing in the comment above this one.

- While in a category page for extensions or complete themes, doing a search for `test` would result in calling `/en-US/firefox/search/?q=test&cat=1%2C0`. The `cat` parameter in that case is a combination of the add-on type id and the category id. Don't ask me why.

I'm not sure we want to replicate that last hack - it's super annoying because it both hijacks the `cat` parameter and uses internal ids on top of that...

**Comment by willdurand** [comment]
@muffinresearch do we want to redirect (server side) or simply map `atype` to the right `addonType` without changing anything else?

**Comment by muffinresearch** [comment]
I was thinking a server-side redirect would be the best thing since this should only come from deep-linking.

We'd probably also want the reverse on the legacy frontend too, which needs a bug filing.

**Comment by muffinresearch** [comment]
See https://github.com/mozilla/addons-server/issues/6846 for the addons-server issue to do the reverse.

**Comment by vcarciu** [comment]
@willdurand : I think that https://addons-dev.allizom.org/en-US/firefox/search/?atype=1  should highlight the Extensions tab in header (tested with FF 56.0.2-latest and Windows 10x64) : 
![headhighlight](https://user-images.githubusercontent.com/1583842/32497706-1ba30644-c3d6-11e7-89b8-4a67fe916ec9.png)

**Comment by willdurand** [comment]
@vcarciu please try with `atype` instead of `type`. The leading `a` is not a mistake :)

**Comment by vcarciu** [comment]
@willdurand : yep, my bad :)
Verified as fixed : 
![atype](https://user-images.githubusercontent.com/1583842/32499100-463c9862-c3da-11e7-8b6f-b77242d08b1c.gif)
