### ISSUE TITLE
Search suggestions cannot be closed anymore if users scroll the page on search suggestions area

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3822]
Steps to reproduce:
1.On your Android device, open amo-dev
2.Enter any search term in search box (ie. fire)
3.While tapping on the area of search suggestions drop down list, scroll up and down
4.Tap somewhere outside of search suggestions drop down

Expected results:
Search suggestions are closed

Actual results:
Search suggestions cannot be closed anymore

NOTES:
Reproducible on Android , FF Release
Reproducible also on Desktop, but it will be an edge case here because you have to mouse select some search suggestions via drag and drop and to mouse scroll in the same time

Please see video for this issue : 
![searchsuggestions](https://user-images.githubusercontent.com/1583842/32500349-d219a160-c3dd-11e7-8a63-9d7a896fe520.gif)

**Comment by tsl143** [comment]
@vcarciu , I cannot reproduce this, may be its already fixed, can you please recheck :)

**Comment by AlexandraMoga** [comment]
@tsl143 This can still be reproduced on all AMO servers. The important step here is to tap in the search results drop down to scroll your page up and down. When this is done, the search results will not be closed when tapping anywhere outside the drop down list.

I've made another video where the steps might be a bit more clear:

![search box](https://user-images.githubusercontent.com/31961530/33766549-ab48d2ac-dc26-11e7-9a71-6ae5a0272257.gif)

**Comment by tsl143** [comment]
Got it, thanks @AlexandraMoga

**Comment by AlexandraMoga** [comment]
Note that this is now also happening with search suggestion list inside the collection form. Maybe in this case the issue is more noticeable, as the suggestion list is occupying more screen size than AMO search suggestions. 
To sum up the issue once more: if the user scrolls the page up and down by tapping inside the suggestion list, the list can't be dismissed anymore when tapping outside

![suggest coll](https://user-images.githubusercontent.com/31961530/38013649-90c33f28-326e-11e8-9666-399cea8e7488.gif)

This is also a follow up for #4623

**Comment by muffinresearch** [comment]
@kumar303 @vcarciu mentioned this issue is very common on mobile now. Do you have a device to be able to investigate this?

**Comment by willdurand** [comment]
I can reproduce on -prod with a real device.

**Comment by kumar303** [comment]
I can reproduce. The bug might be buried in `react-autosuggest` but I'll take a look.
