### ISSUE TITLE
Lastpass should be written LastPass

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3928]
The hero card "Lastpass Password Manager" should be written "LastPass Password Manager" on https://addons-dev.allizom.org/:

![screen shot 2017-11-16 at 15 28 46](https://user-images.githubusercontent.com/217628/32896299-f6d4520a-cae2-11e7-91b9-c398fedf8fe2.png)

**Comment by ioanarusiczki** [comment]
This issue was verified on all AMO servers Using FF57 for Win10x64 and for Android7
Screenshots attached 
![screenshot 27](https://user-images.githubusercontent.com/33448286/32951975-693cdd7c-cbb4-11e7-9e71-1c9e6b681532.png)
![screenshot-1510928598228](https://user-images.githubusercontent.com/33448286/32951979-6ca5a1c4-cbb4-11e7-815e-74ee75fc1057.jpg)
