### ISSUE TITLE
experimental – a tag?

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3946]
https://addons.mozilla.org/search/?sort=created&atype=1&tag=experimental browsed with Firefox 56.0.2 (64-bit) on FreeBSD-CURRENT: 

- finds five extensions, not a full set of results (_if_ 'experimental' is, or was, truly a tag) 
- three of which appear to be not (or no longer) experimental, with a classic view of things. 

![2017-11-18 17 51 33 search add-ons for firefox](https://user-images.githubusercontent.com/192271/32983233-50214dca-cc89-11e7-8f9c-2f8ef7dddc14.png)

Not a major issue, just something I stumbled across whilst answering the _experimental search_ question at https://mozilla.logbot.info/firefox/20171118#c13877033

**Comment by jvillalobos** [comment]
The experimental state is not taken into account for search. Those extensions were tagged with `experimental` by their developers, which is why they appear as such in the results. The tag is unrelated to the add-on state (though I agree it can lead to confusion).

This appears to be working as expected, though at the moment we don't really support tags in the new site. We'll revisit how they interact with search once we bring them back.
