### ISSUE TITLE
Investigate oddities to how "Popular" add-ons content surfaces on Android

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#3960]
The "Most Popular" extensions that surface on Android don't make sense. You'll see some "Popular" extensions with low usage numbers mixed in with legitimately popular content. Furthermore they'll often be low rated extensions. 

Can we investigate why this is happening and fix?

**Comment by jvillalobos** [comment]
Can you specify is this is referring to a shelf in the homepage or something else? For example, if I search for [add-ons with most users on Android](https://addons.mozilla.org/en-US/android/search/?sort=users&type=extension), I get a list that seems to make sense. In the homepage there's a "Top rated" shelf which could potentially include add-ons with little usage, given that it just ranks add-ons by their average rating (with some weight given to number of reviews, I think).

**Comment by tofumatt** [comment]
I think the issue here was we listed what is now "Trending" as "Popular" and that was confusing. Seeing as: the list @jvillalobos posted was fine, we don't have a "Most Popular" search anymore, and this issue hasn't been updated in five months, I think we can close this as it isn't happening anymore and was largely because "Popular" was a confusing search filter.
