### ISSUE TITLE
New "bs" locale causing test failures

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3962]
The Bosnian `"bs"` locale is missing from the configs and causing tests to fail. Fix incoming.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev FF57 (Win10 and Android 7.0)
![image](https://user-images.githubusercontent.com/31961530/33174843-4acbf384-d062-11e7-934b-57238d86489c.png)
![image](https://user-images.githubusercontent.com/31961530/33174856-5b8b1074-d062-11e7-8c6e-b7cd269ad75a.png)
@tofumatt will you also add 'Bosnian' to the old pages? I'm asking because few of the site functionalities are still supported only by the old pages (i.e. User Profile, My Collections).  Currently these options will load the /en-US/ version.

**Comment by willdurand** [comment]
> @tofumatt will you also add 'Bosnian' to the old pages? I'm asking because few of the site functionalities are still supported only by the old pages (i.e. User Profile, My Collections). Currently these options will load the /en-US/ version.

@AlexandraMoga this should be a separate issue in the addons-server project, and yes the "en-US" fallback is expected.
