### ISSUE TITLE
Cannot add extension to collection

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla/addons-frontend#3978]
### Describe the problem and steps to reproduce it:
I am logged in with this user https://addons.mozilla.org/en-US/firefox/user/andreipetcu/
I go to edit collection page https://addons.mozilla.org/en-US/firefox/collections/andreipetcu/container-webextensions/edit/#addons-edit
I type "Search and Switch Containers" in order to add this addon to the collection https://addons.mozilla.org/en-US/firefox/addon/search-and-switch-containers/

### What happened?
The auto complete of the "Enter the name of the add-on to include" does not show the "Search and Switch Containers" extension.

### What did you expect to happen?
I expected the auto complete to show me the "Search and Switch Containers" extension and I should have been able to add it.

**Comment by jvillalobos** [comment]
This looks like a larger search problem, since looking for your add-on by name on the main site puts it on the second page of results. The edit collection popup is limited to the top results (something we should probably fix in the new UX).

Can you please file this bug in the [addons-server repo](https://github.com/mozilla/addons-server/issues/new) instead?

**Comment by andreicristianpetcu** [comment]
https://github.com/mozilla/addons-server/issues/7034
