### ISSUE TITLE
Add an add-on to a new collection

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3993]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

The user should be able to:
- Sign in
- Go to the detail listing of an add-on
- Add the add-on to a new collection
- During the process, name the new collection

Note that there is a feature related to this where you can add an extension to an existing collection: https://github.com/mozilla/addons-frontend/issues/2768

**Comment by pwalm** [comment]
Drop down on the add-on detail page. Normal state:
![screen shot 2017-12-04 at 10 47 53 am](https://user-images.githubusercontent.com/6797635/33570125-acb0664e-d8e0-11e7-9ca4-2fdef0d92d3f.png)

Active state:
![screen shot 2017-12-04 at 10 48 08 am](https://user-images.githubusercontent.com/6797635/33570129-b165a622-d8e0-11e7-9d7c-0b55ade790ca.png)

Launches into "Create a collection" modal flow.

**Comment by tofumatt** [comment]
Just a thought (sure how much of the UI state @kumar303 has implemented so far): can we just use the native OS `<select>` styles instead of that heavily customised one? It's a *lot* more effort to implement that custom one (unless there's an easily restyle-able component out there we can grab) and I'm not sure it helps much with usability. Granted, it looks cool, but doing something like the existing LanguagePicker at the bottom of the page would save us a lot of time and I think still look alright (and probably work better, as `select` tags already have all required browser accessibility stuff built-in).

**Comment by pwalm** [comment]
Totally cool with going native.

**Comment by kumar303** [comment]
> Totally cool with going native.

I like it 🍰 

The implementation uses native styles for when you open the menu (just like the search page). I agree that it would have been a huge rabbit hole (with accessibility issues) to re-style that part.

**Comment by bobsilverberg** [comment]
@jvillalobos This feature has not worked since we implemented the new front end, because all we've done is link to the legacy "Create a collection" form, but without passing any information about the add-on.

Would we still like to implement this, enhancing the current functionality to redirect the user to the new "Create a collection" screen, and also remembering the add-on and automatically adding it to the collection after creation? The latter would require some sort of UX change because right now there's no way to indicate that an add-on will be added to the collection after creation, and we do not currently allow users to add add-ons to a collection before creation.

**Comment by kumar303** [comment]
> Would we still like to implement this

I think it's worth implementing. The *Add to collection* button is a nice shortcut and an entry point that will help users discover the feature of creating collections.

As for implementation, we could start simple by passing `?include_addon_id=N` to the URL and make the API request for including the add-on right after they hit the save button. The UI won't show them anything but that will make it a simple first pass solution. As a follow-up, we could adjust the UI which may be a harder change to make.

**Comment by bobsilverberg** [comment]
> As for implementation, we could start simple by passing ?include_addon_id=N to the URL and make the API request for including the add-on right after they hit the save button. The UI won't show them anything but that will make it a simple first pass solution. As a follow-up, we could adjust the UI which may be a harder change to make.

That does sound like a decent first pass solution. Thanks.

**Comment by jvillalobos** [comment]
What kumar said.

**Comment by vcarciu** [comment]
Verified as fixed : 
![newcolladd](https://user-images.githubusercontent.com/1583842/43147639-32ec90a6-8f6c-11e8-8099-e216188b70cd.gif)
