### ISSUE TITLE
Assign a contributor user to a collection

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3995]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

A user should be able to:
- Create a collection
- Assign another user to be a maintainer of that collection

After https://github.com/mozilla/addons-frontend/issues/4000, the user will have access to maintain the collection.

When showing errors, take this into consideration: https://bugzilla.mozilla.org/show_bug.cgi?id=1393646

**Comment by pwalm** [comment]
This one needs some thinking... How does a contributor get assigned? Email address? Username?

**Comment by kumar303** [comment]
The old site let you add contributors by email address:

<img width="722" alt="screenshot 2017-12-04 13 06 00" src="https://user-images.githubusercontent.com/55398/33570915-0677d1a4-d8f4-11e7-9091-358216a274ed.png">

**Comment by pwalm** [comment]
Doy. OK!

**Comment by pwalm** [comment]
Adding contributors! We're going to split it from adding add-ons to a collection because I don't want to create a massive, super-modal for this. So there will be a button on the collection detail page that says "Manage contributors":
![screen shot 2017-12-04 at 3 13 12 pm](https://user-images.githubusercontent.com/6797635/33581443-b405c8b0-d905-11e7-8607-2ff25e0c951c.png)

And here's the empty state:
![screen shot 2017-12-04 at 3 14 00 pm](https://user-images.githubusercontent.com/6797635/33581473-d9ebeaaa-d905-11e7-9c4a-d547c8a13b75.png)

And here's a state with two contributors:
![screen shot 2017-12-04 at 3 14 12 pm](https://user-images.githubusercontent.com/6797635/33581489-eb1749dc-d905-11e7-80f6-973b1d27eff3.png)

**Comment by kumar303** [comment]
Thanks @pwalm . Looks good. The empty state mock has a typo: the input placeholder should say "Enter email of the contributor..."

**Comment by pwalm** [comment]
Fixed 😎

**Comment by eviljeff** [comment]
in https://github.com/mozilla/addons-server/issues/6273 @jvillalobos confirmed contributors will only be supported for Mozilla collections and adding/removing them won't be exposed in UI (admins can use django admin)

**Comment by jvillalobos** [comment]
Hmm, totally forgot we had decided that. Sorry about the wasted work, but things should be simpler that way.

**Comment by kumar303** [comment]
No worries, thanks!
