### ISSUE TITLE
Going to an invalid addon page logs you out of AMO.

### ISSUE THREAD

**Issue by mkaply** [mozilla/addons-frontend#3997]
Describe the problem and steps to reproduce it:

Go to https://addons.mozilla.org
Login.
Note you are logged in in the upper right.
Go to https://addons.mozilla.org/en-US/firefox/addon/omnibear/
Notice that you are NOT logged in in the upper right.
Go back to https://addons.mozilla.org
Notice you are still not logged in.
What happened?

I got logged out.
What did you expect to happen?

I expected to stay logged in.

**Comment by kumar303** [comment]
Thanks for taking the time to file an issue. I cannot reproduce this so I suspect it may be cookie related (possibly due to your privacy settings or an extension that you are using). Can you still reproduce it in a new Firefox profile? You can also try launching in safe mode from `about:support` but that wouldn't rule out a pref related issue.

**Comment by mkaply** [comment]
Weird. Something must have gotten fixed because this is working now.

Going to a 404 page now shows you as logged in.
