### ISSUE TITLE
Create a new collection (name, description, URL)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4003]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

Depends on: https://github.com/mozilla/addons-frontend/issues/4504, https://github.com/mozilla/addons-frontend/issues/4505

A user should be able to:

- Sign in
- Create a new collection with a name, description, and URL
- Assigning add-ons to the collection will be done in https://github.com/mozilla/addons-frontend/issues/4502
- Save the collection

This will be similar to editing a collection: https://github.com/mozilla/addons-frontend/issues/4002

**Comment by pwalm** [comment]
Create modal:
![screen shot 2017-12-04 at 10 40 14 am](https://user-images.githubusercontent.com/6797635/33569757-8d4d7f40-d8df-11e7-9f90-d9f6d4ef5543.png)

[Collections screens are here](https://mozilla.invisionapp.com/share/YCCYEOFRH).

**Comment by bobsilverberg** [comment]
For QA:

- To access the "Create a collection screen", navigate to http://addons-dev.allizom.org/en-US/firefox/collections/add/.
- It should behave like the edit screen, with the "Save Collection" button disabled as long as the name and slug fields are blank.
- The "Cancel" button should take you back to the previous screen, but because we are navigating to the page manually it will not currently do that.
- The Search field will not do anything yet.
- When you save a new collection it will take you to the details page for that collection.

**Comment by bobsilverberg** [comment]
More for QA:

There's a screenshot attached to #4564 

Please also check the "Edit a collection" feature for regressions as this touched much of the same code.

**Comment by smayer97** [comment]
Missing Privacy settings like old/current Edit Collection window:
- Only I can view this collection
- Anybody can view this collection.

**Comment by jvillalobos** [comment]
This is by design. Collections are now meant to be private (but still accessible by anyone) unless shared by the creator, so there's no privacy setting anymore. Existing private collections are still protected, however.

**Comment by smayer97** [comment]
so like https://github.com/mozilla/addons-frontend/issues/4792

How do you share the collection? 

And is the plan to no longer be able to share and promote collections via AMO?

**Comment by smayer97** [comment]
Also, what does this mean for the Followers of Collections; tracking the #s, getting notifications when new add-ons are added, etc? Is this all going away too?
