### ISSUE TITLE
The 'Featured add-ons only' check box is hardly visible and doesn't always respond to tapping

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4188]
Steps to reproduce:

1.Access the AMO homepage on your mobile device.
2.Tap on "Find add-ons" and enter a valid term that would return results.
3.Open the Filter results and try to tap on the Featured add-ons only check box.
     
Expected result:
The check box is selected and the list of search results is renewed.

Actual result:
The check box is unresponsive. 

Notes:
When the screen is zoomed in the check box responds to tapping.
Reproduced on all AMO servers with FF57(Android 8.0).

![cotzca](https://user-images.githubusercontent.com/33448286/35159138-eb9074e6-fd41-11e7-9454-d3230ddabf92.png)

**Comment by muffinresearch** [comment]
We should check to see the size of the click target and make sure it's sufficient and see if that improves the tapability.

**Comment by wagnerand** [comment]
Mentor: @kumar303 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by SeanPrashad** [comment]
Hey guys,

I tried to replicate this bug however it seems that the **Featured add-ons only** checkbox has been improved since this bug was opened. See below:

<img width="358" alt="screen shot 2018-03-30 at 11 27 44 pm" src="https://user-images.githubusercontent.com/13009507/38159224-1b6e694a-3472-11e8-8d5e-5e8e98efd474.png">

Notice that the border has a darker outline and responds quite well to touch (_without the need to zoom in_):

**Portrait**:

![triage_portrait_mode](https://user-images.githubusercontent.com/13009507/38159290-6492caac-3473-11e8-9f25-7cf92ce2f8d0.gif)

**Landscape**:
![triage_landscape_mode](https://user-images.githubusercontent.com/13009507/38159314-bcb0adbc-3473-11e8-8241-dde1964e0a03.gif)

**Comment by tofumatt** [comment]
I think the click target of the checkbox (especially on small/mobile/touch screens) should still be larger and there should be more padding around it that allows for clicking. I think this bug is still valid.

**Comment by caitmuenster** [comment]
Hey @SeanPrashad, were you able to replicate this?

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF59 (Android 8.0.0)

![pixelfix](https://user-images.githubusercontent.com/33448286/39633264-22800edc-4fc0-11e8-8df9-0043e883178b.gif)
