### ISSUE TITLE
Find ways to improve performance of the frontend

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#4235]
I did some measurements of the load time of the new frontend vs the legacy site. Since we have lost our access to speedcurve I used webpagetest.

I used "Dulles, VA - Firefox" in WebPageTest, with 3 runs (using median for results), first view only, cable connection, private. For the legacy site, I used their scripting capabilities to set the cookie, as setting through a custom header didn't seem to work. I think 3 runs is not enough to get a clear picture (need to eliminate outliers to get a more real median result) but it's a start.

Also, load time is not a great indicator, but it's _something_.

**New Site (Taken on Jan 25, before the push):**
- [Homepage median load time: 5.2s](https://www.webpagetest.org/result/180125_MK_98236855cacdafaa6ba7b3e39b466c76/)
- [Search results ("adblock") median load time: 4.8s](https://www.webpagetest.org/result/180125_DZ_034a750b8e03e2f81244e7efe9c16e66/)
- [Detail page (adblock-plus) median load time: 5s](https://www.webpagetest.org/result/180125_Z6_595c084703de0fecf7f1ac9d92614e06/)

**Legacy Site:**
- [Homepage median load time: 3s](https://www.webpagetest.org/result/180126_4S_f0f3615a504fff1351c1aa9f66a86eed/)
- [Search results ("adblock") median load time: 2.5s](https://www.webpagetest.org/result/180126_0R_be8ed47a5515e44e2cec4edba2c8875f/)
- [Detail page (adblock-plus) median load time: 3.3s](https://www.webpagetest.org/result/180126_W3_7c532b01f171286fddf0a4cc0e862951/)

Observations:
- **New site is roughly 2 seconds slower**.
- For the homepage, I used `/`, so we're losing a bit of time redirecting to `/en-US/firefox/`. But I think that's somewhat realistic, and happens both on the legacy and the new site.

- A lot of time is spent loading images, and on the homepage at least, we load better quality ones on the new site, causing us to load more data overall. We don't run developer uploaded images through lossless optimizers, and we probably should to help here.
- We also spend a lot of time loading fonts, but I'm not sure if there is something we can do here. It's hard to optimize fonts on a multilingual website where we don't fully control the text content.
- I haven't tested repeat views, so caching headers are not taken into consideration.

**Comment by diox** [comment]
Relevant issues that would help:
- [Add Preconnect header for mozilla CDNs](https://github.com/mozilla/addons-frontend/issues/3730)
- [Run developer-uploaded images through pngcrush/optipng/jpegoptim](https://github.com/mozilla/addons-server/issues/7406)

**Comment by muffinresearch** [comment]
@diox thanks for doing this it would appear that we may have gotten slower since launch. Would be interesting to see if we get any benefits from reducing the pre-compressed CSS size to approaching a quarter of what it was now that's shipped.

First load is a good metric to have and we should aim to get this down from where it is. However one positive side-effect of the that upfront load penalty is the faster subsequent navigation. Of course there is almost certainly some optimisations we can do here but we need to do them carefully. 

We have an issues for investigating bundle splitting, but this is something that would be quite complex and we'd need to weigh up carefully - tackling the lower hanging fruit makes more sense first.

* Investigate JS bundle splitting https://github.com/mozilla/addons-frontend/issues/3734
* Investigate CSS bundle splitting https://github.com/mozilla/addons-frontend/issues/3735

That said if webpagetest scripting allowed it, it would also be interesting to track something that shows where we are at beyond the first load. So we can see the benefits of the client-side navigation with data requests.

What would be useful is to start graphing this in some way for -dev stage and prod and getting alerts on significant negative changes. Speedcurve did provide some features like that,  I'm already expecting an update on where that's at and if we can get back on that it will likely provide the quickest way to get ongoing updates and historical data.

**Comment by diox** [comment]
Re-ran the tests on the new site today, so post-push. I increased the number of runs to 9 to get a more accurate median time (which I calculated myself, rounding the numbers - WPT seems to take the best run, not the median).

We can see improvements:

* [Homepage median load time: 4.3s](https://www.webpagetest.org/result/180126_WE_91738e2df31b7283effdf8195c66d1e8/)
* [Search results ("adblock") median load time: 4.4s](https://www.webpagetest.org/result/180126_T2_ce62cc0f8302c399a4e40beb10b2294f/)
* [Detail page (adblock-plus) median load time: 5.1s](https://www.webpagetest.org/result/180126_2V_00d4a8a61d42786136bccee82fb8a897/)

Some of the improvements is due to the smaller CSS (we only gain 30 KB because of gzip, but every bit counts, and I guess it also helps parsing), but also increasing the number of runs helped reduce variance between the runs, since there are some large differences between the runs: For the homepage for instance, some runs were below 3.6 seconds, some were above 5 seconds.

I've focused on initial load rather than using scripting to navigate because I was more interested in the low hanging fruits that don't carry any risk, but that's definitely an option.

**Comment by muffinresearch** [comment]
> I've focused on initial load rather than using scripting to navigate because I was more interested in the low hanging fruits that don't carry any risk, but that's definitely an option.

Yep that's a fair point, the navigation one will definitely be something more of interest should we start looking into bundle splitting. Since doing that might optimise the initial load at the cost of slowing the subsequent navigations in some cases.

**Comment by kumar303** [comment]
Ugh. We should really start tracking performance regressions so we can get an idea of what changes are causing slowdowns.

**Comment by tofumatt** [comment]
I'm just adding to this that a new low-handing fruit is the code in #4286. It makes our flow integration better at the expense of an easy-to-shave 16kB. Maybe even something in a build step could change things. Figured I'd just mention it here for now so it's on record 😄

**Comment by stephendonner** [comment]
@digitarald not sure if you've seen this yet

**Comment by kumar303** [comment]
It would be nice to automate this for regressions. I re-ran them today out of curiosity. It's quite a bit slower.

* [Homepage median load time: 5.9s](https://www.webpagetest.org/graph_page_data.php?tests=190904_4H_2db166d90d478b994809f770847451f8&medianMetric=SpeedIndex)
* [Search results ("adblock") median load time: 5.6s](https://www.webpagetest.org/graph_page_data.php?tests=190904_VB_f640c8fbed4eb3773ad5ea414ca1ca2a&medianMetric=SpeedIndex)
* [Detail page (adblock-plus) median load time: 6.4s](https://www.webpagetest.org/graph_page_data.php?tests=190904_VY_85052b658bbd7e0e622b79d727168aaa&medianMetric=SpeedIndex)
