### ISSUE TITLE
azure debug tool required download disabled

### ISSUE THREAD

**Issue by gsears4now** [mozilla/addons-frontend#4250]
### Describe the problem and steps to reproduce it:
http://go.microsoft.com/fwlink/?LinkId=528798&clcid=0x409

### What happened?
administratively blocked

**Comment by muffinresearch** [comment]
This tracker is for bugs related to addons.mozilla.org's frontend and the website itself. 

It's unclear from your report what the issue is. If you have an issue with a specific add-on please contact the developer of that add-on for support as we cannot provide support for specific add-ons here.

On the basis that there's no action we can take at this time I'm going to close this issue. However, if you feel that there _is_ a problem with the site, please re-open this ticket and add as much information as possible so we can reproduce the bug.
