### ISSUE TITLE
theme category pages without ending slash don't go to new frontend

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#4252]
`https://addons-dev.allizom.org/en-US/firefox/themes/<category-slug>` goes to legacy frontend, whereas `https://addons-dev.allizom.org/en-US/firefox/themes/<category-slug>/` goes to new frontend

e.g.
https://addons-dev.allizom.org/en-US/firefox/themes/holiday
https://addons-dev.allizom.org/en-US/firefox/themes/holiday/

Seems to replicate on all theme categories on dev, stage, prod.  But not extension categories.

**Comment by kumar303** [comment]
On a local frontend server it works as expected (no redirect to the legacy site, no 404). Example:

http://localhost:3000/en-US/firefox/themes/film-and-tv/
http://localhost:3000/en-US/firefox/themes/film-and-tv

Since we use a separate nginx conf for local development it makes me think this is an nginx issue (maybe).

**Comment by bqbn** [comment]
To give some background, the reason why it behaves like it does today is because we do explicit routing for the front-ends, and the original ticket (https://github.com/mozilla/addons-frontend/issues/2082#issue-214723041) requested only category pages **with** ending slash (`/(dictionary|extensions|language|search|themes)/%slug%/`) are to be redirected to the front-end.

And https://github.com/mozilla/addons-frontend/blob/master/src/amo/routes.js#L45 also seems to indicate that the routing table requires an ending slash.

Could you confirm it's no problem for nginx to redirect theme category pages without ending slash to the front-end?

**Comment by eviljeff** [comment]
@bqbn why do extension category pages work __without__ the slash though?  the pattern in #2082 shows extensions as well as themes (plus dictionaries, lang packs, search plugins)

**Comment by bqbn** [comment]
@eviljeff that's a good question.

In extensions case (and I bet it's the same for others) is because addons-server adds a trailing slash and returns a 301 to Nginx, which Nginx passes to the browser, the browser tries the 301 again, and landed on the mobile site.

For example, on an addons-server instance, I did this:
```
$ curl -H "host: addons-dev.allizom.org" -I localhost:9000/en-US/firefox/extensions/bookmarks
HTTP/1.1 301 MOVED PERMANENTLY
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
Content-Security-Policy: ... ...
ETag: "d41d8cd98f00b204e9800998ecf8427e"
Location: http://addons-dev.allizom.org/en-US/firefox/extensions/bookmarks/
X-Frame-Options: DENY
Content-Type: text/html; charset=utf-8
```

And apparently the addons-server doesn't treat `themes/<slug>` the same way, in this case, it returns a 200 directly to Nginx. That's why you see the different behaviors for `themes/<slug>`.

```
$ curl -H "host: addons-dev.allizom.org" -I localhost:9000/en-US/firefox/themes/holiday
HTTP/1.1 200 OK
x-xss-protection: 1; mode=block
Content-Security-Policy: ... ...
x-content-type-options: nosniff
ETag: "e4fadee8602922594c0abe8e1a5dfd1c"
X-Frame-Options: DENY
Content-Type: text/html; charset=utf-8
Set-Cookie:  ... ...
```

**Comment by eviljeff** [comment]
From some local testing (without frontend) it appears extension categories always end _with_ `/` (if you enter a url without a slash it redirects - so the nginx rule always kicks in); and theme categories always end _without_ a `/` (similarly, if a url with a slash is entered it redirects to the url without).  Because the theme categories work the opposite way if the url is entered without a `/` it doesn't match the nginx rule, and if there is a slash nginx catches it before django redirects.

I'm not sure exactly if this was an intentional design, or some side effect of the regex's we added to redirect complete-themes in the past.  But I think it's safe to change anyway - catching just theme categories without `/` is strictly all that's needed.

**Comment by bqbn** [comment]
@eviljeff so to be clear, in the theme categories case, do you want nginx to catch both with and without `/` cases and redirect them to the mobile site, or, do you want addons-server to redirect the requests without `/` (e.g. make it the same behavior as extension categories)?

**Comment by eviljeff** [comment]
@muffinresearch wants addons-server fixed to be consistent with it's slashes instead so this is a wontfix then.
