### ISSUE TITLE
Move to new React imports (import * as React from 'react';)

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4263]
In the future we should import React as `import * as React from 'react';` instead of our previous style (`import React from 'react';`). This should be doable as a simple find + replace 😄

**Comment by muffinresearch** [comment]
> In the future we should import React as import * as React from 'react'; instead of our previous style (import React from 'react';). This should be doable as a simple find + replace 😄

@tofumatt Is there more context to the rationale for doing this?

**Comment by kumar303** [comment]
Something changed in React 16 where `import React from 'react'` no longer works for referencing some things. I looked in their changelog but I couldn't find a specific mention, I just know that we had to update a fair bit of imports to get some components to work. We didn't have to update all of them *but* the `import * as React` approach means that nothing will break so it seems like a good pattern to switch to.

**Comment by willdurand** [comment]
My 2 cents: I haven't seen anything related to such a change on large React apps migrated to React 16, but I've found a note on Flow:

> Note: We import React as a namespace here with import * as React from 'react' instead of as a default with import React from 'react'. When importing React as an ES module you may use either style, but importing as a namespace gives you access to React’s utility types.

https://flow.org/en/docs/react/components/

If the "update a fair bit of imports to get some components to work" was related to Flow, then it's fine but otherwise it might mean something is not working properly anymore and I'd look at Babel/Webpack instead.

**Comment by kumar303** [comment]
Aha, it was indeed all Flow related! Sorry for the confusion. I remember now. The reason is that we sometimes access `React.Node` or `React.ChildrenArray` in our Flow definitions. These are in https://flow.org/en/docs/react/types/ so you'd need to use `import * as React` to reference them or import them explicitly (which could be tricky).

**Comment by AlexandraMoga** [comment]
Please add some STR or the label 'qa:not needed'
