### ISSUE TITLE
Mixed case version of slug leads to blank page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4271]
Re-filed copy of https://github.com/mozilla/addons/issues/586

### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Go to an addon location (https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/), but change the case of the name (https://addons.mozilla.org/en-US/firefox/addon/snapLinksplus/) and you don't get an error page, just a blank screen.

### What happened?

You don't get an error page, just a blank screen.

### What did you expect to happen?

Get an error page, like with (https://addons.mozilla.org/en-US/firefox/addon/sadmknmsadlksa/)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Working: https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/
Working: https://addons.mozilla.org/en-US/firefox/addon/sadmknmsadlksa/
Not working: https://addons.mozilla.org/en-US/firefox/addon/snapLinksplus/

Looks like this:

<img width="1384" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/35622244-06a87378-067f-11e8-8cb2-e602f84990e5.png">

As noted by @diox in https://github.com/mozilla/addons/issues/586#issuecomment-357675409 this worked on the old site. The only issue is the legacy site shows the same content on a different URL (I'm not sure if it uses rel=canonical) - the ideal solution is probably to provide a 301 cacheable redirect to the lower case version.

**Comment by muffinresearch** [comment]
I think we should consider doing the redir at the nginx level so it doesn't even need to hit the appserver CC'ing @bqbn for input.

**Comment by muffinresearch** [comment]
We appear to have this problem for all slugs e.g: https://addons.mozilla.org/en-US/firefox/collections/mozilla/Bookmark-managers/

So we'll want to do it for all slugs I think. @diox presumably that'll be ok from the server perspective?

**Comment by diox** [comment]
I think it makes sense yeah. From the server perspective slugs should be lowercase, it's just that addons-server doesn't care (because MySQL doesn't care) about case at all when fetching the add-ons/collections.

**Comment by bqbn** [comment]
So if I understand correctly, is the ask that for a mixed case slug, return 301 to its all lower case version? If that's the case, can we make the front-ends do it?

The reason is this. Nginx currently uses 

https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/urls.py#L9

to match a slug. As you can see there is no tell from that regex a slug is mixed cased or not. In order for it to determine if a slug is mixed cased or not, Nginx would have to first match the above regex, then do some further complicated regex matching. However, unlike high level languages such as Javascript or Python, Nginx's limited directives are not designed to handle strings. If we were to do it at the Nginx layer, the end result will be some complicated regex matching logic and it slows down the speed.

It's probably better to put less logic in the routing and proxying layer and keep its speed so it can handle more connections.

**Comment by kumar303** [comment]
The only way a user will experience this is if they edit the URL bar so I think we should drop the priority.

**Comment by diox** [comment]
There has got to be links in the wild with mixed/wrong case slugs, though. Links that used to work perfectly fine before.

**Comment by kumar303** [comment]
I've only seen [one bug](https://github.com/mozilla/addons/issues/586) reported by a user and they didn't mention any external links. They talked about editing the URL bar.

**Comment by bqbn** [comment]
So to give a sense of the scale, I checked yesterday's nginx access log on one of the instance. Out of 1,282,906 lines of access log, only 13 used the mixed cases. And all 13 returned 200 as well.

```
$ sudo zegrep -o '"[^"]+" [0-9]{3}' i-06e755f2d127e687b-2018-02-13.log.gz |egrep "/\w{2,3}(?:-\w{2})?/(?:firefox|android)/addon/[^/<>\"']+([a-z][A-Z]|[A-Z][a-z])[^/<>\"']+/"
"GET /eu/android/addon/temaCNdeF/ HTTP/1.1" 200
"GET /ja/android/addon/J-Cole_Cole-World/ HTTP/1.1" 200
"GET /fr/android/addon/sz%C3%ADnes-fonal/ HTTP/1.1" 200
"GET /vi/android/addon/p%C3%A8re-no%C3%ABl-christmas/ HTTP/1.1" 200
"GET /hu/android/addon/seznam-li%C5%A1ti%C4%8Dka/ HTTP/1.1" 200
"GET /vi/android/addon/v%C3%ADzcseppek-lila/ HTTP/1.1" 200
"GET /vi/android/addon/for%C3%AAt-et-montagne/ HTTP/1.1" 200
"GET /ja/android/addon/r%C3%AAveries/ HTTP/1.1" 200
"GET /eu/android/addon/Beach_View/ HTTP/1.1" 200
"GET /nl/android/addon/portugu%C3%AAs-portugal-language/versions/ HTTP/1.1" 200
"GET /nl/android/addon/so%C5%8Bay-senni-hantum-tenjandikaw/versions/ HTTP/1.1" 200
"GET /mn/android/addon/pot%C3%A1p%C4%9Bn%C3%AD/ HTTP/1.1" 200
"GET /ru/android/addon/dolnopo%C4%8Dernick%C3%BD-rybn%C3%ADk-1/ HTTP/1.1" 200
```

I think the impact of this is low based on the above.

**Comment by muffinresearch** [comment]
> I think it makes sense yeah. From the server perspective slugs should be lowercase, it's just that addons-server doesn't care (because MySQL doesn't care) about case at all when fetching the add-ons/collections.

@diox I think if the server does consistently surface all slugs as lower-case then we can fix this at the nginx level and will never have to hit the app server.

This would be a good one to fix since it also hurts SEO due to duplicate content.

**Comment by willdurand** [comment]
@bqbn do you think we can do something at the nginx level with a lua or perl module? that would avoid a too complicated regex.

**Comment by bqbn** [comment]
@willdurand in general I'd rather not have Nginx process every request because that has the potential of slowing down the proxy. 

Besides we're not using OpernResty so Lua is not available. Perl is not as fast as Lua (supposedly) and the customized Nginx we're using doesn't have perl module compiled in. We'd have to re-compile and test that first.

I still wish we could have the app send 301 if a slug is not all lower cased (meaning either mixed cased or all upper cased). For example,

```
function isNotLowerCase(str) {
    return str !== str.toLowerCase();
}

if (isNotLowerCase(str)) {
    // 301 to str.LowerCase()
}
```

As noted in https://github.com/mozilla/addons-frontend/issues/4271#issuecomment-365718129, there are really not that many requests that are using mixed case slugs, so hopefully it doesn't impose too much burden over the app (each request needs to do one case comparison, which should be fairly quick since either Javascript or Python is meant to be very good at handling strings).

**Comment by willdurand** [comment]
Fair enough, so I guess we would have to do that at the app level. I'll see what it involves.

**Comment by willdurand** [comment]
@muffinresearch can we move the logic at the app level given that there are not a lot of requests that are using mixed case slugs?

**Comment by muffinresearch** [comment]
> @muffinresearch can we move the logic at the app level given that there are not a lot of requests that are using mixed case slugs?

Yeah I think that should be ok for this case, especially if it saves some yak-shaving.

**Comment by ioanarusiczki** [comment]
Verified this issue on AMO dev with FF62(Win10) for an add-ons detail page, collections, the view profile page (when the username is modified) and when the slug is changed and uppercase is used these pages redirect accordingly. 

![redirects to addon](https://user-images.githubusercontent.com/33448286/46959237-3eb40800-d0a4-11e8-931d-f45fcfaf0f5b.gif)

**Comment by willdurand** [comment]
> Seems odd to me that we need to consider mixed case slugs at all. The UI for the devhub doesn't seem to support anything but lower case slug entry. Is there anywhere else that you can?

According to @eviljeff and @bobsilverberg, it is a feature we have for a while (and "cool urls never change").

According to [HTML and URLs](https://www.w3.org/TR/WD-html40-970708/htmlweb.html), nothing says that URLs should be lowercase or case insensitive, quite the contrary actually.

> I think there might be a redirect loop case if you can have a cached 301 for one case variant and then change it back.

That should lead to two (or more) `301` but if there is content served, the page will be displayed because recent-ish browsers detect redirect loops.

Do you know if we previously sent server redirects on AMO (for those pages, with a different URL)?

**Comment by eviljeff** [comment]
> Do you know if we previously sent server redirects on AMO (for those pages, with a different URL)?

legacy pages on addons-server have redirects for missing locale (`\en-US`); missing app (`\firefox`); and missing trailing slash in the URL.  And for numeric ids.  I don't think we've ever redirected a complete url addon url like https://addons.mozilla.org/en-US/firefox/addon/snapLinksplus/ though.
