### ISSUE TITLE
Search results for 100 random char string

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-frontend#4278]
Steps to reproduce:

    1. Go to https://addons-dev.allizom.org.
    2. In the "Search" field introduce a 100 char string(ex. T@@#$%^&*#$%^&*($%^&*%^&*$%^&*#$%^&*(#$%^&**()&^%$$#%^&*&(*)(*&^%$^&*&(*)_)(*&^%$^&*()_+)(*&^%&*()_%)
    3. Press "Enter". 

Expected result:
No results are displayed.

Actual result:
"1,763 results for "T@@#$%^&*#$%^&*($%^&*%^&*$%^&*#$%^&*(#$%^&**()&^%$$#%^&*&(*)(*&^%$^&*&(*)_)(*&^%$^&*()_+)(*&^%&*()_%"" is displayed.

Notes: There are also suggestion for the 100 chars long string. Results are not related by more than 1 character.
![100 search result](https://user-images.githubusercontent.com/28138132/35628704-a8cef2f2-0694-11e8-923e-67981edb6845.gif)

**Comment by kumar303** [comment]
Huh. That's pretty odd. I guess it has something to do with how our Elastic Search backend strips out characters. My hunch is that this is a feature to help normalize certain realistic search terms, like ones that have punctuation where the punctuation should be stripped.

Thanks for the report but since nothing is broken here and the search isn't realistic, I don't think we should spend time figuring out why it's happening.
