### ISSUE TITLE
Make reviews and ratings clickable on detail page

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#4287]
### Describe the problem and steps to reproduce it:
Go to any add-on's detail page

### What happened?
The reviews and ratings area on the upper right corner are not clickable.

### What did you expect to happen?
I expect to be taken to the /reviews page relevant to the add-on when I click on the "Reviews" and "Overall Rating" labels, as well as the number above "Reviews" and the stars above "Overall Rating".

### Anything else we should know?
![b68aa4ae-f069-49be-8e09-43860be77901](https://user-images.githubusercontent.com/6797635/36614390-63e01d92-1891-11e8-85b4-e2695d6f5a18.jpeg)

**Comment by tofumatt** [comment]
I forget if I filed an issue for this already, but I'll look later 😆. At any rate: I agree and we should do this. It shouldn't even be super difficult.

**Comment by kumar303** [comment]
I can't find an existing issue but I know we've talked about this. It will go hand in hand with https://github.com/mozilla/addons-frontend/issues/3918

**Comment by bhavyaagg** [comment]
Hi,
If no one is working on this issue, can i give it a try?

**Comment by tofumatt** [comment]
Sure thing, just file a pull request when it’s ready and we will review it :-)

**Comment by bhavyaagg** [comment]
Sure. Thanks @tofumatt

**Comment by bhavyaagg** [comment]
Hello @tofumatt ,
I have tried the following method but i am not sure which is the best:
1) Using <Link> tag with href, but in this case the styling of the text gets broken.
2) Using a onClick listener on the MetaDataCard Component
3) Using window.location.href to reload the reviews page.

Thank you for your help.

**Comment by tofumatt** [comment]
You will want to use our `<Link>` component to link to the reviews similarly to how reviews are linked to elsewhere in the app (I think the link is "Read all reviews" or something similar.

You will need to override the link's style to make it keep its existing appearance. You can probably leverage the `inherit` value in CSS a fair bit, hopefully 😄

**Comment by a-one-d-one** [comment]
I am currently working on resolving this. I was wondering if anyone has already started on the issue.

**Comment by a-one-d-one** [comment]
Hi again,

I believe I have solved this issue but I am newly introduced to testing. I was wondering if I could get some help in resolving them. It is a expecting a string for ratings but because it is now using a link to direct to reviews page it is failing the tests. I have added the following image: 

![screen shot 2018-03-17 at 7 47 08 pm](https://user-images.githubusercontent.com/12375686/37561102-4585b77a-2a1c-11e8-9f49-0b6bd5398646.png)

**Comment by a-one-d-one** [comment]
I have been trying to get around this testing to receive the expected values for the ratings, rating counts etc.. and have not been successful because the variables are now being wrapped by links. example : 
```
content: (
                <Link
                  className="Addon-all-reviews-link"
                  to={`/addon/${addon.slug}/reviews/`}
                >
                  {reviewCount}
                </Link>
              )
```

the testing fails and this is the explanation : 

```
expect(received).toEqual(expected)
    
    Expected value to equal:
      "5"
    Received:
      <Connect(LinkBase) className="Addon-all-reviews-link" to="/addon/chill-out/reviews/">5</Connect(LinkBase)>
    
    Difference:
    
      Comparing two different types of values. Expected string but received object.
      
      at Object.<anonymous> (tests/unit/amo/components/TestAddonMeta.js:115:44)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```


I would appreciate any help in figuring out how retrieve the reviewCount value or some direction in re-writing the tests to accommodate the new changes.

**Comment by SeanPrashad** [comment]
@tofumatt @a-one-d-one and I would appreciate your thoughts on what we should do next - since we've wrapped the `reviewCount` value inside a `<Link>`, we're unsure how to properly go about accessing the value

**Comment by jvillalobos** [comment]
@kumar303 might be able to resolve the question in the last comment.

One thing I'd like to add after going over the [PRD](https://docs.google.com/document/d/1oUz9Ng9v159IPdW4UqHhbNspWa9m5SaicAAX5jU7OjA/edit#) for Ratings: the stat in the top right shows the number of _ratings_, while the link in the left column below the summary shows the number of _reviews_ (ratings with written text). It makes sense that the review stat is the one linked, because we don't show empty ratings in the All Reviews page.

For simplicity, I suggest we only show total reviews (not total ratings). That can make the star average confusing in some cases, but [some future designs](https://mozilla.invisionapp.com/share/PRL0I8WUHQT#/screens/294859912) change the copy to Reviews and Ratings to clarify things. @MeridelW, what do you think?

**Comment by muffinresearch** [comment]
Superceded by https://github.com/mozilla/addons-frontend/issues/5434
