### ISSUE TITLE
Add a config to run server in 'production' specifically for addons-server UI tests.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#4294]
@kumar303 helped me get this going but there would need to be a config added to the repo to allow this to work for anyone else wanting to run the tests, as well as, running the tests in CI.

I am thinking of naming it ```uitests-production-amo```, but I am open to suggestions.

**Comment by kumar303** [comment]
Will the tests always run in production? That seems a bit risky. As for the name, I'm not picky about it but I think we should avoid the concept of *ui tests* because the `addons-frontend` repo is an implementation of the UI so all of our unit tests are UI tests. This actually causes real confusion around our [`ui/components`](https://github.com/mozilla/addons-frontend/tree/master/src/ui/components). I would suggest using the term *functional tests* in place of *ui tests* to indicate that they are tests of how the end product should function.

**Comment by jrbenny35** [comment]
This is confirmed working. I can open a PR.

**Comment by jrbenny35** [comment]
Fixed in #4295

**Comment by AlexandraMoga** [comment]
Please let us no if any QA is needed here, otherwise add the label "qa:not needed"
