### ISSUE TITLE
Improve Collection Function in the new design Addon pages

### ISSUE THREAD

**Issue by decembre** [mozilla/addons-frontend#4331]
### We Can't see in which Collection an extension is already:
- Need to be Like in the old design where we see a check before each collection where the extension is added.
Click on it delete the addon from here and an external link icon can open the collection

**Comment by decembre** [comment]
Here a screentshot of  the add to collection process inb old AMO design.
It is tweaked by a perso Usertyle:
https://userstyles.org/styles/92268/mozilla-addon-widescreen-v-66
but it show what i need  in the NEW design:
- A mark for collection where the addon is already
- Possibility to delete the addon from a collection
- Icon to go to any collection directly

![amo - collection - old - for request big](https://user-images.githubusercontent.com/868778/37569174-c596518c-2ade-11e8-9d04-efca591811a6.gif)

**Comment by decembre** [comment]
@tofumatt 
Ok but the principe stay the same (manage directly from the collection list):
- See  if the addon is added or not in a collection (checked or not)
- Add or delete the addon to a collection (directly in the dropdown menu)
- An icon near each collection label to go to its collection detail page
of course, the list should be sorted by alphabetical order
The screenshot:
![amo - collection - old - for request big - without style](https://user-images.githubusercontent.com/868778/38152856-fa0a5032-3469-11e8-82aa-ea5d7271bcbc.gif)

**Comment by pwalm** [comment]
@tofumatt Yep, adding to multiple collections wasn't spec'd for this pass. But do keep it open as a low priority.

**Comment by smayer97** [comment]
There are 3 related Issues posted that make up ALL the functionality that is needed to reproduce the original design of the Add To Collection menu, as per decembre's post above:
https://github.com/mozilla/addons-frontend/issues/4331#issuecomment-377615994

Add To Collection - List not sorted by name -- https://github.com/mozilla/addons/issues/676
Add To Collection - Cannot search the list -- https://github.com/mozilla/addons/issues/677
Add To Collection - There is no link to open collection from list of collections -- https://github.com/mozilla/addons/issues/679

**Comment by smayer97** [comment]
BTW, you can review these discussions started 2 years ago about why this set of features is SO important.
https://discourse.mozilla.org/t/no-favorite-button-in-new-amo-design/8015/40
and
mozilla/addons-server#2264

**Comment by smayer97** [comment]
Please consider increasing the priority.

**Comment by jvillalobos** [comment]
I don't think we should do this. It will make the add feature more complex than it needs to be, and turn it into a multi-collection management tool that is only useful for a small group of users. Collections can be managed in the My Collections and Edit pages. The add feature should be limited to that.

This feature can already be used to add an add-on to multiple collections, by using it multiple times. We also show an error when an add-on is already part of a collection. So, while it's inconvenient for power users, it's still possible to do what they need to do.

**Comment by smayer97** [comment]
No, No, No. Please say it ain't so. The Add To Collection is NOT simply about adding an addon!

Sorry in advance for my long post...but I just am not sure how to get my point across better...

(Let me also bring in the text from your other related post https://github.com/mozilla/addons/issues/679#issuecomment-381192154 to make my points easier to make.)

"My argument is that the Add to Collection menu should be limited to what it's meant to do, instead of being a complete management tool. Having so many features crammed into a little popup makes it harder to use for most users. It optimizes usage for power users, at the expense of more casual ones.

The changes to collections are intended to make the feature simpler and easier to maintain..."

I am not sure how much or if you use collections but you state "... the Add to Collection menu should be limited to what it's meant to do, instead of being a complete management tool." BUT that is exactly what the Add To Collection menu was designed to do; to add to and give access to collections, and for VERY GOOD REASONS. It is the MAIN link between the add-on pages and collections.

This is what many of us have been clamouring about for over 2 years when arguing for the return of the Add To Collection menu, in this thread https://discourse.mozilla.org/t/no-favorite-button-in-new-amo-design/8015/64 and https://github.com/mozilla/addons-server/issues/2264 (and other related discussion threads).

When Mozilla acknowledged that removing this menu was a mistake, I thought (and I suspect others following this discussion too thought) that there was now an understanding of its importance and how this menu and collections were used.

You state, "The changes to collections are intended to make the feature simpler and easier to maintain." If this is true, then having this design is ALL THE MORE REASON to add this, not keep them out.

Consider this analogy...what you are proposing is like a bank saying:
- they will provide a menu to be able to add your money 
- BUT if you want to see money is, and see the context where it is, you will first, need to
           - figure out where to find that info on the site
           - have to go through multiple steps to pull up that info
           - possibly search through each account to find if the money is there or not
           - and by the way, they will not provide a quick and easy link to take you directly to where you put it.
How long would you deal with such a bank? 

Think about the casual user - user wants to add add-on to collection. Creates collection and adds collection. What do you think their next question will likely be? Where is my collection stored and how do I access it? For the uninitiated, there are no clues. And once (or if) they figure out where they can be found, the process of maintaining them is arduous at best because they have to use 2 different areas just to manage them. The information they need about the add-on is in one place and the list of collections is in a different area. How long do think they will continue to use collections? I as a very savvy collection user am having a VERY HARD TIME.

No, the BEST and most conducive place to tie add-ons to collections is the Add To Collections menu. 

You also mention "Having so many features crammed into a little popup makes it harder to use for most users." and "It optimizes usage for power users, at the expense of more casual ones."

     - "crammed" - how would these 2 elements make it crammed? The new Add TO Collection menu takes up the WHOLE screen width, FAR MORE than the old one did. 

     - "harder to use" - I would argue that what you are proposing actually achieves the very opposite; making it MUCH HARDER to use collections. I do not believe for a moment that having the 2 simple elements of a check mark and a link makes it harder to use. In fact, the WHOLE POINT is that it makes it EASIER to use for BOTH the power user AND the CASUAL user. 

     - "at the expense of more casual [users]" - Again WITH these 2 elements in the menu, it makes the use of collections MUCH EASIER...and the implementation is so subtle that it is unobtrusive to the passer-by. 

And this could further easily be addressed by linkifying the collection name(s) in the Add To Collection (instead of a visible link to the right like the old design, as depicted above), thereby making the UI even cleaner with only one element showing; the checkmark. 

And what VALUABLE info to see the checkmark in the list, especially as users engage in the use of collections a bit more, with a simple yet powerful interaction, with easy access to the related collection with only 1-click.

Note that what now takes MANY MINUTES and MANY clicks and flipping back and forth between the collection pages would literally only take only 2 clicks! That's it! You can add to, you can delete from and you can open a collection, and have valuable information all from one convenient location.
(see the detailed example illustrating this here https://discourse.mozilla.org/t/no-favorite-button-in-new-amo-design/8015/16?u=smayer97 )

Even for the more engaged collection users, though the My Collections and Edit pages serve a purpose, they do not have the right tools...there is no search or sort feature, etc. Even if there were, it still magnifies the effort to flip over to those areas to track down a collection or an add-on within a collection. 

That is the POWER and SIMPLICITY of the original Add To Collection, for BOTH the power users AND the CASUAL users. 

Also keep in mind the audience - If users are using add-ons, they are already a little more savvy than many. And if users use collections, they are even a bit more savvy. And to make it EASIER for the uninitiated to start using collections, having the tie-ins between the add-on page and the collections makes the most sense.

You state "...collection management tool that is only useful for a small group of users". I think you are also incorrect on this point. I want to point out once again that the users of collections represent a far greater number of users that benefit from collections. How many users of collections support other users? How many sit in IT departments or schools, etc. and use them to manage the many users they are responsible for? I know I have supported hundreds, if not thousands with just my collections. And even if only supporting family and friends, this has a multiplicative impact. 

Because again, users of Collections are likely the ones who impact far more than meets the eye, the ones that are likely more savvy, and the ones managing them to support others. So keep in mind that it would serve Firefox to facilitate their need. 

So again, please reconsider this. In summary:
- adding these features back will make it easier for BOTH the power user AND the CASUAL user
- the visual impact to the user is minimal
- the impact and benefit FAR outweighs any detriment, saving time and energy, making far better use of add-ons
- the number of users that would benefit is far greater that the visible users of collections

Features to add:
- checkmark to show each collection the add-on already belongs
- clicking the check mark allows either adding or removing the add-on from the desired collection
- link to each collection (either link beside the name or linkify the name)

This is a case of THE WHOLE IS GREATER THAN THE SUM OF ITS PARTS... The old Add To Collection with these features is an INVALUABLE tool when it comes to using collections ...please do not lose sight of this...

**Comment by smayer97** [comment]
BTW, I also the your suggestion you made here: https://github.com/mozilla/addons/issues/679#issuecomment-379908984

"it may make sense to linkify the collection name in the notification that appears after an add-on is added to it, or it could be a link next to it ("Edit", "Add Notes", or something like that)."

I would suggest that this be a bonus, not a replacement for what I am suggesting. And I would make the links next to the add-on be "Add Note", "View" (Collection), "Edit" (Collection), or something similar.

**Comment by smayer97** [comment]
Would further feedback be possible regarding this feature? 

BTW, I am wondering why more emphasis in not placed on such a feature that has a meaningful use and application to a base of users that can and do support others vs simply cleaning up the look and feel of AMO and Collections? It would seem to me to be a more worthy feature to implement, and sooner? I know I have been crippled in my use of Collections and Add-ons ever since its absence.

TIA for any consideration of this.

**Comment by decembre** [comment]
"Collections can be managed in the My Collections and Edit pages. The add feature should be limited to that.":
Sorry i can't understand the logic of that.

The old / Desktop design is better for usability and informations provided than the Mobile version.

Why broke something which work fine and with efficiency ?
Why you don't want preserve it on Mobile version ?
Why you don't show "Related Collections" in addon info page ?

**Comment by decembre** [comment]
Now we can't Follow a collection:
Why ?

**Comment by decembre** [comment]
And now we can't see our old legacy extensions (which i use always with ESR or Waterfox ):
They are not listed, but strangely they are count in our list of collections...

PS:
By the same way we lost The Fav icon and the relted collections in the addon page...
(which was practical because many addons have name very similar and we can make mistake about them).
Why you don't remove all the collection functionality now ?

**Comment by smayer97** [comment]
Yes, still wanting and desperately needing the old functionality that allowed you to see what collections an add-on already belongs to. Currently, there is NO visibility to such info. 
And there is no way to easily navigate to the collection that an add-on was just added to or already exists in. These 2 features are a great deterrent to users adopting the use of collections.

The current design ends up being relegated to be used only by the most savvy. This is very counter to the value that collections bring. This will only contribute to a declining use of this once very useful feature.

PLEASE restore these 2 critical features to making the use of collections appealing.

**Comment by smayer97** [comment]
I know that it has severely crippled my ability to use collections and hence my usage has declined dramatically, and forcing me to seriously consider abandoning Firefox (though for other reasons at the moment, I am not able to completely do that; plus I value the privacy values of Mozilla over Google).

I had been a big advocate of Firefox and had convinced and supported MANY to convert to use Firefox. Based on my experiences the last few years, it is much harder to justify my continued promotion of Firefox and support of the users I convinced, with the loss of effective collections management.

PLEASE restore this simple UI for collection management.

**Comment by smayer97** [comment]
To clarify, the 2 critical features are:
-  checkmark to show each collection the add-on already belongs
-  link to each collection (either link beside the name or linkify the name)

And the third may not be critical but would make it A LOT easier:
-  clicking the check mark allows either adding or removing the add-on from the desired collection (or at least just removing)

**Comment by smayer97** [comment]
@jvillalobos "...So, while it's inconvenient for power users, it's still possible to do what they need to do."

Actually it is not... one key thing where is NO WAY TO DO is to know which of collection (personal ones) an add-on already belongs to. 

Maybe as a compromise, a simpler solution could be implemented...see the following:

**Comment by decembre** [comment]
> 
> 
> I don't think we should do this. It will make the add feature more complex than it needs to be, and turn it into a multi-collection management tool that is only useful for a small group of users. Collections can be managed in the My Collections and Edit pages. The add feature should be limited to that.
.........
 So, while it's inconvenient for power users, it's still possible to do what they need to do.

Closed in april 2018 after with just this short and definitive advise..... !
That's like my bank refuse me a credit....

Many reasons provided here to make/keep a better user experience are ignored just like that.
If collections exist you should make it usable and promote it.

The collection sharing is an important way to discover other addons and promote them.
The facility to maintain a collection give a better view , more accurate and updated to collections.

And if collections are hard to manage for us (these "PRO" user) and can't be shared , you should consider to erase this function.

The "it's still possible to do what they need to do" is not a good reason.
PS:
Before on AMO i can discover easily some unconventional or original extensions, now it's more difficult to find them:
Sharable Collections can be useful at this point
