### ISSUE TITLE
"Add to Firefox" button is displayed as being active before the add-on's auto approval

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4348]
Steps to reproduce:
1. Load AMO dev and from Developer Hub submit a new add-on.
2. While it is awaiting for auto approval click on View Listing.
3. Observe Add to Firefox button.

Expected results:
Add to Firefox button is greyed out until Awaiting Review changes state into Approved.

Actual results:
Add to Firefox button is displayed as being active and it can be clicked. 

Notes:
This issue is also reproducible before manually approving static themes.
This issue is reproducible on AMO dev and AMO stage using FF58 (Win10).

![blue active button 2](https://user-images.githubusercontent.com/33448286/35982025-6e121810-0cf7-11e8-8fe2-3aa24760af68.gif)

**Comment by tofumatt** [comment]
What happens when you click on the "Add to Firefox" button in this case? If the add-on is viewable it should be install-able. Maybe the issue is you can see the install button because you're signed in as the author of the add-on so it's always visible to you? What happens if you view it as an anonymous user?
