### ISSUE TITLE
Edit review by deleting the previous submitted text does not work

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4367]
STR:
1. Load AMO dev and go to an add-on's detail page.
2. Submit a review with text, preferably one that has No reviews yet.
3. Edit your review by deleting the previous text.
4. Go back to the add-on's detail page.
5. Observe the number of reviews mentioned in 'Read all <number> reviews' link.

Expected result:
The link shows No reviews yet.

Actual result:
Read 1 review is displayed and when clicked the review contains text.

Notes:
This is reproducible on AMO dev and AMO stage with FF58 (Win10).

![edit review by deleting text](https://user-images.githubusercontent.com/33448286/36092211-40bac3c6-0fef-11e8-8248-4717ce5b97ec.gif)

**Comment by tofumatt** [comment]
Filing this as a P4 because it's definitely weird and not great but I venture the case of wanting to remove a review's text entirely rather than edit it is not common.

**Comment by rebmullin** [comment]
After looking into this a bit it seems that even if there is a review rating only (i.e. there is no body text) it’s still considered a review so it SHOULD be displayed in the reviews list, right? This is my understanding per the api docs here:

https://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#post

So I have few questions regarding this:
If a review does NOT have body text, should it be counted as a review and displayed here (in the addon's reviews list) - with just the star rating? It seems per the notes above this isn't expected so just wanted to verify this..

When I test this in postman updating/PATCHing the review by removing the body text it actually does the same thing - it doesn’t change the body text - so I am wondering if this potentially an actual API bug and if someone could direct me on where I should go to look into this a little bit more.?

@bobsilverberg @muffinresearch

**Comment by bobsilverberg** [comment]
Thanks for the investigation @rebmullin. I did a bit of testing too, and what I see is that when the "edit review" form is submitted with an empty body the old text is still sent to the PATCH API request, so that would explain why the review doesn't appear to be updated. This may have something to do with code we have in place to cache the values in the form in case a user leaves the page and comes back, and is definitely a bug. I'm not sure how small/simple an issue that actually is. If you want to try to figure that out go ahead, or if you want to move onto something simpler for now that's fine too.

The question of whether a review that used to contain text, and now does not, should be considered a review or not is a valid one. It seems like maybe we (or the back end) need to delete the review if the new version contains no text, if it is meant to be treated as a non-review. I'll ask around about that one.

**Comment by bobsilverberg** [comment]
This is complicated by the fact that review text is localized, so even if we are successful in emptying out the review text, it will still be counted as a review. We should fix the issue that a user cannot remove their review text by blanking it out, but we might not be able to fix the issue of it being counted as a review.

**Comment by rebmullin** [comment]
hey @bobsilverberg  - hmm i might have made a few changes to get it be a null value when i reached the api call..? I'll double check this tho...but again i used Postman to double check this call and it was doing the same thing. I guess i thought the benefit of using Postman - altho i could totally be wrong here - was that it was outside of all the code and if it wasnt producing expected results there, it *might*  indicate an API issue :/

I guess once we figure out if it's supposed to be a review or not  - without this text- we can figure out the approach and dig in a little bit more. 

I'll def circle back on this 1

**Comment by bobsilverberg** [comment]
I believe the issue with the API is that if you pass a null (or don't pass a value) for the body test then it ignores it and doesn't update it. This is because it is a localized field. What we need to do instead, is pass an empty string as a localized string to the API. That should allow us to blank out the body text. That may or may not address the issue of whether that rating is still counted as a review - that's something we'll have to test, but for now we should fix the issue that it is impossible for a user to entirely remove the text of their review by blanking out the form.

Does that make sense, @rebmullin?

**Comment by rebmullin** [comment]
i think so..i vaguely remember that passing in empty string *does* work. I'll re-look into this part at least. thanks @bobsilverberg

**Comment by rebmullin** [comment]
hey @diox  - I was told that maybe you could assist w/ the following questions in relation to this issue:

When submitting a review it doesn't * seem * to allow empty text (null or string). These are the scenarios I am running into:

First time creation of review:
Passing in null for body text - it doesn’t get saved as a review
Passing in string for body text - it doesn’t allow this - I get the following message (“This field may not be blank”)

When I try to modify an existing review:
Passing in null for body text - it doesn’t change the text (text remains unchanged) and stays as a review
Passing in string for body text - i get the same message as above (“This field may not be blank”)

I have a few questions related to these various scenarios:
- Should it be considered a review despite having no body text?
- Shouldn’t passing string or null value be allowed on update or even original creation of review?

It does  *seem* like this should be a review regardless and updating with empty string should be ok per the api docs here:
https://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#review-filtering-param
also this: https://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#detail

I know there are potential complications b/c of localization but would that affect updating this field? altho...now that i am talking through this i realize - altho not certain-  since we are grabbing the user input via textarea.. i am not sure we are using localization here so this (localization) might not even be a factor in this case..? from what i can tell this *shouldn't * be an issue...

also, that's why i tested in postman to extract it out and i see the same. I am not sure if this will help but here is a video too of what I see: 
![Alt text](https://monosnap.com/image/XYMk7isceh7uOsG0RiQFOc64WJ3VWx.png)

please let me know if you need any clarification on anything to help sort this out : ) 

// cc @bobsilverberg

**Comment by bobsilverberg** [comment]
After discussing this with @diox in IRC, I believe this mostly needs to be fixed on the back end, and to that end I opened https://github.com/mozilla/addons-server/issues/8226. We will still need to make sure that our code sends a null to the API when a user blanks out the body text, which should work after https://github.com/mozilla/addons-server/issues/8226 is fixed.

**Comment by bobsilverberg** [comment]
The new ratings and reviews UI provides links to both delete a rating and delete a review. There is no way to just delete a review and leave the rating intact, but I think we have accepted that with this new flow, so I think this is now invalid.

What do you think @kumar303 / @pwalm / @jvillalobos?

**Comment by jvillalobos** [comment]
If you wrote a rating with a review and you want to only keep the rating, the way to do that is to delete the review and then rate again? If that's what's being asked, I'm okay with it. I don't expect that to be a common use case. /cc @atsay

**Comment by kumar303** [comment]
I re-read this bug report and I think the new UI addresses it in a straight forward way without confusion. In addition to https://github.com/mozilla/addons-frontend/issues/4367#issuecomment-425201649 I'll add that if you delete the text in your review while editing then you won't even be able to submit the form. This seems like the right thing to do.

The button is disabled:

<img width="343" alt="screenshot 2018-09-27 16 51 40" src="https://user-images.githubusercontent.com/55398/46176608-a6c9b800-c275-11e8-9f50-cc42fd23164f.png">
