### ISSUE TITLE
"Unexpected error" banner displayed if page is refreshed before content is loaded

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4399]
Steps to reproduce:
1.Open AMO
2.Open any page (ie. open a category or a detail page)
3.Immediately (before content of page is loaded) press Refresh button

Expected results:
Page is refreshed without any problem

Actual results:
"Unexpected error" red banner is displayed for a second (until page content is displayed after refresh)

NOTES:
Reproducible on all servers

Please see video for this bug : 
![unexpectederror](https://user-images.githubusercontent.com/1583842/36271870-8872c66e-1288-11e8-8e9b-a107b5174fa4.gif)

**Comment by kumar303** [comment]
Oh, sorry, I didn't realize it on IRC but this is actually expected behavior.

When you refresh the page, it aborts the current request which causes `TypeError: NetworkError when attempting to fetch resource.` The site is telling you that an unexpected network error occurred -- it was unexpected that the request got aborted. As you point out, this only happens if the user refreshes at precisely the right moment. I think it would be an uncommon usage pattern.

I can see how maybe the message would be confusing but the site is actually reporting a real error that happened. I'm inclined to close it but if someone thinks we should change this behavior then please re-open.
