### ISSUE TITLE
Inconsistency for the number of users displayed by themes on the new front pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4415]
STR:
1. Load AMO prod and load Themes page then select any category.
2. Check for some themes the number of users displayed before you hover and click the theme.
3. Observe the number of users from the detail page.

Expected results:
Both pages display the same number of users.

Actual results:
The number of users from categories is different than the number displayed in the detail page.

Notes:
This issue is also reproducible for themes displayed on AMO prod's homepage or in search results using FF58 (Win10).
This issue is not reproducible for Extensions or with classic view that displays the daily user.

![number of users](https://user-images.githubusercontent.com/33448286/36414204-2260fb84-162a-11e8-9029-0b1ed08a91b7.gif)

**Comment by tsl143** [comment]
This is because of different `average_daily_user` numbers in the API response
Example- 
Listing API 
`https://addons.mozilla.org/api/v3/addons/search/?app=firefox&appversion=58.0&featured=true&page_size=4&sort=random&type=persona&lang=en-US&wrap_outgoing_links=true` 
shows `average_daily_user` as `41`
<img width="890" alt="screen shot 2018-03-03 at 9 27 47 pm" src="https://user-images.githubusercontent.com/5318732/36936321-ec5d0fa6-1f29-11e8-8684-2782c1cfee29.png">

But fetch Addon API 
`https://addons.mozilla.org/api/v3/addons/addon/siamese-cat-with-blue-eyes/`
show `average_daily_user` as `50`
<img width="827" alt="screen shot 2018-03-03 at 9 27 31 pm" src="https://user-images.githubusercontent.com/5318732/36936335-0df3b67e-1f2a-11e8-9f33-83273c8e6b93.png">

**Note** - This doesn't happen with all themes.

**Comment by tofumatt** [comment]
Again, hate to pass the buck, but is it possible the API results for search results aren't as up-to-date here as detail results @diox? We aren't doing anything with the data here so it doesn't seem like a front-end issue.

**Comment by diox** [comment]
It's an API issue yes, looks like it missed a reindex.
