### ISSUE TITLE
March 1 homepage content programming update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#4419]
For the **1 March** push, please update homepage content in accord with what's outlined here:

https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#

@EnTeQuAk @diox @muffinresearch

**Comment by bobsilverberg** [comment]
I'll take this. It'll be nice to work on something that is actually as simple as it sounds. :-P

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified the new layout on AMO dev with FF58 (|Win10).
The last three collections from Customize the way Firefox works with extensions. Are you interested in… display a Page not found error in dev. Couldn't check to see if they have an equivalent on AMO dev  because of https://github.com/mozilla/addons-server/issues/7448, collection search is not working right now.

**Comment by ioanarusiczki** [comment]
@bobsilverberg As far as I remember the collections were available. Well, thanks, I think it's fine now. 
I'll mark this as verified on AMO dev with FF58 (Win10).
