### ISSUE TITLE
The screenshot previews for rejected or disabled static theme versions should not be displayed on listed pages 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4425]
STR:
1. Load AMO dev and from Dev Hub submit a static theme (I used the theme wizard).
2. From Edit information page click the Listed Review Page and reject the first version.
3. Submit a second version for the theme and approve it this time.
4. From Edit information page click on View Listing.
5. Observe the screenshot section.

Expected results:
Only the screenshot of the approved version is displayed.

Actual results:
The rejected and the approved version are both displayed.

Notes:
This issue is also reproducible for static theme versions that were automatically disabled because they were not reviewed.
Also reproducible with the classic view.
This issue is reproducible on AMO dev with FF58 (Win10).

![rejected previews](https://user-images.githubusercontent.com/33448286/36485487-049d600a-1725-11e8-96a0-a72bdd33e52a.gif)

**Comment by tofumatt** [comment]
@diox @eviljeff Seems like the API is sending down screenshots it shouldn't be here, as I'd think we should only be getting approved screenshots.

**Comment by eviljeff** [comment]
At the moment there is no special support for static themes in the API, and nothing that tries to disable/enable screenshots based on status. So the behaviour reported is expected for now, until more stuff is added.

**Comment by tofumatt** [comment]
Ah, okay. It’s expected but not intended though, right? I guess: should we keep this around as a bug?

**Comment by eviljeff** [comment]
It's not intended. But Frontend will need to know how to display static themes anyway. Also, previews disabled versions shouldn't be exposed at all but I'm not sure if previews for older, approved, versions should be available or not from the API (I'm thinking they should be, in which case the right one should be displayed)

**Comment by eviljeff** [comment]
We're going to make a few changes to fix this on the addon-server side:
 - https://github.com/mozilla/addons-server/issues/7752 creates per-version Preview objects instead of per-addon
- https://github.com/mozilla/addons-server/issues/6804 will expose these in the API
- https://github.com/mozilla/addons-server/issues/7756 will delete Previews when the version is deleted, though you don't need to worry about this one - 6804 will only expose valid previews anyway.

On the addons-frontend side, once https://github.com/mozilla/addons-server/issues/6804 lands you'll need to make an adjustment to get the preview from Addon.current_version.previews rather than Addon.previews.  Right now there will only be max one preview per version but that may change in the future so it'll be a list like now.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/6804 made the API expose the previews through the `previews` property on the addon transparently, so there are no changes to make on the frontend side.

**Comment by ioanarusiczki** [comment]
I filed https://github.com/mozilla/addons-server/issues/7866 and https://github.com/mozilla/addons-server/issues/7868 for what I've noticed during testing. 
This issue is verified fixed on AMO dev with FF59 (Win10).
