### ISSUE TITLE
Extension page dead link

### ISSUE THREAD

**Issue by JosephSamela** [mozilla/addons-frontend#4454]
### What happened?
I submitted an extension to AMO. I clicked the link it worked. I logged out. I clicked the link again and received "Sorry, but we can't find anything at the address you entered." I logged back in again and the link works correctly bringing me to the extension AMO page.
https://addons.mozilla.org/en-US/firefox/addon/colorize-tabs/

### What did you expect to happen?
I expected to link to work regardless of who's logged in. For example if I send this link to someone they should be able to click it and install my extension.

### Anything else we should know?
Logged in
![screenshot 2018-02-25 at 10 20 11 pm](https://user-images.githubusercontent.com/16111451/36652019-1a82990a-1a7a-11e8-95c9-873daa5a83d1.png)

Not logged in
![screenshot 2018-02-25 at 10 20 27 pm](https://user-images.githubusercontent.com/16111451/36652020-1a931b7c-1a7a-11e8-9387-8932c5b61222.png)

**Comment by ioanarusiczki** [comment]
I made some exploratory testing around this issue on AMO dev and AMO stage using FF58 (Win10) and I noticed that it is reproducible before the extensions are auto approved or manually approved. 
STR: I submitted an add-on and before the auto approval I copied the detail's page link, opened a new profile where I've never been logged with my AMO credentials and pasted it in the browser. The issue is also reproducible with language packs or themes. 

![page not found](https://user-images.githubusercontent.com/33448286/36677909-0fb8fc3c-1b18-11e8-8155-f4598eec6cee.png)

**Comment by JosephSamela** [comment]
To follow-up, I noted the dead link _after_ the extension was approved. I received the link in an automated confirmation email. Then I attempted to access the page from another machine and observed the issue above. Thanks for looking into this!

![image](https://user-images.githubusercontent.com/16111451/36679170-907f23ec-1ae0-11e8-80b4-6262609cd486.png)

**Comment by tofumatt** [comment]
Is the page still unavailable? This is not great but I'm wondering if it's simply a caching/approval issue. I don't think it's a frontend bug at any rate as it isn't the part of the app that sets the state of the add-on–we're just rendering what the API sends.

I'm going to close this for now as I think it might have been a timing issue, but if there are clear steps to reproduce it we can re-open the issue.
