### ISSUE TITLE
Show multiple authors in search results

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4461]
### Describe the problem and steps to reproduce it:

* Create an add-on with multiple listed authors
* Search for the name of the add-on

### What happened?

The search result for the add-on only lists the first author.

Compare the search results:

<img width="846" alt="screenshot 2018-02-26 14 57 23" src="https://user-images.githubusercontent.com/55398/36695055-c6933980-1b05-11e8-8092-30524c6a7310.png">

... to the detail listing:

<img width="523" alt="screenshot 2018-02-26 14 58 22" src="https://user-images.githubusercontent.com/55398/36695065-cb702652-1b05-11e8-9838-a9225a7a4200.png">

### What did you expect to happen?

The search results should list all authors.

**Comment by tofumatt** [comment]
Originally I think this was a deliberate decision because there’s limited real estate to show multiple authors (especially on mobile).

If you look at this on mobile there isn’t much room to expand I think, so maybe this is working as intended. Admittedly it’s a bit weird, maybe it should be “first author name + 2 others” or something.

**Comment by kumar303** [comment]
We could also use an ellipsis

**Comment by kumar303** [comment]
I'll add `needs:ux` for thinking about small screens

**Comment by tofumatt** [comment]
That’s a much better idea :-) We could even just put them all in and use overflow with an ellipsis if it DID exceed the width we assign based on screen size.
