### ISSUE TITLE
Can't search for search plugins at /firefox/search/

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#4496]
Search plugins type addons don't appear to have been fully implemented. There is no selection in the dropdown to search for them via https://addons.mozilla.org/de/firefox/search/ though https://addons.mozilla.org/de/firefox/search/?q=OpenThesaurus&type=search does work.  Also https://addons.mozilla.org/de/firefox/search-tools/ still goes to a legacy page.

**Comment by eviljeff** [comment]
This isn't really priority: p2 but it's deserves more attention that getting dumped in the soup of all other p3 issues.

**Comment by eviljeff** [comment]
origially logged https://github.com/mozilla/addons-server/issues/7681

**Comment by bobsilverberg** [comment]
I'd be happy to take this on. Are there more specific requirements, or is it just that they don't appear as a type in the dropdown at https://addons.mozilla.org/en-US/firefox/search/? 

@jvillalobos Do we have a stated direction for supporting them in the future, and to what extent we want to support them?

**Comment by eviljeff** [comment]
They don't appear as a type in the dropdown and the landing page for search plugins isn't implemented.  This might need splitting into different issues - I would have thought there would already be an issue for implementing the remaining type of add-on though.

**Comment by jvillalobos** [comment]
The Firefox settings page points to `/search-engines/`, which redirects to `/search/?type=search`. That should be fixed in the header menu.

I've been discussing the future of search engines as an add-on type with a few people involved in search, but we don't have clear steps forward at the moment. The general feeling is that we won't have them on AMO for much longer, but the decision hasn't been finalized.

I don't object to adding search engines to the filter. However, we need to figure out how that will work with https://github.com/mozilla/addons-frontend/issues/3942, particularly on mobile where space is limited.

**Comment by jvillalobos** [comment]
Whoops, wrong button.

**Comment by tsl143** [comment]
I am not sure, but what I understood is all we need is to do is add an entry `search` in `addon type` select box, is it correct?

**Comment by tsl143** [comment]
Something like this?
![searchplugin](https://user-images.githubusercontent.com/5318732/37505795-a6f28490-290c-11e8-9b7e-e5050e65a359.gif)

**Comment by eviljeff** [comment]
@tsl143 - it's two things: the search plugin type in the select box, and changing the link in the "More ..." menu

**Comment by vcarciu** [comment]
Verified as fixed : 
![searchengines](https://user-images.githubusercontent.com/1583842/38244030-f95114b6-3741-11e8-9c4f-0cd1e62cbe4d.gif)
