### ISSUE TITLE
API helpers for creating a collection

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4504]
We need API helpers to facilitate editing a collection #4003

For QA: please check for regressions in any of the existing collection pages and in particular with the "Edit a collection" feature.

**Comment by bobsilverberg** [comment]
I'm going to try using `invariant` (see issue #1461) for the code I'm writing for this.

**Comment by AlexandraMoga** [comment]
I've looked for regressions around collections with focus on 'Edit collection' feature. and there were no issues observed.
@bobsilverberg I have one question regarding collection IDs which were enabled in collections API ([#7529](https://github.com/mozilla/addons-server/issues/7529)). Should this also be possible on the frontend? I've tried using IDs instead of slugs for certain operations but they did not work (collection page is not loading).

**Comment by bobsilverberg** [comment]
@AlexandraMoga I don't believe any of the front-end code has changed to allow one to access a collection by its ID, even though the API now supports it, so I believe what you're seeing is expected. Maybe @tofumatt or @kumar303 could confirm that?

**Comment by AlexandraMoga** [comment]
@bobsilverberg I will go by your opinion and will mark this as verified fixed, since no regressions have been found around collections.
@kumar303 if you think there can be a problem with how the frontend is currently handling collection IDs, I could file a new issue.
