### ISSUE TITLE
Localizers adding locales not in the configuration

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#455]
@mathjazz I noticed that there was a commit from pontoon adding locales that aren't in our configuration.

It's great to have new locales but as a result of them not being added to the config those locales won't be used until they are setup.

Is there way to stop new files being added via Pontoon until they're setup from this end? If new locales aren't added correctly they won't work - clearly we need some docs for that - but disallowing it on the pontoon end if possible would also help make sure things are done in the right order.

**Comment by muffinresearch** [comment]
We can additionally fail our tests this end if we see new locale directories that don't match the config.

**Comment by mathjazz** [comment]
@muffinresearch Actually we add those files manually for now, so it's easy to stop them from coming. ;)

Is this breaking something on your end or is it just that you're afraid more such locales will appear in the repository unnoticed and they will never end up on production?

**Comment by muffinresearch** [comment]
@mathjazz They need to be added via the config or there's no guarantees they will work properly or will ever make it to production.

Also I see the search.po files have been totally deleted. What's the reason for that?

**Comment by mathjazz** [comment]
> @mathjazz They need to be added via the config or there's no guarantees they will work properly or will ever make it to production.

OK. Many other projects have similar configs as well, so I wonder if we could go ahead and add new locales upon request and then you could catch those with tests and add them to config?

> Also I see the search.po files have been totally deleted. What's the reason for that?

Yes, I removed those because @andymckay says they aren't supposed to be translated yet:
https://groups.google.com/d/msg/mozilla.dev.l10n.web/FivbS8W92e8/YYm-zRynCAAJ

**Comment by muffinresearch** [comment]
Can we handle changes to remove or add flies through issues here in future as that will ensure we're all on the same page. I'm not following those threads.

Whilst we might not need the search to be localized having it extracted is useful for being able to know what multiple localized apps in this repo will look like since this repo is not just about the discovery pane. Not having them there makes building the tools needed to deal with that scenario much harder and I'll need to add them back to test locale merging.

**Comment by mathjazz** [comment]
> Can we handle changes to remove or add flies through issues here in future as that will ensure we're all on the same page. I'm not following those threads.

Absolutely, sorry I acted without notice. I wanted to prevent localizers from translating these files in vain. I'll make sure to report any such removals in the future, but I hope they won't be necessary. I'll also communicate with project managers to file issues when they add new locales.

> Whilst we might not need the search to be localized having it extracted is useful for being able to know what multiple localized apps in this repo will look like since this repo is not just about the discovery pane. Not having them there makes building the tools needed to deal with that scenario much harder and I'll need to add them back to test locale merging.

Pontoon will automatically detect all l10n files it supports and show them in the translation interface. It does that by design. We look at the repository as the ultimate source of truth of what's localizable and localized. Which means localizable and non-localizable files will need to live in different places.

**Comment by muffinresearch** [comment]
@mathjazz excellent, thanks. I'll see if I can just revert the commit locally for my own testing to add the locale scripts so we can avoid noise in Pontoon of adding the search.po files back. I'll file a bug to remove the gettext calls from the search app.
