### ISSUE TITLE
AMO homepage is not loading on stage

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4552]
STR:

1. Access AMO homepage on stage (https://addons.allizom.org/en-US/firefox/)

Actual result:
Homepage content is only partially loading

Expected result:
AMO homepage is fully loaded

Notes: 
- it seems that collection 'Good time tabs' doesn't exist on stage and it's generating a 404; this might be the root of the isue - https://addons.allizom.org/api/v3/accounts/account/mozilla/collections/good-time-tabs/addons/
- reproduced on AMO-satge with FF58 Win10x64

![image](https://user-images.githubusercontent.com/31961530/37387495-47375f06-2765-11e8-83ec-de23d8bf8fec.png)

**Comment by bobsilverberg** [comment]
Thanks @AlexandraMoga. As we've seen before, and as you've noticed, this is because there is a collection missing on stage. The solution to this is to recreate the collection. The steps to do it are:

1. Log in to the site.
2. Switch to the Classic Desktop site.
3. Go to https://addons.allizom.org/en-US/firefox/collections/add.
4. Create a collection with the required name, and save it.
5. Click on "Edit this collection".
6. Add "addons-team@mozilla.com" as a contributor and save the collection.
7. From the "Contributors & More" tab, click the link beside addons-team@mozilla.com that says "Make owner" and then save the collection.

I have done this to create the "good-time-tabs" collection, but it looks like at least the "wikipedia-boosters" collection is also missing. Are you able to follow the above steps to create any collections that are missing, or do you need a developer to do that? If the former, this is something that you could do yourself, as part of the verification process, if that's acceptable to you.

**Comment by bobsilverberg** [comment]
Just to reiterate what I said in https://github.com/mozilla/addons-frontend/issues/4552#issuecomment-373010781, this doesn't actually prevent QA from testing stage, as whoever is testing could create the missing collections themselves, by following the instructions I provided.

**Comment by AlexandraMoga** [comment]
@bobsilverberg  thanks for providing the above steps.
 I've added the missing collections -   "wikipedia-boosters"  and "trending-add-ons" - and stage homepage is now functional.

If we are going to see similar issues in the future, I think QA will be able to fix them without your intervention, as long as these steps are applicable. It will save a lot of time.

**Comment by bobsilverberg** [comment]
That's great, thanks @AlexandraMoga!
