### ISSUE TITLE
Deselecting a category during submission, will automatically check the "My add-on doesn't fit into any of the categories" checkbox

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4565]
Steps to reproduce:
1.Start a new webextension submission in AMO Stage
2.After validation, when selecting categories, select a category, then deselect it 

Expected results:
The category is not selected anymore and no other category is selected

Actual results:
The " My add-on doesn't fit into any of the categories" is selected automatically

NOTES:
Reproducible on all servers

Please see video for this issue:
![deselect](https://user-images.githubusercontent.com/1583842/37466999-c0f72166-2867-11e8-9fde-424a0f5be1e0.gif)

**Comment by tofumatt** [comment]
1. This is not an addons-frontend issue as the developer hub is on the old site. This should be filed on addons-server, as should all bugs with that old-style look 😄. That *said*...

2. This seems entirely intentional: if the user says they have no categories, it selects "my add-ons doesn't fit into any of these categories". It's weird UX and could be improved in a lot of ways, but I think this is intended behaviour.
