### ISSUE TITLE
Delete an add-on from a collection

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4577]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

A user should be able to:

- Sign in
- View an existing collection that they created
- Edit the collection (which opens the overlay)
- Delete an add-on from the collection

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10).
The items from a collection can be removed by clicking the Remove button.
@bobsilverberg If an item is added and then the user removes something from the list the message stays permanent but that is because of https://github.com/mozilla/addons-frontend/issues/5011 which is still open.
Also "remove" is permanent once it is clicked. If the user wishes to undo the action by clicking "Cancel" that won't work.

**Comment by bobsilverberg** [comment]
> If an item is added and then the user removes something from the list the message stays permanent but that is because of #5011 which is still open.

Yes, #5011 should resolve that issue.

> Also "remove" is permanent once it is clicked. If the user wishes to undo the action by clicking "Cancel" that won't work.

Correct, that is expected.
