### ISSUE TITLE
Estonian ID Card PKCS11 module loader 

### ISSUE THREAD

**Issue by mliiv** [mozilla/addons-frontend#4589]
### Describe the problem and steps to reproduce it:

Estonian ID Card PKCS11 module loader - link in google exists but empty when opened.

### Anything else we should know?

Cannot find the extension anywhere.

**Comment by tofumatt** [comment]
Closing due to lack of information. It sounds like the extension you're looking for was removed, which makes sense because I recall this add-on being incompatible with the WebExtensions API.

Please add information to your issue including the error you encountered, a URL (if applicable), and steps to reproduce.
