### ISSUE TITLE
Add an add-on to a collection from the edit screen

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4590]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

A user should be able to:

- Sign in
- View an existing collection that they created
- Click *Edit collection* to open the editor overlay
- Type the name of a new add-on in the search box and select a result from the list to add it to the collection

**Comment by bobsilverberg** [comment]
I believe we need some UX input on this, and also issue #4502 (create a new collection with add-ons). The mocks show a form overlay, with an area at the bottom for managing the add-ons in a collection, for example:

<img width="554" alt="screenshot 2018-04-11 10 41 02" src="https://user-images.githubusercontent.com/142755/38623934-e094b430-3d74-11e8-8897-e91135a018e1.png">

But the edit form has now been implemented not as an overlay, but rather by replacing the detail card with an edit form, like this:

<img width="1386" alt="screenshot 2018-04-11 10 42 25" src="https://user-images.githubusercontent.com/142755/38624007-0c3ad506-3d75-11e8-940a-5d2d95df87b2.png">

With this configuration I don't think it makes sense to also have a list of collection add-ons at the bottom of the form, but rather have them managed on the right-hand side of the screen. Perhaps the list of add-ons that appears on the right when viewing a collection could change to an editable list of add-ons (still on the right) when a user switches to edit mode. That list would include buttons to remove an add-on from the collection and something that would allow a user to add notes to an add-on in the collection.

@pwalm Would it be possible to get new mockups of this, or whatever you think would work for the new version of the edit and create screens? I think the mockups related to editing and creating a collection in Sketch are no longer directly applicable due to the change to the edit screen.

**Comment by pwalm** [comment]
How's this?
<img width="1546" alt="screen shot 2018-04-11 at 10 45 27 am" src="https://user-images.githubusercontent.com/6797635/38633766-7eda9ce0-3d75-11e8-90bf-b7903d795c3d.png">

**Comment by bobsilverberg** [comment]
Thanks @pwalm, that looks great! I think we also need a button to save the comment.

**Comment by bobsilverberg** [comment]
@pwalm Another question: Would you say that choosing an add-on from the "Find add-ons" select box would immediately add it to the collection, or would that just make it appear on the right in a "pending" state, and it (and any other newly added add-ons) wouldn't be added to the collection until the "Save collection" button was clicked?

**Comment by pwalm** [comment]
- Choosing would immediately add to the collection.
- "Save collection" is like "Save and exit," so the user doesn't have to save each time they add an extension. Maybe it should just get changed to that, I'll ask Meridel.

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev with FF59 (Win10) and Android 8.0
1. The search seems to work alright, a list of mixed themes and extensions are displayed on the right and for now their order cannot be edited. Also remove is not functional (these are upcoming implementations).
2. I filed https://github.com/mozilla/addons-frontend/issues/4829 
3. I'll update this if any other issues are found while testing.
