### ISSUE TITLE
29 March homepage content programming update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#4603]
Please find all homepage programming changes reflected in this doc:

https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#

Thank you!

**Comment by muffinresearch** [comment]
@devaneymoz no one saw this come in so it's not going to make the 29th push.

In future if you could give time-sensitive issues a `priority: p1` label (which means next release) and additionally make sure someone in the team is highlighted about it, it'll be more visible since we review p1s and p2s on a weekly basis.

**Comment by bobsilverberg** [comment]
I was on PTO last week or I likley would have jumped on this, but in the future please feel free to tag me directly on these, @devaneymoz.

**Comment by devaneymoz** [comment]
I usually do tag people when I file these, don't know why I didn't this time. 

Do I need to file a new issue so this can make the following release on **5 April**, or will this one suffice?

**Comment by tofumatt** [comment]
This one is fine, we’ll just move the date up.

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev with FF59(Win10 and Android 8.0.0). 
I'll add the verified fixed label after it is fully verified in production.

**Comment by vcarciu** [comment]
Marking as verified since I verified them in production too.
