### ISSUE TITLE
Abstract out "add-ons by authors" card to use in UserProfile

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4621]
We currently don't have a reusable card that can show an `AddonsCard` based on a username or list or usernames. I have one nearly ready that we can use to easily add cards to UserProfile for #4280 and #4281.

**Comment by tofumatt** [comment]
This ended up being a lot more work than I thought but it's ready now 😄

**Comment by tofumatt** [comment]
For QA:

Make sure the "More add-ons by this user" card on an add-on detail page and theme detail page continue to work as they did before this patch.

**Comment by vcarciu** [comment]
@tofumatt : We tested around "More add-ons by this user" section and we observed the next issues : 

1. If a theme developer submitted more than 6 themes , only 3 themes by this author are displayed on -dev and stage instead of 6 like in prod:
![morebyauthornumber](https://user-images.githubusercontent.com/1583842/38316761-1e333c30-3834-11e8-97c4-7006b8a1ed01.gif)

2.Same issue for extensions, but in this case we will display 4 add-ons in -dev and stage and 6 in production: 
![morebyauthornumberextensions](https://user-images.githubusercontent.com/1583842/38317399-ad26d0f4-3835-11e8-972c-472eb52448f8.gif)

3. If a theme is opened from developer hub, then the themes displayed in "More add-ons by this user" section will have a different alignment : 
![themes by author](https://user-images.githubusercontent.com/1583842/38317933-dd4e1e4e-3836-11e8-8d33-5874d9cd545e.gif)

**Comment by vcarciu** [comment]
And another issue (nor reproducible in prod) : 
![name](https://user-images.githubusercontent.com/1583842/38318929-3f09fa20-3839-11e8-9a18-c37a9e766b1e.png)

**Comment by vcarciu** [comment]
The latest issue is caused by the fact that we are using both display names and user names which can be different for same developer.

**Comment by tofumatt** [comment]
> The latest issue is caused by the fact that we are using both display names and user names which can be different for same developer.

Definitely a legit issue caused by this but the fix is a bit more effort and I think worth doing in a separate patch. I've filed: #4742.

**Comment by vcarciu** [comment]
@tofumatt : sure, I logged https://github.com/mozilla/addons-frontend/issues/4744

**Comment by vcarciu** [comment]
Since the issue related to number of addons and themes displayed in "More add-ons by this user" was solved and the other issues were logged as separate bugs, I will mark this one as verified.
