### ISSUE TITLE
Portrait orientend thumbnails look squashed on the user info's card 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4629]
As a followup for https://github.com/mozilla/addons-frontend/issues/4598

STR:
1. Load AMO dev and go to Edit profile.
2. Choose a .png sample with portrait orientation (.jpg won't work for now because of #4596 ) 
3. Click update account and then go to My Profile.

Expected result:
The profile picture thumbnail looks alright.

Actual result:
The profile picture thumbnail is squashed.

Notes:
This issue is reproducible on AMO dev with FF59 (Win10).

small .png sample with 75 KB with dimensions 240x320

![the portrait view](https://user-images.githubusercontent.com/33448286/37823169-58de2720-2e91-11e8-954c-5d2867baa0d1.gif)

**Comment by tsl143** [comment]
@tofumatt , right now we have `width 100%` and `height: auto`, due to which if the height of image is greater than `64px` its cropped from bottom (not squashed). Isn't this desired behavior?

**Comment by tofumatt** [comment]
The issue describes the image as squashed so that's what I assumed it was. If that's incorrect and the image is cropped I personally think that's fine. If the image is very tall/wide and it's cropped one way I think that's better than a bunch of whitespace in a tiny version of the image.

If the image is cropped I think this can be closed as a won't fix because I think it's better than the alternative. Eventually image upload should allow a crop but that's another issue.

**Comment by ioanarusiczki** [comment]
@tofumatt Ok, I understand that heights above 64px will be cropped. 

You said
> Eventually image upload should allow a crop but that's another issue.

Should I file an issue that when the image is selected for upload the edit profile page should display it cropped (as the correct preview of the thumbnail) ?

**Comment by tofumatt** [comment]
That page on addons server is going away so I think it’s fine to just leave it alone.

- Matt (Sent from mobile)
