### ISSUE TITLE
Form validations are not displaying correctly on the edit collection screen

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4650]
This is a follow-up to #4623.

STR:

1. sign in
2. create a collection
3. view the collection
4. click Edit collection underneath the collection info
5. Blank out both the collection name and slug
6. Click save
7. Observe a validation error for collection name
8. Enter a name but leave the slug blank

Expected:

The validation error for collection name should disappear and one for slug should appear.

Actual:

The validation for collection name remains, and none appears for slug. Note that if you start typing a slug at that point the extra error appears.

Note to self: It seems there's a problem with clearing the errors at the appropriate time, as well as a problem with not re-rendering the form when needed, as the rendering seems to be delayed.

**Comment by AlexandraMoga** [comment]
@bobsilverberg not sure if you observed this scenario as well, but I'm sure it has the same root cause:

1. blank out the collection slug
2. click on Save Collection to generate the slug error
3. delete the collection name
4. write a new slug for your collection
5. click on Save Collection

**Actual:** the error related to the collection slug is still the one displayed
**Expected:** an error pointing to the empty collection name should be displayed

![col error](https://user-images.githubusercontent.com/31961530/38031375-b54dd83c-32a3-11e8-83cb-ea634d2a87da.gif)

**Comment by bobsilverberg** [comment]
Thanks @AlexandraMoga, yes I noticed that case as well. I just didn't bother to list it out. I agree that it is likely the same root cause.

**Comment by bobsilverberg** [comment]
The "validation" for collection name has been addressed differently via PR #4698 which ensures that the form cannot be submitted without a collection name. As well, https://github.com/mozilla/addons-server/issues/7936 has been opened to update the API to prevent a collection from being created which has a name which only contains spaces.

I suggest we take the same approach for collection slug, and disable the Save button if it is blank. That will eliminate the cases behind this issue, rendering it invalid.

**Comment by bobsilverberg** [comment]
This can be closed. There are no longer any form validations for this form.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF59(Win10). The Collection name and Collection slug are mandatory fields. The issue is no longer reproducible.
