### ISSUE TITLE
A collection slug consisting only of numbers will generate a 404 for the collection details page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4653]
Follow up for #4623 

STR:
1, Log in to AMO dev and select 'View My Collections' from the user menu
2. Choose a collection to view its details page
3. Click on Edit collection underneath the collection info card
4. Edit the collection slug by entering only numbers
5. Click on Save Collection

Actual result:
a 404 error is received when a collection slug consists only of numbers

Expected result:
A collection with a slug consisting only of numbers should be correctly rendered

Notes:
- the collection is displayed when looking at the legacy site 
- reproduced on AMO-dev, with FF59, WIn10x64

![col 404](https://user-images.githubusercontent.com/31961530/38032479-6f420ac2-32a6-11e8-8a1d-1ce1d8838bda.gif)

**Comment by muffinresearch** [comment]
Needs investigation to diagnose what's happening here.

**Comment by eviljeff** [comment]
Entirely numeric slugs aren't allowed - either for collections or addons - because there's no way to differentiate an ID from a slug in a url.  (This was more a policy of consistency until #7529 added the ability to refer to collections by ID as well as slug).

It appears, from @tsl143's comment, that the slug isn't being changed to `122`, and the existing slug returned in the response.  This is correct.  What's not correct (afaik) is the API not highlighting that the slug value is invalid so is being ignored.

**Comment by eviljeff** [comment]
Oh, while what I said about numeric slugs is correct, @tsl143's example isn't the same as @AlexandraMoga's - it looks like @tsl143 is trying to change his _favorites_ collection, which is special (right now anyway), and will be reset to be called `favorites`, regardless of what the slug is changed to.  

Problem for frontend is we don't expose that it's a "special" collection in the API because special collections are deprecated - but we can't remove until legacy frontend stops expecting special collections 🙄 

So @tsl143 has highlighted another bug, and this issue needs more diagnosis.

**Comment by tsl143** [comment]
@eviljeff , so do we need to put a check at frontend, disallowing only numeric slug?

**Comment by tsl143** [comment]
@eviljeff , If you return error from API, it will aleady be sorted at frontend, so can we close this bug from addons-frontend and file a bug at addons-server?

**Comment by eviljeff** [comment]
@tsl143 there should be a bug on addons-server, yep.  Not sure exactly what's happening though.

on addons-frontend there are things that _could_ be changed, I guess.  But I suppose this issue can be closed, at least until the API is functioning correctly.

**Comment by AlexandraMoga** [comment]
@eviljeff  here is an example: https://addons-dev.allizom.org/en-US/firefox/collections/AlexandraMoga1/1234/
Is there a server issue opened already to track this?

**Comment by AlexandraMoga** [comment]
This is verified via https://github.com/mozilla/addons-server/issues/8070
