### ISSUE TITLE
CRYPTO TAB LINK BROKEN

### ISSUE THREAD

**Issue by Lonkosi** [mozilla/addons-frontend#4669]
### Describe the problem and steps to reproduce it:

I want to install Cryptotab for firefox by clicking on the link https://addons.mozilla.org/en-US/firefox/addon/cryptotab/ from the page https://getcryptotab.com/en/
### What happened?
Upon clicking the link i get the following error
Page not found

Sorry, but we can't find anything at the address you entered.
### What did you expect to happen?
I was expecting to install the CryptoTab add-on
### Anything else we should know?

![image](https://user-images.githubusercontent.com/37927575/38132450-6651d292-340b-11e8-8ae4-06671dd30606.png)

![image](https://user-images.githubusercontent.com/37927575/38132482-8bf8f7a0-340b-11e8-9a65-755115a6ba8a.png)

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on.

If you're having an issue with an add-on please contact the developer directly; you will need to contact the author on their web site because their add-on has been unlisted. I'm guessing it might be because crypto-mining extensions are usually sketchy, but I'm just guessing. 😄
