### ISSUE TITLE
Special case the Firefox download link for Facebook Container

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4737]
Refiled from https://bugzilla.mozilla.org/show_bug.cgi?id=1451542

>The Facebook Container team would like to change the link that takes you to the Firefox install page to instead take you to the moz.org landing page, https://www.mozilla.org/en-US/firefox/facebookcontainer/, for the funnel cake set up for Facebook Container.

>For context, here's a summary of the discussion that led to this request:

>If you get to the Facebook Container AMO page, it will prompt you to download Firefox to install the add-on.

>It would be great for people who go straight to the AMO page from browsers other than Firefox, if we could link to the landing page first (from green download firefox link) and then have users go through the funnel cake from there. Need this change by Thursday, April 4th.

So in a nutshell the Download Firefox link seen by a non-firefox user on https://addons.mozilla.org/en-US/firefox/addon/facebook-container/ should be special-cased to link to  https://www.mozilla.org/firefox/facebookcontainer/ (Note I removed the locale from the latter so that Mozilla.org can handle the locale itself.

<img width="1459" alt="facebook_container_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/38363355-45173322-38cc-11e8-8aa3-5a8f0430505e.png">

We'll need to see how easy it is to special-case this change. The request was to have it ready for today's push (5th April). If it's a minimal change then we can look to cherry-pick it, but the first step is to investigate and see how viable it is.

**Comment by tofumatt** [comment]
From a very quick look it seems like a kinda hacky, special-case fix could be made relatively easily: we *do* have access to the `addon` object in question at the point we render that component. We could simply pass it the Facebook container ID in production and special-case the URL it links to. We could even change the text then too, for what it's worth.

To ship this quickly we'd need to special-case it and it'd be a bit hacky–also we can't really test it on stage as the add-on IDs aren't consistent. Well, if that add-on has the same ID on stage we can test, otherwise we just have to trust it works.

If that all sounds okay we could rush this out today. The actual PR would take < one hour to cook up.

**Comment by tofumatt** [comment]
QA steps here:

1. Visit https://addons.mozilla.org/en-US/firefox/addon/facebook-container/ in a non-Firefox browser
2. Check that the "Download Firefox" link appears in the green notice bar and make sure the link points to https://www.mozilla.org/en-US/firefox/facebookcontainer/ instead of https://www.mozilla.org/en-US/firefox/new/

Other add-ons in non-Firefox browsers should still point to https://www.mozilla.org/en-US/firefox/new/

**Comment by muffinresearch** [comment]
This change is now live on -dev at https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/

**Comment by muffinresearch** [comment]
This change is now live on stage at https://addons.allizom.org/en-US/firefox/addon/facebook-container/

**Comment by vcarciu** [comment]
Verified as fixed in Chrome and Edge : 
![facebookcontainer](https://user-images.githubusercontent.com/1583842/38376592-9715238e-3901-11e8-8426-b3c777aa1762.gif)
