### ISSUE TITLE
Failur to add Cryptotab extension to my mozilla firefox browser

### ISSUE THREAD

**Issue by Luckybravia** [mozilla/addons-frontend#4751]
Mozilla firefox couldn't add the cryptotab extension

I needed to add a Cryptotab extension to mozilla firefox web browser but it failed.

I  expected that the Cryptotab extension be added to my mozilla firefox web browser with its icon showing among the tabs at the top right corner of the browser.

Please, allow getcryptotab.com to be added as an extension on the mozilla firefox web browser. Thanks!

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on.

If you're having an issue with an add-on please contact the developer directly; their contact info is on their site, but their add-on has been unlisted because of issues with review. It's up to them to update it, sorry about that!

**Comment by tofumatt** [comment]
Actually, looks like there is an installation problem with this add-on, which is now listed. Opening this up again...

**Comment by jvillalobos** [comment]
I think that's a separate issue. The add-on has an Awaiting Review state, so it isn't visible to the general public. I suppose we didn't account for that (mostly legacy) state, so the new front-end makes it appear as normally listed if you have sufficient permissions to see inactive listings. I'll file a separate issue for it.

**Comment by Kristofp** [comment]
Seems that the cryptotab extension is gone
