### ISSUE TITLE
In "Add to Collection" list, sort collections alphabetically by name

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4755]
When adding an add-on to a collection, the collection list is not sorted alphabetically, making it hard to find the right collection/scan the list. More info/originally filed at: https://github.com/mozilla/addons/issues/676

I think sorting the collections in the front-end by name is a good call.

**Comment by smayer97** [comment]
:-) Nice...Thx
Please keep in mind that this request is part of a suite of 4 features that work together to re-create the original functionality that was in the Add To Collection menu under the old design. Fixing this particular feature would be a good start.

Note that this particular feature above has a long history of being fixed, broken, fixed, broken, and finally fixed, under the old AMO front-end design, which I worked hard over years back and forth to make happen, only to have it removed with the new design 7 months after its final implementation (see link in originally filed issue #676 above).

I add the other 3 issues here for reference to not lose sight of them:

Add To Collection - Cannot search the list https://github.com/mozilla/addons/issues/677 
Add To Collection - No indicator showing which collection(s) the add-on already belongs to https://github.com/mozilla/addons/issues/678
Add To Collection - There is no link to open collection from list of collections https://github.com/mozilla/addons/issues/679

<PITCH> FYI, for those who work with collections, these 4 features are INVALUABLE...  I have over 120 collections I use to support many other users but for the past 2 years, since the Add To Collection menu has been removed, it has been extremely difficult (and many other users too). At the moment, without all 4 features, it is extremely painful and time consuming to even try, to the point that I have almost abandoned that effort. 

But the one thing that used to differentiate Firefox from Chrome and others, was the access to and management of Add-ons, which is what made Firefox such a huge attraction to many users. Please keep this in mind.<END PITCH>  ;-)

**Comment by smayer97** [comment]
P.S. Those other 3 Issues are probably misfiled under Add-ons and need to be moved to Addons-frontend.

**Comment by tofumatt** [comment]
@smayer97 You don't need to continually cross-reference the other issues; they are on our radar and we will triage them accordingly. 😄

We understand you'd like this feature, but I'm under the impression that power-users of the collections features are small in number. Rest assured, we are keeping these issues open and will discuss them, but we're a small team and we have to prioritise a basic feature-set first.

**Comment by smayer97** [comment]
Appreciate your the feedback. Not trying to be a nuisance. Just not sure how everything is cross-referenced for visibility so did not want for these to be lost in the shuffle. Thanks for your consideration.

**Comment by tofumatt** [comment]
No worries! I don’t want you to have to do more work than is needed either :-)

If your job is to file the issues then our job is to triage them. ;-)

**Comment by vcarciu** [comment]
Collections are now ordered : 
![collectionordered](https://user-images.githubusercontent.com/1583842/38617503-e2a834e2-3d9f-11e8-89d2-6d03790bf86e.gif)

**Comment by smayer97** [comment]
I look forward to seeing it deployed. :-D
