### ISSUE TITLE
Enhance the AutoSearchInput component to return addonIds

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4771]
This blocks #4590.

In order to add an add-on to a collection, we need the `addonId`, but currently the `AutoSearchInput` component only returns the `iconUrl`, `name` and `url` for the add-on.  This issue is to enhance the `SuggestionType` returned by `AutoSearchInput` to include the `addonId`.

**Comment by bobsilverberg** [comment]
For QA: This should not result in any changes to the site behaviour. Please just verify that nothing has regressed with the Search box at the top of the page:

<img width="358" alt="screenshot 2018-04-11 10 04 01" src="https://user-images.githubusercontent.com/142755/38621835-b67f5628-3d6f-11e8-86a5-3a81fe950562.png">

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev with FF59(Win10 and Android 8.0)
The Search in Collections - returns extensions instead of collections issue logged https://github.com/mozilla/addons-server/issues/7448 with a won't fix because new page is going to be implemented
Same for https://github.com/mozilla/addons-server/issues/7394
