### ISSUE TITLE
Content view for Collection missing link to show other collections by same creator.

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#4792]
### Describe the problem and steps to reproduce it:
Opening view of add-ons in collection give info about collection at the top but offers no link to see other collections by the same creator.

### What happened?
as above.

### What did you expect to happen?
To be able to click a link to pull up list of other collections by the same creator.

**Comment by jvillalobos** [comment]
This is by design. Collections are now meant to be private unless shared by the creator, so there's no way to discover collections unless there's a public link elsewhere.

**Comment by smayer97** [comment]
Why have they been made private? and how do you make a public link?

So is the plan to no longer be able to share and promote collections?

**Comment by smayer97** [comment]
just for cross-ref:
https://github.com/mozilla/addons-frontend/issues/4003

**Comment by smayer97** [comment]
Also, what does this mean for the Followers of Collections; tracking the #s, getting notifications when new add-ons are added, etc? Is this all going away too?

**Comment by jvillalobos** [comment]
> Why have they been made private? 

Collections are often a target for spammers, since they are trivial to create, have user-generated content, and are immediately published and browseable on the site. Additionally collections are a very complex feature that is secondary to AMO's purpose, and has bugs (including security issues) reported about them often. Greatly simplifying the feature was a requirement to keep it. The alternative would have been to drop it entirely.

> and how do you make a public link?

The URL to any new collection (or existing public collection) is accessible by any user. It can be shared on any external site of your choosing. It just won't be discoverable on the site.

> So is the plan to no longer be able to share and promote collections?

Not on AMO. It's up to you if you want to share them. There may be notable public collections that are featured on the site at times, but that's just an idea at this point.

> Also, what does this mean for the Followers of Collections; tracking the #s, getting notifications when new add-ons are added, etc? Is this all going away too?

Yes.

**Comment by smayer97** [comment]
Thanks for the reply. That is very very unfortunate and sad...one more discoverability feature gone to help leverage what others discover. I know some collections are very well followed.

Too bad the complexity seems to outweigh their potential benefit. 

But I would contend that although collections may be somewhat secondary, please keep in mind that the number of people impacted by them numbers far greater than the number of immediate users/creators of collections by the very nature of how many are used (see the latter part of my comments here https://github.com/mozilla/addons-frontend/issues/4331#issuecomment-381342181)

And I think more users would use them better and more often if the discoverability features were better implemented (but that is another issue ;-P ). 

...but I am at least glad that collections have been preserved.
