### ISSUE TITLE
Collections with a large number of add-ons have a long loading time

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4812]
STR:

1. Log in to AMO-dev with an Admin account and check the details page for a collection with a large number of add-ons - see https://addons-dev.allizom.org/de/firefox/collections/AlexandraMoga1/friday-afternoon-100/
2. Click on Edit collection
3. Check the time it takes for the collection to load

Actual result:
The loading time is a bit too long when the collection has over 100 add-ons. For me, it took between 8-12 seconds to load.

Expected result:
The loading time for large collections should be reduced 

Notes: 
reproduced on AMO-dev, with FF59, Win10x64

![coll load time](https://user-images.githubusercontent.com/31961530/38817111-587867ec-41a0-11e8-80a6-1b9ce9516f9f.gif)

**Comment by bobsilverberg** [comment]
This is likely the result of a design decision I made, which perhaps should be changed. I figured it was best to load all of the collection's add-ons when we switch into edit mode, because that seems like the easiest way to allow a user to manage their collection. It also means when we add an add-on to a collection from the edit screen, we don't need to worry about displaying a page which does not include the just added add-on.

For collections that are not particularly large, I think this is a good thing, but for large collections it becomes a performance issue. It may be possible to tackle the performance issue, and improve performance for large collections for this screen, but I'm not sure how difficult and how much work that would be. Perhaps we should move to a model where the list of add-ons is limited and pagable, just like on the collection details screen.

@jvillalobos and @pwalm what do you think about the above?

**Comment by jvillalobos** [comment]
It sounds like it's still possible to edit large collections currently, just slow, so this is low priority IMO. I think we should investigate if it's possible to make performance improvements without UX changes, and take that direction if it isn't too much effort. Otherwise, pagination sounds like the best next step.

**Comment by bobsilverberg** [comment]
We discussed this a bit more and have decided that the first step would be to add pagination to the list of add-ons on the edit screen. We may also want to look at using [occlusion culling](https://jlongster.com/Removing-User-Interface-Complexity,-or-Why-React-is-Awesome) in the future.

**Comment by smayer97** [comment]
If you decide to paginate, please make is so the numbers per page is user selectable, including a Show All option.

**Comment by smayer97** [comment]
BTW, I would much rather have a longer loading time where I can work with all the add-ons in a collection than to have pagination. At least, I would suggest making it an option for users to choose one over the other as they see fit.

**Comment by bobsilverberg** [comment]
>BTW, I would much rather have a longer loading time where I can work with all the add-ons in a collection than to have pagination. At least, I would suggest making it an option for users to choose one over the other as they see fit.

That is not a feature that we plan to implement at this time.
