### ISSUE TITLE
Strings for Facebook Container extension page not localizable

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-frontend#4819]
### Describe the problem and steps to reproduce it:
Localization communities and marketing would like to see this page localizable soon. The marketing page on mozilla.org in many languages are on production, promoting this.

### What happened?
Strings from this page are not extracted for localization: https://addons.mozilla.org/firefox/addon/facebook-container/ 

### What did you expect to happen?
Make the strings localizable through Pontoon

**Comment by peiying2** [comment]
@muffinresearch any ETA on this?

**Comment by EnTeQuAk** [comment]
You're talking about the description and name etc? These can be
localized through the devhub by the respective developers. We are
working on updating that process so that more metadata will be extracted
from the XPI directly but for now it's a manual process.
Involving Pontoon is something we can't do and would involve a huge
amount of work.

On Mon, Apr 16, 2018, at 8:53 PM, Peiying wrote:
> @muffinresearch[1] any ETA on this?


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].> 

Links:

  1. https://github.com/muffinresearch
  2. https://github.com/mozilla/addons-frontend/issues/4819#issuecomment-381710835

**Comment by peiying2** [comment]
Yes, the name and description. This is unfortunate. We heavily promote the page, but it is in English only.

**Comment by peiying2** [comment]
@EnTeQuAk We need the German version out. Can we get it done for German only? I will share the localized content once I have it.

**Comment by muffinresearch** [comment]
@peiying2 As @EnTeQuAk mentioned it's up to the Mozilla extension developers to localize it - can you reach out to them and ask them to update it via the AMO developer hub?

**Comment by peiying2** [comment]
Sorry for not knowing all the details. You mean here: https://addons.mozilla.org/en-US/developers/ (localized site of course)? Or is it through github? If so, what is the link?

**Comment by EnTeQuAk** [comment]
Yes, the add-on is being localized in https://addons.mozilla.org/en-US/developers/, once the respective maintainer of the "Facebook Container" add-on logs in he can enter all the localized detail information.

**Comment by muffinresearch** [comment]
Closing this since there's no action to be taken in this repo.
