### ISSUE TITLE
Permissions KB article should open in new tab

### ISSUE THREAD

**Issue by swarnava** [mozilla/addons-frontend#4846]
### Describe the problem and steps to reproduce it:
Go to an addon page.
Click on **Learn more about permissions** button.

### What happened?
The link opens in the same tab.

### What did you expect to happen?
The link should open in new tab

### Anything else we should know

![image](https://user-images.githubusercontent.com/1162991/38949709-ce4f85ce-4360-11e8-9c8f-7247b68c9228.png)

**Comment by bobsilverberg** [comment]
I believe that this is intentional. @pwalm can you comment on that?

**Comment by willdurand** [comment]
My 2cents: I don't think it is a general best practice to force tab opening.

**Comment by swarnava** [comment]
Feel free to close this issue. 😊

**Comment by jvillalobos** [comment]
Generally, I agree, but that link is taking the user out of AMO, so they could close the tab after reading the information and have no way (they know) to go back.

**Comment by swarnava** [comment]
Also, there is a developer hub link at the top of the AMO website which I
would expect to open in a new tab too as a beginner. 😀

**Comment by jvillalobos** [comment]
That's a bit different because it's in the same site, and there should be a link to go back (https://github.com/mozilla/addons-server/issues/4580). I do agree that the icon next to both of those links suggests you're going to a new place.

**Comment by bobsilverberg** [comment]
When I wrote the original code I did ask whether this link should open a new tab, and was told "no", but I don't remember exactly who told me that. Maybe @muffinresearch or @pwalm. I'd like to resolve that before we merge the PR in #4850.

**Comment by muffinresearch** [comment]
> When I wrote the original code I did ask whether this link should open a new tab, and was told "no", but I don't remember exactly who told me that. Maybe @muffinresearch or @pwalm. I'd like to resolve that before we merge the PR in #4850.

Opening in a new window/tab was originally proposed here too: https://github.com/mozilla/addons-frontend/issues/2757#issuecomment-345861242

I did find this reference from the review after a bit of digging: https://github.com/mozilla/addons-frontend/pull/4462#discussion_r171311643

**Comment by muffinresearch** [comment]
Personally I think there are definitely some usability issues to consider with opening links in a new tab [1].

To me the icon currently for this link represents an external site not opening in a new tab. But it's possible this could be a source of confusion.

We should consider the context too. This article [2] makes an interesting point that opening a new tab might be good when the site is providing help or assistance. In this case we are wanting to cross-reference permissions so using a new tab here might be helpful rather than a hindrance.

The latter article also suggest that this should be a user controlled option on each site, which seems reasonable but that does assume all external links should be treated equally.

[1] http://www.dave-woods.co.uk/why-opening-external-links-in-new-tabs-should-no-longer-be-standard-behaviour/
[2] https://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/

**Comment by pwalm** [comment]
Open permission article in a new tab, we don't want to interrupt the flow of a users decision-making process.

**Comment by ioanarusiczki** [comment]
This issue is verified fixed on AMO dev with FF59(Win10) 

![different tab](https://user-images.githubusercontent.com/33448286/39037029-fc95b6d8-4487-11e8-9523-fae8ba2bee4d.gif)
