### ISSUE TITLE
The message displayed when an add-on is added to a collection before approval is unclear

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4897]
Prerequisites:
A developer or admin account for a personal submitted extension that was not auto approved yet or it is waiting to be approved by a reviewer

STR:
1. Load AMO dev and go to your own submitted add-on that was not auto approved yet or from Rev tools to New Themes queue as a reviewer - where a list of extensions are waiting for approval such as static themes.
2. Try to add the add-on to a collection from it's detail page on the new frontend.
3. Observe the message displayed.

Expected results:
The message explains the reason the add-on cannot be added to the collection.

Actual results:
The message is unclear - Invalid pk or slug "488318" - object does not exist. 

Notes:
This issue is reproducible on AMO dev with FF59(Win10). 
This message is visible only to the developer who submitted the extension or someone with admin/reviewer rights.
![message when adding to collection before approval](https://user-images.githubusercontent.com/33448286/39433051-9d17d768-4c9d-11e8-8c78-c9f1add39373.png)

**Comment by bobsilverberg** [comment]
This is the message we are getting back from the API when we try to add the add-on to the collection. If this can be fixed it sounds like it needs to be fixed on the back end, sending a message saying that the add-on has not yet been approved, instead of just that it could not be found. I'm not sure how big of a deal it would be to implement that, and if it would be very difficult, or impact performance, this might be an edge case that we choose not to support.

@eviljeff and @jvillalobos What do you think?

**Comment by eviljeff** [comment]
The queryset used for creating/patching Collection Add-ons is public add-ons so if the add-on is not public then the slug or id lookup fails at that point.  

We can change the queryset to be any add-on, so you could add a non-public add-on to a collection.  If that's going to be any add-on, belonging to any user then that's easy (which would then, by default, not be shown in the collection addon list response, so hidden).

If it's going to be available for lookup, then fail because the Add-on isn't public and selectively do something different based on the user (being an author, or their permissions) then that's a difficult change.

**Comment by bobsilverberg** [comment]
Ok, so one question is whether we want to allow non-public add-ons to be added to collections, although it sounds like that would be kind of pointless anyway.

@eviljeff Are you saying that even if we allow them to be added, they will never be seen because the API that returns collection add-ons only ever includes public add-ons? If that's the case then it seems like we shouldn't allow them to be added as that could just be confusing to a user.

If we're not going to allow them to be added, and we want the API to tell us that that's the reason an add-on wasn't added to a collection - is that the part that's going to be a difficult change?

**Comment by jvillalobos** [comment]
There's a fairly narrow window between an add-on being submitted and it being auto-approved, or manually approved by theme reviewers. Exceptions to this are legacy add-ons pending review, add-ons flagged by admins for manual approval, and rejected add-ons. I don't think those cases are compelling enough to do something complex to address them. You're the developer and presumably you know their status, so it doesn't seem worth making a big change for this.

wontfix, IMO.

**Comment by eviljeff** [comment]
> Are you saying that even if we allow them to be added, they will never be seen because the API that returns collection add-ons only ever includes public add-ons? 

Well that's not exactly what I was saying - note "by default".  [[api docs](http://addons-server.readthedocs.io/en/latest/topics/api/collections.html#collection-addon-filtering-param)]

> If we're not going to allow them to be added, and we want the API to tell us that that's the reason an add-on wasn't added to a collection - is that the part that's going to be a difficult change?

It's not only wanting the reason to be exposed, it's selectively wanting the reason to be exposed depending on the user.

**Comment by bobsilverberg** [comment]
Thanks for the feedback @eviljeff, and thanks for the report @ioanarusiczki. I agree with @jvillalobos that this is an edge case that we shouldn't put too much effort into supporting. I'm going to close it.
