### ISSUE TITLE
User profile page cards show the 'username' instead of the 'display name' for the associated account

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4958]
Prerequisites: 
User is logged out or logs in with a non-admin account

STR:
1. Load AMO-dev homepage
2. Choose an add-on to view its details page (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/better-history/)
3. Clock on the developer name to access the user profile page
4. Notice the developer name displayed in the user profile cards

Actual result:
User profile cards are displaying the username associated with the developer account instead of the display name

Expected result:
User profile cards should show developer's display name for consistency with the add-on details page

Notes:
- if logged in with an admin account, the user profile cards will show the developer display name, as it should be
- reproduced on AMO-dev with FF59, WIn10x64

![prof-user](https://user-images.githubusercontent.com/31961530/39759568-ae0edfb4-52db-11e8-9b06-c0687a34d24c.gif)

![image](https://user-images.githubusercontent.com/31961530/39759578-b5bfd844-52db-11e8-9bb0-493c53b5dccc.png)

**Comment by tsl143** [comment]
For the given case we are getting `vasilicamihasca` as `displayName` from API response.
<img width="263" alt="screen shot 2018-05-10 at 8 16 17 am" src="https://user-images.githubusercontent.com/5318732/39849533-80973b12-542a-11e8-9af2-c2d4e317f1e2.png">

In addition we are using `name` key in addon-details page to show author name, instead shouldn't that be `displayName` instead?

**Comment by bobsilverberg** [comment]
Thanks for looking into this @tsl143. I'm not sure which API call those results are from. I believe the API call that is used for the User Profile screen is to `accounts/account/{username}` and that returns the displayName in the `name` field, and the username in the `username` field:

<img width="246" alt="screenshot 2018-05-10 08 23 29" src="https://user-images.githubusercontent.com/142755/39869432-80ebebe8-542b-11e8-95f6-f886f1b4f207.png">

I don't even see a result for something called `displayName`. So I don't think there's a problem with the API itself.

Because this problem only occurs when you are viewing a profile belonging to a user other than yourself (which includes viewing your own profile when you are logged out), I think it must be a bug in the logic for displaying the name on the View Profile screen itself.

**Comment by willdurand** [comment]
Ah I got it! We should not rely on `display_name` except when we edit a profile. The `name` field (returned by the API) always exposes the correct value to display in the UI (it will be the display name if user has one, the username otherwise).

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60, Win 10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/40115114-0a9038cc-5918-11e8-8769-da033aee3296.png)
![image](https://user-images.githubusercontent.com/31961530/40115127-0ff57d04-5918-11e8-97b0-b10aec4c315a.png)
