### ISSUE TITLE
Server error on user profile page when user does not exist

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5036]
### Describe the problem and steps to reproduce it:

1. Make sure you are logged-in
2. Go to a user profile page with a username that does not exist

### What happened?

Server Error:

<img width="1392" alt="screen shot 2018-05-18 at 10 01 18" src="https://user-images.githubusercontent.com/217628/40223174-7124ca9c-5a82-11e8-8dd9-d569fd8ee46b.png">

### What did you expect to happen?

No server error, but a 404.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF60, Win 10x64. A non-existent username will now generate a 404 error.

![profile load](https://user-images.githubusercontent.com/31961530/40293897-afc4d4a8-5cdb-11e8-8b91-9a72c4999c14.gif)

@willdurand - you can see in the attached video that before the "Page not found" is displayed, the user profile card will load for a brief moment. Is this an expected behavior or can it be eliminated?

**Comment by willdurand** [comment]
It can be eliminated with a different error handler.
