### ISSUE TITLE
I can't access my themes

### ISSUE THREAD

**Issue by Tallis40** [mozilla/addons-frontend#5055]
### Describe the problem and steps to reproduce it:
Simple.  I try to change the theme on my page. 
### What happened?
I keep getting an error message.
### What did you expect to happen?
I expected to be able to change the theme on my page like I have multiple times per year for years!
### Anything else we should know?
I'm mad.  I've been trying for weeks to change the theme and I keep getting the same error message.
I actually started an account for GitHub though I don't see what it has to do with anything.  It certainly hasn't helped the problem.

**Comment by muffinresearch** [comment]
@Tallis40 please can you provide more information:

* What is the URL of "my page"?
* What is the error message you're getting?

Please provide screenshots if that helps show us where the problem is. You should be able to do that by dragging a screenshot onto the comment box in github.

**Comment by Tallis40** [comment]
Sorry.

Random URL from my pages because they all get the same response:  <
https://addons.mozilla.org/en-US/firefox/collections/
Dawn_Grib/pentecost-and-summer/>

error message:  see attachment

**Comment by willdurand** [comment]
This URL (https://addons.mozilla.org/en-US/firefox/collections/Dawn_Grib/pentecost-and-summer/) works for me :/ We'd need the error message to see what went wrong.

I don't really know what else we can do so far, so I am going to close this issue because it starts to be stale. Please re-open or create a new one if the problem still occurs.
