### ISSUE TITLE
Turn on TAAR lite recommendations for stage and production.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5063]
This is to put the recommendations on details pages live in stage and prod as well as -dev and local development where it is already enabled.

**Comment by AlexandraMoga** [comment]
Verified on AMO-stage with FF60, Win10x64

Test results:

**Verified**
1. add-on recommendations card is present in extensions detail page
2. four recommendations are displayed for each extension visited
3. a cookie is applied when a user visits an extension details page; this cookie will be either `"TAAR_COHORT_INCLUDED"` (when the user receives recommendations from Taar/fallback), or `"TAAR_COHORT_EXCLUDED"` (when the user receives curated results; I have tested this with several users and FF profiles in order to capture both instances.
4. GA pings are sent when a user within a specific group visits an extension detail spage

**Not verified**
As mentioned in [addons-server/issue #8299](https://github.com/mozilla/addons-server/issues/8299#issuecomment-391326670) the scenario in which the user sees results recommended by TAAR could not be verified. I was not able to find an extension for which the guids recommended by TAAR were all available on stage. Therefore, for all the extensiosns visited on the frontend, the recommendations were always coming from `fallback` for users included in the TAAR group.

Overview of the extension detail page with recommendations from `fallback`:
![image](https://user-images.githubusercontent.com/31961530/40424898-856846d4-5e9f-11e8-95da-2121a9b0d5cd.png)

**Comment by bobsilverberg** [comment]
We should be able to get some recommended add-ons on stage, but I think we need to coordinate it. We'll need to know the guids generated by the TAAR Lite service for a particular add-on and then upload add-ons to stage with those guids. Do we feel this is important to do, or are we happy to wait to test it on prod, where all the guids should exist?

**Comment by muffinresearch** [comment]
It was showing results before the new tag was landed. It would be good to get at least one addon showing all 4 recommendations. You can call TAAR directly to find that out. 

@bobsilverberg if you start with https://addons.allizom.org/en-US/firefox/addon/noscript/ yesterday it was only missing one recommendation.

**Comment by bobsilverberg** [comment]
Ok, I'll see if I can get recommendations to appear for noscript.

**Comment by bobsilverberg** [comment]
@AlexandraMoga After much finagling, I was finally able to get recommendations for a single add-on on stage. Please use this add-on for final verification: https://addons.allizom.org/en-US/firefox/addon/flagfox/?src=featured

**Comment by bobsilverberg** [comment]
This can now be re-closed.
