### ISSUE TITLE
The user's profile page is not displayed for an admin if the URL is missing the slash

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5132]
STR:
1. Load AMO dev and log in with an account and go to Edit my profile page
2. Copy the link https://addons-dev.allizom.org/en-US/firefox/user/Contdedisplaytestadmin/edit
3. Log in with an admin account and paste the above link into the address bar

Expected results:
View user's profile page is displayed.

Actual results:
We're sorry, but we can't find what you're looking for message is displayed.

Notes:
If a "/" is added at the end of the URL the user's profile page is correctly displayed.
This issue is reproducible on AMO dev with FF60(Win10). 

![edit user s profile](https://user-images.githubusercontent.com/33448286/40666117-a9da79b6-6367-11e8-8182-66bb11f30932.gif)

**Comment by willdurand** [comment]
The new frontend has a middleware to make sure we go to URLs with a trailing slash. It is not the case of the legacy frontend, and we did not add any Nginx redirection for URLs without a trailing slash if I remember correctly.

**Comment by willdurand** [comment]
@muffinresearch not sure what to do here, maybe we want to update the nginx rule? or is it a wontfix because this URL does not exist anyway?

**Comment by muffinresearch** [comment]
> The new frontend has a middleware to make sure we go to URLs with a trailing slash. It is not the case of the legacy frontend, and we did not add any Nginx redirection for URLs without a trailing slash if I remember correctly.

The users' url for editing the user profile in the new frontend doesn't have a slash though. Is that expected? There seems to be some inconsistency.

**Comment by willdurand** [comment]
I thought we only had `/user/:username/edit/` with a trailing slash, so I expected the URL without a trailing slash to be invalid, but you're right it is not what we have currently.

**Comment by willdurand** [comment]
So if we change the nginx rule to fix this issue, we make the edit user URLs consistent but it is not what we want, right? We want to have trailing slashes on all URLs if I remember correctly.

**Comment by willdurand** [comment]
Meanwhile, I stumbled upon this: https://github.com/mozilla/addons-frontend/blob/dabf02480ad420949f4706e9d002fdc6933242bd/config/default-amo.js#L90-L111

**Comment by willdurand** [comment]
@bqbn could you please update the -dev nginx rule added in https://github.com/mozilla/addons-frontend/issues/4284 from `/user/:username/edit/` to `/user/:username/edit` (without a trailing slash)? The related PR is: https://github.com/mozilla-services/cloudops-deployment/pull/1987.

**Comment by willdurand** [comment]
@bqbn how long does it take to be available usually?

**Comment by bqbn** [comment]
@willdurand it depends on the urgency of an issue and how much fire we're trying to put off elsewhere. :) We needed to deal with some kinto -prod issue thus this is not deployed immediately after merging.

That said, redirecting `/user/:username/edit` (without trailing slash) is on -dev now. 

However, it looks like the application will add a trailing slash and redirect the user:

```
$ curl -is frontend-amo-amodev1.amo.us-east-1.dev.mozaws.net:4000/en-US/firefox/user/Contdedisplaytestadmin/edit |egrep '^HTTP|^Location'
HTTP/1.1 301 Moved Permanently
Location: /en-US/firefox/user/Contdedisplaytestadmin/edit/
```

**Comment by willdurand** [comment]
> However, it looks like the application will add a trailing slash and redirect the user:

Yes... It is actually broken now (only when editing another user though). My request to change the nginx rule was a mistake, I am sorry for that. We cannot simply do that because of the "trailing slash" middleware on addons-frontend.

So here are the information I have in mind now:

- `/users/edit` is a valid URL (without the trailing slash). It is the URL used in the legacy frontend as well as the new frontend
- `/users/edit` is white-listed (`validTrailingSlashUrlExceptions`) in the new frontend so that the "trailing slash" middleware does not append a trailing slash and leaves this URL as is
- `/user/:username/edit` does not exist on the legacy frontend (legacy frontend uses the user ID in the URL)
- `/user/:username/edit/` does not exist on the legacy frontend (legacy frontend uses the user ID in the URL)
- it is not possible to whitelist URLs with a placeholder other than `$lang` or `$clientApp`
- the first nginx configuration was correct
- the recent nginx configuration changes I asked are not correct
- this issue should have been marked as "wontfix" because it is the correct behavior
- we need to fix the new frontend code to use:
    - `/users/edit` to edit the current logged-in user profile (to keep BC with the legacy frontend)
    - `/users/:username/edit/` (with the trailing slash) to edit another user profile as an admin
- we should see if `/users/edit/` could be used too (thus removing `/users/edit` from the list of exceptions for the "trailing slash" middleware)

First thing first: I will open a PR to revert the nginx change introduced yesterday so that admins can edit other user profiles again (in -dev). I'll submit a PR on this project to fix inconsistencies.

**Comment by willdurand** [comment]
Something I still don't really understand is why the trailing slash did not get appended in the first place and why did nginx replied instead of the app?

**Comment by bqbn** [comment]
> Something I still don't really understand is why the trailing slash did not get appended in the first place and why did nginx replied instead of the app?

Do you mean why the trailing slash did not get appended for `/user/:username/edit` endpoint?

The frontend does append a trailing slash to that, it looks like,

```
$ curl -is frontend-amo-amodev1.amo.us-east-1.dev.mozaws.net:4000/en-US/firefox/user/Contdedisplaytestadmin/edit |egrep '^HTTP|^Location'
HTTP/1.1 301 Moved Permanently
Location: /en-US/firefox/user/Contdedisplaytestadmin/edit/
```

**Comment by willdurand** [comment]
@bqbn indeed, but why is "https://addons-dev.allizom.org/en-US/firefox/user/Contdedisplaytestadmin/edit" not redirected?

Do we need to add a second nginx rule to redirect `/user/:username/edit` to `/user/:username/edit/` at the nginx level?

**Comment by bqbn** [comment]
> why is "https://addons-dev.allizom.org/en-US/firefox/user/Contdedisplaytestadmin/edit" not redirected?

Because in https://github.com/mozilla-services/cloudops-deployment/pull/2071, Nginx was told to **ONLY** send `<locale>/user/<:username>/edit/` to frontend-amo, thus `<locale>/user/<:username>/edit` is sent to the desktop site by default.

Yes, the application (frontend-amo) will add a trailing slash to `<locale>/user/<:username>/edit` and return 301, but that only happens when Nginx passes that URI to the application.

> Do we need to add a second nginx rule to redirect /user/:username/edit to /user/:username/edit/ at the nginx level?

Nginx can do that. 

`Do we need to`? I'm not sure because I'm a little confused actually. Because per https://github.com/mozilla/addons-frontend/issues/5132#issuecomment-393854047, the purpose of https://github.com/mozilla-services/cloudops-deployment/pull/2071 (i.e. only send `<locale>/user/<:username>/edit/` to frontend-amo) was to fix some "inconsistency". If you want to send both (with or without trailing slashes) to the application, is it considered as not fixing "inconsistency"?

That said, since you also said both `/user/:username/edit` and `/user/:username/edit/` do not exist on the legacy frontend, maybe you can claim one of them is a valid (and expected) 404 on the new mobile site, thus there is no need for a second Nginx rule, and the code consistency you referred to in https://github.com/mozilla/addons-frontend/issues/5132#issuecomment-393854047 is also kept.

Finally, if you decided Nginx should send `/user/:username/edit` to the application, we can file a PR to add that rule. Ideally, we want to keep Nginx rules simple, i.e. not doing the redirection in Nginx, but just sending the URI to the app, and let the app decide what to do.

**Comment by willdurand** [comment]
Thanks @bqbn, that makes sense.

> That said, since you also said both /user/:username/edit and /user/:username/edit/ do not exist on the legacy frontend, maybe you can claim one of them is a valid (and expected) 404 on the new mobile site, thus there is no need for a second Nginx rule, and the code consistency you referred to in #5132 (comment) is also kept.

Yep, that's what I am going to do now. We have the following routes for the edit page:

- `/users/edit`
- `/user/:username/edit/`

This issue will be marked as wontfix when #5179 will be merged.

**Comment by ioanarusiczki** [comment]
@willdurand This issue is still reproducible if I test it using the above scenario. Is it a won't fix ?

I've also noticed something:
I login with a developer account and go to Edit profile page then log out and click on "Edit this profile" and I login with an admin account ->I see the admin's edit page displayed. The URL has the /users/edit format.
The developer's account can be edited by an admin when I log out from the View Profile page because the URL will have the /user/:username/edit/ format when logging back in with the admin account.

**Comment by willdurand** [comment]
> @willdurand This issue is still reproducible if I test it using the above scenario. Is it a won't fix ?

Yes, adding the label now.
