### ISSUE TITLE
Biography section is missing a title on the User profile card

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5145]
STR

1. Log in to AMO-dev
2. Open a user profile page that includes a biography (https://addons-dev.allizom.org/en-US/firefox/user/MaDonna-3/)
3. Check the biography section

Actual result:
There is no title marking the beginning of the user biography

Expected result:
The biography section should include a title, in order to be consistent with the rest of the user data listed on the profile card

Notes:
- reproduced on AMO dev with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/40772019-91ed3eae-64c7-11e8-804e-c313d909fac5.png)

**Comment by rishabh-bansal** [comment]
Hey! This is my first time, how can I get started?

**Comment by willdurand** [comment]
Hi @rishabh-bansal, thanks for your interest! You have to write a Pull Request with a change located in the [`UserProfile` component](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/UserProfile/index.js).

First, you have to install the application locally and run the test suite (always!). The requirements are there: https://github.com/mozilla/addons-frontend#requirements, in short you need node 6 (but node 8 works too!). Once you have Node installed on your computer, please also install Yarn as described here: https://yarnpkg.com/en/docs/install.

Make sure that `yarn --version` returns something like (the version may not be the same):

```
$ yarn --version
1.6.0
```

Now, you can install the project dependencies by running `yarn install`. Run the test suite to make sure the project is successfully installed `with yarn test`. Then, you can make your changes and re-run the test suite yarn test. It is not super fast but that's because we have lots of tests (which is super-great).

You will have to write new tests for your patch. We have a test file for each "source" file (in src/). The test file for the `UserProfile` component is here: https://github.com/mozilla/addons-frontend/blob/master/tests/unit/amo/components/TestUserProfile.js.

A test starts with a new block it:


```js
it(`shows the user's biography`, () => {
  // here you have to write the code for the test
});
```

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO -dev with FF60, Win10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/41601795-f6eb024a-73e1-11e8-9a9c-857cb0c57424.png)
