### ISSUE TITLE
Update react-transition-group to the latest version and the components that use it

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5155]
the react-transition-group package has a newer version and we should look into upgrading to that (either through Greenkeeper if possible (?) or explicitly updating in package.json)

The package is used currently in the Disco and Collection Manager so these components need to be adjusted to work with the newer version

**Comment by championshuttler** [comment]
@rebmullin can i take this up? ;)

**Comment by rebmullin** [comment]
sure @championshuttler, go for it : )

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label 'qa:not needed' to this issue?

Thanks

**Comment by willdurand** [comment]
@AlexandraMoga can you please check that CSS transitions still work:

- when an addon has been added to a collection, a message is displayed and then removed shortly after with a fading effect
- on Disco Pane, when there is an error or need to restart the browser: I don't know how complicated it is to verify that, but I guess if the previous transition works, it should work in Disco Pane as well (because I did the same change)

**Comment by AlexandraMoga** [comment]
Verified on AMO stage with FF61, Win10x64 and Android 8.0

- for the first scenario - adding an add-on to the collection - the success message displayed will fade away after ~5 sec, i.e. working as before
- @willdurand for the disco pane scenario I couldn't trigger any other error, except for the one exhibited below and as far as I recall this didn't use to have a transition effect.  This error is displayed when you try to install an add-on on dev or stage using Firefox release.


![image](https://user-images.githubusercontent.com/31961530/42940126-0dae5978-8b61-11e8-8d46-630bf40c72ee.png)
