### ISSUE TITLE
微信隐私  饼干

### ISSUE THREAD

**Issue by 78760611** [mozilla/addons-frontend#5157]

**Comment by 78760611** [comment]
微信隐私反馈  里的链接  我输入法 显示语言  就是没有中文

**Comment by muffinresearch** [comment]
It's hard to tell since I'm relying on auto translation but this looks like you're looking for support with a particular extension. This issue tracker is only for issues directly to do with the website addons.mozilla.org. If you think this issue has been closed in error, then please re-open the issue and add additional details so we can figure out the problem you are facing.
