### ISSUE TITLE
Autocomplete search results on mobile are awkwardly small

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5306]
### What happened?

* Load AMO on a mobile device with a small screen
* Type the name of an add-on in the search box
* Wait for search results to autocomplete
* Read the results and select one that matches your query

This technically works but the results are very small which makes them awkward to deal with: 
* The text gets cut off so it's hard to read the results. 
* The click targets are not very big so it's hard to select results.

### What did you expect to happen?

Autocomplete results should be easier to deal with on mobile.

**Comment by ioanarusiczki** [comment]
Verified this issue on AMO dev and AMO stage with FF60(Android 8.0)
The search suggestions are easier to read and to be selected - what I see is that the user/display name won't be entirely displayed if it's a bit longer because of the search bar.

![search bar and suggestions on mobile device](https://user-images.githubusercontent.com/33448286/41648669-3c2c00ca-7482-11e8-9f3e-f78fb15139b7.png)

**Comment by kumar303** [comment]
> what I see is that the user/display name won't be entirely displayed if it's a bit longer because of the search bar.

I think that's fine. It's enough of a hint to indicate that tapping on it will give you a menu of user related actions.
