### ISSUE TITLE
Change copy on top of the about:addons page (disco pane)

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/addons-frontend#5322]
The copy at the top of the disco pane is quite outdated. Update it with Meridel's new copy (TBD). Below is a screenshot of what exists today.
![Current top of disco pane content](https://user-images.githubusercontent.com/911251/41627108-bc57acf4-73d3-11e8-8608-a5fe65ef0bd9.png)

**Comment by devaneymoz** [comment]
Note the above copy is the result of significant Legal input -- mostly about being abundantly clear that most (nearly all) extensions featured on this page come from third party sources, not Mozilla. 

Also note that soon this page is likely to feature a mix of TAAR (machine) and editorial (hand-curated) selection. The overarching copy should likely reflect whatever the new manifestation entails.

**Comment by willdurand** [comment]
See also: https://github.com/mozilla/addons-frontend/issues/5637

**Comment by willdurand** [comment]
@MeridelW as soon as you have content for this issue, please paste the Google doc link in a comment here, thank you!

**Comment by MeridelW** [comment]
@willdurand Will do! It's on my to-do list.

**Comment by willdurand** [comment]
@MeridelW let me know when you have something ready, the sooner the better because we might have to iterate 😃

**Comment by MeridelW** [comment]
@willdurand I've got a draft of options here but I'd like to better understand scope. Ideally, we would be able to split out extensions and themes into two different sections, rather than co-mingling the two as we do now. 

Please see my copy doc and let me know your thoughts...https://docs.google.com/document/d/1UELyvclz-RxHWdIy-SD8hYVGO3ybwO8n3N-p0mK9-Yk/edit

**Comment by devaneymoz** [comment]
I like a lot of these options, but please see my note in this issue from June 19 about referencing how add-ons come (primarily) from third party sources.

**Comment by muffinresearch** [comment]
@MeridelW Echoing my comments in the google doc, a bigger change to split the display of addons and themes is out of scope for this project. We are running a shield study currently and we shouldn't make big changes whilst that is underway. 

Changes to the existing copy should be ok though, so if we want to do that now it can be added here, or otherwise we can defer this issue as Will suggested in the google doc comments.

**Comment by willdurand** [comment]
I am closing this issue for now. If there is an update on the top paragraph of the disco pane, please open a new issue. Anything else should be discussed with @jvillalobos first.
