### ISSUE TITLE
The page numbers for a collection with more than 25 add-ons are not alligned

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5335]
STR:
1. Load AMO dev and create a collection then add more than 25 items
2. Observe the page numbers in both Edit my collection and View my collection

Expected result:
The numbers are aligned.

Actual result:
The number that indicates the page displayed is not aligned with the others.

Notes:
This issue is reproducible on AMO dev with FF60(Win10).

![alignment](https://user-images.githubusercontent.com/33448286/41656739-b0fd2bf6-7499-11e8-8db7-631fb9c62fb4.png)

**Comment by willdurand** [comment]
This is intended, according to the mock-ups:

![screen shot 2018-06-20 at 14 07 20](https://user-images.githubusercontent.com/217628/41657319-43e9d33a-7493-11e8-8215-a02604e5b985.png)

Note: the mock-ups show a different paginator with:

- number of results instead of pages
- some pages, then three dots, then the last page

Those changes will be addressed later.

**Comment by ioanarusiczki** [comment]
Oh, alright, I've just noticed that this changed for the reviews too while checking this https://github.com/mozilla/addons-frontend/issues/4890
Noted!
