### ISSUE TITLE
Refreshing several times an add-ons detail page generates server error

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5392]
STR:
1. Load AMO dev and go to an add-on's detail page
2. Refresh page several times - press the F5 key multiple times
3. Observe the screen

Expected result:
Page is refreshed.

Actual result:
At one point Server error is displayed then the add-on's detail page.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF60(Win10x86 & Android 8.0). 
For lang packs - the your version of FF does not support search plugins is displayed intermittent and also the button becomes inactive.
For lang packs, dictionaries and user profile page - An unexpected error occurred message is displayed.
Not reproducible with static or lightweight themes.

Add-on's page

![refresh page - server error](https://user-images.githubusercontent.com/33448286/41852358-82d1f042-7893-11e8-9b4d-55f33d92332f.gif)

Edit profile page

![refresh page several times edit profile](https://user-images.githubusercontent.com/33448286/41852219-2bf2b342-7893-11e8-94db-ee606b2fc135.gif)

**Comment by ioanarusiczki** [comment]
This is reproducible on a search tool detail page too with FF61(Win10&android 8.0).

![search tools reloading page](https://user-images.githubusercontent.com/33448286/42166169-d68e9c9c-7e12-11e8-973b-b8de5be2a927.gif)

**Comment by kumar303** [comment]
This is expected behavior. What happens is you load the page once and your browser makes a request to the server. If you press Refresh quickly--before the page has loaded--the browser cancels the pending request. This cancellation aborts the first request which is technically an error. For a split second, you are seeing our app render an error about the aborted request but then it goes away.

This is definitely a little confusing but I'm not sure it's worth fixing right now.
