### ISSUE TITLE
Edit collection page - The title of the text box is "User comment" instead of "Add-on note" 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5395]
STR:
1. Load AMO dev and go to a collection
2. Click on Edit this collection and try to make a comment for an extension/theme from the list
3. Notice that the name of the text box is "User comment"
4. Save the comment and then click on Save collection
5. Observe the name of the text box

Expected result:
In both edit and view collection - "Add-on note" is displayed - as mentioned[ here]( https://user-images.githubusercontent.com/6797635/33636526-6ef3ae78-d9d1-11e7-9a80-5ce5bf85717b.png
)

Actual result:
There's an inconsistency between the two pages - Edit collection displays "User comment" instead of "Add-on note".

Notes:
This issue is reproducible on AMO dev with FF60(Win10). 
![add-on note2](https://user-images.githubusercontent.com/33448286/41857509-5d146b7a-78a0-11e8-9f56-458ed0fb2034.gif)

**Comment by bobsilverberg** [comment]
This was intentional, but perhaps should be re-evaluated. There are two different contexts, hence it may be that the two headings are appropriate.

The use of the "User comment" heading in the edit form is based on the mockup at https://github.com/mozilla/addons-frontend/issues/4578#issuecomment-393260468.

@pwalm Do you want to keep the different headings, i.e., "Add-on note" when viewing a collection and "User comment" when editing a collection, or should we make them both the same?

**Comment by pwalm** [comment]
"Leave a note" in edit mode.

"Collector's note" when the note is being viewed by either the creator or a user.

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @kumar303

**Comment by Shubhamchinda** [comment]
Hey @caitmuenster I'd like to work on this issue.

**Comment by willdurand** [comment]
@Shubhamchinda go for it

**Comment by willdurand** [comment]
Thanks @Shubhamchinda!

**Comment by vcarciu** [comment]
Verified as fixed : 
![collector](https://user-images.githubusercontent.com/1583842/61300185-2bc49480-a7ea-11e9-827f-6c385dca8c82.png)
