### ISSUE TITLE
Remove the A/B test from the TADAr so that recommendations are 100% of traffic

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5408]
Ahead of making incremental changes to the underlying TADAr (Telemetry Aware Details Add-ons Recommendations) engine we'd like to turn of the fallback part of the A/B test so that recommendations are shown to all users (the fall-back will still apply in cases where TAAR errors).

**Comment by bobsilverberg** [comment]
It looks like we can stop sending both `dimension4`, which indicates which TAAR cohort a user is in (because they will all be in `TAAR_COHORT_INCLUDED` from now on) as well as `dimension5`, which indicates which experiment the user is a part of (which up until now was always `TAAR-LITE-AB` but now doesn't seem to have a valid value because there is no longer an experiment being conducted). Can we confirm that with someone? Will it mess up the data in the future to stop sending one or both of those?

**Comment by bobsilverberg** [comment]
@motin I'm not sure if you're the right person to ask about the above, but I figured I'd give it a try. If you're not, and you know who is, please let me know.

**Comment by willdurand** [comment]
> It looks like we can stop sending both dimension4, which indicates which TAAR cohort a user is in (because they will all be in TAAR_COHORT_INCLUDED from now on) as well as dimension5, which indicates which experiment the user is a part of (which up until now was always TAAR-LITE-AB but now doesn't seem to have a valid value because there is no longer an experiment being conducted). Can we confirm that with someone? Will it mess up the data in the future to stop sending one or both of those?

From what I understand, we completely remove the GA logic and only fetch add-on recommandations, all the time.

**Comment by mlopatka** [comment]
@willdurand @bobsilverberg 
Please leave the logic around dimension5 intact. This value should always indicate TAAR-LITE-AB.

While this will now apply to 100% of the visitors to AMO, its continued existence is valuable in examing the use of tracking protection which can (in some cases) prevents proper association into a group and/or visibility in the GA. 

also, some custom reports I have made rely on it as a filter condition.

**Comment by mlopatka** [comment]
@bobsilverberg The `AMO Addon / Recommendations Shown` is still a very valuable piece of information, perhaps even more so now that we are moving to 100% of the visitors seeing the TAAR-lite condition. We estimate that the number of _failures_ where TAAR-lite times out should be <= 0.05%. 

However, we are planning to extend the fallback functionality to further diversifying the addons shown when TAAR-lite determiens that no suitable recommmendations can be determiend from the guid of the Detail page where the API call originates.

This will mean having GA indicate 1 of 3 possible outcomes:
1- TAAR-lite successfully provides recommmendations.
2- TAAR-lite does not provide recommmendations, but successfully returns a selection of featured addons.
3- TAAR-lite times out or is otherwise unreachable fallback of 4 addons are displayed.

In both cases 2 and 3 the copy should read "Other popular extensions".
In case 1, the copy should read "Other users with this extension also installed"

This will require and additional parameter passed between TAAR-lite's API and AMO to distinguish between cases 1 and 2. I am meeting with Stuart and Jorge today to scope this work. 

Please hold off on GA related changes until we have agreed on a plan to the next incremental TAAR-lite improvement.

looping in @crankycoder

**Comment by mlopatka** [comment]
One additonal consideration is whether we would like to have three different versions of client-facing copy to correspond to the three conditions. For example:

1- Other users with this extension also installed
2- Other featured extensions
3- Other popular extensons

I defer to @devaneymoz to make that call.
Regardless of the cleint-facing copy, we should absolutley make sure that GA logs these events differently.

**Comment by devaneymoz** [comment]
Yes indeed, we'd like those three versions of copy to display when appropriate. If further details are needed, they're outlined in this [PRD](https://docs.google.com/document/d/1PF_5_TGsS_BTUDivhrPrSHZJ3xcv9xMA9UjaX5zN8zg/edit#). 

1- Other users with this extension also installed
2- Other featured extensions
3- Other popular extensons

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev with FF61(Win10)
I created new accounts and also tested with the existing accounts - 9 in total - went to on an extension's detail page. In all cases the TAAR_COHORT_INCLUDED was displayed in the Console and also the recommendation api is present in the Network with recommended=true

![console](https://user-images.githubusercontent.com/33448286/42227574-78babb18-7eea-11e8-9222-346d60150140.png)

![recommandations](https://user-images.githubusercontent.com/33448286/42227559-6fde4bc2-7eea-11e8-9ad0-35b2e0e84d66.png)

If any further investigations should be made please let me know.
