### ISSUE TITLE
Featured collection page instead of My Collections is displayed after view classic desktop site is clicked

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5421]
STR:
1. Load AMO dev and go to View My Collections from the drop down menu.
2. Click on View classic desktop site.

Expected result:
My Collections old view appears. https://addons-dev.allizom.org/en-US/firefox/collections/Contdedisplaytestadmin/

Actual result:
Featured Collections loads. https://addons-dev.allizom.org/en-US/firefox/collections/?sort=featured

Notes:
This issue is reproducible on AMO dev with FF60(Win10). 

![classic view for my collections](https://user-images.githubusercontent.com/33448286/41966494-efc36260-7a07-11e8-9886-2e3005996fcf.gif)

**Comment by willdurand** [comment]
URLs have changed and we do not use `/collections/:username/` anymore for a user's list of collections, simply `/collections/`, that is not tied to a public page anymore.

I guess there is some sort of nginx configuration to add.

**Comment by bobsilverberg** [comment]
I don't think there's any need to support the use case of switching from the new site to the legacy site while you are on the My Collections page and ensuring you land on the legacy version of the My Collections page, especially as we will be turning on the new UI for collections very soon. I am therefore going to close this. If anyone vehemently disagrees with that, feel free to reopen it.

**Comment by bobsilverberg** [comment]
It would be nice if we could fix this with a simple redirect, but I think there's an issue because we need to go from a URL that is `https://addons-dev.allizom.org/en-US/firefox/collections/` (i.e., a generic URL) to a URL that is `http://addons-dev.allizom.org/en-US/firefox/collections/{username}/` (i.e., a URL specific to a user), so I don't think nginx would have the smarts to do this.

@eviljeff Is there something reasonably simple we could do on the legacy site which could redirect from `https://addons-dev.allizom.org/en-US/firefox/collections/` to `http://addons-dev.allizom.org/en-US/firefox/collections/{username}/` using the username of the logged-in user?

**Comment by eviljeff** [comment]
@bobsilverberg I think this may get complicated because `/firefox/collections/{username}/` and `/firefox/collections/` are two different things on legacy frontend.  (the latter being a generic list of collections... albeit only featured collections now).

We could drop that view entirely, though then it would arguably be better to move the 'my collections' view to `/firefox/collections/` from `/firefox/collections/{username}/`, to match addons-frontend. (Then it would be good to have an nginx rule to strip off the `{username}/`)

Or yeah, just ignore it because we don't really support switching backwards and forwards between legacy and new frontend.  Though I still think eventually having an nginx redirect would be good on the off chance someone has bookmarked an existing `/firefox/collections/{username}/` page.

**Comment by eviljeff** [comment]
(picking up an old issue I didn't reply to in Q3)

I don't think it's worth doing any further legacy frontend changes because no-one should be using legacy frontend really.
