### ISSUE TITLE
Show star rating breakdown on detail page

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#5437]
Show the star rating breakdown at the top of the detail page. Example:
<img width="1005" alt="screen shot 2018-06-27 at 11 28 25 am" src="https://user-images.githubusercontent.com/6797635/41992487-715053b6-79fd-11e8-9892-ca2a1ed29c88.png">

Spec:
<img width="1507" alt="screen shot 2018-06-27 at 11 28 32 am" src="https://user-images.githubusercontent.com/6797635/41992495-76964d26-79fd-11e8-84b6-11dff1a40ef6.png">

**Comment by ioanarusiczki** [comment]
I filed https://github.com/mozilla/addons-frontend/issues/5846 and https://github.com/mozilla/addons-frontend/issues/5847 for the scenarios when the user cancels the given rating.

@kumar303 What I've noticed about the layout:
- the spec above mentioned a Fira Sans-Regular font, I have with Inspector a font-family: Fira Sans,sans-serif font (Could be the same but I'm not sure)
- the spec mentioned 15 px font size for the Ratingsbystar-count, I see it as 14 px with Inspector
- the length of the bar is 315.45 px and I see above that it should have 306px

font size
![font size](https://user-images.githubusercontent.com/33448286/43781955-d318e8ae-9a66-11e8-9b89-48e5f3ea882d.png)
bar lenght
![lenght of the bar](https://user-images.githubusercontent.com/33448286/43781825-808c781c-9a66-11e8-8c66-f6770ba0af70.png)


Verified on AMO dev with FF61(Win10 & Android 8.0).

**Comment by kumar303** [comment]
Thanks for the detailed observations. I don't think any new issues are needed. Here are some responses:

> the spec above mentioned a Fira Sans-Regular font, I have with Inspector a font-family: Fira Sans,sans-serif font

Yep, they're the same. This is the default font we already use on the site.

> the spec mentioned 15 px font size for the Ratingsbystar-count, I see it as 14 px with Inspector

I chose 14px because it is the closest standard font size [we already have](https://github.com/mozilla/addons-frontend/blob/f3efa1158a7e0b9f36d36e25b378bd4abb19a827/src/core/css/inc/vars.scss#L21). I filed https://github.com/mozilla/addons-frontend/issues/5866 to update font sizes.

> the length of the bar is 315.45 px and I see above that it should have 306px

To accommodate different screen sizes, this section of the page has a width of 35% (minimum 300px). The page was already styled this way so I left it.
