### ISSUE TITLE
"You do not permission to perform this action" should be displayed when others than the owner try to add an extension/theme

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5498]
STR:
1. Load AMO dev and login with an admin account then open the edit page of a collection created by another user (log out from the first account while being on the edit collection page and then log back in with the admin account)
2. Try to add an extension/theme to the collection and observe the red message

Expected result:
"You do not have permission to perform this action" is displayed

Actual result:
"Not found"

Notes:
This issue is reproducible on AMO dev with FF61(Win10). 

Message when trying to edit name, description or URL 
![message1](https://user-images.githubusercontent.com/33448286/42284691-f6337dca-7fb5-11e8-923a-10197ae28137.png)

Message when trying to add an extension/theme 
![message2](https://user-images.githubusercontent.com/33448286/42284735-175638bc-7fb6-11e8-9565-1f96f1f9f6ed.png)

**Comment by bobsilverberg** [comment]
These messages are returned by the API calls that we make to perform these operations. While I agree that it would be better if we could display the message "You do not have permission to perform this action" when trying to add an add-on fails, I'm not sure we need to put the effort in to override the default error message coming back from the API.

I say this because a user will never land on that edit page, except by typing it on the URL (because we have removed the link to the edit page if you don't have access to edit), in which case they have navigated to a part of the site where they don't really belong. I'm not sure we need to put extra effort into friendly error messages for use cases where users are attempting to abuse the site.

What do you think @jvillalobos?

**Comment by jvillalobos** [comment]
As I understand this issue, only a privileged user can get to the page in the first place, so I agree with Bob that we don't need nice error messages for something that should be clear to them.
