### ISSUE TITLE
Detail handling multiple states in the install button UI

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#560]
Since the install button is reflecting multiple states at once it would make sense to have some docs to show what how the states are reflected based on the starting point.

Here's the current way we're dealing with the core button states in word form - we can ignore the intermediate states e.g. downloading/uninstalling as they're not relevant to the main user interactions.
I'm also ignoring the restart case for the time being because that's handled separately.

## The core states

The 3 core states are:

### `Uninstalled` 
![add-ons_manager](https://cloud.githubusercontent.com/assets/1514/15905566/388d5acc-2dad-11e6-9457-8302db6f126b.png)
### `Installed/Enabled`
![add-ons_manager](https://cloud.githubusercontent.com/assets/1514/15905601/5b4985b8-2dad-11e6-9177-6d447e0afdfe.png)

### `Installed/Disabled`
![add-ons_manager](https://cloud.githubusercontent.com/assets/1514/15905566/388d5acc-2dad-11e6-9457-8302db6f126b.png)

_Both `Uninstalled` and `Installed/Disabled` look the same in the UI._

## Core State Changes

- When `Uninstalled` click the button will **install** the Addon. At which point it's implicity **enabled**.
- When `Installed/Enabled` clicking the button will **uninstall** the add-on at which point it's implicitly **disabled**.
- When `Installed/Disabled` clicking the button will just **enable** the add-on (Once we have an API for that)

## The issues

* There's no way to go from installed enabled to just disabled. Clicking the button when installed will simply uninstall the add-on.
* It's a little bit unclear what the button actually does e.g. we rely a lot on visuals without anything really saying what's going on. Is that a problem?

**Comment by muffinresearch** [comment]
@designakt @pwalm I'd be interested on your thoughts on this as this is what we're working towards.

**Comment by pwalm** [comment]
In the revised pref pane designs (coming soon! one day!), this is taken into account. Meaning we're in a weird middle place.

<img width="885" alt="screen shot 2016-06-08 at 6 17 08 pm" src="https://cloud.githubusercontent.com/assets/6797635/15916231/4000d57a-2da5-11e6-8858-3e45576e3a10.png">

The revised states are:
- **Active** (installed, running)
- **Inactive** (uninstalled or installed, not running)
- **Disabled** (installed, cannot be run by user)
Users then can remove any of these add-ons by clicking the small "x" that appears on hover.

Now, this is not built, so it's all hypothetical. Since the install switch isn't implemented in about:addons prefs yet, this `uninstalled` and `uninstalled/disabled` issue isn't a concern (for me, @designakt might feel differently), since once the user goes into about:addons prefs there are `disable/enable` and `remove` buttons to address those actions.

That was long-winded. To address your concerns:
> There's no way to go from installed enabled to just disabled. Clicking the button when installed will simply uninstall the add-on.
That's ok. This will only happen on about:addons for now, and will be changed in the future.

>  It's a little bit unclear what the button actually does e.g. we rely a lot on visuals without anything really saying what's going on. Is that a problem?
For the time being, no. It's something we should watch though, and solicit feedback during the Nightly rollout. That being said, are we still highlighting the new add-on in the menu bar using the tour UI? That is the final "Success, you've installed it, this is wear it lives" part of the flow.

**Comment by muffinresearch** [comment]
> That being said, are we still highlighting the new add-on in the menu bar using the tour UI? That is the final "Success, you've installed it, this is wear it lives" part of the flow.

The ui tour is not implemented at all and I'm not clear on where that's at. So at the moment there is no feedback to installing an add-on and the only feedback to the installation of the theme is the bar at the top.

**Comment by designakt** [comment]
_muffinresearch:_
> It's a little bit unclear what the button actually does e.g. we rely a lot on visuals without anything really saying what's going on. Is that a problem?

_pwalm:_
> are we still highlighting the new add-on in the menu bar using the tour UI? That is the final "Success, you've installed it, this is wear it lives" part of the flow.

and where we tell you with words that the add-on is now ready to use.

_muffinresearch:_
> The ui tour is not implemented at all and I'm not clear on where that's at.

@muffinresearch @andymckay So what does it take for progress on that?
Will we be able to have that install-confirmation in 48?

![138946213](https://cloud.githubusercontent.com/assets/8145891/15358442/c25d2f84-1d04-11e6-9308-bce35a92d25b.png)

**Comment by muffinresearch** [comment]
Ok so I think we covered everything in this discussion and #565 has been implemented.
