### ISSUE TITLE
User profile is still displayed after logging out

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5668]
Steps to reproduce:
1.Login to AMO prod
2.Go to your user profile view
3.Log out

Expected results:
AMO homepage is displayed

Actual results:
User profile is still displayed even if user is logged out

NOTES:
Even if user is logging in with another profile, the old profile is still displayed until you go again to "View my profile"

**Comment by bobsilverberg** [comment]
I think that the first issue reported has been discussed before, and it was decided that it should remain thus. The second issue (in the NOTES: section), however, does sound like a bug.

**Comment by willdurand** [comment]
I don't think there is any bug here, user profile pages are public and the username is part of the url, so when you log in you remain on the same user profile page.

**Comment by willdurand** [comment]
Closing this issue and marking it as "invalid" because there is no issue as far as I understand.

To add more context: a user profile page has a URL including the username, so when you "browse your user profile", the URL ends with `/user/:username/`. When you log out, you stay on this page, so you are still on `/user/:username/`. When you log in again with a different account, you are redirected to the page where you initiated the login process, that is: `/user/:username/`.

**Comment by bobsilverberg** [comment]
That all makes sense @willdurand, but I wonder if the use case still has some validity? If it does then we could perhaps introduce a new URL that is for "my profile", which is linked to from the menu, and always shows the current user's profile. Then, if you are on that page, and log out and back in again, it *would* take you to the new user's profile.

Does that seem like something worthwhile to support?

**Comment by willdurand** [comment]
> Does that seem like something worthwhile to support?

How many people have and switch to different user profiles on a daily basis? I don't think the use case is worth the effort involved here.
