### ISSUE TITLE
Save button from edit collection page remains disabled when an add-on is added/removed from the collection

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5702]
Follow up for #5635 

STR:

1. Log in to AMO -dev
2. Go to View my Collections and choose one of your collections to edit
3. Add an new add-on to the collection
4. Observe the 'Save collection' button

Actual results:
Save collection button remains disabled when an add-on is added/removed from the collection

Expected result:
Save collection button should be enabled when a new add-on is added to the collection to allow the users to confirm their updates

Notes:
- even if the new collection feature will automatically save an add/remove add-on action without having to hit the save button, showing a disabled 'Save Collection' button after one of the above actions is taken is counter-intuitive. With this installment, the user has only the option to 'Cancel" the form in order to leave the Edit collection screen
- reproduced on AMO -dev with FF61, Win10x64 and Android 8.0

![save collection](https://user-images.githubusercontent.com/31961530/43127189-88345a10-8f37-11e8-9371-9346fcf6fd8a.gif)

**Comment by bobsilverberg** [comment]
This is entirely intentional and is fact the main reason we made this change. We do not want users to think that they need to "Save" the collection after editing the add-ons (adding, removing, changing notes), which is why we have disabled the button. It could be that more work can be done to improve the UX for this, but enabling the Save button when it's unnecessary will not be one of them.

Note that there is still one UX improvement that has been submitted and is in review that will move the select box for adding a new add-on out of this edit form, and that should make things a bit less confusing for users.
