### ISSUE TITLE
Look into GA install type to see why there is an invalid type appearing

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5707]
### Describe the problem and steps to reproduce it:

In GA, there used to be just an extension or theme type but now an invalid category is coming up (on prod). 

### Anything else we should know?

This has something to do with the action type. We should look into these changes pertaining to this

**Comment by AlexandraMoga** [comment]
I have checked this on AMO dev and stage by installing each available add-on type and here is what I've got in the console:

- for extensions, dictionaries, language packs and search tools ->` "eventAction":"addon" `
- for LWT -> `"eventAction":"theme"`
- for static themes -> `"eventAction":"statictheme"`

@willdurand I believe this is what is expected now. If there is something else that we should check please let me know, otherwise I will mark the issue as verified fixed.

**Comment by vcarciu** [comment]
Verified as fixed : 
![galangpack](https://user-images.githubusercontent.com/1583842/43266086-1eade7ce-90f3-11e8-979e-0d3606311998.png)
