### ISSUE TITLE
"Add-on belongs to the collection" message is not dismissed from the edit collection page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5722]
STR:

1. Log in to AMO stage
2. Go to View my Collections
3. Choose one of your collections to edit
4. In the search field, try to add an add-on that is already included in your collection
6. After the "Add-on belongs to the collection" message is received, click on 'Back to collection'
7. Click again on Edit this collection on the details page

Actual result:
"Add-on already belongs to the collection" message is not dismissed

Expected result:
There are no error messages in the edit collection page

Notes:
- reproduced on AMO dev and stage with FF61, Win10x64

![2019-01-22_08-38-34](https://user-images.githubusercontent.com/31961530/51516808-46ace200-1e21-11e9-8dad-ef661cfb3167.gif)

**Comment by bobsilverberg** [comment]
This is happening because the `CollectionAddAddon` component now has its own error handler in order to display the message above the select box. So when we save the collection, via the `CollectionManager`, the `CollectionManager`'s error handler is cleared, but not the `CollectionAddAddon`'s error handler. I'm not even sure how we'd get access to the `CollectionAddAddon`'s error handler from the action that is dispatched when the collection is saved.

@kumar303 do you have any advice?

One thing we could do, which is a bit of a cheat, would be to use the same fade out technique for the error message that we use for the success message, but I'm not sure that's a good idea.

**Comment by AlexandraMoga** [comment]
* Note that the same behavior can be noticed when an addon is added to a collection where it already belongs from the addon details page.

**Comment by kumar303** [comment]
This is a limitation of our error handlers. We might need https://github.com/mozilla/addons-frontend/issues/3101 to fix it. Otherwise, there could be some hacks in forcing an update or checking for location changes in redux, maybe.
