### ISSUE TITLE
Use the collection owner when adding an add-on to a collection from the collection edit screen

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5935]
The function that should allow users with either `Admin:Curation` or `Collections:Contribute` to add add-ons to collections that they do not personally own is currently not working. That's because the code that calls the API assumes that the current user is the owner of the collection. We need to change the code in `CollectionAddAddon` to use the username of the owner of the collection, rather than the username of the current user, when trying to add an add-on to a collection.

**Comment by kumar303** [comment]
Could you add STR for QA?

**Comment by bobsilverberg** [comment]
STR:

1. Log in with a user with the `Admin:Curation` permission.
2. Navigate to a collection owned by `mozilla`.
3. Click the "Edit this collection" button.
4. Add an add-on to the collection.

Step 4 should work properly, whereas without this fix it would yield an error message.

You can also test with a user with the `Collections:Contribute` permission, in which case the only mozilla collection you can edit would be the one found at https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/featured-personas/

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this on AMO -dev with FF61(Win10)
1. Admin:Curation permission works - I could edit the mozilla collections (add, remove add-ons) without problems.
2. Collections:Contribute - I could click the featured themes from here https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/featured-personas/ then edit it by adding/removing items but when I go to AMO dev - click the link [See more featured themes](https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=statictheme%2Cpersona) I don't see the added new add-ons. It won't work for removed add-on too because I can still see them in the list.

I added "Firefox Galaxy" theme and "The Galaxy of Andromeda" theme but  they're not available from AMO "See more featured themes" link

![added but not visible](https://user-images.githubusercontent.com/33448286/44205409-f8533300-a15e-11e8-8ecc-b9d0539956d6.gif)

**Comment by bobsilverberg** [comment]
@ioanarusiczki So it's only when accessing the featured themes via the https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=statictheme%2Cpersona link that you don't see your changes?

If that's the case then I think it's either a server issue, or maybe just a timing issue. There's some magic on the server side that adds/removes the "featured" flag to/from a theme when it's added/removed from this collection. So I think that either:
1. That logic is broken on the server, or
2. It's updated via some sort of scheduled task, which only runs every so often, and that's why you don't see it updated immediately.

@diox can you confirm which of the two you think is the case (or if maybe it's something else entirely)?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Yes, I don't see the changes via 

> https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=statictheme%2Cpersona

The collection's page shows it's been added/removed without problems  https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/featured-personas/  But when I access the other link it won't show the changes made.

**Comment by bobsilverberg** [comment]
Re-pinging @diox about the question asked above at https://github.com/mozilla/addons-frontend/issues/5935#issuecomment-413524544.

**Comment by diox** [comment]
Updating a featured collection should trigger a reindex of the add-ons in that collection, allowing clients to find them using the `featured` parameter. That should definitely happen asynchronously, but it shouldn't take more than a few minutes.

Not sure why it's not updating here. I guess it's a bug.

**Comment by bobsilverberg** [comment]
@ioanarusiczki Could you please verify how long it takes for changes to be reflected at https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=statictheme%2Cpersona and then open an addons-server bug describing the issue?

**Comment by ioanarusiczki** [comment]
@bobsilverberg So I'm closing this issue since I filed on server https://github.com/mozilla/addons-server/issues/9235
Problem is the changes are not reflected no matter how long I wait.
