### ISSUE TITLE
Display a notification when an add-on is removed from a collection

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5937]
This is a spin-off from #5748, because that issue discusses more than just the notification.

For this issue:
- when a user removes an add-on from a collection, display a notification similar to the one that is displayed when a user adds an add-on to a collection
- the message bar should be grey rather than  green in this case

**Comment by kumar303** [comment]
Since removal doesn't relate to the search box I think this will be a little awkward. There was another thread where we talked about putting a header over the add-on list while in edit mode. I think now is a good time to do it!

<details>
  <summary>Example of control header in edit mode</summary>

<img width="1108" alt="screenshot 2018-08-14 15 25 08" src="https://user-images.githubusercontent.com/55398/44116688-d35264e2-9fd6-11e8-9eec-11ea7eb10744.png">

</details>

<details>
  <summary>Example of notice about adding an add-on</summary>

<img width="1108" alt="screenshot 2018-08-14 15 21 43" src="https://user-images.githubusercontent.com/55398/44116704-df9e4e64-9fd6-11e8-9d2f-9ea156f59a30.png">

</details>

<details>
  <summary>Example of notice about removing an add-on</summary>

<img width="555" alt="screenshot 2018-08-14 15 26 14" src="https://user-images.githubusercontent.com/55398/44116723-e7d39a30-9fd6-11e8-82a9-c23dc1d53583.png">

</details>

What do you think, @pwalm ?

**Comment by pwalm** [comment]
After talking about this in our weekly stand-up, SHIP IT

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10&Android 8.0)
I've noticed on the Android platform an issue which is already filed here https://github.com/mozilla/addons-frontend/issues/5964 

![remove from collection](https://user-images.githubusercontent.com/33448286/44338807-d07a0d00-a487-11e8-8928-0dcf7648fa74.gif)
