### ISSUE TITLE
Edit review in a text box (not an overlay) on the listing page

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5944]
This is part of a new UX for reviews/ratings. See #5519

- Go to an add-on detail page
- Rate an add-on
- Write a review (see https://github.com/mozilla/addons-frontend/issues/5942)
- Go to the review listing page
- Click *Edit my review*

This should let you edit the review in a text box, not an overlay.

**Comment by ioanarusiczki** [comment]
Verified on AMO dev with FF62(Win10 and Android 8.0)
Filed 2 issues here https://github.com/mozilla/addons-frontend/issues/6272 and here https://github.com/mozilla/addons-frontend/issues/6271

@kumar303 I need a confirmation for this because I think it is an expected behavior but not completely sure : if the text box is opened for edit on the detail page it will be displayed as open on the listing review page too if the user clicks the "Read all reviews" link (see the .gif below). Text typed in without clicking the "update review" button is not visible if user navigates from one page to the other clicking the "read all reviews" from the detail page and the name of the add-on from the listing review page. 

![the opened text box](https://user-images.githubusercontent.com/33448286/45688136-3e822480-bb59-11e8-8a23-a8e568042c60.gif)
