### ISSUE TITLE
prouni

### ISSUE THREAD

**Issue by higorrodrigues3443** [mozilla/addons-frontend#5991]

**Comment by jvillalobos** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
