### ISSUE TITLE
Wunderlist plugin missing

### ISSUE THREAD

**Issue by Asadlerpwcom** [mozilla/addons-frontend#5995]
The link from the Wunderlist website to the extension is broken:

https://www.wunderlist.com/integrations/external/add_to_wunderlist_firefox

https://addons.mozilla.org/en-us/firefox/addon/add-to-wunderlist/

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

I think it makes the most sense to contact the wunderlist authors directly and make them aware.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
