### ISSUE TITLE
Warning: Encountered two children with the same key (in MetadataCard)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6010]
There is a key problem with `MetadataCard`. Here is the full warning:

```
Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (created by MetadataCard)
    in MetadataCard (created by AddonMetaBase)
    in div (created by AddonMetaBase)
    ...
```

This may be causing https://github.com/mozilla/addons-frontend/issues/6003

**Comment by willdurand** [comment]
That's because the `MetadataCard` used to expect string values for `title`, but now objects (`Link`) are passed. Flow does not catch it because we use this declaration:

```js
type Props = {|
  className?: string,
  metadata: Array<Object>,
|};
```

I think the `metadata` flow type should be restricted to avoid such issues.

I think it is a bad habit to pass data of very different type in a single prop, so we could maybe add a new prop `link` or an extra prop `id` that, when set, is used as the `key`. That would be only used when `title` gets a value that is not a string.

**Comment by willdurand** [comment]
@kumar303 That's because the `MetadataCard` used to expect string values for `title`, but now objects (`Link`) are passed. Flow does not catch it because we use this declaration:

```js
type Props = {|
  className?: string,
  metadata: Array<Object>,
|};
```

I think the `metadata` flow type should be restricted to avoid such issues.

I think it is a bad habit to pass data of very different type in a single prop, so we could maybe add a new prop `link` or an extra prop `id` that, when set, is used as the `key`. That would be only used when `title` gets a value that is not a string.

**Comment by bobsilverberg** [comment]
@willdurand I think you make a good point, and this is something we should tackle, but we'd also like to get the fix for this bug into this week's tag, so I'm going to do a simple fix for now, and open a follow-up as a code quality bug.

**Comment by AlexandraMoga** [comment]
Considering that #6003 looks fixed, I'm marking this as verified fixed as well.
