### ISSUE TITLE
Hero area in homepage is too tall for common screen resolutions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#6018]
Here's how the hero area looks in a 1280x720 viewport:
![screen shot 2018-08-22 at 11 15 16](https://user-images.githubusercontent.com/62568/44479111-dc3b1000-a5fc-11e8-84d7-5367b0a996e0.png)
So, even if the window is maximized, most of the AMO homepage real estate is being taken over by the hero area, which is also not very informative and has been shown to confuse some users.

@pwalm will be looking into new designs for this for Q4, but @kumar303 suggested we could do something more short-term by maybe detecting the resolution and scaling the hero area down for those cases. Let's see what can be done and decide if it's a good stopgap measure.

/cc @devaneymoz

**Comment by kumar303** [comment]
We should add some kind of A/B testing for this so we can know if it has an impact or not.

**Comment by bobsilverberg** [comment]
> We should add some kind of A/B testing for this so we can know if it has an impact or not.

I agree that's a good idea. Can we get some requirements for how we should scale down the hero area, and also exactly what we want to test?

**Comment by jvillalobos** [comment]
Here's a proposal that cuts the height in half:
![screen shot 2018-08-31 at 11 03 44](https://user-images.githubusercontent.com/62568/44926120-a89f6a80-ad0d-11e8-9e87-194f690e2284.png)
All I did was reduce the `min-height` of the `.HeroSection-link-wrapper` to 50px, and the font size to 18px, for the panels on the right. @pwalm, what do you think? Anything else that should be changed for font and spacing?

As for the A/B test, I think we should run it for all resolutions, so we can determine which (if any) resolutions see the most change in user engagement. I'm not sure what the population size should be for the test. Probably something similar to what we used for TAAR. @muffinresearch, what do you think?

**Comment by pwalm** [comment]
Hero area proposal:
<img width="988" alt="screen shot 2018-08-31 at 4 00 12 pm" src="https://user-images.githubusercontent.com/6797635/44939002-fe3c3d00-ad36-11e8-90e2-763e05bd1447.png">

Each block would lead to an editorial article talking about what each kind of extension does, why you might need one, and a selection of 3-5 extensions to seal the deal.

**Comment by jvillalobos** [comment]
@pwalm This is for the Q4 work, right? The question was for an A/B test we want run this quarter so we can make a more immediate improvement.

**Comment by kumar303** [comment]
In the UX meeting today, we agreed that scaling down the existing home page is something we want to pursue as it has the potential to retain more page views in a session (this may or may not be the final metric we use to measure success).

As for A/B testing, we could keep it simple like the recommendations component:

https://github.com/bobsilverberg/addons-frontend/blob/27e9c8ee44927d3d3241cc6c9651a781e620d882/src/amo/components/AddonRecommendations/index.js#L65-L67
(note that this code was deleted when we discontinued the A/B test)

Instead of setting a cookie, I'm imagining that this would just send a Google Analytics event so that we can differentiate between the two user sessions -- one where they saw the existing header and another where they saw a scaled down header.

As part of this issue, it might be nice to introduce a generic higher order component for A/B testing. This could be done in a future issue, too.

**Comment by rebmullin** [comment]
@kumar303, thanks for the additional info : ) I'll look into this.

**Comment by muffinresearch** [comment]
> Instead of setting a cookie, I'm imagining that this would just send a Google Analytics event so that we can differentiate between the two user sessions -- one where they saw the existing header and another where they saw a scaled down header.

It would need to set a cookie otherwise the user might see a different hero render on every request.

As discussed in the design call, the A/B test should send 50% of traffic to the new variant and 50% to the existing design. Tracking should track what variant the user is exposed to and we should check we have params in any hero links to be able to know that users are clicking the hero content (this should already be the case)

**Comment by rebmullin** [comment]
@jvillalobos, just verifying the scaled down testing - is this ok for all viewports or just for larger sizes?

also, I have followed the direction noted [above / here](https://github.com/mozilla/addons-frontend/issues/6018#issuecomment-417731488) - is this ok? //cc @pwalm

**Comment by jvillalobos** [comment]
I didn't test very narrow screens where the three modules appear vertically stacked. It seems like the CSS changes would still work, but it'd be good to see a screenshot of that change. But to answer the question, yes, we want to test on all resolutions to see which ones if any see engagement differences.

**Comment by rebmullin** [comment]
ok cool, thanks for the info.

Regarding screenshots, here are some mobile and tablet examples:

## Mobile
![Alt text](https://monosnap.com/image/NKugWvSbH6ITBWpubbQ3kt4tFyAkCd.png)

## Tablet
![Alt text](https://monosnap.com/image/BuNp1vLk5xQKKWiFr4SFRqybH7QKGK.png)

@jvillalobos @pwalm

**Comment by jvillalobos** [comment]
lgtm

**Comment by pwalm** [comment]
Yep, signed off.

**Comment by ioanarusiczki** [comment]
@rebmullin 
I see the changes - the new view is available on AMO dev - FF62 - Win10
![new view on desktop](https://user-images.githubusercontent.com/33448286/45631134-e7ba1380-baa2-11e8-851a-2c9f4a99adaf.png)

But on Android (8.0) I still see the old view - AMO dev - FF62
![old view on android](https://user-images.githubusercontent.com/33448286/45631169-fe606a80-baa2-11e8-8490-b72823ce32ca.png)

**Comment by willdurand** [comment]
@ioanarusiczki there is an a/b experiment, so maybe on Android you are in the second cohort (which sees the large hero blocks)

**Comment by rebmullin** [comment]
hey @ioanarusiczki, as @willdurand mentions it could be 1 or the other. You can try deleting the cookies tho. You may have to do this a few times tho (as it's a 50% chance to get this).

**Comment by ioanarusiczki** [comment]
@rebmullin @willdurand I got lucky from the first try this morning. 
Verified fixed on AMO dev - FF62(Win10 &Android 8.0)

Android 
![newbannersandroid](https://user-images.githubusercontent.com/33448286/45672626-56de4900-bb31-11e8-8aa0-f3143885fcb8.png)
