### ISSUE TITLE
Web Mirrors 

### ISSUE THREAD

**Issue by vosk111** [mozilla/addons-frontend#6065]

**Comment by SeanPrashad** [comment]
Adding a description about your problem with Web Mirrors would help a lot ✌🏽

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
