### ISSUE TITLE
While another add-on is added to the list, "Leave a note" should be left editable 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6072]
STR:
1. Load AMO dev and go the Collection page click a collection made
2. Click the "Leave a note" button and write some text but don't save it yet
3. Make a search and add a theme/add-on to the list
4. Observe the note's text box

Actual result:
The button must be clicked again in order to edit the note and the previously typed in chars are no longer available.

Expected result:
The box is still available in edit mode.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF61(Win10). 

![note no longer available](https://user-images.githubusercontent.com/33448286/44651658-a3cb7580-a9f2-11e8-8ebd-77ca44f380ae.gif)

**Comment by bobsilverberg** [comment]
It looks like we can keep the edit form open, even after an add-on is added to the collection, by changing `resetOnUnmount` to `false` [here](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/EditableCollectionAddon/index.js#L205) (or actually removing it because `false` is the default).

I'm not 100% clear on what all of the impacts of that will be. @willdurand can you comment on whether that seems like a reasonable change to make to address this?

Unfortunately that will not keep any of the text that had been typed into the box, because that is not saved in any state. If we want to address that use case I think we need some extra code to store temporarily typed text in state, but I'm not sure the time, effort and complexity of doing that is worth it to support this particular use case (i.e., preserving text a user has typed into a note when they add or remove an add-on to/from a collection).

**Comment by bobsilverberg** [comment]
Ah, so I noticed an issue with using `resetOnUnmount: false` here. If we do that, then the "edit a note" text box will remain open for the add-on every time the Edit Collection screen is accessed, even for a different collection. I think we could address that by changing `extractId` in `EditableCollectionAddon` to include both the `addonId` and the `collectionId`, although currently the `EditableCollectionAddon` does not know anything about the current collection (but that's easy to fix).

@willdurand what do you think?

**Comment by willdurand** [comment]
> Unfortunately that will not keep any of the text that had been typed into the box, because that is not saved in any state. If we want to address that use case I think we need some extra code to store temporarily typed text in state, but I'm not sure the time, effort and complexity of doing that is worth it to support this particular use case (i.e., preserving text a user has typed into a note when they add or remove an add-on to/from a collection).

I'd close this issue as wontfix, this part of the UI reloads entirely, so it is expected to loose the content in the note textarea. I doubt this is a use case, either users add new add-ons or leave comments. I don't think users will start leaving a note and then decide to add a new add-on.

**Comment by bobsilverberg** [comment]
@willdurand So you don't think it's worth addressing just the closing of the text box by using `resetOnUnmount: false`? Isn't that why that option exists?

**Comment by willdurand** [comment]
I don't think it is worth fixing indeed.

`resetOnUnmount` is used when we want to mimick React `setState` behavior.

**Comment by bobsilverberg** [comment]
Fair enough. I do agree that the use case is quite edgy and unlikely to affect an average user.
