### ISSUE TITLE
Make user profile reviews look like add-on reviews (mostly)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6104]
Make user profile reviews look identical to add-on reviews with a few exceptions:

* user profile replies will appear on their own, without the original review (~~and styled the same way, with a blue background, etc~~; see https://github.com/mozilla/addons-frontend/issues/5858#issuecomment-417794798 for styles)
* ~~user profile reviews need to indicate the add-on they are attached to~~ (this will be handled in https://github.com/mozilla/addons-frontend/issues/5858)

Why make user profile reviews look identical to add-on reviews?

* we can share more component code and remove hacks like the forked byline
* we can implement deleting reviews easier (see https://github.com/mozilla/addons-frontend/issues/5495)
* reviews will be editable and flaggable on the user profile page (i.e. we get all the features)

**This issue depends on https://github.com/mozilla/addons-frontend/issues/5943 because we will need a shared review component for both**

**Comment by kumar303** [comment]
From the UX meeting today, @pwalm agrees 👍

**Comment by bobsilverberg** [comment]
@pwalm Do we want user replies in the User Profile to appear with the blue background like replies on the Reviews Listing? I'm not sure that looks very good and am thinking that maybe they should just look like regular reviews, but with a heading that says "Developer response". Here's what the screen currently looks like, with the blue backgrounds, and I am suggesting we lose the blue background for replies on the User Profile.

![screenshot 2018-08-30 13 52 43](https://user-images.githubusercontent.com/142755/44869598-fcea1200-ac5b-11e8-9fc5-8b98aa887050.png)

**Comment by pwalm** [comment]
Is this a response to a developer response?

**Comment by pwalm** [comment]
Proposed adjustments:
<img width="1308" alt="screen shot 2018-08-31 at 2 30 58 pm" src="https://user-images.githubusercontent.com/6797635/44936679-8b2cc980-ad2a-11e8-8e3f-13f7d49110be.png">

**Comment by AlexandraMoga** [comment]
Verified on -dev and stage with FF62, Win10x64 and Android 8.0

- the user has now the option to write a review (for previously rated add-ons), Edit their reviews, Delete their reviews or Flag a dev reply left for one of their reviews. Additionally, developers can edit or delete their replies

![image](https://user-images.githubusercontent.com/31961530/46071525-e2d31f00-c188-11e8-89f5-6dd62dc61f18.png)


@bobsilverberg  I have some observations:
- I've read your discussion around having a Flag option for reviews on user profiles and judging by the conclusion from https://github.com/mozilla/addons-frontend/pull/6285#issuecomment-422822206, the Flag option will be made available _only_ for a reply left by another developer. I believe this should be addressed soon enough, otherwise the users will have to see this redundant Flag option next to their reviews.

- I've noticed that, when signed in as a developer, your own replies won't have a blue background anymore.
However, replies left by other developers do have this blue background. I'm not seeing this as an issue, but I wanted to confirm with you that this was indeed intended. 

![image](https://user-images.githubusercontent.com/31961530/46071538-e9fa2d00-c188-11e8-9398-17dfc1649d1b.png)




I've also filed some follow ups, which were linked to this issue.

**Comment by bobsilverberg** [comment]
> I've noticed that, when signed in as a developer, your own replies won't have a blue background anymore. However, replies left by other developers do have this blue background. I'm not seeing this as an issue, but I wanted to confirm with you that this was indeed intended.

Do you mean that your own replies that show up as top-level items (as opposed to inside reviews to which they are a reply) are the ones without the blue background? If so then yes, that is intended. If a reply is displayed *inside* a review (because it is a reply to the review) it should still have a blue background. So if I am interpreting your observation correctly, this is all intended.

**Comment by AlexandraMoga** [comment]
@bobsilverberg Thanks. That was my question and your answer clarified it.
