### ISSUE TITLE
Installing a non-restartless extension says it is corrupt

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6240]
### Describe the problem and steps to reproduce it:

- Go to https://addons.mozilla.org/en-US/firefox/language-tools/
- Follow a link to one of the first dictionaries: https://addons.mozilla.org/en-US/firefox/addon/akan-ns%C9%9Bmfuaasekyer%C9%9B/
- Install it in Firefox 62

### What happened?

It cannot be installed because it's non-restartless, which is not supported. In the browser console:

```
1536858701111	addons.xpi	WARN	Download of https://addons.mozilla.org/firefox/downloads/file/376172/akan_spelling_dictionary-0.9.1-typefix-fx.xpi?src=dp-btn-primary failed: Error: Non-restartless extensions no longer supported (resource://gre/modules/addons/XPIInstall.jsm:646:13) JS Stack trace: loadManifestFromRDF@XPIInstall.jsm:646:13
loadFromRDF@XPIInstall.jsm:786:23
```

In the UI:

<img width="922" alt="screenshot 2018-09-13 12 11 50" src="https://user-images.githubusercontent.com/55398/45504052-6551ec80-b74e-11e8-8717-f632911269d8.png">

### What did you expect to happen?

We should show an incompatible banner just like for other incompatible extensions.

### Anything else we should know?

It's weird that this extension is listed at all but that's a separate bug: https://github.com/mozilla/addons-server/issues/9418

**Comment by willdurand** [comment]
I have just uploaded this add-on in -dev: https://addons-dev.allizom.org/en-US/firefox/addon/akan-spelling-dict-issue-6240/

**Comment by AlexandraMoga** [comment]
@willdurand related to this subject, with the new install buttons, when an add-on can't be installed, there is no error message displayed anymore. 

In the previous set-up, when an add-on failed to install, we used to see a prompt mentioning that the addon is "corrupt" or "incompatible" for example. 

I've tried with `extensions.webextPermissionPrompts` both `true` and `false`

**Comment by kumar303** [comment]
According to https://hg.mozilla.org/mozilla-central/rev/6b6162e51247#l1.32 , non-restartless extensions were dropped in Firefox 61 (via https://bugzilla.mozilla.org/show_bug.cgi?id=1446686)

**Comment by kumar303** [comment]
@AlexandraMoga 

> when an add-on can't be installed, there is no error message displayed anymore.

I see the *add-on is corrupt* message with the new install button. Can you file a new bug with STR?

**Comment by kumar303** [comment]
Ah, here is a more intentional sounding bug (the title, anyway): https://bugzilla.mozilla.org/show_bug.cgi?id=1448221

**Comment by AlexandraMoga** [comment]
I've verified this on AMO -dev with FF60 esr, FF61 and FF62, WIn10x64

1. On 60esr - the Add to Firefox button is enabled and the add-on can be installed

![image](https://user-images.githubusercontent.com/31961530/45811054-cf313f80-bcd4-11e8-8afa-64447bf06c5e.png)

2. On 61 and above - the Add to Firefox button is disabled, an incompatibility banner is displayed and the add-on can't be installed


![image](https://user-images.githubusercontent.com/31961530/45811567-17049680-bcd6-11e8-9565-9151c9ad5ef7.png)


@willdurand I'm not entirely sure that the incompatibility message is very informative, since it says that the add-on is not compatible with the user's platform, when in fact this has to do with the version of Firefox he is using. 
I've seen in disco pane, for example, that we also have the following error message, which it looks more representative for this case:

![image](https://user-images.githubusercontent.com/31961530/45811526-005e3f80-bcd6-11e8-8bf4-de5c793080a7.png)

**Comment by AlexandraMoga** [comment]
or even a better example:

![image](https://user-images.githubusercontent.com/31961530/45811918-0f91bd00-bcd7-11e8-9007-8004609d62f5.png)

**Comment by AlexandraMoga** [comment]
Opened #6323 as a follow up issue.
Marking this issue as verified fixed on dev and stage.
