### ISSUE TITLE
Use cache immutable

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#632]
http://bitsup.blogspot.ca/2016/05/cache-control-immutable.html?m=1

This will cut down on all those super fast 304 hits, as long as our URLs are definitely immutable. Rumour has its landing in Firefox 49.

**Comment by muffinresearch** [comment]
@bqbn when you have a moment could you look at adding this to all our statics served from the CDN that currently have far-future expires?

**Comment by bqbn** [comment]
Yep, I'll try to implement this next week.

**Comment by bqbn** [comment]
This is filed under addons-frontend repo, but I assume this is for the desktop site as well?

**Comment by kumar303** [comment]
> I assume this is for the desktop site as well?

I think we only want it for assets served from the CDN

**Comment by bqbn** [comment]
> > I assume this is for the desktop site as well?

> I think we only want it for assets served from the CDN

So I assume the answer to my question is yes, since the desktop site uses CDN too.

**Comment by muffinresearch** [comment]
> So I assume the answer to my question is yes, since the desktop site uses CDN too.

Yes any static assets that are currently served with far future expires and require a url change to bust cache.

**Comment by bqbn** [comment]
This is now on -dev and -stage.

**Comment by muffinresearch** [comment]
Looks good to me:

CSS:

<img width="470" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/35512259-058cf66e-04f7-11e8-8fa4-c7c1ea2c60d6.png">

JS: 

<img width="532" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/35512286-26dd1222-04f7-11e8-9ffe-5db6d9600bdb.png">

@bqbn Out of interest I note on this response there are two headers rather than one: 

<img width="674" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/35512354-695545de-04f7-11e8-96d6-c7896b6cb8e2.png">

**Comment by bqbn** [comment]
This is now on -prod as well.

I notice that files that are already in CDN before today's release will still get 304. But if you change the number in the query string to some random value, it'll force the CDN to talk to the origin (nginx in this case) to retrieve the file and the immutable header. 

I don't know if it's worth the effort invalidating our CDN cache though. One side effect of doing that is more requests will hit the origin and increases its load. I think overtime with new releases coming out, more and more files will get the immutable cache-control header.
