### ISSUE TITLE
Edit collection page closes when the language is changed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6341]
STR:
1. Load AMO dev and open one of your collections
2. Click Edit collection details, make some changes (edit the text)
3. Change the language 
4. Observe the screen

Actual results:
Collection's page is displayed not the edit page and edited text is lost.

Expected results:
The Edit collection page is still displayed.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF62(Win10). 

![language3](https://user-images.githubusercontent.com/33448286/45879035-b6e02400-bdab-11e8-96b6-01850911677d.gif)

**Comment by willdurand** [comment]
I think that's because there is a page reload, no?

**Comment by ioanarusiczki** [comment]
@willdurand Yes, just like in any screen actually - when another language is selected from the page's footer is looks like it reloads.

**Comment by kumar303** [comment]
Yeah, this would be nice to fix. Using Redux for language changes will be hard, though, since it may require some hacks to our "dynamic" locale loader code.

Here is an issue about using Redux for language changes: https://github.com/mozilla/addons-frontend/issues/1640

I'm going to keep both open, though, because this one provides a concrete example of a bug that can be fixed. The older issue is written from a very technical perspective which could be confusing.
