### ISSUE TITLE
Simplify the 'rating saved' notification

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6345]
### Describe the problem and steps to reproduce it:

- Sign in
- Go to an add-on you haven't rated
- Select a star to rate the add-on

### What happened?

You see a green notification banner

### What did you expect to happen?

You should see a text notification with a green check mark (no banner)

<details>
<summary>Example</summary>

![ratings and reviews flow v2](https://user-images.githubusercontent.com/55398/45893948-8a6bde00-bd92-11e8-8c76-f4a85c95ef1e.png)

</details>

**Comment by bobsilverberg** [comment]
@kumar303 Do you think we should rip out all of the code in [`RatingManagerNotice`](https://github.com/mozilla/addons-frontend/tree/2018.09.20-2/src/amo/components/RatingManagerNotice) which implements the `Notice` component, because it doesn't seem like we need it anymore, or do you think we should leave it in place, in case we do want to show a `Notice` at some point, and just use the alternate code path that also already exists in `RatingManagerNotice` for a non-Notice?

**Comment by bobsilverberg** [comment]
> We have /src/ui/components/Notice/img/check-mark.svg@2018.09.20-2, but I think it may be too big, and also isn't green.

I copied the svg mentioned above, made it green, using the equivalent of `$green-60` and adjusted the size using css. It may or may not be satisfactory.

**Comment by ioanarusiczki** [comment]
Looks good to me. Verified fixed on AMO dev with FF62(Win10&Android 8.0) 
The "Saving star rating" message appears for a very short time before "Star rating saved".
![star rating saved](https://user-images.githubusercontent.com/33448286/46293833-31bff080-c59d-11e8-8a5c-e8e73a19fde8.png)
