### ISSUE TITLE
hotfix 10072018(2).exe

### ISSUE THREAD

**Issue by jillpip** [mozilla/addons-frontend#6394]
### Describe the problem and steps to reproduce it:

Total AV offered a free safe website browsing download for Firefox. Followed the link and Firefox informed me no such link

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
