### ISSUE TITLE
The add-on card reloads when the time stamp of a review is clicked 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6478]
STR:
1. Load AMO dev and go to a page of reviews
2. Click the time stamps of the given reviews and observe the left side of the screen

Actual result:
The add-on card reloads every time a time stamp is clicked

Expected result:
The add-on card won't reload 

Notes:
This issue is reproducible on AMO dev with FF62-Win10

![breakdown reloads](https://user-images.githubusercontent.com/33448286/46335852-8e6ceb00-c631-11e8-9fb4-230919561e48.gif)

**Comment by willdurand** [comment]
@kumar303 did you see this issue by chance?

**Comment by kumar303** [comment]
> @kumar303 did you see this issue by chance?

Apparently I did not.

@ioanarusiczki thanks for the bug report. It happens because when fetching and loading a review, the rating counts might need to be recalculated. In this case, it's pretty unlikely that the rating counts would change but if you load the review detail page directly (or press the browser refresh button) then the rating counts would definitely need to be calculated. I don't want to make a special case just for this.

**Comment by xu3u4** [comment]
Hi @willdurand and @kumar303 ,
cc. @bobsilverberg 
I looked into this bug few days ago. I have some thought about it.
In [FeaturedAddonReview/index.js](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/FeaturedAddonReview/index.js#L66`), `this.props.reviewId !== nextProps.reviewId` will trigger fetchReview, which reloads the review scores. Since it only need the `featuredReview`, maybe we don't need the condition?
Or is anything I missed?

If you agree with it, I'd like to send a PR for it.
