### ISSUE TITLE
Install buttons have functionality issues in responsive design mode

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6481]
STR

1. Open AMO - https://addons.mozilla.org/en-US/firefox/
2. Go to an add-on details page
3. Enter responsive design mode
4. Install the add-on

Actual result:
The installation is completed but the install button is stuck in the animation state

Expected result:
Add to Firefox changes to Remove after installation completes

Notes:
- for LWT, the install button doesn't work at all
- reproduced on all AMO servers with FF62, Win10x64

[add-on installation]
![add-on install rdm](https://user-images.githubusercontent.com/31961530/46344848-37740f80-c64b-11e8-800b-eceae23aab78.gif)

[lwt installation]
![lwt install](https://user-images.githubusercontent.com/31961530/46344909-5a062880-c64b-11e8-9d94-b6ed5948a0ee.gif)

**Comment by willdurand** [comment]
@AlexandraMoga can you try to refresh the browser before continuing the step 2 of the STR. I don't think this is an issue with the website but rather an issue with the responsive design mode (we already had issues with it in the past).

For me, everything works fine (after having refreshed the page in responsive mode). LWT don't work because `mozAddonManager` is not used for them.

**Comment by AlexandraMoga** [comment]
@willdurand  I can see the correct installation flow only when I refresh the page _after_ entering responsive design mode (step 3)

If you think that the problem doesn't come from AMO, we can close this issue and I can try to file a bug on the Firefox side.

**Comment by willdurand** [comment]
I don't think it is a bug with AMO.
