### ISSUE TITLE
Consider removing the `logRequests` middleware

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6484]
The [`logRequests`](https://github.com/mozilla/addons-frontend/blob/1e8e81c5b726959a465d79de6a4fe99247ddf987/src/core/middleware/logRequests.js) middleware is logging both the full `req` (request) and `res` (response) objects. It adds a huge amount of useless information on the console, and I don't think we need this middleware. In addition, it is not used in production since the log level is `debug`.

Can we remove it?

**Comment by kumar303** [comment]
What do we gain by removing it? Is it creating too much noise when you turn on debug logging? If my guess is correct, then I suggest introducing a separate config param to turn it on/off.

I'd like to keep this middleware around just in case we need it because mat has already needed some server request logging to debug another issue and we don't new relic set up yet (I think).

**Comment by willdurand** [comment]
> I'd like to keep this middleware around just in case we need it because mat has already needed some server request logging to debug another issue and we don't new relic set up yet (I think).

This middleware logs the request/response of our server (`server/base.js`) only, not all reqs/resps sent by the app. I am not sure how useful this can be for mat or anyone.

**Comment by kumar303** [comment]
Yeah, that's exactly what mat needed. It's important because you can't see that in the console when looking at a production request/response.

**Comment by kumar303** [comment]
Oh, wait, sorry, he was looking for API requests/response. Sorry, multi-tasking too many things. You can delete it! Hah. I agree that it is probably not useful. We have nginx logs.
