### ISSUE TITLE
Add admin user link to user profile page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#6487]
(Similar to #4632 but for users)

This link would appear in the left box, somewhere below the ratings (along with "Report user for abuse" and "Edit user" buttons):

"Admin user". Goes to `/admin/models/users/userprofile/ID/` (note that the slug won't work). Requires `Users:Edit` and `Admin:Tools` to appear.

**Comment by AlexandraMoga** [comment]
@bobsilverberg, @wagnerand the Admin User link doesn't seem to work as expected. I have the following scenario:

1. I log in on AMO frontend with an account that has `Admin:Tools` and `User:Edit` permissions
2. I'm opening a User profile page and I'm selecting the Admin user button
3. Since I'm entering to the admin domain, I'm asked to log in again
4. After logging in with the same user, I'm receiving a "Not allowed" error
5. If I'm navigating manually to `/admin/models/users/` I can see that I have the required edit permissions

![2018-11-14_17-06-13](https://user-images.githubusercontent.com/31961530/48491816-19482480-e831-11e8-87db-a1dfe88403a2.gif)

**Comment by bobsilverberg** [comment]
@AlexandraMoga This sounds like a server issue. We just need to verify that the link shown on the User Profile page is the correct link. What happens if you log into the Django Admin site first, and then go to the User Profile and click the link? Does it take you to the correct page without any errors in that case?

**Comment by AlexandraMoga** [comment]
@bobsilverberg yes, I'f I'm already logged in the Django Admin solves the problem for the frontend and I'm able to access the required page:

![2018-11-15_11-38-38](https://user-images.githubusercontent.com/31961530/48544232-d38c6a00-e8cb-11e8-88ad-3592bd5ca108.gif)

I'm going to mark this issue as verified fixed and will open a follow up on addons server for what I've noticed before.

**Comment by bobsilverberg** [comment]
Thanks @AlexandraMoga!
