### ISSUE TITLE
design install confirmation for Firefox 48

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-frontend#658]
It seams that we will not be able to access the UI Tour components in 48 after all. Therefor we need a design to bridge the gap till 49 hits.
I would suggest doing something that will be similar to what we will have in 49, but only on the page itself. It could be just the same confirmation, but without the connection to the toolbar. That would at least direct the user's focus to the area of the screen where the add-on appeared.

![discopane_installconfirm](https://cloud.githubusercontent.com/assets/8145891/16394451/91369fe6-3cb5-11e6-9e95-0e08c0768a2a.png)

@pwalm what do you think. Is this visually OK?
@muffinresearch fyi

**Comment by muffinresearch** [comment]
Presumably we know we will always have something added to the toolbar?

There's a bit of a disconnect in the sense of what "here" means in "Click _here_ to access uBlock Origin whenever you need it". 

We have a bug filed to allow the uitour on about:addons [1]  but if that can't be fixed in time we might have to pull this together quickly. We definitely can't ship without user feedback to add-on installs.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1281847

**Comment by designakt** [comment]
For the first version we will always have something added to the toolbar, as those add-ons are the ones easiest understood by users.
In terms of copy we need to check with @devaneymoz https://github.com/mozilla/addons/issues/142#issuecomment-228028673 . The copy for 48 also might have to differ from the future one, as it will not be connected to the add-ons button directly (but either hang from the menu button, or overlay the page).

**Comment by devaneymoz** [comment]
I agree the "here" in this case is problematic. For this stopgap fix, I'd recommend very streamlined functional messaging (note the capitalization of "Toolbar" since it's a specific product feature):

**Install complete**
Now you can access [name of add-on] from Toolbar.

**Comment by designakt** [comment]
> **Install complete**
Now you can access [name of add-on] from Toolbar. 

I know that we talk a lot about install internally but we also have evidence that users have negative associations with install. I wonder how we can make that feel lighter...

**Comment by devaneymoz** [comment]
I'm fine tweaking "install" but figured we were good there since it's in the current version of confirmation messaging. It gets wordier, but we could go with:

**Add-on enabled**
Now you can access [name of add-on] from Toolbar. 

... or...

**Your add-on is ready**
Now you can access [name of add-on] from Toolbar.

**Comment by pwalm** [comment]
```
Your add-on is ready
Now you can access [name of add-on] from Toolbar. 
```
+1,111,111

**Comment by designakt** [comment]
While implementing there was discussion outside this issue about what the copy for 48 should be. It was set as:

> **Your add-on is ready**
> Now you can access [name of add-on] from the toolbar. 

To summarize the discussion was around capitalizing toolbar or not, and whether or not a "the" is required before it.

@mheubusch I know you work on a copy style guide. What do you think?
I think the question is around whether "toolbar" is a generic term that carries across all browsers, or is it a feature term exclusive to Firefox?

**Comment by mheubusch** [comment]
@devaneymoz @designakt   the toolbar.  It's a generic noun (at least it is now - no one at FF has told me otherwise) so it s/b lowercase and takes the article "the".
