### ISSUE TITLE
Collection pages should rely on the user ID, not the username anymore

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6609]
To support https://github.com/mozilla/addons-server/issues/8302, we need to make a rather big change: not using `username` in the URL anymore but the `userId` everywhere `username` is referenced.

**Comment by HosseinMarzban** [comment]
@willdurand , i would like to work this issue, but first things first, I did some tests and find out when I change **authorUsername** to **authorId**, collection page -> collections item page, does not load any data and  stay in loading stage, I checked console log, and find out that page facing to error in loading data and try again and again in some kind of loop!
Is that okay, or it must have some changes in server routing API?

**Comment by willdurand** [comment]
@HosseinMarzban thanks, but this issue is not open to external contributors right now.

**Comment by kumar303** [comment]
@HosseinMarzban thanks so much for your interest. You can get started with a [good first bug](https://github.com/mozilla/addons-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+good+first+bug%22) and then take a look at [contrib: welcome](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome) bugs.

**Comment by HosseinMarzban** [comment]
@kumar303, willdurand tanks.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF64, Win10x64

1. Collection details URLs are now displaying the user id:
![2019-01-09_10-55-18](https://user-images.githubusercontent.com/31961530/50888258-eae46100-13fd-11e9-94a0-6d6c00086dfd.gif)

2. URLs containing a username instead of a user Id will be redirected to the new format:
https://addons-dev.allizom.org/en-US/firefox/collections/LexaSV/hopes/ - is redirected to https://addons-dev.allizom.org/en-US/firefox/collections/10640485/hopes/
