### ISSUE TITLE
Withhold reference to themes from Android

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#6689]
When Lightweight themes (LWTS) migrate to static themes there will be no themes on AMO that are installable by Android. 

Because of that we need to hide the references to themes for the Android site. 

- [x] Hide the navigations for themes on the Android site
- [x] Hide the theme search filters.
- [x] Hide the featured themes cards on the homepage
- [x] Hide the "Change the way Firefox looks with themes." card on the homepage.
- [x] Double-check that the search does not return static themes for android theme searches - e.g. if someone gets this by making a manual search.
- [x] theme category pages should return a 404: http://addons-dev.allizom.org/en-US/android/themes/fashion/
- [x] theme categories page should return a 404: http://addons-dev.allizom.org/en-US/android/themes/categories/
- [x] theme landing page should return a 404: http://addons-dev.allizom.org/en-US/android/themes/
- [x] a not found page should not have a link to the themes page

All changes should be config based so that we can reverse this in future.

**Comment by willdurand** [comment]
I updated the list of things to change.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF63, Android 8.0

The following Theme references are now hidden on Android:

- Theme navigation in the header [1]
- Featured Themes collection and Customize the way Firefox looks... shelves [2]
- Themes filter option in search [3]
- Links to "Browse all Themes" in 404 pages [4]
- `/themes/` homepage, `/themes/categories/`  and `/themes/category_name/` pages are returning 404s

For the search part - it's currently not possible to fully verify on the frontend  that manual searches won't bring static themes among the results. This is because the lwt migration wasn't completed yet and it is not clear at this moment if/when this is going to happen for -dev (@eviljeff for input)

I tried to verify with the api that a search request for static themes on android doesn't bring results, and I received the expected outcome:
see https://addons-dev.allizom.org/api/v4/addons/search/?app=android&type=statictheme 
However, this doesn't completely eliminate the need to also test this on the frontend.

[1]
![image](https://user-images.githubusercontent.com/31961530/48563698-8e812b80-e8fd-11e8-8bfd-47ff15357e68.png)

[2]
![image](https://user-images.githubusercontent.com/31961530/48563769-b96b7f80-e8fd-11e8-86ea-83ba5d6463b4.png)

[3]
![image](https://user-images.githubusercontent.com/31961530/48563751-abb5fa00-e8fd-11e8-9fc1-806977583d31.png)
[4]
![image](https://user-images.githubusercontent.com/31961530/48563788-c2f4e780-e8fd-11e8-8004-911349b79cf8.png)
