### ISSUE TITLE
Loading/Install of Extension incorrect

### ISSUE THREAD

**Issue by e-pang** [mozilla/addons-frontend#6692]
### What happened?
Animation of the loading throbber isn't implemented correctly.  The one that's located here:
<img width="77" alt="screen shot 2018-10-19 at 13 08 32" src="https://user-images.githubusercontent.com/30128313/47233266-22fc7a80-d3a0-11e8-9b3e-8c04a4f7a958.png">
The dot's motion is wobbly on the edges

### What did you expect to happen?
The animation should mimic what is seen in tab loading which is more snappy

### Anything else we should know?
If this is implemented by svg sprite I can provide a new one

**Comment by willdurand** [comment]
Hi!

> If this is implemented by svg sprite I can provide a new one

It is not implemented with a SVG sprite because it is super bad performance-wise.

Could you explain what is different *exactly*? We know that it is slightly different because we re-created the animation in plain old CSS, but no one noticed any differences so far. 

That being said, we'd **love** to try and improve the CSS-based animation if possible (because that seems to be the best option in terms of performance). Otherwise, I saw that the Firefox Monitor folks use a Gif, so that could be another option.

Thanks for your feedback!

**Comment by Patil2099** [comment]
Do we have to insert a gif in page if yes can I take this one?

**Comment by willdurand** [comment]
No, it's not about a Gif. It's about fine-tuning the CSS animation, but that's not an easy fix.

**Comment by snitin315** [comment]
I want to work on this issue.

**Comment by caitmuenster** [comment]
Hey @snitin315! We just reviewed this issue and we've decided it's a WONTFIX. I'll pop back in in a moment to help you find another bug to work on!

**Comment by caitmuenster** [comment]
Hi @snitin315, sorry for the delay! You'll want to look for issues with the label 'contrib: good first bug` to help you get familiar with the code base and also get hands-on support during the bug fix. :) 

It doesn't look like there are any tagged good first bugs in this repository at the moment. You're welcome to keep an eye on [this list](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20good%20first%20bug) for when new ones become available, or see if any other [good first bugs](https://addons-pm.herokuapp.com/contrib/good-first-bugs/?dir=desc&sort=updatedAt) are open for other add-ons projects. If nothing is available, you can find other good first bugs for other Mozilla projects by going to [codetribute.mozilla.org](https://codetribute.mozilla.org/).

**Comment by snitin315** [comment]
@caitmuenster Thanks for your help. I will check on good first issues.
