### ISSUE TITLE
Keep the edit page open after the page is refreshed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6773]
Follow up for https://github.com/mozilla/addons-frontend/issues/6729

STR:
1. Load AMO dev and go to your collections
2. Click on "Edit collection details" button
3. Refresh the page

Expected result:
Edit page is displayed

Actual result:
Edit page closes and Edit collection details button must be clicked again 

Notes:
This issue is reproducible on AMO dev and AMO stage with FF63

![edit and refresh collections4](https://user-images.githubusercontent.com/33448286/47661652-25ca4d00-dba2-11e8-8234-d24a22f5a334.gif)

**Comment by kumar303** [comment]
Thanks for the bug report. I think this bug always existed. I set a reduced priority on it because I can't think of why anyone would want the feature. If someone thinks of a reason, let me know.

**Comment by willdurand** [comment]
> If someone thinks of a reason, let me know.

There is nothing more annoying that no sync between the client and the URL. Refresh by mistake and 💥 you are somewhere else.

**Comment by kumar303** [comment]
> There is nothing more annoying that no sync between the client and the URL

It's a single page app; you can get into many states that don't match the URL. For example, submitting a rating, replying to a review, editing your profile...

**Comment by willdurand** [comment]
> It's a single page app; you can get into many states that don't match the URL

We chose to do that, that's not what SPA means. If we really want to enable users without js to use the site, we can improve things like this. That would benefit everyone I think. 

Add a query param to the collection page and user without js should be able to access the edit state/page. Not saying they can edit anything though (because we don't support POST requests on the server yet).

User profiles have their own edit pages, and ratings are left on the add-on detail pages. Replying to a review is inlined, no? All of that sounds good to me, and expected from a user POV. Yet, the edit collection page changes entirely.

Pages that change completely should reflect that in the URL IMO, which is why I think this issue makes sense. I agree that it should not have a high priority too, but that does not mean it is not legit.

**Comment by kumar303** [comment]
Yes, I think it would not be hard to add a query param to enter this state via URL and I agree that it could be useful. In my other examples, I was speaking to how refreshing the page loses your form edits but I guess that's a separate issue. I'll up priority slightly and add `contrib: welcome` 😃

**Comment by SeanPrashad** [comment]
#7053 will fix this when it lands!

**Comment by rishabh-bansal** [comment]
Hi @suhailsinghbains Can I please work on this please, I am completely new to this Mozilla.

**Comment by harshv47** [comment]
Hi @ioanarusiczki , can I work on this please?

**Comment by Albaalah** [comment]
can I please work on it?
