### ISSUE TITLE
Add `hrefLang` on other pages (not add-on detail pages)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6774]
Now that #6644 has been implemented for the add-on detail pages, we can add those `alternate` links to the other (crawlable) pages too. Some guidelines:

- We add a `x-default` link pointing to the `en-US` page
- We add a `en` link pointing to the `en-US` page
- We add a `pt` link pointing to the `pt-PT` page
- We ignore ISO 639-2 locales for now (locales with three letters, e.g., `ast`, `cak`, etc.)

## List of the pages that should have `alternate`/`hrefLang` links

- Homepage
- All category pages
- Landing pages (extensions, themes)
- Search tools page
- Language tools page
- About page
- Review Guide page
- Categories pages (used on mobile, lists all the categories for extensions or themes)

**Comment by ioanarusiczki** [comment]
@willdurand I checked the pages you mentioned and they display now the `alternate` links with `x-default` en-US, `en` and `pt` were added. Also checked the meta-properties and they're displayed. 
Because of https://github.com/mozilla/addons-frontend/issues/6689 we do not have Themes for android therefore no categories or any other pages. 

I've noticed that the `og:type` and `og:locale` are displayed for some pages right below the title in the HTML's <head> then the `alternate` links follow and at the end the rest of the meta-properties but that is not a problem since they're all added. 

Verified on AMO dev with FF63(Win10).
