### ISSUE TITLE
Extract out renderInstallError into its own component

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6902]
Now that we've used this a few times, we should make this into its own component.

QA instructions: Please make sure install error notices still appear

**Comment by ioanarusiczki** [comment]
@rebmullin I tested this issue using the dictionaries from https://addons-dev.allizom.org/en-US/firefox/language-tools/ that cannot be installed because they're missing the "id" in the manifest. - with FF63 (release and unbranded) on AMO dev 
For add-ons that cannot be installed there's an error message "Download failed. Please check your connection." Same with disco pane.

![download failed](https://user-images.githubusercontent.com/33448286/49018447-1dab0080-f194-11e8-8158-5c045e5dd64a.gif)


Let me know if there's anything else I should check.

**Comment by rebmullin** [comment]
so @ioanarusiczki, FYI - this is where the original issue came from: https://github.com/mozilla/addons-frontend/issues/6261

I think if the addon is not compatible now, you should show a red notice (like above) and the button should be disabled. I think when the original issue was filed, maybe this wasn't all set up yet. 

As far as getting other types of errors, it seems that the following are possible:
 
 - Installation failed. Please try again.
 - Download failed. Please check your connection.
 - An unexpected error occurred during installation.
 - An unexpected error occurred during uninstallation.
 - An unexpected error occurred.

Except for the "Download failed...", I am not sure how to cause each type of error to be displayed.

@willdurand, do you know? is there more info on this somewhere?

**Comment by willdurand** [comment]
I believe that if an error can be displayed then it would also work for the other errors. I don't know how to generate them on the hosted environments.

**Comment by rebmullin** [comment]
ok cool, that makes sense. So @ioanarusiczki, it sounds like the test that you have here is sufficient then.
