### ISSUE TITLE
Redirect user profile pages (only public pages, not edit pages): username => user ID

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6915]
See also: #6526

---

After #6526, all user profile pages are accessed using the user ID in the URL and not the `username` anymore. All the links generated by AMO use the user ID too, but we should support the old URLs (i.e. the URLs containing `username`s).

⚠️ we will not redirect "edit" profile URLs because those URLs are not public/published.

**For QA:** make sure that loading a profile page with a `username` in the URL redirects to the same profile page but with the user ID in the URL.

**Comment by AlexandraMoga** [comment]
In order to verify that the user profiles are correctly redirected to the new URL containing the user ID instead of the username I have started form the following page..

 https://addons-dev.allizom.org/en-US/firefox/user/Amoga-dev/

and I've been correctly redirected to this page

https://addons-dev.allizom.org/en-US/firefox/user/10641527/

While I was being redirected, I've followed the network logs and made sure that a 301 - Moved permanently entry for the user profile page was present.

![2018-11-23_15-48-07](https://user-images.githubusercontent.com/31961530/48947050-7da56b00-ef38-11e8-9098-08275a05bd40.gif)
