### ISSUE TITLE
Review count and average rating are not always updated

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6958]
### Describe the problem and steps to reproduce it:

* Log in to AMO
* Go to an add-on detail page
* Make a note of the number of reviews and the average rating (example: *4.6 stars*) in the upper right
* Rate the add-on and write a review for the first time
* Observe the review count and average rating again

### What happened?

* The review count does not always increment
* The average rating is not always updated to reflect your newly submitted rating

### What did you expect to happen?

Both of these values should always update

### Anything else we should know?

Since this bug doesn't happen all the time, it's hard to reproduce. The out of sync average rating is easier to reproduce because you can enter edit mode and toggle between a one star and a five star repeatedly to trigger lots of updates. At least one of the updates will show the wrong average rating.

This is similar to https://github.com/mozilla/addons-frontend/issues/5986

**Comment by ioanarusiczki** [comment]
@kumar303 I tested this issue on AMO dev and AMO stage with FF63 (win10)

I think we should reopen this issue because I could reproduce now the issue and it is no longer intermittent.

Every time I rate with a star (no need to make a written review) I look on the detail page to the upper right corner and I see that 2 ratings were registered instead of one. The average is also calculated as 2 ratings were given. If the page is refreshed the ratings will be displayed correctly (number and average).

Please take a look 

![the case of two and refresh1](https://user-images.githubusercontent.com/33448286/49213165-4ddce400-f3cc-11e8-8a4e-22dbfc37d029.gif)

**Comment by ioanarusiczki** [comment]
@kumar303 I verified it on AMO stage again and the merge problem seems to be fixed. I could not reproduce the issue. I tested with extensions and themes from the add-ons detail page and reviews page too. 

![works](https://user-images.githubusercontent.com/33448286/49237288-90bbad80-f406-11e8-9f75-1cdc0c396483.gif)
