### ISSUE TITLE
Revert HCT config for production

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#7025]
Due to https://bugzilla.mozilla.org/show_bug.cgi?id=1509151 collection isn't possible so we may as well hold off pushing this to production until it's fixed.

**Comment by muffinresearch** [comment]
Once this lands it will need to be cherry-picked and then testing on stage to make sure HCT isn't loaded.

Note: the base config entry for `hctEnabled` is false see https://github.com/mozilla/addons-frontend/blob/a3ce519060fcc955bba9d5658705b1a64c494b09/config/default.js#L291

**Comment by ioanarusiczki** [comment]
@muffinresearch 
Events are only sent on -dev now with FF65 - but only using the https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/48.0/Darwin/normal and not directly about:addons (with the pref changed for dev extensions.webservice.discoverURL ) I noticed and mentioned that first time I tested this issue on AMO dev the last week. 

Events are no longer sent on -stage with FF65(what worked yesterday won't work anymore). 
I also followed steps from https://bugzilla.mozilla.org/show_bug.cgi?id=1509151 and I can confirm I received the same errors and then tried with FF63 too.

![errors](https://user-images.githubusercontent.com/33448286/48909264-7ec19400-ee75-11e8-9dc5-8ff27161f7e9.png)

AMO stage: clicks in about:addons or the link https://discovery.addons.allizom.org/en-US/firefox/discovery/pane/48.0/Darwin/normal. For both the  Browser Console returns this message  [GA: ON] Not logging to telemetry since hctEnabled is disabled

Also, the HTC enabled was false
![errors2](https://user-images.githubusercontent.com/33448286/48909277-84b77500-ee75-11e8-8cf3-dd94fb207a5c.png)

**Comment by muffinresearch** [comment]
@ioanarusiczki thanks 👍
