### ISSUE TITLE
Update the addons order on the Enhance Your Media Experience guides page

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#7048]
> the [document]((https://docs.google.com/document/d/1u1tbRo_ivfEAh_er2XKPciuYLARiNa2N5qXPGC0jfcY/edit?ts=5baeae48)) has for the Enhance Your Media Experience guide another order for the three sections meaning Bring media right into the browser is the first, the middle is Get more out of media and the last one is Improve videos. On AMO -dev the first one is Improve videos. So I don't know, perhaps that should be switched to match the order from the docs. Let me know if I should file an issue.

REF: https://github.com/mozilla/addons-frontend/issues/6701#issuecomment-441034219

**Comment by ioanarusiczki** [comment]
@rebmullin I verified this on AMO dev with FF63(Win10) - I still see "Improve videos" the first one instead of "Bring media right into the browser" 
Also, the Improve videos section no longer displays an add-on with description and install button. 
 
![improve videos is the first one](https://user-images.githubusercontent.com/33448286/49020586-8052cb00-f199-11e8-9e80-614dd7da55ed.png)

**Comment by rebmullin** [comment]
@ioanarusiczki, that's weird. I show this order now:

![Alt text](https://monosnap.com/image/UbY1KYgxYQvtIqvPTX9oU1toNwtpUR.png)

can you try cashing busting?

regarding the missing addon, yes, I see that missing too. I am looking into why that's gone now :/ I think that's a separate issue tho..

**Comment by ioanarusiczki** [comment]
@rebmullin I re-checked and it's in the right order now (did not do anything, just simply clicked the guide line again).
For the add-on I filed https://github.com/mozilla/addons-frontend/issues/7061 and I can mark this verified. 

![the right order](https://user-images.githubusercontent.com/33448286/49024004-235b1300-f1a1-11e8-82df-004aea8974ac.png)
