### ISSUE TITLE
Page not found for some old Addons

### ISSUE THREAD

**Issue by LiveDe** [mozilla/addons-frontend#7095]
STR:
1. Search in Google for "e-mail myself firefox"
2. Choose the first link: https://addons.mozilla.org/en-US/firefox/addon/email-yourself/
3. Page not found

API-Call return: "Authentication Credentials are provided" and that it isn't disabled by the dev or mozilla. 

What did I expect to happen?
That I can still see the page. Maybe with the "not compatible with firefox Quantum"-Information.

**Comment by diox** [comment]
This is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error. In the long run they will disappear from Google search results.
