### ISSUE TITLE
addons:'js print setup' is missing

### ISSUE THREAD

**Issue by aydenling** [mozilla/addons-frontend#7106]

**Comment by willdurand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.
