### ISSUE TITLE
Why I can not install js print setup

### ISSUE THREAD

**Issue by junqing124** [mozilla/addons-frontend#7109]
I can not find the addon js print setup.
why

**Comment by willdurand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.

**Comment by junqing124** [comment]
So,I must wait the author update this add-ons?But I want install this add-ons now.

**Comment by willdurand** [comment]
There is nothing we can do unfortunately.
