### ISSUE TITLE
ipfood

### ISSUE THREAD

**Issue by filipusneri09** [mozilla/addons-frontend#7123]

**Comment by filipusneri09** [comment]
I need an ipfood 2.4.1.1-signed file, thanks
how i get it

**Comment by willdurand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.

**Comment by filipusneri09** [comment]
thanks  for teh response. respon was very fast


Pada tanggal Jum, 30 Nov 2018 pukul 17.17 William Durand <
notifications@github.com> menulis:

**Comment by filipusneri09** [comment]
I need an ipfood 2.4.1.1-signed file, does anyaone have this file??
 thanks

Pada tanggal Jum, 30 Nov 2018 pukul 17.31 Filipus Neri Widyawan <
filipus.neri09@gmail.com> menulis:
