### ISSUE TITLE
don't download Seamless Print

### ISSUE THREAD

**Issue by lc15700767384** [mozilla/addons-frontend#7126]
### What happened?
I can't download seamless print for my firefox. help me.
### What did you expect to happen?
I need download seamless print,please open download! thanks!

**Comment by willdurand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.
