### ISSUE TITLE
Addon not found

### ISSUE THREAD

**Issue by fr0z3nfyr** [mozilla/addons-frontend#7127]
### Problem:
The add-on DownThemAll seems to have disappeared from the addons library. Neither the direct URL https://addons.mozilla.org/en-US/firefox/addon/201/ nor a search shows the add-on. The offical website of the addon at https://www.downthemall.net/ still points to the link above to download/install. I remember that the addon was incompatible with the last update I performed on firefox so I removed it. Today, I went back to check if the addon was updated to install it but its gone now. It worked all hunky dory with my previous version of FF. :disappointed: 

### What happened?
Explained above

### What did you expect to happen?
Well, that's definitely not what I expected. I expected to see the addon page irrespective of whether it was compatible with my browser version

### Anything else we should know?
Pretty much everything is mentioned. BTW, I don't know if the backend search function is written to check the browser version from headers and decide if the addon should be displayed. I'm on version 62.0.3 64 bit. I didn't get a chance to check on a different/older browser version.

**Comment by XavierFR** [comment]
+1

**Comment by willdurand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.
