### ISSUE TITLE
Broken Link: Websocket Monitor add-on

### ISSUE THREAD

**Issue by unity-frankie** [mozilla/addons-frontend#7129]
### Describe the problem and steps to reproduce it:
There's a broken link on this page:
https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#Filtering_WebSockets

Specifically, the hyperlink in the sentence "To monitor the data exchanged in WebSocket connections, try the WebSocket Monitor add-on."

The dead link on the above page links to: https://addons.mozilla.org/en-US/firefox/addon/websocket-monitor/

### What happened?
The add-on page is missing.

### What did you expect to happen?
There to be an add-on for 'websocket-monitor'.

**Comment by willdurand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.

**Comment by jcrben** [comment]
@willdurand that's a pretty disappointing way to handle the removal - instead, you could've provided a landing page which pointed out that this extension was removed and hopefully even pointed some way to find the original source code. I might be willing to port a legacy extension but now I can't even get the original code.

I'm noticing the broken extension link from https://superuser.com/a/263425
