### ISSUE TITLE
Session Manager not found

### ISSUE THREAD

**Issue by fcomuniz** [mozilla/addons-frontend#7132]
### What happened?
A page i followed from a google search of "firefox session manager" showed a result, with a specific link, but the result was not found inside firefox domain.
### What did you expect to happen?
I expected to find a plugin for firefox to manage sessions, but it was not found, even if it appeared to exist
### Anything else we should know?

https://addons.mozilla.org/en-US/firefox/addon/session-manager/reviews/

**Comment by willdurand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.
