### ISSUE TITLE
Old hackbar addons for Firefox. h3ll4r_h5h-hackmod/ 

### ISSUE THREAD

**Issue by Anacondanet** [mozilla/addons-frontend#7141]
Hello.
I'm looking to download the old h3ll4r_h5h-hackmod/ hackbar addon for Firefox. 

I've downloaded an old version of firefox (47) But still can't seem to find it.

The new versions of hackbar (Quantum) Is so bad, almost no SQLi options for databases and tables.
Also it auto encodes half my characters every time I click execute. Also they don't support GET based. 

I tried every single new addon, and I really do not like it.
Is there any way to get the old hackbar?

**Comment by wagnerand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error.
