### ISSUE TITLE
PLease Fix My words

### ISSUE THREAD

**Issue by hirfan7** [mozilla/addons-frontend#7148]
My words addon has been removed

Mywords should be reinstated

Anything else we should know?
One of the most helpful addon has been removed also it should be designed to suit latest mozilla versions

**Comment by wagnerand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error.
