### ISSUE TITLE
Can't find the "S3.google Transrator" in Add-Ons by Firefox.

### ISSUE THREAD

**Issue by nao-yamazaki** [mozilla/addons-frontend#7161]
### What happened?
I was search the "S3.google Transrator" in Add-Ons by Firefox. but result was 0.
Is it gone?

**Comment by EnTeQuAk** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error. 

Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.

**Comment by nao-yamazaki** [comment]
Hi Mr.EnTeQuAk.
Thanks the above information.
