### ISSUE TITLE
Firefinder, Firepath  addons are not available 

### ISSUE THREAD

**Issue by chandrashivappa** [mozilla/addons-frontend#7170]
Firefox addons which were available at https://addons.mozilla.org/ca/firefox/addon/firefinder-for-firebug/ are no more available. 
How do we go about getting those addons/extensions for firefox ?

Are they not available any more and why? 

Any other tool in place of these released?

Thanks,
Chandra

**Comment by wagnerand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error. 

Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.
