### ISSUE TITLE
Urgent Install FireHbbTV addon for firefox v.53.0 not possible!

### ISSUE THREAD

**Issue by edagalaki** [mozilla/addons-frontend#7172]
Hello, 

I want to install FireHbbTV addon on firefox version 53 but when i enter on the folowing link

https://addons.mozilla.org/en-US/firefox/addon/firehbbtv/

I get the following answer Page not found.

Sorry, but we can't find anything at the address you entered.

In the past I used to have it installed but I had to remove and re install and since then I face this problem.

I am on ubuntu 16.04 (64bit) and have tried to re install firefox as well.

Have you encountered similar problems? 

Is this add on not available any more for this version? Or what is suggested to do to solve it?

**Comment by wagnerand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error. 

Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.
