### ISSUE TITLE
botcheck not found

### ISSUE THREAD

**Issue by wrhite** [mozilla/addons-frontend#7173]
### Describe the problem and steps to reproduce it:

from this site https://botcheck.me/ I click on "add to firefox"

### What happened?
Page not found
https://addons.mozilla.org/en-US/firefox/addon/botcheck-me/

Manual searching for botcheck reveals nothing is available

### What did you expect to happen?
option to install the botcheck addon

**Comment by Ackis** [comment]
Getting the same error with this passifox:

https://addons.mozilla.org/en-US/firefox/addon/passifox/

URL comes from the addons github page, and even a google search links to it.

**Comment by wagnerand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error. 

Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.
