### ISSUE TITLE
The video not stopping upon browser window resize

### ISSUE THREAD

**Issue by SylviaOr** [mozilla/addons-frontend#718]
Firefox Developer Edition 49.0a2
OS X Yosemite 10.10.5
## STR
1. Navigate to: about:addons
2. Click button „Click to play” - video is starting
3. Resize browser window (shrink) to about tablet size (1024x768)

Expected result: The video is hidden and stopped upon resize.

Current result: The video is hidden but it is still playing, sound from video is audible.

![bbb](https://cloud.githubusercontent.com/assets/20317898/16625969/40cbe98c-43a7-11e6-9bf2-81eeea885832.png)

**Comment by muffinresearch** [comment]
@pwalm @designakt what do you think should be the behaviour here, should we keep the video instead? If so how should it be treated at smaller vp widths?

**Comment by designakt** [comment]
If there is no video, it should not play.
But how about keeping the video also for small screens and mobile?
It does not use relevancy only because the screen is smaller, only issue is how we integrate it without using too much space.
Maybe like this:
![screen shot 2016-07-11 at 15 20 11](https://cloud.githubusercontent.com/assets/8145891/16732118/d6086fa2-477b-11e6-8861-c23589552384.png)

**Comment by muffinresearch** [comment]
What happens to that when you press play? Doe it then fill more of the screen and push the content down?

I think having the video move under without shrinking should work fine as a starting point (keeping it very simple initially). For now we're really only looking at desktop with minimal viewport sizes as opposed to actually dealing with mobile since this isn't exposed on android yet, and I presume the same is true for ios?

**Comment by designakt** [comment]
Yes, please let it push the content down.

**Comment by willdurand** [comment]
There is no video anymore.
