### ISSUE TITLE
Need access to Selenium IDE Button 1.2.1 add-on

### ISSUE THREAD

**Issue by saca-puntas** [mozilla/addons-frontend#7197]
I have a client who needs to use this old addon because he needs to use the old Selenium. The page for the addon is now an error page https://addons.mozilla.org/en-US/firefox/addon/selenium-ide-button/

Can someone please give me the download so he can keep it on his computer? Thank you.

**Comment by wagnerand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error. 

Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

**Comment by saca-puntas** [comment]
Hi, thank you and I totally understand. This client has to use Firefox 54 and the old Selenium, however, and it will not work on his machine without this addon. He understands that it is not updated anymore, but it has been working without any issues. He recently had to reinstall Firefox 54 however and now is unable to use the old Selenium without this addon.
