### ISSUE TITLE
Import on Firefox not working

### ISSUE THREAD

**Issue by kerzhner** [mozilla/addons-frontend#7224]
Importing json state files on Firefox does not seem to work. To repro:
1. Export a json state file.
2. Import the file.
3. The imported actions and sates do not appear in the add-on.
The flow above works on Chrome.

I am using:
Redux DevTools 2.15.4
Firefox 64.0
Mac OS version 10.13.6

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.

**Comment by kerzhner** [comment]
Oops, my apologies for using the wrong github repo for the issue. 🙁
