### ISSUE TITLE
After installing an add-on its door-hanger is not RTL

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#726]
Steps to reproduce:
1. Install an add-on from about:addons by clicking the green radio button using FF48b5 (a RTL build) against AMO-prod (ie. Adblock Plus)
2. Observe the door-hanger

Expected results:
The door-hanger is RTL.

Actual results:
The door-hanger is LTR.

Notes/Issues:
Verified on FF48b5 on Windows 7 X64 and Mac OS x10.8.
Screenshot for this issue: 
![rtl](https://cloud.githubusercontent.com/assets/15685960/16654916/a13cd90c-4460-11e6-8a09-c842e4a9c40c.png)

**Comment by muffinresearch** [comment]
Positioning the in-page notification on the right for LTR and RTL was a conscious decision due to the padding that's on the left on the outside of the iframe. It will look very strange if we position it there. 

The padding removal is due to happen in FF50, but also by then we are likely to move to using the UI tour which should eventually point to the add-on icon in the toolbar.

**Comment by muffinresearch** [comment]
Oh hang on, that scroll-bar suggests that the padding is now on the right. If that's the case we can look at moving the notification. Also that scroll-bar is ugly we should look at seeing if anything can be done for that too.

**Comment by muffinresearch** [comment]
Are there any console messages?

**Comment by muffinresearch** [comment]
Ah I know why, when I tested this I didn't use an actual RTL browser locale, I just changed the site via the discovery url in about:config. Looks like when you actually use a proper rtl browser ui locale the padding is inverted.

**Comment by madalincm** [comment]
Verified as fixed in FF50 in addons-dev.allizom.org
Postfix screencast:
![rtlbanner](https://cloud.githubusercontent.com/assets/15685441/16733375/019c09e0-478a-11e6-9d8d-7fac00691212.png)
