### ISSUE TITLE
bad link to MKiosk

### ISSUE THREAD

**Issue by primonate** [mozilla/addons-frontend#7267]
### Describe the problem and steps to reproduce it:
From a google search for mkiosk I got a link (https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwi-y6Lg9rHfAhUNP60KHbhGCuAQFjAAegQICRAB&url=https%3A%2F%2Faddons.mozilla.org%2Feu%2Ffirefox%2Faddon%2Fmkiosk%2F&usg=AOvVaw1DpE4_Ogr1N9nlLr4ygj1e) which gives a "Sorry, but we can't find anything at the address you entered."   

I really need the mkiosk addon in firefox  for my local library. 
I have been making computers that only view my local libraries online card catalog pages. The last batch worked very well for the last 5 years but now I can't find mkiosk anymore 

Can you find a way for me to be able to use mkiosk ?

**Comment by SeanPrashad** [comment]
Hey @primonate - I think the majority of the team is on holidays and might not see your message immediately.

To help, it may be a good idea to try contacting someone in #amo on Mozilla's IRC. Instructions on how to get there can be found [here](https://wiki.mozilla.org/IRC)!

**Comment by jvillalobos** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error. 

Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
