### ISSUE TITLE
DTM Switch extension is not found

### ISSUE THREAD

**Issue by friendlymahi** [mozilla/addons-frontend#7273]
### What happened?
Tried to download DTM extension from the link available in https://marketing.adobe.com/resources/help/en_US/dtm/search_discovery_plugins.html But addon is not found from firefox addons page

### What did you expect to happen?
Extension is available in the past

### Anything else we should know?
Quite possible it is renamed.

**Comment by jvillalobos** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error. 

Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions. I also suggest you contact Adobe to update their documentation.
