### ISSUE TITLE
Add - Ons appearing, then dissapearing 

### ISSUE THREAD

**Issue by DjDiddles2000** [mozilla/addons-frontend#7280]
### Describe the problem and steps to reproduce it:
~ I looked up "Firefox Themes" to customize my interface. When clicking links from this website, and others, majority of the links lead to a error. 

### What happened?
![untitled](https://user-images.githubusercontent.com/33147500/50549783-ebb80e80-0c17-11e9-82a8-e00d82abc124.png)
~This happens whenever I click on any add on link, from anywhere

### What did you expect to happen?
The link would lead to the add-on, allowing me to install it. 

### Anything else we should know?
I have edit my Config Page, however nothing with add-ons ( Left Those Integers Alone )

**Comment by AlexandraMoga** [comment]
I've tried to open various theme pages on https://addons.mozilla.org but I couldn't reproduce the issue.
It could be that some of your configurations or addons that you've installed might interfere though.
Could you try to create a new Firefox profile and check if the issue is still happening?

**Comment by willdurand** [comment]
We should not surface unknown themes in the search results, but I am not sure the search results come from AMO. Looking at the screenshot, it looks like a 404, likely related to the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.
