### ISSUE TITLE
I am unable to find the firebug and firepath addon ,kindly share the proper donwload link for same.

### ISSUE THREAD

**Issue by muralibv17** [mozilla/addons-frontend#7281]

**Comment by jvillalobos** [comment]
This is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.
