### ISSUE TITLE
Send to Kindle Add on

### ISSUE THREAD

**Issue by BL-P** [mozilla/addons-frontend#7282]
### Describe the problem and steps to reproduce it: link from Amazon site comes to an error page. 

https://www.amazon.com/gp/sendtokindle/firefox

**Comment by jvillalobos** [comment]
This is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.

**Comment by immartian** [comment]
Can't imagine Amazon didn't even care about it.

**Comment by mirh** [comment]
Has anybody bothered to ping sendtokindle-feedback@amazon.com ?

The add-on is still available [here](https://legacycollector.org/firefox-addons/399764/index.html) anyway.

**Comment by willlma** [comment]
I reached out to Amazon on this issue, was told to use Chrome or email to Kindle. When I made it clear that I was just reporting an issue, the rep said they would pass this info to the kindle dev team. I passed a link to this page hoping we can get a comment from them on whether they plan to build a new extension.

**Comment by Zauxst** [comment]
> Has anybody bothered to ping [sendtokindle-feedback@amazon.com](mailto:sendtokindle-feedback@amazon.com) ?
> 
> The add-on is still available [here](https://legacycollector.org/firefox-addons/399764/index.html) anyway.

I've just send them an email 'bout this. 
More people should do this... 

It could be that they don't have enough dev resources to rebuild the kindle app for Firefox Quantum (or whatever the new dev API is). 
It would be quite good if the extension link had an URL to their email support since this is mostly on their shoulders... 

... Unless the Firefox team wants tot repair that extension.

**Comment by jtswartz** [comment]
> I've just send them an email 'bout this.
> More people should do this...

I'm doing the same.
