### ISSUE TITLE
"View source chart" add-on for Mozzilla not found

### ISSUE THREAD

**Issue by Neubert2285** [mozilla/addons-frontend#7291]
Dear Sirs,

I would like to add the "view source chart add-on" to my Mozilla Firefox browser.
This is why I opened    http://viewsourcechart.com/
and then pressed "Firefox browser add-on".

However, I then got the this message: Seite nicht gefunden (= page not found)
Entschuldigen Sie, aber wir konnten zu der eingegebenen Adresse nichts finden.
https://addons.mozilla.org/de/firefox/addon/view-source-chart/?src=external-viewsourcechart.com

Does the View Source Chart add-on no longer exist for the Mozilla Firefox browser?

Thank you in advance for your attention.

Best regards
Sabine Neubert

**Comment by jvillalobos** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error. 

Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.
