### ISSUE TITLE
Firefox Link is broken

### ISSUE THREAD

**Issue by DAMANgoldberg** [mozilla/addons-frontend#7295]
https://addons.mozilla.org/en-GB/firefox/addon/timeline-support/ 
is not found. Could it be that Timeline Support isn't fully functional in Firefox? I have it on both Vivaldi and Chrome though running Windows 10 1809 and have it native.

**Comment by willdurand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.

**Comment by DAMANgoldberg** [comment]
Wow! This add-on isn't that old. Thanks for the information.

**Comment by willdurand** [comment]
> Wow! This add-on isn't that old. Thanks for the information.

Interesting. In that case, it might be that the author simply disabled/removed their add-on. It happens sometimes... Best thing for you would be to send an email to the author if you can get in touch with them.
