### ISSUE TITLE
DOM Inspector DL link broken

### ISSUE THREAD

**Issue by 95north** [mozilla/addons-frontend#7302]
### What happened?
I was on this page:
https://developer.mozilla.org/en-US/docs/Tools/Add-ons/DOM_Inspector

In this section: 

_Getting DOM Inspector
Section

Firefox & Thunderbird
    You may download and install the DOM Inspector from the AMO web site._ 

And I clicked the link within the above sentence under Firefox & Thunderbird subheading.   It linked to this page: 

https://addons.mozilla.org/en-US/firefox/addon/6622/
(Page Not Found) 

### What did you expect to happen?

I expected to find a download page, or to be told the add on was discontinued.

**Comment by jvillalobos** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.

That documentation is not valid anymore and should be archived, though. /cc @caitmuenster

**Comment by caitmuenster** [comment]
Thanks, @jorgev. Just scheduled those docs for obsoletion.

**Comment by PeteDiMarco** [comment]
As of August 8, 2019, this problem still exists.
