### ISSUE TITLE
"Error during uninstallation" displayed after repeated install\uninstall actions

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#731]
Prerequisites:
FF 48 beta 5
Build identifier: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0

Steps to reproduce:
1.Set your disco pane to production following the steps from https://mana.mozilla.org/wiki/display/SVCOPS/AMO+Dev+Resources#AMODevResources-TestingDiscopaneinProd
2.Go to Discovery pane and repeatedly press install\uninstall button for any addon

Expected results:
No errors

Actual results:
"Error during uninstallation" displayed

Please see video for this bug : 
![erroratuninstall](https://cloud.githubusercontent.com/assets/1583842/16659330/34a384be-4472-11e6-9cfd-50c8ef708201.gif)

**Comment by vcarciu** [comment]
Attaching logs from browser console...
[Logs.txt](https://github.com/mozilla/addons-frontend/files/352530/Logs.txt)

**Comment by vcarciu** [comment]
Please note that this is reproducible for Themes too.

**Comment by vcarciu** [comment]
Also, even if the video was performed for RTL , this issue is reproducible on normal orientation, for EN-US for example

**Comment by muffinresearch** [comment]
Running this for an uninstall shows that we're hitting this state because the browser APIs are called multiple times. In the uninstall case if the uninstall is underway the addon lookup fails, makes an exception and creates the error message here: https://github.com/mozilla/addons-frontend/blob/master/src/disco/components/Addon.js#L404
