### ISSUE TITLE
Firebug

### ISSUE THREAD

**Issue by riszinryan** [mozilla/addons-frontend#7361]

**Comment by willdurand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.

**Comment by EnTeQuAk** [comment]
Firebug has been replaced by the https://www.mozilla.org/en-US/firefox/developer/ Firefox Developer Tools since ~2017.
