### ISSUE TITLE
antigameorigin not found

### ISSUE THREAD

**Issue by krassen89** [mozilla/addons-frontend#7362]
### Describe the problem and steps to reproduce it:

Followed many links from google search, antigameorigin for firefox, file not found on extensions website for firefox.

**Comment by willdurand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.
