### ISSUE TITLE
how to get xpath-checker

### ISSUE THREAD

**Issue by material2010** [mozilla/addons-frontend#7404]
### Describe the problem and steps to reproduce it:
Firefox  access  https://addons.mozilla.org/zh-CN/firefox/addon/xpath-checker/

### What happened?
Oops! We can’t find that page
If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.
If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by filing an issue. Tell us where you came from and what you were looking for, and we'll get it sorted.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available extensions or themes.
### What did you expect to happen?
I want to get xpath-checker

**Comment by wagnerand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error. 

Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.
