### ISSUE TITLE
Enable TAARDIS in all environments

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7445]
See also: #7218

---

Quoting @muffinresearch:

> @rebmullin @willdurand This will need to go into prod next week to make the 29th January deadline so we'll want to get this config'd on for stage and prod ahead of the Monday tag.

We want to enable TAARDIS in all environments.

**Comment by AlexandraMoga** [comment]
There are no clientIDs to test recommendations on stage as far as I know. In this context, I'm not sure how we can confirm the fix for stage, apart from making sure that the clientID is correctly sent in request header.

- stage disco:
![image](https://user-images.githubusercontent.com/31961530/51485593-26404180-1da7-11e9-92cb-2c3519470da2.png)

The feature is not yet enabled in prod as far as I can tell.

**Comment by willdurand** [comment]
> There are no clientIDs to test recommendations on stage as far as I know. In this context, I'm not sure how we can confirm the fix for stage, apart from making sure that the clientID is correctly sent in request header.

Yeah, that sounds good to me. There is nothing else we can do on our side.

**Comment by AlexandraMoga** [comment]
I have attempted to verify this in prod but so far the taar prod api is throwing a 500 error, therefore no recommendations were received on DiscoPane.

From our end, the request is correclty sent - i.e. the clientID is sent with the request header.
I'm waiting for someone from taar to respond on this. 

I will mark this as verified as soon as prod is functional.

**Comment by AlexandraMoga** [comment]
Verified fixed in -prod:

![2019-02-15_09-50-57](https://user-images.githubusercontent.com/31961530/52842260-37127780-3107-11e9-9c6b-d678f7dbd84a.png)
