### ISSUE TITLE
Implement a search results page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#755]
This may have some things in common with the admin search app. 

This component should show a list of add-ons from the search results data.

Relates to mozilla/addons#151

**Comment by tofumatt** [comment]
I would say this can server as the tracker for search-related bugs, cc @andymckay.

**Comment by muffinresearch** [comment]
@tofumatt I would suggest making a new bug as a tracker this is quite specific, but feel free to break these down as much as you need to.

**Comment by tofumatt** [comment]
Gotcha, will do.

- tofumatt

On 26 July 2016 at 15:41:46, Stuart Colville (notifications@github.com)
wrote:

@tofumatt <https://github.com/tofumatt> I would suggest making a new bug as
a tracker this is quite specific, but feel free to break these down as much
as you need to.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/addons-frontend/issues/755#issuecomment-235288930>,
or mute the thread

**Comment by ValentinaPC** [comment]
There is a way for us to test this, or others like this one? Thanks!

**Comment by muffinresearch** [comment]
@ValentinaPC not as yet, going to look to get this up on -dev soon though.
