### ISSUE TITLE
Viewing Personas 

### ISSUE THREAD

**Issue by Susanilow** [mozilla/addons-frontend#7643]
Although, I have uploaded the new version of Firefox, I can not see the personas as I did before the change. So at the bottom of the new version page, I have been able to click the link to view the personas using the previous version of Firefox. However, now that link is gone. I can not see the persona now & my saved favorites are gone. 

Please tell me why the new version of Firefox is not working for me. Mind you, this problem is only with the personas. Using the Firefox browser works great. 

Thank you,
Susanilow at aol dot come

**Comment by kumar303** [comment]
Hi Susanilow. Sorry you are having trouble finding your personas (knowns as themes). I wasn't aware that the new version page in Firefox provided a link -- maybe the link was removed. I would suggest looking for your themes by doing this instead: 
- Go to the top menu bar of the Firefox application and choose *Tools*
- In the dropdown menu, select *Add-ons*
- This opens a page for all of the add-ons you installed into Firefox. From the left side, select *Themes*

This should show you all themes that have installed.

Since your issue is not related to https://addons.mozilla.org/ I'm closing the issue.
