### ISSUE TITLE
`/search-engines/` leads to empty query sorted by Relevance

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#7682]
In the Firefox search preferences, there's a link that offers to "Find more search engines", which leads to `/search-engines/` and then redirected to `/search-tools/`. This just shows [a search results page](https://addons.mozilla.org/firefox/search-tools/) filtered by type Search Tool, with no query, and sorted by Relevance. Unfortunately that means the results are kinda random.

Since we don't have any usage info for search engines, I think the best bet is to send people to the [search results sorted by rating](https://addons.mozilla.org/firefox/search/?sort=rating&type=search).

Making this a P2, since it's a Firefox integration.

Update: we decided to change the default sorting in https://github.com/mozilla/addons-frontend/issues/7682#issuecomment-472962140.

For QA: navigating to https://addons.mozilla.org/firefox/search-tools/ should list search tools extensions sorted by "top rated".

**Comment by willdurand** [comment]
Given that the redirect happens in Nginx, I believe we should update the nginx rule from https://github.com/mozilla-services/cloudops-deployment/pull/2983.

The frontend does not know which URL was before it receives `/search-tools/`.

**Comment by willdurand** [comment]
Another option would be to always sort results by rating on this page by default.

@jvillalobos what do you think?

**Comment by jvillalobos** [comment]
If there's no query, defaulting to Ratings sorting is okay with me.

**Comment by diox** [comment]
Note: in the API, if there is no `sort` parameter and no `q` parameter, we sort by `downloads`.

**Comment by ioanarusiczki** [comment]
@willdurand 
Verified on AMO dev - FF66 (Win10). Navigating to https://addons-dev.allizom.org/firefox/search-tools/
will display "Top rated" as default.

![top rated as default](https://user-images.githubusercontent.com/33448286/55713430-52a84900-59f9-11e9-9f2a-dc8a71abee2e.gif)

If  `search-engines` is types instead of `search-tools` the URL redirects correctly to the page except I've noticed that the layout is broken (I think right now it's an intermittent issue on AMO dev). Page must be refreshed once or even twice to load correctly. 

![broken layout](https://user-images.githubusercontent.com/33448286/55713685-d104eb00-59f9-11e9-899d-0ed341e3d88b.gif)
