### ISSUE TITLE
Can't find Ugly Email, listed as a Firefox extension that will let me know if my gmail is being tracked

### ISSUE THREAD

**Issue by Cythera** [mozilla/addons-frontend#7768]
### Describe the problem and steps to reproduce it:

I clicked on a link from this site:  https://lifehacker.com/how-to-see-if-someone-is-tracking-emails-they-send-you-1833529784 in order to install a Firefox addon
I got "page not found"

### What did you expect to happen?
I expected to find instructions on installing the addon
### Anything else we should know?

https://lifehacker.com/how-to-see-if-someone-is-tracking-emails-they-send-you-1833529784

**Comment by muffinresearch** [comment]
This add-on is no longer available because it hasn't updated to the web-extension format and legacy add-ons have now been fully removed from AMO.

The best thing you can do is ask the developer if they can submit a new web-extension version. See https://uglyemail.com/ for contact details. From their twitter stream it sounds like they were already working on a beta: See https://twitter.com/OneClickLab/status/997228903960907776
