### ISSUE TITLE
Show recommended badge on details page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#7794]
UX is as follows:

![Screenshots](https://user-images.githubusercontent.com/1514/55243745-bed7bf80-5237-11e9-8178-0e2d2494f897.jpg)

Depends on changes in https://github.com/orgs/mozilla/projects/68

See https://mozilla.invisionapp.com/share/BXQTIIC86ZN for the latest UX

TBD: There should be a tooltip that pops up when hovering over the badge, explaining what it means.

TBD: The badge should link to a SUMO article explaining the recommendation process.

Note also that the Recommended badge should not appear for Android.

**Comment by fr-liyi** [comment]
Hello, may I take this one?

**Comment by xu3u4** [comment]
Hello, may I take this one 🙂 ?

**Comment by willdurand** [comment]
@xu3u4 sorry, this issue is not for contributors.

**Comment by xu3u4** [comment]
Ok, sorry.

**Comment by bobsilverberg** [comment]
@jvillalobos The PRD doesn't discuss the "all versions" page. Some questions:
1. Should there be any badging on the all versions page?
2. If so, would we have one badge at the top of the page for the add-on if it is currently recommended, or one badge per version which shows which versions were recommended?
3. If we want to show it per version, would we want to badge an old version that *was* recommended, even if the current version *is not* recommended, or would we consider all older versions to now also be non-recommended if the current version is not recommended?

**Comment by jvillalobos** [comment]
No need to add badges to this page.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos

**Comment by bobsilverberg** [comment]
@brassy- I tried to ping you on Slack, but I figured I'd try here as well. I need access to some of these assets, such as the Recommended icon. I tried to figure out how to extract them from InVision, but failed. Would you be able to help me out with this? Thanks!

**Comment by bobsilverberg** [comment]
Here's the latest mockup from InVision:

<img width="715" alt="Screenshot 2019-05-07 11 01 46" src="https://user-images.githubusercontent.com/142755/57310298-88ebed80-70b7-11e9-8e86-ae6e75b01e4d.png">

**Comment by ioanarusiczki** [comment]
@bobsilverberg I have a question:

> For QA:
> When recommended badges are turned on (which is the case on dev, currently), Featured badges for 
> extensions will no longer be shown on the details page. They will still be shown for other add-on types.

- The [Featured extensions ](https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=extension)on AMO dev  shows the "Recommended" badge for an add-on only the [Awesome Screenshot PLus](https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/?src=featured) . The rest of the extensions in the featured list don't even display the "featured extension" blue label (this is not reproducible for the [Featured extensions](https://addons.allizom.org/en-US/firefox/search/?featured=true&type=extension) from stage ). 

Shouldn't these display the Recommended label already or do I have to make changes for them from admin tools following the instructions from[ https://github.com/mozilla/addons-server/issues/11278](https://github.com/mozilla/addons-server/issues/11278#issuecomment-489995653)

**Comment by bobsilverberg** [comment]
> @bobsilverberg I have a question:
> 
>  The Featured extensions on AMO dev shows the "Recommended" badge for an add-on only the Awesome Screenshot PLus . The rest of the extensions in the featured list don't even display the "featured extension" blue label (this is not reproducible for the Featured extensions from stage ).
> 

What you describe is as expected. No extensions should ever show a "featured" badge with this patch.

> 
> Shouldn't these display the Recommended label already or do I have to make changes for them from admin tools following the instructions from[ https://github.com/mozilla/addons-server/issues/11278](https://github.com/mozilla/addons-server/issues/11278#issuecomment-489995653)

The recommended badge will only appear for extensions that have been explicitly marked as recommended, so yes, you will need to use the admin tools to mark an extension as recommended in order for the badge to appear.

For all intents and purposes, the "featured" flag for extensions becomes meaningless with this patch (although you can still search for featured extensions and they will appear, but that's something that will likely be changed in the future). Marking an extension as featured will have no effect on badges (i.e., no featured badge will appear, and it will not cause a recommended badge to appear).

**Comment by ioanarusiczki** [comment]
@bobsilverberg I will write down what I consider it needs to be clarified after testing this on AMO dev - FF66(Win10):

1. I was asking more about this because the first shelf on AMO homepage is named "Featured extensions with the [See more featured extensions](https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=extension) blue link.  

> What you describe is as expected. No extensions should ever show a "featured" badge with this patch.

I think the name of the shelf and the "See more..." link should change to "Recommended extensions" and [See more recommended extensions](https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=extension).  

![changes for the Name of the shelf](https://user-images.githubusercontent.com/33448286/57621753-f060dc00-7594-11e9-8e7c-1db9e79d4711.gif)


2. I could add the Recommended badge (adding from admin tools the Recommendation approved flag in the versions page and making the extension recommendable in the discovery items for extensions).
For example this [extension]( https://addons-dev.allizom.org/en-US/firefox/addon/%E4%BA%AC%E4%BB%B7%E4%BF%9D-%E4%BA%AC%E4%B8%9C%E4%BB%B7%E4%BF%9D%E5%8A%A9%E6%89%8B/) has the badge added. But I see this add-on won't appear in the  current [Featured extension](https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=extension) shelf.  
Perhaps something must be done from admin tools to make it visible in the featured/recommended list ?

3. > (although you can still search for featured extensions and they will appear, but that's something that 
> will likely be changed in the future)

I understand that the search after "featured add-ons only" filter will continue to  display results but instead they'll be the recommended ones? 

![search for featured](https://user-images.githubusercontent.com/33448286/57624291-4e43f280-759a-11e9-9718-77cb81658567.gif)


4. Perhaps this is a future implementation but for now I don't see the "Recommended" badge in the search results. I saw it should be available[ here, on page 2](https://mozilla.invisionapp.com/share/BXQTIIC86ZN#/screens)
![no badge](https://user-images.githubusercontent.com/33448286/57622879-361ea400-7597-11e9-8f8a-71b79d232bc8.png)

5.
> TBD: There should be a tooltip that pops up when hovering over the badge, explaining what it means.
> TBD: The badge should link to a SUMO article explaining the recommendation process.

While hovering over the badge the tooltip is available and clicking on it will redirect to https://support.mozilla.org/en-US/ which I think it's not about the recommendation process.

![tooltip and link](https://user-images.githubusercontent.com/33448286/57623530-96621580-7598-11e9-92b0-8c32d1a2e8fd.gif)

6. I've noticed that "Recommended" with "Experimental" could coexist - the "Experimental" badge can be set from dev hub by the developer.

![Experimental](https://user-images.githubusercontent.com/33448286/57623848-50598180-7599-11e9-94c6-fd309b1c5b8a.png)

**Comment by bobsilverberg** [comment]
> @bobsilverberg I will write down what I consider it needs to be clarified after testing this on AMO dev - FF66(Win10):
> 

Thanks @ioanarusiczki. I will respond to these below:
 
>     1. I was asking more about this because the first shelf on AMO homepage is named "Featured extensions with the [See more featured extensions](https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=extension) blue link.
>

This *is* a change that should be made, but it's not part of this issue/patch. We don't actually have an opened issue for this, so perhaps you can open one about changing the shelves on the home page?
 
> 
> > What you describe is as expected. No extensions should ever show a "featured" badge with this patch.
> 
> I think the name of the shelf and the "See more..." link should change to "Recommended extensions" and [See more recommended extensions](https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=extension).
> 
> ![changes for the Name of the shelf](https://user-images.githubusercontent.com/33448286/57621753-f060dc00-7594-11e9-8e7c-1db9e79d4711.gif)
> 

I think this goes along with my comment above. I agree the shelves need to change, but it's not part of this issue/patch.

>     1. I could add the Recommended badge (adding from admin tools the Recommendation approved flag in the versions page and making the extension recommendable in the discovery items for extensions).
>        For example this [extension](https://addons-dev.allizom.org/en-US/firefox/addon/%E4%BA%AC%E4%BB%B7%E4%BF%9D-%E4%BA%AC%E4%B8%9C%E4%BB%B7%E4%BF%9D%E5%8A%A9%E6%89%8B/) has the badge added. But I see this add-on won't appear in the  current [Featured extension](https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=extension) shelf.
>        Perhaps something must be done from admin tools to make it visible in the featured/recommended list ?
>

Same as above. Nothing has been done to make recommended extensions automatically appear anywhere. Changes to the home page should be tracked in a separate issue.
 
>     2. > (although you can still search for featured extensions and they will appear, but that's something that
> 
> 
> > will likely be changed in the future)
> 
> I understand that the search after "featured add-ons only" filter will continue to display results but instead they'll be the recommended ones?
> 
> ![search for featured](https://user-images.githubusercontent.com/33448286/57624291-4e43f280-759a-11e9-9718-77cb81658567.gif)
>

That is probably how it will work, but there are not any issues currently opened about this. Could you please open an issue describing what you've said above?
 
>     1. Perhaps this is a future implementation but for now I don't see the "Recommended" badge in the search results. I saw it should be available[ here, on page 2](https://mozilla.invisionapp.com/share/BXQTIIC86ZN#/screens)
>        ![no badge](https://user-images.githubusercontent.com/33448286/57622879-361ea400-7597-11e9-8f8a-71b79d232bc8.png)
>

This is being tracked by issue #7793, and is therefore not part of this issue/patch.
  
> 
> > TBD: There should be a tooltip that pops up when hovering over the badge, explaining what it means.
> > TBD: The badge should link to a SUMO article explaining the recommendation process.
> 
> While hovering over the badge the tooltip is available and clicking on it will redirect to [support.mozilla.org/en-US](https://support.mozilla.org/en-US/) which I think it's not about the recommendation process.
>

We do not have a URL on SUMO yet to link to, but issue #7961 has been opened to track this.
 
> ![tooltip and link](https://user-images.githubusercontent.com/33448286/57623530-96621580-7598-11e9-92b0-8c32d1a2e8fd.gif)
> 
>     1. I've noticed that "Recommended" with "Experimental" could coexist - the "Experimental" badge can be set from dev hub by the developer.
> 
> 
> ![Experimental](https://user-images.githubusercontent.com/33448286/57623848-50598180-7599-11e9-94c6-fd309b1c5b8a.png)

I don't think this is an issue. @jvillalobos Do we need to do anything to exclude any other badges when displaying the recommended badge?
