### ISSUE TITLE
There is a localization problem with Kabyle (kab)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#7797]
### Describe the problem and steps to reproduce it:

Load this page: https://addons.mozilla.org/kab/firefox/addon/jjb/?src=rating

### What happened?

500 error

### What did you expect to happen?

It should load without an error, like: https://addons.mozilla.org/en-US/firefox/addon/jjb/?src=rating

### Anything else we should know?

There seems to be a problem with a format string in the `kab` locale:
https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/5149119/

**Comment by muffinresearch** [comment]
This is already on -dev, but this URL is failing on stage so this can be tested once stage has the fix after the next tag: https://addons.allizom.org/kab/firefox/addon/noscript/?src=featured

**Comment by ioanarusiczki** [comment]
@kumar303 I uploaded the addon on AMO dev[ here](https://addons-dev.allizom.org/kab/firefox/addon/%E4%BA%AC%E4%BB%B7%E4%BF%9D-%E4%BA%AC%E4%B8%9C%E4%BB%B7%E4%BF%9D%E5%8A%A9%E6%89%8B/) and I cannot seem to reproduce the 500 error. 
I did the same on prod where it's reproducible once en-US is changed to kab.
Let me know if my way of testing this on dev is ok  because @muffinresearch gave a specific addon https://addons.allizom.org/kab/firefox/addon/noscript/?src=featured to test with on stage.

**Comment by ioanarusiczki** [comment]
Verified on AMO prod, FF66(Win10) - the add-on is displayed with kab

![in kab](https://user-images.githubusercontent.com/33448286/56025394-b2189880-5d1a-11e9-88c1-b707657be986.png)
