### ISSUE TITLE
11 April homepage programming update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#7817]
For the **11 April** push, please update the homepage per details found [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch @bobsilverberg

**Comment by ioanarusiczki** [comment]
@willdurand verified this on AMO dev - FF66 (Win10)
The new shelves are displayed on AMO homepage and I could edit all of them by adding new extensions/themes except for the featured themes which had problems in the past because I filed an issue a while ago on the server side https://github.com/mozilla/addons-server/issues/10403 but it looks like it cannot be edited using the frontend link either (it requires an admin account to see the Edit button)
This is the link https://addons-dev.allizom.org/en-US/firefox/collections/4757633/featured-personas/
It allows me to add themes but they won't be visible when going back on homepage and clicking the see more link from Featured Theme shelf.

Also the featured themes link from the [content update document](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit) doesn't show any theme on prod
https://addons.mozilla.org/en-US/firefox/search/?featured=true&type=persona

**Comment by willdurand** [comment]
> Also the featured themes link from the [content update document](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit) doesn't show any theme on prod
> [addons.mozilla.org/en-US/firefox/search/?featured=true&type=persona](https://addons.mozilla.org/en-US/firefox/search/?featured=true&type=persona)

I might be wrong but I think that's not exactly the link we're using in the frontend.

**Comment by willdurand** [comment]
We'll be using https://addons.mozilla.org/en-US/firefox/search/?featured=true&type=statictheme

**Comment by ioanarusiczki** [comment]
@willdurand 

> We'll be using https://addons.mozilla.org/en-US/firefox/search/?featured=true&type=statictheme

It means that is should be alright, the document kept the old URL which was available for lw themes.

I also filed https://github.com/mozilla/addons-frontend/issues/7856. It's only an assumption, but this could also be caused by the changes from lw to static themes.

**Comment by ioanarusiczki** [comment]
Verified on AMO prod - FF66(Win10)
