### ISSUE TITLE
Addon details user count should be a link

### ISSUE THREAD

**Issue by mymindstorm** [mozilla/addons-frontend#7835]
Relevant: #5434

If user statistics are public (or the signed-in user has access to them), the count should be clickable like the "Reviews" button.

![image](https://user-images.githubusercontent.com/27789806/55563940-75b2c000-56bc-11e9-9218-3ee43c8383f3.png)

I'm willing to write a PR for this.

**Comment by jvillalobos** [comment]
I don't think we want users in general going to the stats dashboard, because it's sort of a dead end (needs better design, https://github.com/mozilla/addons-server/issues/10920), and doesn't provide information that is particularly interesting for end users. Having it as a secondary link on the product page is sufficient, IMO. People who are looking for it should be able to find it.

**Comment by mymindstorm** [comment]
That issue is on the board for this quarter. For the few amount of add-ons that have public stats, I thought it would just be nicer to have more consistent UX.
