### ISSUE TITLE
Correct "characters" in "character" for the search suggestion tooltip

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7951]
The (you are currently using 2 characters) use case is no longer applicable so the plural can go 

STR:
1. Load AMO dev any type in a char then hover over the search box and observe the text visible in the tooltip

Expected result:
Please use at least 2 characters (you are currently using 1 character).

Actual result:
Please use at least 2 characters (you are currently using 1 characters).

Notes:
Reproducible on AMO dev - FF66(Win10). 

![newtooltip](https://user-images.githubusercontent.com/33448286/56959283-92280800-6b55-11e9-857e-416e50722d6b.png)

**Comment by AdityaSrivast** [comment]
@ioanarusiczki I would like to work on this issue. Can I take it up?

**Comment by willdurand** [comment]
@AdityaSrivast go for it!

**Comment by arnavvats** [comment]
Hi, investigated this. Turns out this is a bug in firefox. The tooltip shows differently in chrome.
We can add novalidate to the search input, and suppress the tooltip and add a custom tooltip.
What should be our approach here? I would like to fix this issue.
<img width="378" alt="Screenshot 2019-05-08 at 11 40 16 PM" src="https://user-images.githubusercontent.com/26125232/57397624-c56c3600-71ea-11e9-92a1-db4919aac3f2.png">

**Comment by kumar303** [comment]
I don't think it's worth adding a custom tooltip just to workaround this bug. Could someone please file a Firefox bug about this? https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Form%20Manager

**Comment by jvillalobos** [comment]
Closing this bug in favor of fixing it in Firefox. @rpl to file the Firefox bug.

**Comment by rpl** [comment]
I just discussed about this with flod and the bug would be currently closed as wontfix, until [the related strings](https://dxr.mozilla.org/mozilla-central/rev/6f732caaed60783f57944a66f7ea494f5fd78d6c/dom/locales/en-US/chrome/dom/dom.properties#34-35) have been migrated to Fluent.
