### ISSUE TITLE
All extentions marked as legacy

### ISSUE THREAD

**Issue by creidhne** [mozilla/addons-frontend#7967]
Soon after updating to 66.0.3, all extensions were marked as legacy and will not load from addons.mozilla.org or any other source. The problem occurred immediately after visiting www.upi.com.

### What happened?
All extensions worked after update, but suddenly were marked as legacy after visiting www.upi.com.
Extension/Version
ADB Helper/0.12.1
Adblock Plus/3.5.2
Cookie AutoDelete/3.0.2
Cookie Manager/1.5
Firefox Lightbeam/2.1.0
Greasemonkey/4.7
S3.Translator/6.19
NoScript/10.6.1
TinEye/1.4.0
Video DownloadHelper/7.3.5
WindowSizer/1.2.0

### What did you expect to happen?
Valid extensions as not marked legacy.

### Anything else we should know?
As far as I can determine, all extensions are certified and up to date.

**Comment by caitmuenster** [comment]
Thanks @creidhne, this is due to a certificate issue. The team is working on a fix and we'll be providing updates on this thread: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/4

**Comment by smayer97** [comment]
What makes NO SENSE is for installed addons to be disabled. This should NEVER be. 

So not only should this certificate issue be addressed, once the dust settles, someone needs to fix this model so that install addons are never automatically disabled. If there is a change in status, users could be warned BUT NOT AUTOMATICALLY disable addons.
