### ISSUE TITLE
All firefox themes and add ons are suddenly broken and unusable.

### ISSUE THREAD

**Issue by Nawakwa** [mozilla/addons-frontend#7971]

**Comment by Nawakwa** [comment]
All firefox themes and add ons are suddenly broken and unusable. I was watching a vid on Netflix when my browser suddenly lost its theme and a note appeared saying that some add ons are no longer supported by firefox. I don't care about add ons as much as I do themes. I tried to get a new theme, but every single one I click on leaves me with a red error note saying that the download failed and that I should check my internet connection. My internet is fine, your themes and add ons are all suddenly unusable. I tried replacing an add blocker too, but it's the same story. I tried updating, but no updates are available. I tried closing all windows, turning my pc off and on, but nothing changed.The only theme that works is "space fantasy" from the suggestions in the "customize" page thing, but it's far from anything I want. There's no way to search for a theme that is still compatible with firefox, and every one I click is somehow broken. I want to know when this is going to be fixed, the theme function is half the reason I use firefox and I'm switching if I can't have a theme I like..

**Comment by Nawakwa** [comment]
![image](https://user-images.githubusercontent.com/50267345/57179799-0a851680-6e3f-11e9-8b65-b43f8132694e.png)

**Comment by Nawakwa** [comment]
![image](https://user-images.githubusercontent.com/50267345/57179804-24bef480-6e3f-11e9-9d70-611c06f95287.png)

**Comment by wagnerand** [comment]
We rolled-out a fix for release, beta and nightly users. The fix will be automatically applied in the background within the next few hours, you don’t need to take active steps.

In order to be able to provide this fix on short notice, we are using the Studies system. You can check if you have studies enabled by going to Firefox Preferences -> Privacy & Security -> Allow Firefox to install and run studies.

You can disable studies again after your add-ons have been re-enabled.

We are working on a general fix that doesn’t need to rely on this. Sorry for the inconvenience.
