### ISSUE TITLE
Accès Collection Personelle Impossible

### ISSUE THREAD

**Issue by phil1525** [mozilla/addons-frontend#7977]

**Comment by phil1525** [comment]
I can not access my personal collection.
Error message: Unable to access the server.
"An error has unfortunately occurred on our server and we were unable to respond to your request, we recorded this error and will analyze it."

**Comment by willdurand** [comment]
Hi @phil1525, could you please tell me if the error messages you received were exactly the messages you quoted? Or is that translated from French, maybe? I am asking because I can't find these strings in our codebase..

Could you please paste the exact message or a screenshot? French is OK (I speak french).

**Comment by muffinresearch** [comment]
Please feel free to re-open this with further information, until then I'm going to close this out.
