### ISSUE TITLE
Replace "Featured" with "Recommended"  in "Featured extensions" and "See more featured extensions" 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8018]
A followup for https://github.com/mozilla/addons-frontend/issues/7794
Because the extensions will no longer have a "Featured" label which will change to "Recommended"
STR:
Observe AMO homepage - the "Featured extensions" shelf and the "See more featured extensions" blue link on the right side of the screen. 

Expected result:
"Recommended extensions"  and "See more recommended extensions" 

Actual result:
"Featured extensions" and "See more featured extensions"

Notes:
This issue is reproducible on AMO dev and stage - FF66(Win10). 
Please note that on Android the recommended label will not appear. 

![shelf](https://user-images.githubusercontent.com/33448286/57684363-505f8d00-763e-11e9-8d1e-7279ad3b0946.png)

**Comment by bobsilverberg** [comment]
@jvillalobos @devaneymoz Could you please comment on this and/or update the issue with the implementation you'd like to see.

Perhaps, because all extensions shown anywhere on the home page will be recommended (at least that's what I understand our goal to be), we can just remove the "featured" shelf entirely and not replace it with anything?

**Comment by devaneymoz** [comment]
The nomenclature cases noted here are all programmatically driven (i.e. I request what the copy and CTA's say with each. So when the Recommended Extensions program launches in June, I'll file the appropriate front end changes.

**Comment by jvillalobos** [comment]
So, the homepage is updated manually on a monthly basis, but this issue is still valid for [category](https://addons.mozilla.org/firefox/extensions/download-management/) and [type](https://addons.mozilla.org/firefox/extensions/) pages. In the PRD, I mentioned that these shelves should be renamed to Recommended and should only show recommended add-ons.

**Comment by bobsilverberg** [comment]
> So, the homepage is updated manually on a monthly basis, but this issue is still valid for [category](https://addons.mozilla.org/firefox/extensions/download-management/) and [type](https://addons.mozilla.org/firefox/extensions/) pages. In the PRD, I mentioned that these shelves should be renamed to Recommended and should only show recommended add-ons.

For the [category](https://addons.mozilla.org/firefox/extensions/download-management/) and [type](https://addons.mozilla.org/firefox/extensions/) pages, do we need to replace the existing "Featured" shelf with a "Recommended" shelf? I was under the impression that any add-on appearing on any of these shelves would be recommended (because we are going to limit them to recommended add-ons), and therefore we wouldn't really need a "Recommended" shelf at all.

@jvillalobos / @devaneymoz Could you please clarify this?

**Comment by jvillalobos** [comment]
We're keeping the Featured Extensions collection just so the link isn't broken. It will have a subset of the Recommended list, but we probably won't update it often. I would prefer that those shelves are renamed and use the Recommended list rather than the collection.

**Comment by devaneymoz** [comment]
@bobsilverberg @jvillalobos 

We won't have enough Recommended extensions per all 15 categories to show four extensions in a row (or for that matter even one extension in multiple category cases). So this may require a change to category level pages. 

"Type" pages will be fine.

**Comment by bobsilverberg** [comment]
Ok, I will open an issue to rename the shelves for now. Further changes required for categories can be covered by future issues.

**Comment by bobsilverberg** [comment]
This is now covered by #8028, so I'm closing this one.
