### ISSUE TITLE
Consider changing category pages once only recommended add-ons are shown

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#8050]
In https://github.com/mozilla/addons-server/issues/11067 there is a requirement to only show recommended add-ons on the category pages, but at the category level there will be some redundancies in what's shown and there may be insufficient add-ons in the near-future to fully populate the page.

Current Category page:
![Screenshot 2019-05-20 17 28 04](https://user-images.githubusercontent.com/768592/58037140-a774ce80-7b24-11e9-90ee-6d199ed102aa.png)

The "featured" shelve is redundant when all the content is recommended; "trending" could be empty as it relies on new add-ons surfacing and becoming popular (whereas recommended add-ons will be likely based on more mature established add-ons); and if three shelves were retained, e.g. with different sorting (such as created, downloads and ratings), with the number of extensions per category it's very likely there will be some duplicates between the shelves anyway.

These are all potential problems at the extension level too, but IMO it's at the category level where the restrictions will be more apparent.

@jvillalobos @atsay @devaneymoz

**Comment by jvillalobos** [comment]
@atsay and I talked about this earlier and there are a couple things we can do here:

1) Change category pages to a search results page with a category filter. This would allow users to choose different sorting options and filter further by entering a query string. I'm thinking this would be a possibly longer term solution since we don't do category filtering now.

2) Have a couple of taller shelves on category pages, to be mostly sure there will be some useful content. So, for example, there would be a Recommended shelf and a Trending shelf, both with up to 8 add-ons each. Is that a good solution for now?

I'm not too concerned about duplicate results for those pages, but I do want to show users at least a few good options instead of just 3-4.

**Comment by bobsilverberg** [comment]
I'm adding this to the [Recommendations Front-end Changes project](https://github.com/orgs/mozilla/projects/69) to track it. 

> @atsay and I talked about this earlier and there are a couple things we can do here:
> 
>  1. Change category pages to a search results page with a category filter. This would allow users to choose different sorting options and filter further by entering a query string. I'm thinking this would be a possibly longer term solution since we don't do category filtering now.
> 

This seems like a good idea to me, although you are right that it will require changes to our search filters.

>  2. Have a couple of taller shelves on category pages, to be mostly sure there will be some useful content. So, for example, there would be a Recommended shelf and a Trending shelf, both with up to 8 add-ons each. Is that a good solution for now?
> 

I'm not sure that this addresses @eviljeff's concerns about the "Recommended" shelf being redundant. If everything on this page will always be recommended, why do we need a Recommended shelf at all?

**Comment by atsay** [comment]
For #2, perhaps it could be just the Recommended shelf that is 2-3 rows high and that's it.

**Comment by jvillalobos** [comment]
If we show "top rated" or "trending", presumably those wouldn't be exclusively recommended. Showing a single, tall Recommended shelf works for me.

**Comment by atsay** [comment]
Just spoke to @devaneymoz, many of the categories won't have enough recommended extensions, some not at all. So I think we need to go with solution #1, with Recommended (if any) sorted to appear on top.

**Comment by eviljeff** [comment]
option 1. is just linking direct to https://addons.mozilla.org/firefox/search/?category=alerts-updates&sort=rating&type=extension I guess, with "Featured add-ons only" being replaced with "Recommended add-ons only" (and possibly pre-selected) - right @bobsilverberg ?

In terms of capabilities, the search api will accept:
- `?recommend=True` to _only_ show recommended add-ons
- `?sort=relevance` to naturally bump up recommended add-ons in the results - _not_ exclusively show them all at the top, but to raise them significantly.  `sort=relevance` needs a search string (`q=`) to return results in an order that makes sense.
- `?sort=recommended,<sort>` (e.g. `?sort=recommended,rating`) to show recommended add-ons at the top of any sort.  

Technically you can do `?sort=recommended,relevance` to force recommended to the top of a relevance search though I'm tempted to remove that (so it'd just be interpreted as `?sort=relevance`) as it seems redundant and frontend would have to special case not including `recommended` in the sort.

**Comment by atsay** [comment]
I prefer #3, to show recommended at the top of any sort. @devaneymoz @jvillalobos What do you think?

**Comment by devaneymoz** [comment]
Agree with #3 to show Recommended at the top of any sort.

**Comment by jvillalobos** [comment]
Yeah, that works, with `?sort=recommended,users` or whatever the ADI sort is.

**Comment by bobsilverberg** [comment]
> I prefer #3, to show recommended at the top of any sort. @devaneymoz @jvillalobos What do you think?

I don't believe there was a #3, but I guess you just created one. 😉 

Reading all the comments above, I'm not sure if we've made a final decision on this, and if so, what it is, or maybe it's still being discussed?

**Comment by atsay** [comment]
The decision is to go with option 1, linking directly to a category search. Any filter applied would sort by recommended extensions, followed by ADI.

**Comment by bobsilverberg** [comment]
> The decision is to go with option 1, linking directly to a category search. Any filter applied would sort by recommended extensions, followed by ADI.

Ok, that sounds good. This does raise the issue that @jvillalobos alluded to, which is that if we use the search results page, the form that appears will not allow a user to change or specify the category, but that's pretty much what we have now if you click on a link in the upper right-hand corner of a shelf on one of these pages.

So it sounds like what we're saying is that we're going to get rid of the category pages all together, and the links that currently lead to them would simply lead to a search results page with the category populated on the URL, and the sort criteria as recommended extensions, followed by ADI, correct? 

Do we want to keep the header at the top of each of these pages (which shows an icon and a title for the category) and show the search results below that, or would the page look just like any other search results page? 

If the user chooses to change the sort criteria on this "category results" page, would we honour their new criteria, but still add `recommended=true` as the first criterion, in order to force recommended results to the top?

**Comment by atsay** [comment]
> Ok, that sounds good. This does raise the issue that @jvillalobos alluded to, which is that if we use the search results page, the form that appears will not allow a user to change or specify the category, but that's pretty much what we have now if you click on a link in the upper right-hand corner of a shelf on one of these pages.

Yes, that's alright.

> So it sounds like what we're saying is that we're going to get rid of the category pages all together, and the links that currently lead to them would simply lead to a search results page with the category populated on the URL, and the sort criteria as recommended extensions, followed by ADI, correct?

Yes, correct.

> Do we want to keep the header at the top of each of these pages (which shows an icon and a title for the category) and show the search results below that, or would the page look just like any other search results page?

No, let's just have it look like a regular search results page.

> If the user chooses to change the sort criteria on this "category results" page, would we honour their new criteria, but still add `recommended=true` as the first criterion, in order to force recommended results to the top?

That's correct.

**Comment by bobsilverberg** [comment]
Ok, I believe we have the final requirements for changing the category pages. What about the type pages, e.g., https://addons.mozilla.org/en-US/firefox/extensions/ and https://addons.mozilla.org/en-US/firefox/themes/?

Each of those pages currently has 3 shelves: Featured, Top Rated and Trending. The same issues exist where (I believe) we want to only show recommended add-ons in those shelves, but there may not be enough to fill all the shelves (or maybe there will be, because now we are talking about *all* extensions and *all* themes?).

If we assume there will be enough recommended extensions and themes to always have at least 4 on each shelf, then I guess we can pretty much keep it as is, and only include recommended add-ons in the shelves.

If we fear that won't always work, I suppose we could change the search criteria to just sort it so that recommended is forced to the top, and then if we're short of add-ons non-recommended ones would fill things in.

@atsay @jvillalobos @devaneymoz What do you all think?

**Comment by eviljeff** [comment]
There's going to be 100+ recommended extensions at launch, so I'm sure there will be enough for 4 on each shelf.

For themes there are currently 34 in the collection, so I guess we're good with them too.

Having an explicit "recommended" shelve is perhaps redundant but could swap that out for something else (updated?) or just use random.  I.e. they'd be `?type=extension&sort=random&recommended=true`; `?type=extension&sort=rating&recommended=true`; `?type=extension&sort=hotness&recommended=true`

**Comment by devaneymoz** [comment]
I concur with @eviljeff. We should be fine with 100+ Recommended extensions at launch.

**Comment by jvillalobos** [comment]
Also, we don't need `/themes/` to be limited to recommended results, only `/extensions/`.

**Comment by bobsilverberg** [comment]
> There's going to be 100+ recommended extensions at launch, so I'm sure there will be enough for 4 on each shelf.
> 
> For themes there are currently 34 in the collection, so I guess we're good with them too.
> 
> Having an explicit "recommended" shelve is perhaps redundant but could swap that out for something else (updated?) or just use random. I.e. they'd be `?type=extension&sort=random&recommended=true`; `?type=extension&sort=rating&recommended=true`; `?type=extension&sort=hotness&recommended=true`

Are we settled on what the shelves should be on the Extensions and Themes landing pages? Do we want to replace the "Featured" shelf with a "Recommended" shelf and have the sort sequence `random`, as @eviljeff suggested?

**Comment by bobsilverberg** [comment]
I forgot to tag anyone on my question above, so doing it here:

> There's going to be 100+ recommended extensions at launch, so I'm sure there will be enough for 4 on each shelf.
> 
> For themes there are currently 34 in the collection, so I guess we're good with them too.
> 
> Having an explicit "recommended" shelve is perhaps redundant but could swap that out for something else (updated?) or just use random. I.e. they'd be `?type=extension&sort=random&recommended=true`; `?type=extension&sort=rating&recommended=true`; `?type=extension&sort=hotness&recommended=true`

Are we settled on what the shelves should be on the Extensions and Themes landing pages? Do we want to replace the "Featured" shelf with a "Recommended" shelf and have the sort sequence `random`, as @eviljeff suggested? @jvillalobos @devaneymoz

**Comment by jvillalobos** [comment]
Using `random` for the Recommended shelf sounds good to me. I don't think we need to make major changes to the shelves now.

**Comment by bobsilverberg** [comment]
Ok, I believe that everything discussed here has been moved into an issue. Here's what I opened as follow-ups:

- [Replace Category pages with search results pages](https://github.com/mozilla/addons-frontend/issues/8079)
- [Include only recommended add-ons on the Extensions landing page](https://github.com/mozilla/addons-frontend/issues/8085)
- [Redirect the links from the theme category shelf on the home page to Search Results](https://github.com/mozilla/addons-frontend/issues/8092)
- [Force recommended results to the top when sorting from a Category page](https://github.com/mozilla/addons-frontend/issues/8084)
- [Replace Featured shelves with Recommended shelves on the landing pages](https://github.com/mozilla/addons-frontend/issues/8028)
- [Replace Featured shelves with Recommended shelves on the home page](https://github.com/mozilla/addons-frontend/issues/8089)

There are also a couple of issues to deal with redirects for URLs that are going away:
- [Redirect category URLs to the Search Results page](#8094)
- [Redirect categories URLs to their respective pages](#8104)

I am therefore going to close this issue.
