### ISSUE TITLE
Redirect category URLs to the Search Results page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8094]
This is a spin-off from #8092.

We currently support URLs like:
- https://addons.mozilla.org/en-US/firefox/extensions/alerts-updates/
- https://addons.mozilla.org/en-US/firefox/themes/fashion/

The Category pages that those URLs currently point to are going away, and we want to redirect any traffic to the URLs to the Search results page similar to what was done in https://github.com/mozilla/addons-frontend/issues/8079.

**Comment by bobsilverberg** [comment]
A hint from @kumar303 on IRC: 

> we only need to care about server side redirects so I suggest following this example https://github.com/mozilla/addons-frontend/blob/master/src/core/server/base.js#L246

**Comment by willdurand** [comment]
> A hint from @kumar303 on IRC:
> 
> > we only need to care about server side redirects so I suggest following this example [/src/core/server/base.js@`master`#L246](https://github.com/mozilla/addons-frontend/blob/master/src/core/server/base.js#L246) [](/mozilla/addons-frontend/blob/HEAD@{2019-05-28T20:25:43Z}/src/core/server/base.js#L246)

Why isn't this solved at the nginx level?

**Comment by bobsilverberg** [comment]
> > A hint from @kumar303 on IRC:
> > > we only need to care about server side redirects so I suggest following this example [/src/core/server/base.js@`master`#L246](https://github.com/mozilla/addons-frontend/blob/master/src/core/server/base.js#L246) [](/mozilla/addons-frontend/blob/HEAD@{2019-05-29T08:09:32Z}/src/core/server/base.js#L246)
> 
> Why isn't this solved at the nginx level?
> 
> That's how we fixed the issue with the `tags` (#5047): [mozilla-services/cloudops-deployment:projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb@`673fa89`#L231-L232](https://github.com/mozilla-services/cloudops-deployment/blob/673fa89a0d62b1a7dd631dbf236a2b13e28e6f12/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L231-L232)

@kumar303 suggested that if we intend for this to be a permanent redirect, as opposed to a temporary redirect, that we should do it in the app, rather than via nginx. @willdurand do you disagree?

**Comment by willdurand** [comment]
We have permanent redirects in nginx too, I believe. For legacy stuff that don't involve any client side navigation, nginx seems a slightly better place to me, because it means we don't have to maintain anything in this repo.

**Comment by bobsilverberg** [comment]
> We have permanent redirects in nginx too, I believe. For legacy stuff that don't involve any client side navigation, nginx seems a slightly better place to me, because it means we don't have to maintain anything in this repo.

I tend to agree with that, and it seems simpler too. Perhaps the issue in this case is that we're redirecting not to a simple URL but to a URL with query parameters, and it's possible that those could change in the future in the app, and then we'd have to remember to change the nginx rule too. Is that your concern, @kumar303?

**Comment by kumar303** [comment]
I originally recommended against putting this in nginx because I considered it application logic (i.e. something specific to addons-frontend). However, since it is a mapping of a feature that will be *going away* from addons-frontend then it will soon no longer be application logic. So, yeah, nginx is a good place to put it.

> we're redirecting ... to a URL with query parameters, and it's possible that those could change in the future in the app, and then we'd have to remember to change the nginx rule too.

Yes, I am slightly concerned about this. If that were to happen, the nginx redirects could be showing the wrong page and we'd never know about it. If the code were in addons-frontend, I'm not sure we'd be much better off, though. This kind of problem is better solved with functional tests, of which we have very little.

**Comment by bobsilverberg** [comment]
Thanks for the feedback @kumar303. I've actually put together a PR (#8105) that solves this in addons-frontend (using a technique @willdurand suggested). Could you take a look and see if you're happy with that, or if you'd prefer we abandon that and just put some rules in nginx?

**Comment by willdurand** [comment]
I am also in favor of nginx because having redirects in our code will likely increase the load on the app servers. I don't know if we have a lot of traffic on those URLs, but that might have a significant impact (but maybe not).

The only argument I like about having redirects in our code is that we'll have them "documented" and covered by tests, which will be a good thing in a far future in which we'll want to change the nginx config.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified this on AMO dev - FF67(win10). 
Instead of https://addons.mozilla.org/en-US/firefox/extensions/alerts-updates/ or https://addons.mozilla.org/en-US/firefox/themes/fashion/ the links are 
https://addons-dev.allizom.org/en-US/firefox/search/?category=alerts-updates&sort=recommended%2Cusers&type=extension
and 
https://addons-dev.allizom.org/en-US/firefox/search/?category=fashion&sort=recommended%2Cusers&type=statictheme
- Every category for extensions and static themes changed the URL from the old format to the new search result pages which have the default sort parameters `recommeneded, users`. 
- the android platform functions under the same rules but without displaying the recommended badge. 
- I see the changes on AMO stage too. An example https://addons.allizom.org/en-US/firefox/search/?category=appearance&sort=recommended%2Cusers&type=extension Is this intended ? AMO stage still shows the Featured badge.

**Comment by bobsilverberg** [comment]
> * I see the changes on AMO stage too. An example [addons.allizom.org/en-US/firefox/search/?category=appearance&sort=recommended%2Cusers&type=extension](https://addons.allizom.org/en-US/firefox/search/?category=appearance&sort=recommended%2Cusers&type=extension) Is this intended ? AMO stage still shows the Featured badge.

Yes, this is intended. This change is landing on stage and prod, even though the recommended badges are not being turned on yet. They can function independently from each other.
