### ISSUE TITLE
Homepage shelves have a broken layout

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8154]
**STR**

1. Load AMO -dev
2. Observe the layout of the homepage shelves
3. Open AMO homepage on stage and compare results

**Actual result:**
On -dev, there is a misalignment between the add-on icons and their names. Theme previews also have a different size - 418x53 on -dev vs. 370x47 on stage

**Expected result:**
There are no layout issues observed

**Notes:**
- you can see the same layout issue on the Extensions and Themes landing pages, on the More extensions by this developer card, on the user profile page etc

**DEV**
![image](https://user-images.githubusercontent.com/31961530/59275947-029e6a80-8c66-11e9-9bbc-2f9e52a32846.png)

**STAGE**
![image](https://user-images.githubusercontent.com/31961530/59275843-c10dbf80-8c65-11e9-92df-f619d5055483.png)

**Comment by bobsilverberg** [comment]
This could have been a result of changes introduced in #8107. I am looking into it.

**Comment by bobsilverberg** [comment]
The problem is that we used to have a `<a>` tag wrapping the entire `SearchResult-result` element, with a class of `SearchResult-link` which was used to control some styling. We no longer have that `<a>` tag wrapping everything and those styles were not moved elsewhere. Complicating this was the fact that we still have an element with a style of `SearchResult-link` but it is no longer a wrapper.

I have a quick fix for now and we may want to do more in a follow-up.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx67, Win10x64 and Android 8.0


![image](https://user-images.githubusercontent.com/31961530/59288265-105eea80-8c7c-11e9-923d-a36a7fadcbf3.png)
