### ISSUE TITLE
Make Primary Hero Shelf decoration load dynamically

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#8248]
Part of [this PRD](https://docs.google.com/document/d/12aD_v5AOj1Y6VmT4xOuyNcrKfZxqhP8R_AOHroQVLV8/edit#).

Followup to https://github.com/mozilla/addons-frontend/issues/8247. The graphic on the bottom left of the Primary Hero Shelf will change dynamically, so every page load may show a different one. It will be chosen randomly from a set of graphics to be provided by @brassy-.

**Comment by kumar303** [comment]
I thought I'd seen a mock somewhere that showed the same noodle SVG but with different colors. Now that I look at Sketch again, I can't find an example of that. 

The only reason I put the SVG inline was so that we could apply styles to change colors *within* the SVG. Without that need, it wouldn't need to be inline.

**Comment by bobsilverberg** [comment]
It's been decided that we should remove the decorations entirely, so this issue is no longer relevant.
