### ISSUE TITLE
The home page re-fetches data infinitely upon error

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8317]
This is a follow up to #8292 and https://github.com/mozilla/addons-frontend/issues/8294

**For QA**: Since it may not be possible to trigger this error, please just check for any regressions on the home page

---

### Describe the problem and steps to reproduce it:

* Trigger an error from the saga that fetches home page data (see https://github.com/mozilla/addons-frontend/issues/8294 for an example). You can also `throw new Error(...)` after [this line](https://github.com/mozilla/addons-frontend/blob/e7774a9396f9530bbac00dcb606690adbfe65535/src/amo/sagas/home.js#L51) or anywhere within the saga's main `try` block.

### What happened?

The loading indicators are visible and the page won't load any data. In addition to that, we can observe countless API calls in the console.

### What did you expect to happen?

The page should not keep making API calls.

### Anything else we should know?

**Comment by willdurand** [comment]
> Trigger an error from the saga that fetches home page data (see #8294 for an example). You can also `throw new Error(...)` after [this line](https://github.com/mozilla/addons-frontend/blob/e7774a9396f9530bbac00dcb606690adbfe65535/src/amo/sagas/home.js#L51)

I find this STR very confusing because it is very tricky to reproduce in real life. Throwing an (unhandled) error anywhere in this saga will not always lead to the bug described here, although it should. I suggest we put the entire saga code into a `try/catch` block (instead of having two blocks wrapping the API calls).

Here, this STR works because (1) we are inside a `try/catch` block and (2) the error is not handled correctly, which is not exactly a real life scenario. We usually get a network error, which is handled here: https://github.com/mozilla/addons-frontend/blob/e7774a9396f9530bbac00dcb606690adbfe65535/src/amo/sagas/home.js#L57-L59

That's why https://github.com/mozilla/addons-frontend/pull/8304 fixed the infinite API calls problem for collections described in https://github.com/mozilla/addons-frontend/issues/8294. In other words, we should not focus on collections but rather on any data loaded by the saga.

If we want to protect against unhandled errors in this saga, I'd suggest we rephrase the STR to "add a `throw new Error(...)` statement anywhere in the saga and 🙏

**Comment by kumar303** [comment]
> Throwing an (unhandled) error anywhere in this saga will not always lead to the bug described here, although it should.

I addressed this in the patch and updated the STR.

**Comment by vcarciu** [comment]
Home page looks good. Marking the issue as verified.
