### ISSUE TITLE
+Add to Firefox button has the same state when adding search engines

### ISSUE THREAD

**Issue by VladLucaci** [mozilla/addons-frontend#8340]
Steps to reproduce:

1. Go to AMO https://addons.mozilla.org/en-US/firefox/search-tools/
2. Pick an option from the listed results to see its details page (i.e. https://addons.mozilla.org/en-US/firefox/addon/google-video-search-10562/?src=search)
3. Click the +Add to Firefox option.
4. When the Add Search Engine prompt is displayed, select the Add option.

Expected result:
The +Add to Firefox button becomes red with the Remove text.
Actual result:
The Add to Firefox button remains in the same state and can be interacted with. 

Notes: When clicked the second time, the button will trigger the installation error stating that an engine with the same name is already installed.

Reproduced with 
FF 68.0.1
FF 69.0b5
Nightly 70.0a1 (2019-07-18) 

Screencast of the issue: 
https://drive.google.com/file/d/1-K4c4Bz52msbuShhjp0TRVmAg2b_D0Sr/view?usp=sharing

**Comment by VladLucaci** [comment]
Also managed to reproduce this issue on a build from 2019-02-02 - 67.0a1 (buildID: 20190202213603)

**Comment by willdurand** [comment]
Hi, thanks for filing this bug. This is not possible becqause search plugins are not web extensions per se and therefore we don't use the `mozAddonManager` object to manage them. That's why we do not know the state of a search plugin and can't have nicer things.

There is some work in progress in Firefox to change that though (i.e. converting the old search engines to shiny new web extensions, compatible with the `mozAddonManager`).
