### ISSUE TITLE
Layout issues in the primary hero caused by unbroken strings

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8522]
Follow up for #8305 

### Describe the problem and steps to reproduce it:
1. Open AMO -dev homepage
2. Refresh the page until you get the primary hero with an unbroken string (see my example below)

### What happened?
Unbroken strings are not wrapped and, because of that, the primary hero section is too wide

### What did you expect to happen?
Unbroken string should be wrapped

**Notes:**
- this is unlikely to happen in production, hence it's a low priority issue

![2019-08-30_16-02-59](https://user-images.githubusercontent.com/31961530/64023274-a0f0ec80-cb40-11e9-9c6b-6117a5b817b6.gif)

**Comment by bobsilverberg** [comment]
While this is a low priority, I figured it would be a quick fix, so I tried, but I can't seem to fix it. The problem is that the long title is causing the flex item for the right-hand side of the promo to overflow its container:

![Screenshot 2019-08-30 09 56 19](https://user-images.githubusercontent.com/142755/64026394-ac2a2500-cb0c-11e9-93dd-46758caedb25.png)

The `div` itself is properly configured with `word-wrap: break-word`, but the problem is that the container is expanding to hold the whole thing. I've tried just about every trick suggested at https://stackoverflow.com/questions/36230944/prevent-flex-items-from-overflowing-a-container, including various combinations for `flex`, `flex-shrink` and `flex-grow`, as well as the suggestion at https://css-tricks.com/flexbox-truncated-text/, but cannot seem to come up with anything that will work.

@kumar303 / @willdurand / @muffinresearch does anyone have any suggestions?

**Comment by muffinresearch** [comment]
@bobsilverberg `word-break: break-word;` works on the h2 or the div within it.

**Comment by bobsilverberg** [comment]
> @bobsilverberg `word-break: break-word;` works on the h2 or the div within it.

I'm confused. `word-break`, either on the `h2` or the `div` doesn't seem to do anything for me. I'm testing it via the dev tools. Are you saying that simply adding `word-break: break-word;` to either the `h2` or the `div` fixes the issue for you? If so then maybe I need to test by changing the css and refreshing the page, rather than via devtools?

**Comment by bobsilverberg** [comment]
Ah, I see, it *does work*. I guess my methodology for testing css changes doesn't work particularly well. Thanks @muffinresearch!

**Comment by kumar303** [comment]
Yeah, this is low priority because AMO staff will have direct control over all text that gets inputted into this header element.

**Comment by bobsilverberg** [comment]
> Yeah, this is low priority because AMO staff will have direct control over all text that gets inputted into this header element.

I'm not sure they have *direct control*. I believe the problem in this case comes from the add-on's name, which I think is controlled by the addon metadata.

**Comment by kumar303** [comment]
Ah, that's true

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

![image](https://user-images.githubusercontent.com/31961530/64231706-06562c00-cef9-11e9-9d9a-17fefe133fc3.png)
