### ISSUE TITLE
Unlisted add-on title in the primary hero section uses an incorrect font style

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8532]
Follow up for #8305 

### Describe the problem and steps to reproduce it:
1. Open AMO homepage on -dev
2. Refresh the page until you get an unlisted add-on in the primary hero section (see example from the below screenshot) 
3. Observe the add-on name
4. Open the dev tools and inspect the font style

### What happened?
Unlisted add-on names are using a `font-weight` of `600`, while for listed add-ons the  `font-weight` is `400`
### What did you expect to happen?
For consistency, unlisted add-ons should use the same font style as listed add-ons

[unlisted add-on]
![image](https://user-images.githubusercontent.com/31961530/64101262-23162680-cd76-11e9-9252-8257a2cbcaea.png)

[listed add-on]
![image](https://user-images.githubusercontent.com/31961530/64101729-252cb500-cd77-11e9-8f36-c745986ead48.png)

**Comment by rbrishabh** [comment]
Hey! Can I take this up?

**Comment by bobsilverberg** [comment]
@rbrishabh Thanks for your interest, but because this relates to a feature that is actively being developed and hopes to ship very soon, it is not ideal for a contributor. We have issues that are marked as being appropriate for contributors, which can be found at https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome. I suggest you try to find one there instead.

**Comment by rbrishabh** [comment]
Alright! Thanks! :)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

![image](https://user-images.githubusercontent.com/31961530/64618146-67459e80-d3e8-11e9-9834-981e5505f5d2.png)
