### ISSUE TITLE
Don't send the GA enrollment event for Android

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8546]
Followup for:
https://github.com/mozilla/addons-frontend/issues/8505

1. Load AMO stage - homepage on a new profile for Android https://addons.allizom.org/en-US/android/
2. Open Browser Console (Ctrl+Shift+J) and land on an add-on detail page
3. Observe Browser Console

Actual result:
The GA Enrollment event is sent (yet, there is no yellow warning experiment message displayed on the detail page when the cookie is set to includeWarning)

Expected result:
Ga enrollment event is not sent since on Android the experiment is excluded.

Notes:
Reproducible with FF68 on AMO dev and stage. 

![GA event](https://user-images.githubusercontent.com/33448286/64250876-e5550180-cf1f-11e9-80e8-d82c0d581946.png)

**Comment by bobsilverberg** [comment]
Thanks for filing this @ioanarusiczki. This one is a bit tricky because the code that sends the enrollment event is quite dumb. It is generic for all experiments and therefore does not take any criteria into account. We can technically change that, but I want to make sure it's necessary (I assume it probably is).

@Felixlawrence How bad is it if we are marking users on Android as enrolled in the experiment, even if they never actually see the experiment? None of the events are ever sent for them, other than the enrolled event, so it shouldn't skew any statistics, other than the total number of users enrolled.

**Comment by felixlawrence** [comment]
This will add a bit of noise to the experiment, but we can live with it. I _might_ be able to filter it out in my analysis, but even if I can't it shouldn't be a big deal - if there were 9 android visitors to every 1 desktop visitor then we'd have to run the experiment roughly twice as long to get the same statistical power; here I bet the ratio is the other way around so the difference should be negligible.

**Comment by bobsilverberg** [comment]
Thanks @felixlawrence. Looking at GA, it looks like around 16% of users are on Android, so based on what you said above it sounds like that shouldn't create a big problem for our analysis. Do you agree?

**Comment by felixlawrence** [comment]
Yes.

Plan A: I'll filter out Android in the analysis
Plan B: I'll cope with the noise.

Happy with plan A or B.

**Comment by bobsilverberg** [comment]
Great, thanks @felixlawrence. I think we can keep things as is for this experiment, but it's something to think about for future ones.

@ioanarusiczki As a result of this conversation, I'm going to close this issue. We're okay with the enrollment event being send on Android.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Understood. I had no information about the[ Android user](https://github.com/mozilla/addons-frontend/issues/8546#issuecomment-527983778) so it looked like an issue that needed discussions.

**Comment by bobsilverberg** [comment]
Definitely, @ioanarusiczki, thanks for filing the issue!
