### ISSUE TITLE
Support wildcards in `hasPermission()`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8575]
The `hasPermission()` function only matches entire permission values (i.e. very specific permissions like `Addons:Edit`) but some users have broader permissions like `Addons:*`.

https://github.com/mozilla/addons-frontend/blob/a6fa499287246a417bcf794bd7351f875416317d/src/amo/reducers/users.js#L443-L462

We should support permission values that contain wildcards so that users with the `Addons:*` permission can access resources protected by `Addons:Edit` for instance.

Given that the "super power" permission is already handled, we can focus on permissions of the form: `SomeName:*` only.

**Comment by ioanarusiczki** [comment]
@willdurand Can you add some STR for qa?

**Comment by willdurand** [comment]
@ioanarusiczki yep, sorry!

**Comment by ioanarusiczki** [comment]
@willdurand 
I created in admin dev 2 groups - Addons:* and then Addons:Edit

What `Addons:*` can access from the detail page for an extension:
[Edit add-on ](https://addons-dev.allizom.org/en-US/developers/addon/webextensionspermissions/edit)
[Content Review Addon](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-content/webextensionspermissions)
[Review Addon code](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/webextensionspermissions)
For a theme the only link available is [Edit add-on ](https://addons-dev.allizom.org/en-US/developers/addon/happycat/edit)

For `Addons:Edit` for both addons or themes the only link available from the detail pages is t
`Edit add-on`

Let me know if it's the expected behavior (I tend to believe it is, themes have other permissions for reviews).

**Comment by willdurand** [comment]
> Let me know if it's the expected behavior (I tend to believe it is, themes have other permissions for reviews).

Yes, looks good to me

**Comment by ioanarusiczki** [comment]
@willdurand Alright! Then I'm marking it verified on dev with FF69(Win10).
