### ISSUE TITLE
Update primary hero gradient to be full-width of viewport

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#8623]
Via feedback from Emanuela:

The primary hero gradient should be updated to be full width across the viewport. ~~The swoosh will also move left, which means on a wider page it won't overlay the image.~~ Update: Swooshes are being deprecated so this can be removed.

The content of the primary hero will stay centred and limited to the max-width as per the rest of the content currently.

The padding/margin above the gradient will need to be removed.

Special consideration will need to be given to where notifications should appear. They should be above the hero content but on top of the full-width gradient.

This mock shows what it looks like albeit without demonstrating the gutter that will appear on a larger screen:

![image](https://user-images.githubusercontent.com/1514/65234000-b1efa680-dacb-11e9-8f62-28b698f13068.png)

**Comment by bobsilverberg** [comment]
Thanks @muffinresearch. This looks like the original mocks, and at some point it was decided that doing this was out of scope at this time. I guess that has changed?

**Comment by muffinresearch** [comment]
> Thanks @muffinresearch. This looks like the original mocks, and at some point it was decided that doing this was out of scope at this time. I guess that has changed?

Yeah, the intent to have this full-width wasn't obvious initially back when we were trying to pull this together quickly as a static version. Based on how Emanuela has described it I think it should work, it just will require some refactoring of markup to allow for it.

**Comment by muffinresearch** [comment]
@bobsilverberg note the update to the issue - based on the frontend review call the swoosh (aka noodles) are now deprecated so that can just be removed.

**Comment by bobsilverberg** [comment]
@muffinresearch I just want to clarify: we're removing the decorations/swooshes entirely now?

**Comment by muffinresearch** [comment]
> @muffinresearch I just want to clarify: we're removing the decorations/swooshes entirely now?

Yes.

**Comment by bobsilverberg** [comment]
@brassy- Looking at the mock, it looks like the gradient now starts at the very top of the page, so the nav bar is included in the gradient, as opposed to just having a black background as it does in the current site. Is that accurate? Or will the nav bar remain solid black and only the hero area will include the gradient?

**Comment by bobsilverberg** [comment]
@brassy- More on the above: If the gradient from the hero is meant to start at the top of the screen, and therefore span across both the nav bar and the hero, how will this work on pages without the hero (which is every page other than the home page)? The colours for the gradient are currently based on data we get back from the hero API, but we shouldn't be required to call the hero API on every page in order to get a gradient. We could just use a default gradient on pages that are not the home page, but this would mean that when navigating both from and to the home page the gradient for the nav bar could change, which seems like it would be very distracting to me.

**Comment by jvillalobos** [comment]
The mock seems to be combining the hero area and the Skyline rebranding, which is out of scope for this project. The header shouldn't change for now.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos

**Comment by bobsilverberg** [comment]
@brassy- @muffinresearch had come concerns about the width of the content in the "full-width" primary hero. Looking at this screenshot, you can see that the content, not just the gradient,  occupies the full width. Should this be changed so that the content (and also the site notification, which is the yellow message bar) are constrained to the width of the other shelves on the home page, such as the secondary hero and the Recommended extensions shelf?

![Screenshot 2019-10-02 13 24 33](https://user-images.githubusercontent.com/142755/66067598-ec206580-e519-11e9-9c4b-44ce62bc3f80.png)

**Comment by bobsilverberg** [comment]
@brassy- Here's an example where the width is constrained, and I think it looks better. Maybe this is what you were after all along, but it wasn't clear from the mocks.

![Screenshot 2019-10-02 13 56 17](https://user-images.githubusercontent.com/142755/66072752-a49ed700-e523-11e9-8d32-35051b3c6192.png)

**Comment by brassy-** [comment]
Yes, the second screen is what we want to achieve!

Thank you for keeping me in the loop!

Il giorno mer 2 ott 2019 alle 20:48 Bob Silverberg <notifications@github.com>
ha scritto:

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

[large screen]
![image](https://user-images.githubusercontent.com/31961530/66297000-6fb1cc00-e8f7-11e9-9050-9242e7d98366.png)



[mobile]
![image](https://user-images.githubusercontent.com/31961530/66296913-44c77800-e8f7-11e9-9084-fde16197174c.png)

**Comment by AlexandraMoga** [comment]
@bobsilverberg forgot to ask if the default header color to be used across the site should be `#20123a`  ` (ink-80)` now?

Previously, the header color was `#0f1126`

**Comment by bobsilverberg** [comment]
> @bobsilverberg forgot to ask if the default header color to be used across the site should be `#20123a` ` (ink-80)` now?
> 
> Previously, the header color was `#0f1126`

Yes, if the new hero elements are enabled, then the default background colour for the header, on every page, should be `#20123a`.
