### ISSUE TITLE
Always show `InstallWarning` when we could

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8642]
### Describe the problem and steps to reproduce it:

1. Make sure you are in the right cohort (`includeWarning`) so that you see the install warning banner when you browse an extension that is not recommended (and not installed)
2. Install the extension
3. Reload the page

### What happened?

The warning banner is not displayed (disappeared). 

### What did you expect to happen?

The warning banner is displayed because it could still be useful (and it is confusing).

We discussed this on Slack a while ago but AFAIK no one has filed an issue so here is one.

**Comment by bobsilverberg** [comment]
I recall an initial discussion where you expressed concerns about the inconsistency of this, but I don't recall a discussion where a decision was made to change it. Of course, I'm not very good at Slack, so that could explain that.

In any case, @jvillalobos, can you please confirm that our intent is to change the behaviour to show the installWarning even when the extension is already installed?

**Comment by bobsilverberg** [comment]
Thanks to @willdurand, I saw the thread on Slack where this was discussed, so I no longer need confirmation.

**Comment by ioanarusiczki** [comment]
@bobsilverberg When cookie is set to `includeWarning` the message is available after installing an add-on.  Also, it is available for `Enable` state.  Verified on AMO dev with FF69(Win10). 

![Brief](https://user-images.githubusercontent.com/33448286/65598517-4b272d00-dfa4-11e9-9aa8-3ce3b3d2dc0d.gif)
