### ISSUE TITLE
A lot of addons are missing

### ISSUE THREAD

**Issue by VitRom** [mozilla/addons-frontend#8683]
After a recent huge crash I've lost both all working software and archives. So I had downloaded back from my cloud my favorite "work horse", portable Firefox 38ESR, tuned and working fine, even with a set of previously opened tabs remembered. And because this copy was uploaded urgently some of these tabs were still with AMO pages with extensions (used earlier) to install. So I decided to finish with addons installation and started to open these tabs.

### What happened?

EVERY tab shows damned "Nothing here. Either deleted by author either violates policy" page.

### What did you expect to happen?

Addons pages, indeed

### Anything else we should know?

https://addons.mozilla.org/ru/firefox/addon/profileswitcher
https://addons.mozilla.org/ru/firefox/addon/switchy/?src=search
https://addons.mozilla.org/ru/firefox/addon/tab-groups-helper/?src=dp-dl-othersby
etc. etc.

**Comment by jvillalobos** [comment]
We can't do anything about those listings if they were removed by their authors or were automatically disabled because they're outdated. You can try contacting the authors to find old copies of the add-ons, or you can dig through these independent archives: [1](https://archive.org/details/addons.mozilla.org_legacy_201810), [2](https://github.com/JustOff/ca-archive/).
