### ISSUE TITLE
Long strings are causing overflow on search results links

### ISSUE THREAD

**Issue by alexkayabula** [mozilla/addons-frontend#8751]
### Describe the problem and steps to reproduce it:
1. Load AMO -dev homepage and set your screen size to  ~750 on Google Chrome.

### What happened?
- Contents should be centred.

### Anything else we should know?
- Screenshot of the issue
- I was able to reproduce this issue on macOS High Sierra.
        
<img width="922" alt="Screen Shot 2019-10-10 at 14 38 05" src="https://user-images.githubusercontent.com/31479458/66565725-d50df300-eb6b-11e9-869d-03de7c4f742d.png">

**Comment by bobsilverberg** [comment]
Thanks for filing this, @alexkayabula, but I am wondering how you generated this problem. When I check this issue on -dev and also on the production site, I cannot reproduce it. 

For example, on prod (note "Facebook Container"):

![Screenshot 2019-10-16 11 48 48](https://user-images.githubusercontent.com/142755/66935983-f313a180-f00a-11e9-8fb6-015d34770f4a.png)
 
And on dev (note "EnhancerforYouTube..."):

![Screenshot 2019-10-16 11 50 04](https://user-images.githubusercontent.com/142755/66936084-1c343200-f00b-11e9-8658-e71c7da5c2b5.png)

It appears that the existing rule for `.SearchResult-link` which specifies `word-wrap: anywhere;` is already working to address this issue.

With which browser and OS were you able to produce the problem in your screenshot above?

**Comment by alexkayabula** [comment]
> Thanks for filing this, @alexkayabula, but I am wondering how you generated this problem. When I check this issue on -dev and also on the production site, I cannot reproduce it.
> 
> For example, on prod (note "Facebook Container"):
> 
> ![Screenshot 2019-10-16 11 48 48](https://user-images.githubusercontent.com/142755/66935983-f313a180-f00a-11e9-8fb6-015d34770f4a.png)
> 
> And on dev (note "EnhancerforYouTube..."):
> 
> ![Screenshot 2019-10-16 11 50 04](https://user-images.githubusercontent.com/142755/66936084-1c343200-f00b-11e9-8658-e71c7da5c2b5.png)
> 
> It appears that the existing rule for `.SearchResult-link` which specifies `word-wrap: anywhere;` is already working to address this issue.
> 
> With which browser and OS were you able to produce the problem in your screenshot above?

I used Google Chrome Version 77.0.3865.90 on macOS High Sierra to produce the issue. 
cc: @bobsilverberg

**Comment by bobsilverberg** [comment]
It looks like the only rules that work here on Chrome are `word-break: break-word`, which we have started trying to avoid because [it is deprecated](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#Syntax), and `word-break: break-all`, which is not deprecated, but is a bit less friendly than `word-break: break-word`. We have instead been using `overflow-wrap: anywhere`, which works on Firefox, but isn't supported on Chrome.

I am guessing this means there may be other places where we're currently using `overflow-wrap: anywhere` and it isn't having the intended effect on Chrome.

@kumar303 @willdurand @muffinresearch what do you think about this? Should we be adding extra rules to make sure that these work on Chrome and other browsers?

**Comment by bobsilverberg** [comment]
Thanks for the information @alexkayabula. I think we're going to address this at a more fundamental level, as we keep coming across this same issue with different elements. For that reason I'm going to close the PR that you opened related to this, but I will leave this issue open to track our progress towards a more complete solution.

**Comment by willdurand** [comment]
> Should we be adding extra rules to make sure that these work on Chrome and other browsers?

Yes.
