### ISSUE TITLE
Support Abuse Report hand-off in clients that support it

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#8762]
Depends on https://github.com/mozilla/addons-server/issues/12741

In [bug 1580561](https://bugzilla.mozilla.org/show_bug.cgi?id=1580561), we implemented an API that allows AMO to trigger the Abuse Report flow in Firefox, for a specific add-on. We need to hook up the current Report Abuse feature to work with it. This just landed in 71.

For clients that have this new API available, clicking on on the "Report this add-on for abuse" button should call this API instead of showing the current form. All other clients should continue using the current UX.

For QA:

- On versions of Firefox below 71, nothing about the report abuse flow should change.
- On Firefox 71 and above, when clicking the "Report this add-on for abuse", the built-in Firefox dialogs will be used to report abuse. Note that this will only happen if the user also has `extensions.abuseReport.amWebAPI.enabled` set to `true`. To test this on dev, `extensions.abuseReport.amoDetailsURL` should also be set to `https://addons-dev.allizom.org/api/v4/addons/addon/` and `extensions.abuseReport.url` should be set to `https://addons-dev.allizom.org/api/v4/abuse/report/addon/`.

Note also that when using the built-in Firefox flow:
- Once the Firefox dialog is opened, the "Report this add-on for abuse" button should be disabled until the Firefox flow completes.
- If the user successfully completes the abuse report (i.e., does not click "Cancel"), the "Report this add-on for abuse" button will be replaced with a message saying "You reported this add-on for abuse", which is exactly the same as what would happen after an abuse report is submitted using the older AMO flow.

**Comment by bobsilverberg** [comment]
This has landed for 71, but I'm not sure how to interact with in in Nightly.

@rpl I can see the `abuseReportPanelEnabled` property, but it returns `false`. Is there an `about:config` flag that needs to be flipped in order to activate the `reportAbuse` function?

**Comment by bobsilverberg** [comment]
> This has landed for 71, but I'm not sure how to interact with it in Nightly.
> 
> @rpl I can see the `abuseReportPanelEnabled` property, but it returns `false`. Is there an `about:config` flag that needs to be flipped in order to activate the `reportAbuse` function?

Nevermind, I found `extensions.abuseReport.amWebAPI.enabled` and `extensions.abuseReport.openDialog`, although I'm not sure what the latter controls.

**Comment by bobsilverberg** [comment]
@rpl I am having trouble testing this locally. No matter what I do the promise from `reportAbuse()` gets rejected. I get the dialog that asks me for a reason, but if I submit it after the second page the promise gets rejected with "Error: Error submitting abuse report". I thought it might have something to do with the lookup process - i.e., it's trying to look up the add-on on prod when I'm running the dev site, but it doesn't even work when the add-on is installed. Can you help?

**Comment by bobsilverberg** [comment]
Further to the above, I tried changing `extensions.abuseReport.amoDetailsURL` to `https://example.com:3000/api/v4/addons/addon/` (an address that works to return API requests to the browser), but I still only get rejected promises.

**Comment by rpl** [comment]
@bobsilverberg The underlying issue should be the same one reported as mozilla/addons-server#12741 (as a side note helpful during development: to be able to see the underlying error that triggered the rejection you have to enable the console messages in the browser console, e.g. by setting the pref "devtools.browserconsole.contentMessages" to true).

**Comment by willdurand** [comment]
@bobsilverberg could you please update the OP to add clear instructions for QA? Thanks!

Other question: do we want to use a feature flag for this feature?

**Comment by bobsilverberg** [comment]
> @bobsilverberg could you please update the OP to add clear instructions for QA? Thanks!
> 
> Other question: do we want to use a feature flag for this feature?

I don't see any reason to use a feature flag for this. Without one, nothing will change for anyone with a version of Firefox that doesn't support the API, and for users on versions of Firefox that do support the API, they will be using the Firefox dialogs to submit abuse reports. 

@jvillalobos Do you see any reason to use a feature flag for this, rather than just landing the changes now?

**Comment by bobsilverberg** [comment]
> > @bobsilverberg could you please update the OP to add clear instructions for QA? Thanks!

I have done so. Thanks for the reminder.

**Comment by willdurand** [comment]
> I don't see any reason to use a feature flag for this. Without one, nothing will change for anyone with a version of Firefox that doesn't support the API, and for users on versions of Firefox that do support the API, they will be using the Firefox dialogs to submit abuse reports.

I was thinking about a kill-switch but that might not be useful.

**Comment by bobsilverberg** [comment]
> > I don't see any reason to use a feature flag for this. Without one, nothing will change for anyone with a version of Firefox that doesn't support the API, and for users on versions of Firefox that do support the API, they will be using the Firefox dialogs to submit abuse reports.
> 
> I was thinking about a kill-switch but that might not be useful.

This patch is so simple that I suppose if we need to undo it that would be quite easy to do. Even a config change to update a flag would require a full push, so if that's the only reason to have a flag I'm not sure it'd be buying us much.

**Comment by jvillalobos** [comment]
I'm okay landing this without a flag.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I tested this following the qa steps specified [above](https://github.com/mozilla/addons-frontend/issues/8762#issue-505946153) on FF71 (Nightly).

- if I test the STR given by the server issue https://github.com/mozilla/addons-server/issues/12741 the new abuse report form is opened when I use the web console from "https://addons.mozilla.org". If I open it in AMO dev and call `await navigator.mozAddonManager.reportAbuse("worldwide@radio")` or use another addon guid from dev I receive an error.

![why from prod](https://user-images.githubusercontent.com/33448286/68676588-0c086780-0563-11ea-9164-c9f284c09060.gif)

- If I go to an add-on detail page from dev I see the old form as being available

![old form](https://user-images.githubusercontent.com/33448286/68677476-d95f6e80-0564-11ea-9142-8b331cb88878.gif)

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. Did you make sure that `extensions.abuseReport.amWebAPI.enabled` is set to `true` in `about:config`, as detailed at https://github.com/mozilla/addons-frontend/issues/8762#issue-505946153?

**Comment by bobsilverberg** [comment]
@ioanarusiczki Please check your setting for `extensions.webapi.testing`. Make sure it's set to `true`.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I created a new profile with FF72.0a1 (Win10) - this is Nightly up to date today - and I did not have the yesterday's problem. 
From the add-ons detail page: 

![new form on dev on extensions](https://user-images.githubusercontent.com/33448286/68762494-f0fb2d80-061e-11ea-86f9-b8d148dbd337.gif)

The problem now is that for themes, lang packs, dictionaries or search tools I cannot open any form - the button is inactive. 

![inactive report ](https://user-images.githubusercontent.com/33448286/68762799-93b3ac00-061f-11ea-8bbc-34f61e6527b0.gif)

**Comment by willdurand** [comment]
mmm I thought we had a fallback in place?

Console log is:

```
Reporting add-on for abuse via firefox failed: Error: Error creating abuse report
```

**Comment by willdurand** [comment]
Having a feature flag for this new feature would have been handy, heh. I guess we have to fix that before tomorrow's push then.

**Comment by willdurand** [comment]
@rpl is the new FF abuse report feature available in FF release? Do you know why it would fail with static themes for example?

**Comment by rpl** [comment]
> @rpl is the new FF abuse report feature available in FF release? 

`mozAddonManager.reportAbuse` and `mozAddonManager.abuseReportPanelEnabled` has been introduced in [Bug 1580561](https://bugzilla.mozilla.org/show_bug.cgi?id=1580561), which landed in Firefox 71 (and so it is currently available, behind the pref, only in 71 Beta and 72 Nightly) 

> Do you know why it would fail with static themes for example?

@willdurand the browser console should provide some additional details about the reason behind the failure. Something that may prevent the abuse report to be created successfully is "being unable to retrieve the addon metadata needed to fill the report abuse panel":
- if the addon is installed in the Firefox instance then Firefox will just use the metadata available locally, - otherwise it is going to try to retrieve the necessary metadata from the API endpoint specified in the "extensions.abuseReport.amoDetailsURL" about:config pref (which by default is set to "https://services.addons.mozilla.org/api/v4/addons/addon/"), if we are unable to retrieve the addon metadata from both these sources, the report creation will fail.

@willdurand would you mind to check in the browser console and see if we have a more details error there?
Alternatively: Do you have an STR (or just the addon id of the static themes) that we currently fail to open a report for? (so that I can reproduce the issue locally and take a look into it)

As an additional side note related to this, the integrated abuse report panel currently support only extension and themes (e.g. we do only have abuse categories and related localized descriptions only for these two kind of addons), and so currently it is going to refuse to create an abuse report panel for langpacks, dictionaries and search tools.

**Comment by willdurand** [comment]
> @willdurand would you mind to check in the browser console and see if we have a more details error there?

Yeah, I just did that. It looks like the API returns a 304 for some reason. I don't get a 304 when I open the link in a new tab. Output of the browser console:

```
XHR GET https://services.addons-dev.allizom.org/api/v4/addons/addon//%7Bd657e5e2-ac3a-4ff4-bb0a-81ec875a8067%7D
[HTTP/1.1 301 Moved Permanently 0ms]

XHR GET https://services.addons-dev.allizom.org/api/v4/addons/addon/%7Bd657e5e2-ac3a-4ff4-bb0a-81ec875a8067%7D/
[HTTP/1.1 304 Not Modified 441ms]

Request URL:https://services.addons-dev.allizom.org/api/v4/addons/addon/%7Bd657e5e2-ac3a-4ff4-bb0a-81ec875a8067%7D/
Request Method:GET
Remote Address:52.207.46.124:443
Status Code:
304
Version:HTTP/1.1
	
Response Headers (1.566 KB)	
Raw Headers
Allow	
GET, HEAD, OPTIONS
Connection	
keep-alive
Content-Security-Policy	
media-src https://videos.cdn.m…ne'; report-uri /__cspreport__
Date	
Wed, 13 Nov 2019 13:18:11 GMT
ETag	
W/"b7bcec8bc6fafc21a3aef3b7a37b78b8"
Public-Key-Pins	
max-age=5184000; includeSubDom…ko/cwxzOMo1bk4TyHIlByibiA5E="
Server	
nginx
Strict-Transport-Security	
max-age=31536000
Vary	
Origin, Accept-Encoding
X-AMO-Request-ID	
fd1baf1fde9e40c1ae8d6de209dd4ee4
X-Content-Type-Options	
nosniff
X-Frame-Options	
DENY
X-XSS-Protection	
1; mode=block
Request Headers (415 B)	
Raw Headers
Accept	
*/*
Accept-Encoding	
gzip, deflate, br
Accept-Language	
en-US,en;q=0.5
Connection	
keep-alive
Content-Type	
application/json
DNT	
1
Host	
services.addons-dev.allizom.org
If-None-Match	
W/"b7bcec8bc6fafc21a3aef3b7a37b78b8"
User-Agent	
Mozilla/5.0 (Macintosh; Intel …) Gecko/20100101 Firefox/72.0
XHRGEThttps://github.com/hovercards?user_id=217628&subject=issue%3A505946153&current_path=%2Fmozilla%2Faddons-frontend%2Fissues%2F8762
[HTTP/1.1 200 OK 1042ms]
```

**Comment by willdurand** [comment]
I tried with this static theme: https://addons-dev.allizom.org/en-US/firefox/addon/fire-and-water2/?src=featured

**Comment by willdurand** [comment]
> and so currently it is going to refuse to create an abuse report panel for langpacks, dictionaries and search tools.

That's good to know, I think we need to change that, too.

**Comment by rpl** [comment]
@willdurand ah, thanks for pointing out those logs, they have been already useful:

I just checked the code on the Firefox side that is querying that API endpoint and [currently it is only considering the request as successful when the status is 200](https://searchfox.org/mozilla-central/rev/6566d92dd46417a2f57e75c515135ebe84c9cef5/toolkit/mozapps/extensions/AbuseReporter.jsm#214-216) (which was quite foolish of me :-( ).

I'm going to reproduce the issue locally and take care of fixing that part of the Firefox side (I'll link the new bugzilla issue here once I filed it).

**Comment by willdurand** [comment]
@rpl Thanks! Did you notice the 301 redirect too? I don't think it is useful :p

**Comment by willdurand** [comment]
I checked and I don't think we can do anything about the HTTP issue. The `mozAddonManager.reportAddon()` call does not return an error but `false`, which indicates that the user has cancelled the report. This means we cannot easily fallback to the frontend UI...

I am going to propose a patch to only use the FF abuse report in extension/theme pages, though.

**Comment by willdurand** [comment]
> The problem now is that for themes, lang packs, dictionaries or search tools I cannot open any form - the button is inactive.

Let's recap. There are different issues related to the comment above.

1. Only extensions and static themes should use the FF abuse report, this is now tracked in https://github.com/mozilla/addons-frontend/issues/8929
2. FF only supports 200 HTTP requests (see @rpl's comment above). This will be fixed in FF
3. When the `mozAddonManager.reportAddon()` call fails, the Promise does not always reject, so we cannot easily implement a fallback as explained above

@rpl we will need a patch in FF for (3) too. You can try with a dictionary: https://addons-dev.allizom.org/en-US/firefox/addon/albanian-dictionary/. It will resolve the Promise with `false`. It should throw instead. Note: it throws for search plugins because the API returns a `401` response.

**Comment by rpl** [comment]
I just reproduced the issue locally and took a look. Turned out I was wrong, it seems that we are actually cancelling that abuse report request because of the addon type returned from those themes, which is currently "statictheme" (instead of "theme" as we expect).

Currently abuse-report-panel is cancelling the report when the addonType is unexpected:
- https://searchfox.org/mozilla-central/rev/6566d92dd46417a2f57e75c515135ebe84c9cef5/toolkit/mozapps/extensions/content/abuse-report-panel.js#597-601

But we could definitely catch the issue earlier and reject explicitly if the AMO API is trying to create a report for an unsupported addon type.

Nevertheless, the static themes are supposed to be supported, and they would be if the addon details returned by that API endpoint would have type "theme" instead of "statictheme".

I can definitely fix that on the Firefox side if we need to, but to get that fix on Firefox 71 we will need to land the fix on Nightly 72 first and then request an uplift to beta, possibly before Friday because QA is going to do a preliminary report this Friday.

@willdurand do you know if this is something that we may change on the API endpoint side? (by making the API endpoint to return a type "theme", at least if it is not too complex as a change and if there isn't anything else that expects the type "statictheme" instead)

**Comment by willdurand** [comment]
> @willdurand do you know if this is something that we may change on the API endpoint side? (by making the API endpoint to return a type "theme", at least if it is not too complex as a change and if there isn't anything else that expects the type "statictheme" instead)

I think we should not change the `type` in the API because `statictheme` is being used everywhere, and that would be super confusing. `theme` refers to lightweight themes but we don't support them anymore. I think FF should adopt `statictheme`.

/cc @diox

**Comment by rpl** [comment]
@willdurand eh, unfortunately the opposite is also true on the Firefox side... we already use "theme" everywhere.

I guess we just have to normalize the addon type in AbuseReporter.jsm when we retrieve and normalize the rest of he addon metadata received from the API endpoint.
I'll do that in the meantime.

**Comment by willdurand** [comment]
> @willdurand eh, unfortunately the opposite is also true on the Firefox side... we already use "theme" everywhere.

Oh, oops. @diox WDYT?

I like the idea of normalizing the add-on type in `AbuseReporter.jsm` tbh, not because it avoids a change in the AMO API but because we'll keep the AMO API consistent.

**Comment by eviljeff** [comment]
> >@willdurand eh, unfortunately the opposite is also true on the Firefox side... we already use "theme" everywhere.
>
> Oh, oops. @diox @eviljeff WDYT?

Changing from "statictheme" to "theme" isn't backwards compatible with existing usage so it's pretty much a no-no. We could change it in a newer version of the API but Firefox would have to switch to that too (which should be largely compatible... but would need testing and possibly other changes on the Firefox side)

**Comment by rpl** [comment]
Filed (and attached a patch on) the following two issues:

- [Bug 1596133 - AbuseReporter.queryAMOAddonDetails should normalize type 'statictheme' into type 'theme'](https://bugzilla.mozilla.org/show_bug.cgi?id=1596133)
- [Bug 1596137 - mozAddonManager.reportAbuse should reject on unsupported addon types](https://bugzilla.mozilla.org/show_bug.cgi?id=1596137)

**Comment by ioanarusiczki** [comment]
Followups have been files so the remaining issues can be tracked.
Verified on dev with FF72(win10).
