### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gggustafson** [mozilla/addons-frontend#8766]
The link 

https://addons.mozilla.org/en-US/firefox/addon/bookmark-favicon-changer/

is broken

**Comment by muffinresearch** [comment]
We are unable to provide support for individual add-ons.

This issue tracker is only for issues related to the https://addons.mozilla.org (AMO) website and related services.  

In this case the add-on is no-longer available because the add-on was not updated to support current versions of Firefox, it's up to the developer to provide an new version.

**Comment by gggustafson** [comment]
That's a cop-out if I've ever heard one. I don't know who the developer is. BUT the addon is published on YOUR site.

More and more, I'm disappointed with mozilla
