### ISSUE TITLE
AMO homepage is displayed instead of dev hub after new register

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8783]
STR:
1. Start registration from https://addons-dev.allizom.org/en-US/developers/
2. Confirm registration on e-mail and notice you are directed to the edit page 
3. Edit the display name and click the "Create account" button 
4. Observe the screen 

Expected result:
URL redirects to https://addons-dev.allizom.org/en-US/developers/ and lands on dev hub logged in view. 

Actual result:
URL is https://addons-dev.allizom.org/en-US/developers/ but AMO homepage is displayed instead. Refreshing the page will show the correct page. 

Notes:
This issue is reproducible on AMO dev with FF69(Win10). 

![testdevelopers](https://user-images.githubusercontent.com/33448286/66920503-1a2e9b00-f02c-11e9-8307-fa61ed481139.gif)

**Comment by bobsilverberg** [comment]
> Creating a white list of urls on either addons-frontend or addons-server sounds impractical. Could addons-frontend intuit that the url is not a frontend url? If not, couldn't a more generic http redirect be used instead that would work for any url?
> 

I assumed there was a downside to doing a http redirect to an internal page, rather than an internal redirect using `react-router-dom`, but I could be wrong about that. It would re-create the redux store, but I guess login information wouldn't be lost because of cookies.

@kumar303 @willdurand Do you think just always doing an http redirect is a reasonable approach to this issue, or should we try to find a way to differentiate between internal and external links and continue to use `history.push` for internal ones?

**Comment by willdurand** [comment]
I think forcing a page reload would be fine because differentiating internal vs external paths seems hard.

**Comment by bobsilverberg** [comment]
> I think forcing a page reload would be fine because differentiating internal vs external paths seems hard.

Ok, I'll give that a shot. Thanks @willdurand.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Dev Hub logged in view is displayed - issue is fixed on AMO dev with FF69(Win10). 

![the correct page](https://user-images.githubusercontent.com/33448286/67386396-8e71bd00-f59d-11e9-811b-4ba6992d13ed.gif)
