### ISSUE TITLE
addons.mozilla.org has failed the SecOps Baseline

### ISSUE THREAD

**Issue by mozcloudsec** [mozilla/addons-frontend#8793]
Site https://addons.mozilla.org has failed the SecOps Baseline scan.

The failing tests are:

 Content Security Policy (CSP) Header Not Set [10038] x 15 
 * https://addons.mozilla.org/af/firefox/collections/4757633/ (301 Moved Permanently)
 * https://addons.mozilla.org/ar/firefox/collections/4757633/ (301 Moved Permanently)
 * https://addons.mozilla.org/ast/firefox/collections/4757633/ (301 Moved Permanently)
 * https://addons.mozilla.org/az/firefox/collections/4757633/ (301 Moved Permanently)
 * https://addons.mozilla.org/bg/firefox/collections/4757633/ (301 Moved Permanently)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=addons.mozilla.org) dashboard.
If you have any questions or concerns please get in contact with @psiinon

**Comment by willdurand** [comment]
@psiinon The URLs mentioned here redirect to `/collections/` with a `301`. I think this is done at the Nginx level and that's likely why there is no CSP on the redirect response.

**Comment by psiinon** [comment]
@willdurand I must admit it not an issue I'm too worried about. However its a good test of the new code for raising issues on baseline failures :)
So, we have some options:

* Change the Nginx configs to add the CSP to 301s
* Whitelist this specific issue on /collections/ in the baseline configs

I'm ok with either of those - any thoughts on which could be the easiest to maintain?

**Comment by willdurand** [comment]
The nginx config has been added in https://github.com/mozilla/addons-server/issues/10638. URLs like `/collections/<user ID>/` have been deprecated/removed in favor of `/collections/`.

According to [the nginx config](https://github.com/mozilla-services/cloudops-deployment/blob/75dc92f61d143b5783a1b456b12a8d818260b371/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L235), we do not set CSP headers on any of the nginx redirects.

I guess we should add the CSP everywhere, no?

**Comment by psiinon** [comment]
That seems like the safest option, unless we find there a specific reasons why this wouldnt be a good idea

**Comment by willdurand** [comment]
@bqbn could you look into that please? (adding CSP to the 301 responses served by nginx)

**Comment by bqbn** [comment]
Yep, I've added it to my to do list, but TBH I don't know if I can get to it this week though, given that this is not urgent.

**Comment by bqbn** [comment]
We don't have a default CSP header for the `addons.mozilla.org` domain, and we do have a default CSP header for the `/` location and everything under that location (except for locations where the default is overridden). See [[1]](https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L309) for the default CSP header for `/` location. 

To fix this, it means we'll have to add a default CSP header to the `addons.mozilla.org` domain, which is at least a medium to large size change, not in terms of the complexity of the change (it's just a one line change), but in terms of the scale of things it may affect.

Before we implement this, I have a few questions for @psiinon and anyone who has an opinion on this issue,

1. how serious a security issue is for 301s not having a CSP header? I guess, knowing this helps us determine the trade-offs of whether or not we fix this.
2. What would be a good default CSP header for the whole domain? Would the same as [[1]](https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L309) work?
3. Do we have tests that cover returned headers? If we do, then it definitely reduces the risk of this change because we'll know if there is regression or not after deploying it to -dev and -stage (e.g.: I know it is some baseline scanning that found this issue. I don't know if we can rely on the same scanning for regression tests or not).

Thanks.

**Comment by psiinon** [comment]
The lack of a CSP header for 301s is not a serious problem. I can whitelist these if its a significant amount of work to fix them. I _should_ be able to just whitelist the 301s.
The baseline scan will runs on all of the sites we know about. The list of AMO sites is: https://sql.telemetry.mozilla.org/dashboard/foxsec-metadata-for-service?p_service_65310=AMO
The full baseline results are available via https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-scores?p_service_60201=AMO&p_w53292_service_60201=AMO

**Comment by muffinresearch** [comment]
@bqbn See also https://bugzilla.mozilla.org/show_bug.cgi?id=1567145

**Comment by moz-hwine** [comment]
The web security baseline scan for site https://addons.mozilla.org now passes - well done team!
