### ISSUE TITLE
UTM params from homepage are removed by outgoing server

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#8826]
If you click on the promoted links in the new homepage, you end up going, for example, to: 
`https://outgoing.prod.mozaws.net/v1/98ca5640820023db63708f4970d3ae2cdbb7fd0c4a54c881d0e59a07bf8cbb22/https%3A//www.mozilla.org/firefox/accounts/?utm_content=homepage-secondary-hero&utm_medium=referral&utm_source=addons.mozilla.org`
and then to: 
`https://www.mozilla.org/en-US/firefox/accounts/`

The real target should be:
`https://www.mozilla.org/en-US/firefox/accounts/?utm_content=homepage-secondary-hero&utm_medium=referral&utm_source=addons.mozilla.org`

It looks like the params should be encoded in this case.

**Comment by bobsilverberg** [comment]
I did some experimenting and I'm not sure that the problem is that the URL params are not encoded. If I encode just the URL params then I get the same result. If I encode the entire querystring, including the `?`, then I get an error message from the outgoing server: "Invalid address." It seems like the outgoing server is stripping the URL params, so maybe we can fix that in the outgoing server.

@eviljeff Do you have any ideas/opinions on this?

**Comment by eviljeff** [comment]
from some irc discussion, it appears the params are being added by frontend _after_ it's been returned by the API.  As the outgoing url contains a hash then adding extra params ends up being ignored

**Comment by bobsilverberg** [comment]
I sounds like we have (at least) a couple of options for dealing with this:
1. Move the logic that adds the UTM params from the frontend to the server so that they can be added before the link is outgoingified.
2. Implement the outgoingify logic in the frontend and apply it after appending the UTM params.

Keeping the logic centralized on the server (1, above) seems like a better approach, as I don't think we want to have to change the frontend code to explicitly outgoingify every link that needs it (which is probably why the API does it in the first place).

WDYT @eviljeff?

**Comment by bobsilverberg** [comment]
We discussed this some more in IRC and it sounds like maybe we don't need to add outgoing to any of the links on the hero shelves, as the links are defined via the admin.

@jvillalobos what do you think about this?

**Comment by jvillalobos** [comment]
I'm fine with that.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

The call to the `/hero/` api does no longer include the `wrap_outgoing_links` parameter:

![image](https://user-images.githubusercontent.com/31961530/67674715-eafe1f00-f985-11e9-8cf9-ee0d33373189.png)


External sites both in the primary and the secondary heroes will include the UTM parameters:
 
![2019-10-28_12-56-56](https://user-images.githubusercontent.com/31961530/67674721-efc2d300-f985-11e9-989b-10c298f42417.gif)
