### ISSUE TITLE
[a11y] Rating indicators are overly verbose with screen readers

### ISSUE THREAD

**Issue by jcsteh** [mozilla/addons-frontend#8829]
Currently, the rating indicators are very verbose with screen readers. For example, if I read the ratings with NVDA, I hear the following:

```
heading level 3  Used by
2,408
Users
65
Reviews
Rated 4.6 out of 5
Rated 4.6 out of 5
Rated 4.6 out of 5
Rated 4.6 out of 5
Rated 4.6 out of 5
Rated 4.6 out of 5
4.6 Stars
```

Note the six instances of "Rated 4.6 out of 5". This occurs because each `div.Rating-star` has `title="Rated 4.6 out of 5"` and each of those is read.

I think it probably makes sense to just set `aria-hidden="true"` on all `div.Rating-star`. Obviously, we don't want to do this for `button.Rating-star`, as these are the controls for the user to set a rating and these are labelled correctly.

**Comment by kumar303** [comment]
This is helpful feedback, thanks!

**Comment by atiqueahmedziad** [comment]
Can I work with this issue ?

**Comment by kumar303** [comment]
@atiqueahmedziad sure, go for it.

**Comment by Shivansh2407** [comment]
Can I work on this issue??

**Comment by willdurand** [comment]
> Can I work on this issue??

@Shivansh2407 yep, go for it!

**Comment by Shivansh2407** [comment]
Hey @willdurand can you please tell me how to proceed?

**Comment by caitmuenster** [comment]
Hi @Shivansh2407, thanks for your interest! We're accepting PRs for this issue but due to limited resources we won't be able to offer more hands-on support for fixing this issue. You might want to look for an issue marked with the label 'contrib:good first bug` label instead for more mentorship. 

It doesn't look like there are any tagged good first bugs in this repository at the moment. You're welcome to keep an eye on [this list](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20good%20first%20bug) for when new ones become available, or fix bugs for other Mozilla projects by going to [codetribute.mozilla.org](https://codetribute.mozilla.org/).
