### ISSUE TITLE
Track Contribute button clicks in GA

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#8942]
I'm splitting this off of https://github.com/mozilla/addons-server/issues/7021, since it's a smaller task that hopefully can be done quickly. We would like to know how popular the Contribute button is, so we would like its clicks to be recorded on Google Analytics.

**Comment by bobsilverberg** [comment]
When recording a click on GA, in addition to sending a `category`, which in this case would track the fact that the event is a click on a Contribute button, we can also send an `action`. My initial thought was that the `action` could contain the url of the link on the Contribute button, but I guess it might be more useful to know which add-on it was, in which case the `action` should perhaps be the add-on's `slug`.

@jvillalobos What do you think?

**Comment by jvillalobos** [comment]
Outside of the `action` there's no way of knowing the URL where the click happened? If that's the case I agree that the slug would be the best thing to store. Otherwise I like the idea of storing the target URL.

**Comment by bobsilverberg** [comment]
> Outside of the `action` there's no way of knowing the URL where the click happened? 

I'm not actually sure about this. You know more about GA than me. I thought that perhaps the location of the click was captured automatically, but I'm not sure how that would work. I can take a look at existing click data in GA to see if we seem to capture that automatically, and maybe you can do the same and we can both update the issue?

> If that's the case I agree that the slug would be the best thing to store. Otherwise I like the idea of storing the target URL.

There is also a `label` that we can send, but I'm not sure how it manifests in GA. If we need to send the `slug` in the `action`, I will also send the target URL in the `label` property.

**Comment by bobsilverberg** [comment]
I took a look at the data that seems to be available for the "AMO Addon / Recommendations Shown" event, for which we are sending the `outcome` of the call to the TAAR API as the `action`, and the add-on's name as the `label`. There is a `Page` attribute, as well as a `Landing Page` attribute available in GA for these events, and those often show the page for the add-on in question, but I believe that both of those represent the first page the user visited for the current session. It's just a coincidence that this is also often the page for the add-on itself, but there is no guarantee that that will be the case. It may be that the `Page` attribute becomes more accurate once we address https://github.com/mozilla/addons-frontend/issues/8647, but until then (and maybe even after that is fixed) it's probably best to send the `slug` in the `action` attribute in order to be able to generate useful statistics.

**Comment by willdurand** [comment]
> I'm splitting this off of [mozilla/addons-server#7021](https://github.com/mozilla/addons-server/issues/7021), since it's a smaller task that hopefully can be done quickly. We would like to know how popular the Contribute button is, so we would like its clicks to be recorded on Google Analytics.

@jvillalobos I was reviewing the patch for this issue but it's hard for me to understand what the business needs are. I _guess_ the idea is to know whether we want to fix or wontfix https://github.com/mozilla/addons-server/issues/7021, but I am not sure 😕 

What are the questions we'd like to answer with GA? What do we want to measure exactly?

For instance, the current patch sends the contributions URL to GA, but is it relevant? We can find all the contributions URLs in STMO if we need to (along with the add-on's ID/slug, etc.).

**Comment by jvillalobos** [comment]
> it's probably best to send the slug in the action attribute in order to be able to generate useful statistics

Agree. I looked into GA too and don't see the URL being recorded as part of the event.

**Comment by jvillalobos** [comment]
> What are the questions we'd like to answer with GA? What do we want to measure exactly?

We want to measure use the Contribute feature. For that we need to see how often the button is clicked. Slicing that data per add-on is useful. Knowing where those clicks are going to would also be nice (given that contributions URLs can change with time), but not as important as the other info.

**Comment by ioanarusiczki** [comment]
@bobsilverberg When I click the `Contribute` button from a detail page I receive the following event in the Browser Console:

`[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon / Contribute Button Clicks","eventAction":"ghostery","eventLabel":"https://outgoing.stage.mozaws.net/v1/c037013d8c041b32399b1d0140a4062a3158ce707067990cd18b04b59842c88b/https%3A//opencollective.com"}`

Another example:
`[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon / Contribute Button Clicks","eventAction":"garfield","eventLabel":"https://outgoing.stage.mozaws.net/v1/378db1f0d0fcd21bda8551309724b40771ffae65a1a3a0cfd108b22259608844/https%3A//donate.mozilla.org/en-US/"}`

This issue is verified on stage with FF70(Win10).
