### ISSUE TITLE
Do not disable the "Report Abuse" button while reporting abuse via Firefox

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9086]
This is a follow-up to #8988, and effectively replaces it.

Firefox was updated in https://bugzilla.mozilla.org/show_bug.cgi?id=1602758 so that if an abuse report is in progress, and a new report is initiated, the window from the first report will close and a window for the new report will open. This fixes the issue discussed in #8988, but it does introduce a new problem with the existing code.

Currently, we disable the "Report Abuse" button when an abuse report via Firefox is initiated, and we do not re-enable the button until the report is finished. This does not cause a problem for the use case discussed at #8988, because if a user reloads the page we lose that status and the button becomes enabled again. This means that the case of clicking away from the open "Report Abuse" window, and then refreshing the page works just fine.

The problem comes when you click away from the open "Report Abuse" window, and then navigate to a different add-on. In this case the "Report Abuse" button is still disabled, which is not what we want. We would want this button to be enabled, so a user could initiate an abuse report for this other add-on, if they wish to do so.

A simple fix for this is to simply not disable the button when an abuse report is initiated via Firefox. This does mean that a user could potentially click the "Report Abuse" button again, for the same add-on, which the Firefox window is open, but this wouldn't cause any issues.

**Comment by AlexandraMoga** [comment]
I've verified the new Report Abuse button behavior on -dev and I have the following results:

- in Beta 73 - the button remains enabled after clicking on it; this helped with fixing the scenario reported in #8988
- in Firefox release (72) - the button remains enabled after clicking on it, however, since the fix for #8988 is not available in 72, if the button is clicked again while an abuse report dialog is opened in the background, nothing will happen. @bobsilverberg This is not an issue with your implementation. I'm only re-stating that the report abuse flow is still broken in 72. 
- in older Firefox clients, where we are still using the old AMO abuse report flow, the feature continues to work as expected

![2020-01-14_16-55-19](https://user-images.githubusercontent.com/31961530/72355849-dada1e00-36f0-11ea-8172-9f108a44c58b.gif)
