### ISSUE TITLE
500 Error for ro locale on 404 pages

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#9105]
See https://addons.mozilla.org/ro/firefox/addon/dogpile/ as an example.

This is the cause: https://github.com/mozilla/addons-frontend/blob/445b373fc3053ef4e7e2768ddcc2f6e0fb60b69b/locale/ro/LC_MESSAGES/amo.po#L861

Note the extra `%(extensionEnd)s`

**Comment by willdurand** [comment]
The issue has been introduced a while ago: https://github.com/mozilla/addons-frontend/commit/b09231719521935ec57f30c6ad212a93e033ff2b

**Comment by willdurand** [comment]
Follow-up: https://github.com/mozilla/addons-frontend/issues/9107

**Comment by AlexandraMoga** [comment]
Verified fixed in stage

This is a reproduction of the error in prod:
https://addons.mozilla.org/ro/firefox/addon/not-a-real-addon-slug/
![image](https://user-images.githubusercontent.com/31961530/72991990-a60a4d00-3dfb-11ea-8183-8c99290e6408.png)

This is the page on stage after the fix:
https://addons.allizom.org/ro/firefox/addon/not-a-real-addon-slug/
![image](https://user-images.githubusercontent.com/31961530/72992013-aefb1e80-3dfb-11ea-89a6-a598bf0814fc.png)
