### ISSUE TITLE
Localize "Only with Firefox - Get Firefox Now" link target

### ISSUE THREAD

**Issue by tiansh** [mozilla/addons-frontend#9114]
### Describe the problem and steps to reproduce it:

1. Open AMO by any browser other than Firefox (Chrome for example);
2. Open any Extension's detail page;
3. Switch to non-English language ([NoScript Extension detail page in S.Chinese](https://addons.mozilla.org/zh-CN/firefox/addon/noscript/) for example);
4. Click the "Only with Firefox - Get Firefox Now" button ("只能用于 Firefox — 获取 Firefox" button in given example)

### What happened?
Webpage https://www.mozilla.org/en-US/firefox/new/?... opened

### What did you expect to happen?
Localized version https://www.mozilla.org/zh-CN/firefox/new/?... instead

**Comment by jvillalobos** [comment]
The link goes to `https://www.mozilla.org/firefox/new/`, which should redirect to the appropriate page depending on your browser settings. It sounds like your browser is set to English, so both AMO and mozilla.org show you the English version of the page by default.

I agree the experience you describe is a bit inconsistent, but it could be a problem to force the language in the target page, since there might not be a 1:1 mapping between the translations available on AMO and mozilla.org, and that could lead to unexpected 404 errors.

I think this should continue to work the way it does.
