### ISSUE TITLE
Proposed implementation to remove add-ons from the "Add to collection" drop-down menu

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-frontend#9133]
### Describe the problem and steps to reproduce it:
* [Create a collection](https://addons.mozilla.org/en-US/firefox/collections/add/) and label it **Test Collection**.
* Visit [HTTPS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/)
* Click on the **Add to collection** drop-down menu
* Click on the **Test Collection** entry. You'll get the confirmation message _Added to Test Collection_.
* Click on the **Add to collection** drop-down menu again. Here's an example how the menu will look my collections:
![Current](https://user-images.githubusercontent.com/6416073/73128959-b0357280-3fd8-11ea-9d78-b201fbf78c9f.png)
* Click on the **Test Collection** again and observe that you'll get this message this time: _This add-on already belongs to the collection_
![Current](https://user-images.githubusercontent.com/6416073/73128959-b0357280-3fd8-11ea-9d78-b201fbf78c9f.png)
![Screenshot at 2020-01-25 22:32:42](https://user-images.githubusercontent.com/6416073/73127607-2dee8380-3fc3-11ea-91b7-00cb36ece0fe.png)

### What happened?
Two issues with the **Add to collection** drop-down menu, none of which occurred with the old [AMO](https://addons.mozilla.org/en-US/firefox/) website (the codebase has been rewriten which is why issues like this has to be solved again):
* First of all, the **Test Collection** entry isn't marked as occupied after it has been added.
* Secondly, it's not possible to remove the add-on from the: **Test Collection** entry by by clicking on it if it has been added earlier.

### What did you expect to happen?
* Add the text " (remove)" to entries that already have been added to a collection so they will be removed from the collection when they are clicked on in the drop-down menu, which is the same way then have been added.
* Modify text in the drop down menu: Change the text  **Add too...** to **Add to/delete from...**.
* Change the text above the drop down menu from **Add to collection** to **Add to/delete from collection**.

![Suggested](https://user-images.githubusercontent.com/6416073/73128964-da873000-3fd8-11ea-8339-b0644404ab70.png)

### Anything else we should know?
Is this a duplication issue?

**Comment by eviljeff** [comment]
iirc we knew about this at the time and decided to ignore it because there wasn't a way to get a list of which collections the user had and which add-ons were in the collection without an extra API call; (returning it as part of the add-on detail response breaks cachablity because each request would be unique)

**Comment by smayer97** [comment]
This basically relates back to #4331 for functionality that is missing since the replacement of the old AMO. Original feature set in the Add To Collection included:
- seeing in which collection an add-on already exists #8997 and #8415
- ability to remove the add-on from any collection to which already belongs #4331 
- link to open any collection listed from the menu #679
- ability to search the list of add-on collections #8996

**Comment by davidhedlund** [comment]
@smayer97 Thanks a lot for the references.

**Comment by smayer97** [comment]
I would then suggest changing the label "Add to Collection" to "Add to/Delete From Collection".

**Comment by davidhedlund** [comment]
> I would then suggest changing the label "Add to Collection" to "Add to/Delete From Collection".

What would your proposed full title be?

**Comment by smayer97** [comment]
Title for this Issue? I would not change it. It is good enough.

**Comment by davidhedlund** [comment]
> I would then suggest changing the label "**Add to Collection**" to "**Add to/Delete From Collection**".

I changed the text in the top post, thanks!

**Comment by smayer97** [comment]
Please keep this request alive. This is still VERY MUCH needed.

**Comment by smayer97** [comment]
keep active...

**Comment by wagnerand** [comment]
I am closing this since there has not been any activity in a long time and adding comments just to keep this issue open does not magically implement the requested feature or even prioritize implementation. Since it has not been triaged, I am not sure we'd even take a contribution, but we can re-evaluate once someone is actually about to start working on it.

**Comment by decembre** [comment]
An old and inexplicable "problem".....
I always don't understand why this function was broken.
And why these suggestions are not implemented now...

No time to solve them?:
But someone take the time to broke it.
