### ISSUE TITLE
Lots of csp errors are thrown (and reported) when loading add-on detail or developer profile pages

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#9511]
### Describe the problem and steps to reproduce it:
0. Open developer tools network tab
1. Load the detail page for a developer, or an add-on that has other add-ons made by the same developer (don't navigate to it from other pages: copy the URL to your browser location bar and press enter)

### What happened?
- Lots of requests to `__cspreport__` are made

### What did you expect to happen?
- No requests to `__cspreport__` are made.

### Anything else we should know?
- There are a lot of `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”)` messages in the console tab
- A similar issue was found and fixed in the past: https://github.com/mozilla/addons-frontend/issues/3655

**Comment by bobsilverberg** [comment]
Is this something new, or has it always been this way? To clarify, this happens only when the page in question is rendered on the server?

**Comment by willdurand** [comment]
> To clarify, this happens only when the page in question is rendered on the server?

It's not new. This is a known issue when we render `<LoadingText />` on the server, which can happen with "secondary data", i.e. data we start to fetch after we receive other data, like an add-on or a user for example. Example: we first need to fetch an add-on to retrieve the authors, and based on these authors, we can fetch new data to display the "add-ons by authors". We tried to avoid these cases but it looks like some pages are still affected.

Fixing this isn't necessarily trivial, though.

**Comment by muffinresearch** [comment]
Here's a few thoughts on some various approaches. Most of them aren't that great. Switching the calculation to a class name based approach is probably the easiest.

### Allow inline styles in the CSP

This would stop the reports, but it could also allow for exfiltration based on attribute selectors pointing to another allowed endpoint assuming a passive injection of style is possible.

### Use a nonce 

This would be to either use a CSP nonce, but that wouldn't work with a style attr so the style would need to be output in a style tag, which is pretty horrible. We'd also need to generate the nonce (which would be unique per page load) and pick that up in component.

### Use hashes of the style attr in the CSP

This sounds attractive but it you'd either need to collect and serve all of the hashes for each page load as in the CSP headers. Or, pregenerate all the possible hashes (which would make for a lot of cruft in the CSP header). Also worth noting if the hash of style attr content is used you'd need to set `'unsafe-hashes'` to support CSP3. This is because small chunks of code hashed could then allow an attacker to use the same code, although in this case where it's only ever setting a width that should be OK.

### Refactor the approach with style attrs and use classes.

This could probably be refactored to use a `class`, but then you'd be adding a lot of classes to support this case. The calculation looks odd (it generates widths > 100%) so you'd probably want to determine a reasonable range and pre-generate those. A width can be passed in too, but a small width wouldn't really make sense so covering. 40-100% would probably work or less if you wanted to break that down to every n% e.g. every 2% or 3%.

### Strip style attrs from the server render

This would fix the errors but whether it would cause problems with react reconciliation would need to be checked. Also this assumes that the width can wait until the JS renders which probably isn't ideal for loading indicators.

**Comment by willdurand** [comment]
> Switching the calculation to a class name based approach is probably the easiest.

I agree.

It's possible that we prevent some cards/parts of the UI to render on the server because of this problem. We should double check that once we have a class name based implementation because we might not need the hacks we introduced. Note that I am not entirely sure if we still have such things.

**Comment by bobsilverberg** [comment]
@willdurand I've started working on this, and I am wondering if we can redefine the requirements of what `LoadingText` needs to be able to do. I see it being called with various values for `width`, `minWidth` and `range`, as well as without any of those props (this latter case is quite common), in which case `minWidth` defaults to `20` and `range` defaults to `60`. 

We definitely need to narrow down the possible widths to a manageable set in order to have a class for each one. I was thinking just `[20, 40, 60, 80, 100]`, but maybe we need that in 10's? Also, I'm not sure we need to allow callers to specify all these different things (`width`, `minWidth`, `range`). What do you think of just having sizes, like `small`, `medium`, `large` (and maybe `xsmall` and `xlarge` if we really need them), and then we assign a random class from the set which falls into that category range? Doing that might help us decide exactly how many we need.

I see some pretty specific numbers in some cases, and I'm wondering if we really need those in those cases. I guess I'll need to experiment locally to see what happens in those cases when I change it.

**Comment by willdurand** [comment]
The idea behind these props was to be as close to the real text as possible, but it's flawed. Instead, we should have a random width between 40 and 80 maybe, and the parent/container should handle the rest. I think that's what we started to do in code manager.

I'd start with noop'ing these props and use the default values only in this component to see what would need some changes. If we use the component without props in many cases, it's a good sign. Maybe we will be able to simplify the component a lot

**Comment by willdurand** [comment]
I have a proposal that isn't going to be quick but which would be very helpful: maybe we could expand our Storybook with stories for some of the components that rely on `LoadingText` (only for the loading state)?

**Comment by bobsilverberg** [comment]
> I have a proposal that isn't going to be quick but which would be very helpful: maybe we could expand our Storybook with stories for some of the components that rely on `LoadingText` (only for the loading state)?

That's a good idea, although I'm not entirely convinced that it will be worth the effort for this single instance when we'll find those useful. At the same time, it will make verifying the fix easier, so there's some value there.

I'll take a look and see just how quickly I can get some stories up for some of these components, especially the ones with "odd" params.

**Comment by bobsilverberg** [comment]
After taking a quick look, one of the issues we have is that a lot of the components that use `LoadingText`, including the ones with "odd" params, are components that are displayed inside other components (which are sometimes also inside other components). Because of the nature of how `LoadingText` works, using percentage widths, in order to create proper stories we'll need to not just create a simple story for a component, but we'll need to make sure it is in the appropriate container. I'll take a look at doing this for one of them, but my sense is that this is going to be a lot more work than it's worth, and it might be much faster/more efficient to just check each component manually after making the adjustments.

**Comment by bobsilverberg** [comment]
> After taking a quick look, one of the issues we have is that a lot of the components that use `LoadingText`, including the ones with "odd" params, are components that are displayed inside other components (which are sometimes also inside other components). Because of the nature of how `LoadingText` works, using percentage widths, in order to create proper stories we'll need to not just create a simple story for a component, but we'll need to make sure it is in the appropriate container. I'll take a look at doing this for one of them, but my sense is that this is going to be a lot more work than it's worth, and it might be much faster/more efficient to just check each component manually after making the adjustments.

I did spend some time, a few weeks ago, trying to create a story for some of the components in question, and it did turn out to be quite difficult and a lot of work. I think the value in doing this will be quite limited, so I'm going to go back to the idea of simplifying the `LoadingText` component and visually verifying what problems, if any, it raises.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on dev - FF81(Win10) and I do not see these csp reports being present on the addon detail page or the user profile page. 

![no css reports](https://user-images.githubusercontent.com/33448286/95074025-7fd0d700-0716-11eb-907a-80923ec510b5.gif)
