### ISSUE TITLE
All supported add-ons should have average daily users

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9527]
Depends on https://github.com/mozilla/addons-server/issues/14982

---

We made some changes to display the number of "Downloads" instead of "Users" for langpacks and dictionaries. We've added support for those add-on types in BigQuery and addons-server. Once the issue above lands, we can revert the UI changes introduced in:

- https://github.com/mozilla/addons-frontend/issues/9460
- https://github.com/mozilla/addons-frontend/issues/9472

**Comment by ioanarusiczki** [comment]
@willdurand 
On dev:
- the detail pages and search results show `users` instead of `downloads` for lang packs and dicts.
- the frontend link to stats is now available on the detail pages for the owners/developers. It's not available in logout view or viewed by another user (except the admin). 

I have a question about the search results that use the `sort=users` parameter:
- on dev I see that after the cron task ran the results show the addons with bigquery data from the [list](https://github.com/mozilla/bigquery-etl/blob/3cefa96e15cebbded340633bed240db36bb8cff5/sql/amo_dev/amo_stats_dau_v2/query.sql) as the top of the results -> https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&sort=users
- on stage I see more add-ons including some of the add-ons which use bigquery.  https://addons.allizom.org/en-US/firefox/search/?platform=windows&sort=users For example, the first theme shows 192 users but it has no stats data (including ADU).

**Comment by willdurand** [comment]
> on stage I see more add-ons including some of the add-ons which use bigquery. [addons.allizom.org/en-US/firefox/search/?platform=windows&sort=users](https://addons.allizom.org/en-US/firefox/search/?platform=windows&sort=users) For example, the first theme shows 192 users but it has no stats data (including ADU).

I see "No users" on the detail page, so having no stats data makes sense. The fact that it shows 192 users in the search results means that we didn't update the ElasticSearch data somehow.

**Comment by willdurand** [comment]
Looks like the theme is gone in the search results now, right?

**Comment by ioanarusiczki** [comment]
@willdurand I still see 192 users in the search results. actually, I see the same results as before.

**Comment by willdurand** [comment]
mmm, right. I maybe clicked the wrong link earlier. I also see 192 users for this static theme. Weird.

**Comment by willdurand** [comment]
@ioanarusiczki do you reproduce in stage by chance?

**Comment by ioanarusiczki** [comment]
@willdurand This issue was about something else and I'm going to mark it verified - FF78(Win10). 

If you consider that I should open a tracking issue for the search part, let me know.
