### ISSUE TITLE
Users who deleted their accounts on FxA receive a 404 when reloading an add-on detail page on AMO

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9549]
### Describe the problem and steps to reproduce it:
1. Log in to AMO stage
2. Open an add-on detail page
3. In a separate tab, open the FxA account management page
4. Delete your account from FxA
5. Go back to AMO and refresh the tab where the add-on detail page was opened

### What happened?
You receive a 404 for the add-on detail page

### What did you expect to happen?
The add-on detail page is loaded

### Anything else we should know?
- there is no authentication cookie present in dev tools 
- reproduced on stage and prod

![image](https://user-images.githubusercontent.com/31961530/88810244-cad1e980-d1bd-11ea-9724-ee62e5a1e6c6.png)

**Comment by willdurand** [comment]
@AlexandraMoga I think this is similar to https://github.com/mozilla/addons-frontend/issues/9490, right? In the patch fixing #9490, it is mentioned that we won't necessarily get rid of the 404 because API requests are sent in parallel, therefore we log the user (that's normal and that's the result of the very first API request sent) but we get a 404 because of a second API request.. I am not sure we can fix this issue. Reloading the page one more time would fix the problem.

**Comment by willdurand** [comment]
> I was surprised to see that it was reproducing again.

Yes, I don't understand that part either, but given that I left a comment in the patch (not specifically intended for you, sorry for not having commented in the issue instead), I am wondering if it was just luck..
