### ISSUE TITLE
Show add-ons in "Sponsored" group as "Verified"

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9585]
We decided to simplify how we present Sponsored add-ons to users, so we need to make these changes:

- Sponsored add-ons will display the Verified badge, so we don't need the Sponsored badge anymore.
- ~~In search, only have one Verified filter that includes both Verified and Sponsored results.~~

The search changes haven't been done yet, and will be completed as part of https://github.com/mozilla/addons-frontend/issues/9615, so this issue is just about the badging portion, and making sure that a "Sponsored" add-on is badged as "Verified".

**Comment by rochisha0** [comment]
Can I take this issue?

**Comment by caitmuenster** [comment]
Hey @rochisha0, thanks for your interest! This isn't a good bug for contributors. :) You will want to get started with an issue labeled '[contrib: good first bug](https://github.com/mozilla/addons-frontend/issues?q=is%3Aopen+is%3Aissue+label%3A%22contrib%3A+good+first+bug%22).'

Currently it doesn't look like there are any open good first bugs. We tend to refresh the list about every two weeks. You're welcome to pick up one of those bugs when they become available, or head over to [Codetribute](https://codetribute.mozilla.org/) for other good-first-bugs across Mozilla projects. :)

**Comment by AlexandraMoga** [comment]
Add-ons belonging to the Sponsored promoted group will display a 'Verified' badge on the frontend.

[Example of a _sponsored_ add-on with the verified badge:](https://addons-dev.allizom.org/en-US/firefox/addon/perms-and-optional-perms/)
![image](https://user-images.githubusercontent.com/31961530/93199861-a4f5a980-f757-11ea-8ac2-e5e44622b6d5.png)

This issue is verified fixed on -dev.
