### ISSUE TITLE
Remove border radius between the main Permissions card and the Card-footer 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9588]
Follow up for #9551

### Describe the problem and steps to reproduce it:
1. Open the following add-on detail page - https://addons-dev.allizom.org/en-US/firefox/addon/more-optional-permissions/
2. Scroll down to the Permissions card section
3. Observe the card styling 

### What happened?
There is a border radius between the main Permissions card and the Card-footer

### What did you expect to happen?
No border radius

### Anything else we should know?

[1] - Current layout on -dev:
![image](https://user-images.githubusercontent.com/31961530/90890123-05483400-e3c2-11ea-8511-976abc25334d.png)

[2] - Expected layout (seen on [stage](https://addons.allizom.org/en-US/firefox/addon/all-of-thepermissionsplurals/)):
![image](https://user-images.githubusercontent.com/31961530/90890161-1e50e500-e3c2-11ea-9888-236b54b6986a.png)

**Comment by caitmuenster** [comment]
Hey @lakshyabatman, welcome! We usually meet every two weeks to review potential good-first-bugs and assign mentors to the. Our next meeting next Monday. If you feel good about getting started, go for it! Otherwise we'll assign a mentor to this issue next week to help answer questions. :) 

We'll assign you to this issue once you submit a pull request.

**Comment by lakshyabatman** [comment]
I can start working on it and put up doubts if I get into some issues, sounds okay?

**Comment by caitmuenster** [comment]
Sounds good! Thanks @lakshyabatman.

**Comment by lakshyabatman** [comment]
@caitmuenster @AlexandraMoga please have a look on my pull request, let me know if there are any changes required. Thankyou.

**Comment by lakshyabatman** [comment]
Also, I found the build is failing cause of scss linting issue, which I am not able to resolve please, have a look at it. :D Thankyou.

**Comment by AdityaArunSharma** [comment]
Is this issue assigned to anyone?
@caitmuenster

**Comment by Aakash2408** [comment]
Can you assign it to me?

**Comment by caitmuenster** [comment]
Hi @lakshyabatman, @navdhakar, @Aakash2408, sorry for the delayed response - normally we check in on these issues every two weeks but we had a holiday come up recently and this slipped through the cracks. 

@lakshyabatman, since yours was the first PR submitted we are going to move forward with it. 

@navdhakar and @Aakash2408, thanks so much for your interest! Would you be interested in working on one of our team's [other good-first-bugs](https://addons-pm.herokuapp.com/contrib/good-first-bugs/?dir=desc&sort=updatedAt)?

**Comment by lakshyabatman** [comment]
Okay, that's awesome @caitmuenster.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

[before expanding]
![image](https://user-images.githubusercontent.com/31961530/93604660-5b62c400-f9ce-11ea-987c-8ae2a393a2a1.png)


[expanded] 
![image](https://user-images.githubusercontent.com/31961530/93604687-64539580-f9ce-11ea-92cf-913ec546fe1c.png)
