### ISSUE TITLE
Instrument if user has add-ons or not in Disco Pane

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-frontend#963]
As disco pane is aiming to best serve people new to Add-ons, it would be great if in Google Analytics we could differentiated people who know about add-ons from those who don't. As we can not detect knowledge, it might be helpful to at least be able to seperate peope who already have add-ons installed before visiting disco pane, from people with no prior add-ons.
This would probably not account for people who have only side-loaded add-ons installed but are not aware of add-ons otherwise. Or would we be able to instrument people with only side-loaded add-ons as well?

**Comment by designakt** [comment]
Would be great to have that as a separate event category so that we can eliminate it from all other event statistics - as I assume this would be fired on every visit.

**Comment by muffinresearch** [comment]
@designakt to find this out we'll be looking at the fragment on the end of the url. If for some unexpected reason this data isn't there what should we do? 

In other words, we will have 3 possible states we can infer. 

- Has add-ons
- Has no add-ons
- unknown ( because we can't tell) .

I'm thinking it probably makes most sense to log each one. This way if the "unknown" states go up we know something is up somewhere else. Does that sounds ok?

**Comment by designakt** [comment]
@muffinresearch 
I noticed we can see themes, extensions and plugins in the data. As plugins are not installed the same way then themes and extension, can we count users that only have plugins as having no add-ons. And the data also lists the default theme, which shouldn't not count as having a theme.

Seeing blocklisted there made me wonder if there are people out there that only have blocklisted add-ons. (And probably are not aware of them.) - Not sure how we would surface that...

How about those thates:
- has no themes/extensions
- has themes/extensions
  - both
  - only themes
  - only extensions
- unknown

**Comment by muffinresearch** [comment]
So talking further in irc this will use a custom user-scoped dimension.

`has-addons` (dimension1) + `has-themes` (dimension2).
