### ISSUE TITLE
Update frontend code to use `promoted=badged`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9632]
After https://github.com/mozilla/addons-server/pull/15478 lands, we can replace the code in frontend that uses [`line,recommended,sponsored,verified`](https://github.com/mozilla/addons-frontend/blob/master/src/core/constants.js#L329) to use just `badged`.

For QA:

The search filter labelled "Reviewed" should continue to work as before. After selecting it you should see `promoted=badged` on the URL.

**Comment by ioanarusiczki** [comment]
@bobsilverberg The URL is https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&promoted=badged
And I see it's returning same results, the recommended are at the top followed by a mix of verified, sposored and line addons. 

I think it's the expected behavior, recommended addons tend to have a boost on top of all other addons.

Verified on dev with FF80(Win10).
