### ISSUE TITLE
The Download file link should always trigger a file download, not an installation

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9679]
Follow up for #4910 

### Describe the problem and steps to reproduce it:
1. Open the following extension detail page - https://addons-dev.allizom.org/en-US/firefox/addon/signature-files/
2. Click on the Download file link

### What happened?
An installation is triggered

### What did you expect to happen?
The add-on `.xpi` is downloaded

### Anything else we should know?
The issue reproduces when you click the Download file link on Firefox desktop 

![image](https://user-images.githubusercontent.com/31961530/93869854-104df700-fcd5-11ea-82e6-339683cefb73.png)

**Comment by bobsilverberg** [comment]
@jvillalobos What do you think? This link is simply an anchor tag with an `href` that points to the downloadable xpi. Firefox's default behaviour on desktop is to try to install the xpi, which is causing this. Do we need to do something special with the link to try to make Firefox not attempt to install the file, or is this current behaviour ok?

**Comment by jvillalobos** [comment]
IIRC, the installation is triggered by the `content-type` of the file, but I don't know if changing it would break other things. I think we can live with the current behavior. It's more obvious to users that right-clicking on that link is a way to download the file. Other browsers and Fenix should trigger the download since they don't support that kind of installation.
