### ISSUE TITLE
Deprecate use of findDOMNode

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#968]
See https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-find-dom-node.md

**Comment by kumar303** [comment]
Enzyme has better solutions for this https://github.com/mozilla/addons-frontend/issues/1104

**Comment by muffinresearch** [comment]
Here's all the cases of this, there aren't that many left: https://github.com/mozilla/addons-frontend/search?q=findDOMNode&unscoped_q=findDOMNode

**Comment by willdurand** [comment]
A bunch will be removed by #5836 + two files should be removed soon and they contain a lot of occurrences (`TestSwitch` and `TestInstallSwitch`).

**Comment by willdurand** [comment]
Almost done! Only the following files use this file:

- `tests/unit/ui/components/TestOverlayCard.js`
- `tests/unit/ui/components/TestRating.js` but will be fixed in #5873 
- `tests/unit/core/components/TestInfoDialog.js` but will be fixed in #5880 

It is present in two "deprecated" files (but no need to make any changes here, those files will be deleted):

- `tests/unit/core/components/TestInstallSwitch.js`
- `tests/unit/ui/components/TestSwitch.js`

**Comment by willdurand** [comment]
no more `findDOMNode` \o/

**Comment by AlexandraMoga** [comment]
@willdurand @bobsilverberg 
Can anyone add a qa:not needed label to this issue?
Thanks
