### ISSUE TITLE
Switch to using .jsx file extensions for JSX files.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#969]
Helps for syntax -  plus, it's more correct see https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md

**Comment by kumar303** [comment]
How does it help for syntax? I think it might be hard to decide when to use `.js` or `.jsx`. Often times during a refactor you are moving functions and classes in and out of utility folders. However, a lint rule would enforce it I guess. 

I've seen a lot of subtle configuration bugs due to forgetting `jsx` in glob patterns so I'd rather stick with `.js` personally.

**Comment by kumar303** [comment]
oh, did this bug already get implemented? :)

**Comment by kumar303** [comment]
ah, sorry, I was confused because the description of https://github.com/mozilla/addons-frontend/pull/971 says it was implemented

**Comment by muffinresearch** [comment]
> How does it help for syntax? I think it might be hard to decide when to use .js or .jsx. Often times during a refactor you are moving functions and classes in and out of utility folders. However, a lint rule would enforce it I guess. 

It was more about syntax highlighting than just syntax per se.

We can totally choose to not worry about doing this if we have consensus that we're ok with continuing to use `.js` for jsx.  However, I do see some of the argument around jsx not being js so using .jsx is strictly more correct which is I think why this lint rule was added.

**Comment by tofumatt** [comment]
If EVERYTHING was `.jsx` over `.js` I'd be okay with this, but otherwise I'm with Kumar: figuring out which extension the file should be is annoying cognitive overhead for developers.

I'm fine sticking with `.js` as Atom seems to syntax highlight `.js` files as `.jsx` just fine, but a mass-rename where everything is `.jsx` also works for me, but we should just use `.jsx` for everything in that case.

**Comment by muffinresearch** [comment]
Since this hasn't caused us any issues so far I think we can ignore trying to adhere to this lint rule and close this issue. We can always reopen if later on there's bigger reasons to change.
