### ISSUE TITLE
Update the site header for Fenix

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9715]
From the PRD at docs.google.com/document/d/1QTt1G05tjQqfi4ZuAx8Jy4lAshQKdFQpTC3_zqMQHQA/edit#heading=h.fiarmnx52wyo:

Milestone 1, item 5a: "The standard header, without the navigational links (Extensions, Themes, More). This can be applied to all AMO pages for Fenix users."

Specifically, when a user is on Fenix, remove the navigational links from the site header on every page.

**Comment by jvillalobos** [comment]
"for Fenix users" should be interpreted as "for users who are identified as being on Fenix based on the user agent". Those users should generally land on `/android/`, which is also a reason I'm not sure we want to keep the menu options to switch between the desktop and mobile site. If someone wants to force it they can change the URL for now.

I prefer that we err on the side of user agent detection. That is, I prefer that people on mobile visiting the desktop site see mobile content, since I think it's more likely they're on the desktop accidentally than intentionally.

My preference for the long term solution is that we drop the platform bit from the URL entirely and we rely on user agent detection. I suppose that would also make it easier to bring back a way to switch between the mobile and desktop sites because it could be implemented as a session setting rather than something that depends on the URL.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos. 

> "for Fenix users" should be interpreted as "for users who are identified as being on Fenix based on the user agent". Those users should generally land on `/android/`, which is also a reason I'm not sure we want to keep the menu options to switch between the desktop and mobile site. If someone wants to force it they can change the URL for now.
> 

Just to be clear, you are saying we don't need a visible control/link to allow users to switch from `/android/` to `/firefox/`, correct?

> I prefer that we err on the side of user agent detection. That is, I prefer that people on mobile visiting the desktop site see mobile content, since I think it's more likely they're on the desktop accidentally than intentionally.
>
> My preference for the long term solution is that we drop the platform bit from the URL entirely and we rely on user agent detection. I suppose that would also make it easier to bring back a way to switch between the mobile and desktop sites because it could be implemented as a session setting rather than something that depends on the URL.

The larger issue of controlling everything based on user agent, as opposed to `clientSite`, is part of Milestone 2. Currently, a lot of the functionality that is aimed at mobile users is solely based on `clientSite`, regardless of what their user agent says, and I don't think we're proposing to change that as part of Milestone 1. 

For now, in terms of this requirement, we can hide these additional links in both cases: 
- if the user is on the `/android/` site, or
- if the user is detected as being on Fenix

**Comment by jvillalobos** [comment]
> Just to be clear, you are saying we don't need a visible control/link to allow users to switch from /android/ to /firefox/, correct?

Correct.

> For now, in terms of this requirement, we can hide these additional links in both cases

For this requirement I think it's fine to stick to `clientSite`, since it's mainly about simplifying the appearance of the mobile site.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this on Fenix - android 9.0 

The site header has been removed. 

![Fenix](https://user-images.githubusercontent.com/33448286/95205329-e543c700-07ed-11eb-99f9-dfa2c20827d5.jpg)
