### ISSUE TITLE
Fetch homepage sponsored shelf using specific addons-server API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#9719]
Once https://github.com/mozilla/addons-server/issues/15617 is built, the frontend needs to call this API (behind a flag) to fetch the sponsored homepage shelf.

**Comment by bobsilverberg** [comment]
@jvillalobos We generally cache data in the frontend so we don't fetch the same data over and over again, and that is how the Sponsored add-ons shelf is currently behaving. I.e., if you navigate away from the home page, and then later return to the home page, we don't re-fetch a new set of add-ons for the Sponsored shelf. I assume we probably want to fetch a new batch each time the shelf is displayed?

**Comment by jvillalobos** [comment]
Correct, we should fetch a new set on every page load for the homepage.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I verified on AMO dev and I believe that's the expected result (but if I'm mistaken, let me know): 

- there are 6 add-ons which are returned on the sponsored homepage shelf - as I understood only these 6 were added to Adzerk on dev (but I believe Adzerk will handle more than 6 on production). 
- reloading the page will reorder these 6 ids. This is caused by https://github.com/mozilla/addons-server/issues/15678 the way Adzerk manages them. 

![reordering ids2](https://user-images.githubusercontent.com/33448286/96419737-38aa1200-11fd-11eb-8a04-6fad385df24a.gif)
