### ISSUE TITLE
Ux issues with the line badge while making a search

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9742]
STR:
1. Make an empty search on AMO and then select from Badging: By Firefox
2. Go to the search bar and start writing the name of an add-ons returned by the list
3. Hover over the autocomplete results
4. Observe the badges from the list of add-ons displayed

Result:
The logo turns white. 

This issue is reproducible on AMO dev and stage - FF81(Win10). 
I could not reproduce it with the other promoted badges. 

![logo goes white](https://user-images.githubusercontent.com/33448286/95336366-45536f80-08b9-11eb-9fdf-981fef646206.gif)

**Comment by ioanarusiczki** [comment]
The above issue is also reproducible on the addon detail pages

![on the addon page](https://user-images.githubusercontent.com/33448286/95438727-5c4c9d00-095f-11eb-80a3-a405c6e87632.png)

**Comment by willdurand** [comment]
This is an interesting issue: it's because the "by Firefox" SVG icon uses `<defs>` and we change the visibility of the very first icon on the page, which affects other icons for some reasons. I can reproduce in a CodeSandbox and in multiple browsers, so I believe this is a common behavior. I didn't know about it before, though. It seems using `visibility: hidden` instead of `display: none` should fix this bug.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev -FF81(Win10). I could not reproduce it - in search results or detail pages.

![fixed label](https://user-images.githubusercontent.com/33448286/95869957-9c9f8700-0d74-11eb-9cdf-3e5fb36ab4be.png)
