### ISSUE TITLE
Implement API, saga and reducer code for new sponsored endpoint

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9744]
Depends on https://github.com/mozilla/addons-server/issues/15617.

This supports #9719. 

Implement the plumbing to allow the frontend to call the new `sponsored` endpoint, and to load the data into the redux store.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

- I don't see anything changed about the feature. The addons are shown - 6 on 2 rows (as expected since there are 7 enabled in admin). 
- GA events (impressions and clicks) work as expected. They are registered and show up once in the Console. 

If there's anything else I should be testing please let me know.
