### ISSUE TITLE
Addons of all promoted types show up as sponsored when the application is android

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9781]
Followup up for https://github.com/mozilla/addons-frontend/issues/9764 and https://github.com/mozilla/addons-server/issues/15671

STR:
1. A promoted addon of recommended, sponsored, by firefox or spotlight type has "Firefox for android" set in admin. 
2. The addon is enabled for the [primary hero shelf](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/9/change/?_changelist_filters=all%3D)

Actual result:
The addons is displayed as SPONSORED on the frontend

Expected result:
The addon should not be visible. 

![Recommended for Android as sponsored](https://user-images.githubusercontent.com/33448286/96595141-08916a80-12f4-11eb-8c16-45c2e3d4910a.png)

Some addon ids in this situation are:
619938, 620079, 619992, 620214, 620213

**Comment by bobsilverberg** [comment]
Thanks for filing this @ioanarusiczki, but this is expected. When an add-on is only promoted for "Firefox for android", then when we are on the desktop site, it appears as if it is not promoted at all. I.e., the name of the promoted category is `''`. Because the default heading for the Primary Hero area is "SPONSORED", that is what shows up. This should not be a problem in production because add-ons that are being enabled for the Primary Hero area will never be those that are only promoted for  "Firefox for android". @jvillalobos Agreed that even if this were to happen, the default heading of "SPONSORED" is what should be displayed.

**Comment by jvillalobos** [comment]
Yes, this is expected behavior. We wouldn't normally add a mobile-only Recommended extension to the desktop primary hero, and by design if you're not Recommended or By Firefox for that application, you should appear as Sponsored.

**Comment by ioanarusiczki** [comment]
@bobsilverberg @jvillalobos Alright, thanks! This is good info for qa.
