### ISSUE TITLE
Review code link not appearing

### ISSUE THREAD

**Issue by iulianacse** [mozilla/addons-frontend#9788]
### Describe the problem and steps to reproduce it:
On the add-on's product page, in the "Admin Links" section only "Content review add-on" is visible. Before I had access to "Review code" link as well.

### What happened?
I entered on an add-on's product page, scrolled down to "Admin Links" and saw only "Content review add-on" available.

### What did you expect to happen?
I was expecting to see both "Content review add-on" and "Review code" links.

### Anything else we should know?
Me permissions are of an admin reviewer.

**Comment by wagnerand** [comment]
In order to reproduce the issue and test the related patch, use accounts that *don't* have the following permissions:

```
AdminTools:View
Personas:Review
Addons:PostReview
Admin:Tools
```

Addon Reviewers should have: `Addons:Review`
Admins should have: `Addons:Edit` (for the _Admin add-on_ link on the listing page) or `Users:Edit` (for the `Admin user` link on the user profile page)
Theme Reviewers should have: `Addons:ThemeReview`

**Comment by AlexandraMoga** [comment]
I've verified several permissions/permission combinations and the links exposed on the add-on detail page:

1. User with `Addons:Review`:
![image](https://user-images.githubusercontent.com/31961530/97327038-41de5300-187d-11eb-96cb-d2b7e9863f23.png)
2. Users with `Addons:ContentReview` 
![image](https://user-images.githubusercontent.com/31961530/97327193-69352000-187d-11eb-92bf-04cba4a89dc1.png)
3.  User with `Addons:Review` and `Addons:ContentReview`: 
![image](https://user-images.githubusercontent.com/31961530/97327281-8538c180-187d-11eb-8327-2df75dc9d163.png)
4. Users with `Addons:ThemeReview`:
![image](https://user-images.githubusercontent.com/31961530/97327419-9c77af00-187d-11eb-879f-4b2ca88ce630.png)
5. Users with `Addons:Review` and `Addons:Edit`:
![image](https://user-images.githubusercontent.com/31961530/97327653-da74d300-187d-11eb-9dc4-11c655733d57.png)

This issue is verified fixed on -dev.
