### ISSUE TITLE
The Sponsored shelf shows no results when the homepage is reloaded by clicking on the site logo

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9800]
### Describe the problem and steps to reproduce it:

1. Open AMO homepage on -dev
2. After the page is successfully loaded, click on the site logo in the header
3. Notice the results displayed in the Sponsored shelf

### What happened?
The Sponsored shelf is empty 

### What did you expect to happen?
The Sponsored shelf should display results

### Anything else we should know?
- when the homepage is loaded the first time or after a normal page reload, you can see seven beacon POSTs in the console; when the homepage is reloaded by clicking on the logo, there is only one beacon sent
- the issue does not reproduce on stage, hence this could be a regression from #9790 or #9783 
- the issue will also reproduce when clicking on Explore in the header menu

![2020-10-26_15-07-45](https://user-images.githubusercontent.com/31961530/97177120-a7a7dd80-179e-11eb-9398-ed4ff5e38c78.gif)

**Comment by bobsilverberg** [comment]
The reason this doesn't reproduce on stage isn't because of the code being different, it's because the `enableFeatureUseAdzerkForSponsoredShelf` flag is `false` on stage, whereas it's `true` on dev. The good thing about this is that this bug won't get to prod until we change that flag on stage/prod, and we have no immediate plans to do so. This bug likely existed on dev prior to the two commits mentioned above.

I will investigate and fix the bug, but it isn't required for this week's push if we cannot get the fix into the tag by tomorrow.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev:

![2020-10-27_17-15-54](https://user-images.githubusercontent.com/31961530/97322168-30df1300-1878-11eb-8ce3-4d0ce416f941.gif)
