### ISSUE TITLE
Investigate refactoring page override code into Page component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9850]
This is a follow-up from https://github.com/mozilla/addons-frontend/pull/9849#discussion_r520538811.

We have some code in a number of page components which checks the status code from `errorHandler` and then returns a `NotFoundPage` or `UnavailableForLegalReasonsPage` for different statuses. This code is virtually identical in each page component, so could benefit from being refactored. As we have a base `Page` component which all page components use, we might be able to move the code there.

This issue is about seeing if we can do that, and how to best do it.

**Comment by AlexandraMoga** [comment]
The frontend will display the following error pages based on the API status code:

- for `401, 403` and `404` we display the **Oops! We can’t find that page** error page:
![image](https://user-images.githubusercontent.com/31961530/100885445-52f13400-34bb-11eb-9200-925dadc395ff.png)

- for `451` we display the **That page is not available in your region** error page:
![image](https://user-images.githubusercontent.com/31961530/100885558-7916d400-34bb-11eb-984f-19a8d4a835f0.png)


This issue is verified fixed on stage.
