### ISSUE TITLE
Enable installation buttons for supported extensions in Fenix on dev

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9864]
We're close to being able to install Fenix add-ons from AMO, so we should enable the installation button for those add-ons that are compatible (Recommended for Android). This change should be behind a flag so we can turn it on when the Fenix work is ready. I'm thinking we should enable it on dev and stage when it lands, and prod should wait until shortly before the Fenix changes make it to Release.

For QA:
I haven't enabled this flag on dev yet, as I wanted you to be able to verify the fix for #9867 first, and that would be difficult to do if this change landed enabled. I think I'll change the milestone for this to the next one, and then enable the flag on dev for this at the next tag.

**Comment by ioanarusiczki** [comment]
@jvillalobos https://github.com/mozilla/addons-frontend/issues/9867 has been verified for Thursday's push. 
I looked over the recommended add-ons for android on AMO dev - even added YouTube High Definition (because it has a common id with prod) but the install button is still displayed as disabled.

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. Yes, that is expected. The add-ons will appear as installable on dev after I flip the flag, which hasn't been done yet.

**Comment by bobsilverberg** [comment]
I am re-opening this to make it about enabling the flag on dev.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
So far my results on AMO dev with Android 8.0 are:

- with the Fenix release - [about:config ](https://github.com/mozilla-mobile/fenix/issues/7865)is no longer available. The result is in this case a download when the install button is tapped on the detail page. 

- I tried Beta (83.0.0. -beta.4) and Nightly Fenix (85.0.a1) versions using the same prefs used for Fennec testing for installs from testing env. 
extensions.webapi.testing -  true
xpinstall.signatures.required - false
xpinstall.signatures.dev-root - true

I still get a download instead of an installation (looks like the prefs have no effect, and I get the same result as in the first case):

![Download triggered](https://user-images.githubusercontent.com/33448286/99973276-4298d500-2da8-11eb-8cd7-23172048947d.png)

- I tried with Fennec (68.9.0) by adding the prefs mentioned above and I could install add-ons from the recommended shelf without issues.

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. This issue is only about enabling the button, it's not about actually allowing the add-ons to install in Fenix. That will require work on the Fenix side. So I believe that your testing above verifies this issue as fixed. With this patch, the buttons should appear as enabled if the add-on is supported on Fenix.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Ok, thanks for the update.  I'll mark the issue verified.
