### ISSUE TITLE
Search button alignment improper when clicked

### ISSUE THREAD

**Issue by Sparsh1212** [mozilla/addons-frontend#9865]
### Describe the problem and steps to reproduce it:
Enter any query in the search bar and click the arrow button in the search bar.
Its position changes and it comes out of the search bar.

![image](https://user-images.githubusercontent.com/55937724/99143012-3e6e0880-2680-11eb-94af-712d62364ddb.png)
### What did you expect to happen?
The alignment should be proper, it should be inside the search bar only.
### Note: 
Reproducible on Chrome86 Ubuntu(20.04)

**Comment by ayu023ban** [comment]
I would like to work on this issue.

**Comment by bobsilverberg** [comment]
I'm not sure this even needs to be fixed. I don't believe the arrow's position changes, it's just that, in Chrome, one sees an outline of the element, and that does look like it's partially outside of the textbox. This doesn't reproduce in Firefox, however. I believe the current layout is intentional, as there is more space below the arrow in the graphic than there is about it, which is why it is positioned the way it is.

We don't have anyone in UX assigned to this project currently, but perhaps @jvillalobos can chime in with an opinion.

**Comment by jvillalobos** [comment]
Isn't the outline controllable via CSS? If we can hide it for Chrome users, I think that's the issue worth fixing.

**Comment by Sparsh1212** [comment]
@jvillalobos I would love to work further on this.

**Comment by ioanarusiczki** [comment]
@eviljeff This issue is no longer reproducible with Chrome - AMO dev

![on Crome](https://user-images.githubusercontent.com/33448286/99784999-44069b00-2b25-11eb-960c-83528e9cdb43.gif)
