### ISSUE TITLE
"Add to Firefox" button is currently enabled in Fenix

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#9867]
There's an [issue to enable the "Add to Firefox" button in Fenix here](https://github.com/mozilla/addons-frontend/issues/9864). However that should only be turned on when Fenix has been updated to handle installs from AMO for recommended. 

The Fenix team noticed that the "Add to Firefox" button is enabled today.

![IMG_7457](https://user-images.githubusercontent.com/1514/99281769-d14aa680-282a-11eb-88e7-3d4cf469eb0f.jpeg)

It should be disabled until Fenix is ready.

**Comment by AlexandraMoga** [comment]
The Add to Firefox button was enabled for Recommended extensions, similar to the issue noticed for themes in #9860

This issue is now fixed, the install button being disabled for Recommended extensions as well:

![image](https://user-images.githubusercontent.com/31961530/99531874-12b68f80-29ac-11eb-9522-c8818032faa1.png)

As a note: the Install button is disabled both for Fenix and Fennec users. 

I'm marking this issue as verified fixed on stage.
