### ISSUE TITLE
Look to remove babel-plugin-react-transform.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#99]
This will allow HMR (hot module reloading) to work on functional components by using the HMR API directly. 

See https://github.com/gaearon/react-transform-boilerplate#you-may-not-need-it for more info.

**Comment by muffinresearch** [comment]
So since this depends on React 0.15 / v15 we're going to hold-off doing this now and look at it again when react 15 lands.

**Comment by muffinresearch** [comment]
React 0.15 has landed.

**Comment by willdurand** [comment]
Update: removing this lib is easy, making HMR work again is... not easy. It works for SCSS but JS code does not get patched, I see patches coming from the server, with the correct updated code, but the client does not apply the patch correctly... It is weird because there is no error or warning, everything looks like it is successfully applied, but the UI does not change.

Possibly an issue with React Router v3.
