### ISSUE TITLE
Some lang packs and dictionaries are missing 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#9967]
Steps to reproduce:
1. Go to https://addons.mozilla.org/en-US/firefox/language-tools/

Expected results:
All lang packs and dictionaries are displayed

Actual results:
Some lang packs and dictionaries are missing

Please see the screenshot : 
![langtools](https://user-images.githubusercontent.com/1583842/103924949-7c872600-511f-11eb-94f1-39b9a8a36ec8.PNG)

**Comment by willdurand** [comment]
As mentioned on Slack, I think the issue is that we're using `target_locale` in the `languageTools` reducer for some reasons. `target_locale` has nothing to do with localized fields, we should load, store and use the `lang` as we did everywhere else. 

It likely worked on -dev because some language tools don't have a `target_locale` and we likely used te localized fallback.

**Comment by vcarciu** [comment]
Verified as fixed in prod.
