### ISSUE TITLE
Disable homepage Sponsored shelf on 21 January

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#9991]
Winding down the Promoted Add-ons pilot, we'd like to remove the Sponsored shelf on the homepage. It may be as simple as finding a flag to disable, or perhaps a bug precludes its elegant removal from the front end? 

@jvillalobos @muffinresearch

**Comment by PedroFonsecaDEV** [comment]
@devaneymoz 

Do you mean remove this section?

<img width="1432" alt="Screen Shot 2021-01-14 at 2 34 34 AM" src="https://user-images.githubusercontent.com/60857409/104558779-5b3ba380-5611-11eb-92da-59c63cf1125b.png">

If so, I would like to help with this.
Thanks.

cc @jvillalobos @muffinresearch

**Comment by bobsilverberg** [comment]
@PedroFonsecaDEV Thanks for the interest, but this issue is not open to contributors.

**Comment by jvillalobos** [comment]
This probably supersedes https://github.com/mozilla/addons-server/issues/16267

**Comment by bobsilverberg** [comment]
I verified that there is a flag we can simply flip to remove the Sponsored shelf from the home page. This is a one-line change and it works, but we are still issuing the API call to get the sponsored shelf's data. As we plan on changing the way the home page retrieves data in https://github.com/mozilla/addons-frontend/issues/9996, and because we also might one day want to bring back the sponsored shelf, I'm suggesting we just flip the flag and leave the rest as is for now.

What do you think @diox @willdurand @eviljeff?

**Comment by willdurand** [comment]
Yes, I think we only need to turn the feature off (that's why we have it behind a feature toggle)

**Comment by eviljeff** [comment]
If the flag doesn't stop the API can that be changed to prevent that too?  Skipping the API call would be better for performance (and avoiding problems like mozilla/addons-server#16267)

**Comment by bobsilverberg** [comment]
> If the flag doesn't stop the API can that be changed to prevent that too? Skipping the API call would be better for performance (and avoiding problems like [mozilla/addons-server#16267](https://github.com/mozilla/addons-server/issues/16267))

There are a number of things I did not detail in my comment at https://github.com/mozilla/addons-frontend/issues/9991#issuecomment-760449695:

1. This API call will not trigger https://github.com/mozilla/addons-server/issues/16267 because it is a different API call. When we flip the flags, we will also be turning off Adzerk integration, so none of the Adzerk-related APIs will be called anymore. This is the old API call which just calls the `search` endpoint with `promoted=recommended`.
2. If we're thinking we might want to turn the shelf back on at some point, we shouldn't just remove the API call, which would then break everything if we do flip the switch back.
3. Based on 2, above, removing this API call would need to be added to the logic currently in place for the switch, and I'd rather not add even more logic to a switch (and associated tests) that will possibly never be used.
4. We do plan on addressing the performance issue of the home page and API calls via #9996, so this extra API call is a temporary thing.

For all of these reasons I think it makes sense to just flip the flag for now, and not make any other changes.

@diox As the only one who hasn't chimed in yet, WDYT?

**Comment by diox** [comment]
We're winding the pilot program down so the code behind the flag is likely going to be completely obsolete. I'm fine with just shipping the flag switch for now, but we should work on removing the entire thing (*especially* if that adds useless API calls) sooner rather than later.

**Comment by bobsilverberg** [comment]
> We're winding the pilot program down so the code behind the flag is likely going to be completely obsolete. I'm fine with just shipping the flag switch for now, but we should work on removing the entire thing (_especially_ if that adds useless API calls) sooner rather than later.

Well, if we don't anticipate re-introducing the Sponsored shelf at any particular time, then I guess it does make sense to just remove *everything* at this point, which will also eliminate the extra API call.  I'll work on a patch for that to land this week.

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and stage and the Sponsored shelf as well as the supporting API calls are no longer present on the homepage:

![image_2021-01-20_164959](https://user-images.githubusercontent.com/31961530/105191274-8ce7c980-5b3f-11eb-89bc-0b449df44ca0.png)
